Stride Reference Manual: stride::viewers::AdoptedFileViewer Class Reference
stride::viewers::AdoptedFileViewer Class Reference
Viewer of Simulator for cases output.
#include <AdoptedFileViewer.h>
Public Member Functions
AdoptedFileViewer (std::shared_ptr< SimRunner > runner, const std::string &output_prefix)
Instantiate cases viewer.
void Update (sim_event::Id id)
Let viewer perform update.
Private Attributes
std::vector< unsigned int > m_adopted
output::AdoptedFile m_adopted_file
std::shared_ptr< SimRunner > m_runner
Detailed Description
Viewer of Simulator for cases output.
Definition at line 33 of file AdoptedFileViewer.h.
Constructor & Destructor Documentation
stride::viewers::AdoptedFileViewer::AdoptedFileViewer (std::shared_ptr< SimRunner > runner, const std::string & output_prefix) inline
Instantiate cases viewer.
Definition at line 37 of file AdoptedFileViewer.h.
References Update().
Member Function Documentation
void stride::viewers::AdoptedFileViewer::Update (sim_event::Id id)
Let viewer perform update.
Definition at line 33 of file AdoptedFileViewer.cpp.
Referenced by AdoptedFileViewer(), and stride::ControlHelper::RegisterViewers().
Member Data Documentation
std::vector<unsigned int> stride::viewers::AdoptedFileViewer::m_adopted private
Definition at line 46 of file AdoptedFileViewer.h.
output::AdoptedFile stride::viewers::AdoptedFileViewer::m_adopted_file private
Definition at line 47 of file AdoptedFileViewer.h.
std::shared_ptr<SimRunner> stride::viewers::AdoptedFileViewer::m_runner private
Definition at line 48 of file AdoptedFileViewer.h.
The documentation for this class was generated from the following files:
AdoptedFileViewer.h
AdoptedFileViewer.cpp