Stride Reference Manual: gengeopop::GeoGridProtoReader Class Reference
gengeopop::GeoGridProtoReader Class Reference
An implementation of the GeoGridReader using Protocol Buffers.
#include <GeoGridProtoReader.h>
Public Member Functions
GeoGridProtoReader (std::unique_ptr< std::istream > inputStream, stride::Population *pop)
Construct the GeoGridJSONReader with the istream which contains the Protobuf info.
std::shared_ptr< GeoGrid > Read () override
Actually perform the read and return the GeoGrid.
GeoGridProtoReader (const GeoGridProtoReader &)=delete
No copy constructor.
GeoGridProtoReader operator= (const GeoGridProtoReader &)=delete
No copy assignement.
Public Member Functions inherited from gengeopop::GeoGridReader
GeoGridReader (std::unique_ptr< std::istream > inputStream, stride::Population *pop)
Parametrized constructor.
GeoGridReader (const GeoGridReader &)=delete
No copy constructor.
GeoGridReader & operator= (const GeoGridReader &)=delete
No copy assignment.
virtual ~GeoGridReader ()=default
Default destructor.
Private Member Functions
std::shared_ptr< Location > ParseLocation (const proto::GeoGrid_Location &protoLocation)
Create a Location based on protobuf Location info.
Coordinate ParseCoordinate (const proto::GeoGrid_Location_Coordinate &protoCoordinate)
Create a Coordinate based on the provided protobuf Coordinate.
std::shared_ptr< ContactCenter > ParseContactCenter (const proto::GeoGrid_Location_ContactCenter &protoContactCenter)
Create a ContactCenter based on protobuf ContactCenter info.
stride::ContactPool * ParseContactPool (const proto::GeoGrid_Location_ContactCenter_ContactPool &protoContactPool, stride::ContactPoolType::Id typeId)
Create a ContactPool based on the provided protobuf ContactPool.
stride::Person * ParsePerson (const proto::GeoGrid_Person &person)
Create a Person based on protobuf Person info.
Private Attributes
std::shared_ptr< GeoGrid > m_geoGrid
GeoGrid being built.
Additional Inherited Members
Protected Member Functions inherited from gengeopop::GeoGridReader
void AddCommutes (std::shared_ptr< GeoGrid > geoGrid)
Add the commutes that were found to their respective Locations symmetrically.
Protected Attributes inherited from gengeopop::GeoGridReader
std::map< unsigned int, stride::Person * > m_people
< Store the persons (id->person) that were found while loping over the ContactPools.
std::vector< std::tuple< unsigned int, unsigned int, double > > m_commutes
std::unique_ptr< std::istream > m_inputStream
file to read.
stride::Population * m_population
population to use in the GeoGrid may be nullptr.
Detailed Description
An implementation of the GeoGridReader using Protocol Buffers.
This class is used to read a GeoGrid from a Proto file.
Definition at line 29 of file GeoGridProtoReader.h.
Constructor & Destructor Documentation
gengeopop::GeoGridProtoReader::GeoGridProtoReader (std::unique_ptr< std::istream > inputStream, stride::Population * pop)
Construct the GeoGridJSONReader with the istream which contains the Protobuf info.
Definition at line 37 of file GeoGridProtoReader.cpp.
gengeopop::GeoGridProtoReader::GeoGridProtoReader (const GeoGridProtoReader &) delete
No copy constructor.
Member Function Documentation
shared_ptr< GeoGrid > gengeopop::GeoGridProtoReader::Read () override virtual
Actually perform the read and return the GeoGrid.
Implements gengeopop::GeoGridReader.
Definition at line 42 of file GeoGridProtoReader.cpp.
References gengeopop::GeoGridReader::AddCommutes(), stride::Person::GetId(), proto::GeoGrid::locations(), proto::GeoGrid::locations_size(), gengeopop::GeoGridReader::m_commutes, m_geoGrid, gengeopop::GeoGridReader::m_inputStream, gengeopop::GeoGridReader::m_people, gengeopop::GeoGridReader::m_population, ParseLocation(), ParsePerson(), proto::GeoGrid::persons(), and proto::GeoGrid::persons_size().
GeoGridProtoReader gengeopop::GeoGridProtoReader::operator= (const GeoGridProtoReader &) delete
No copy assignement.
shared_ptr< Location > gengeopop::GeoGridProtoReader::ParseLocation (const proto::GeoGrid_Location & protoLocation) private
Create a Location based on protobuf Location info.
Definition at line 89 of file GeoGridProtoReader.cpp.
References proto::GeoGrid_Location::commutes(), proto::GeoGrid_Location::commutes_size(), proto::GeoGrid_Location::contactcenters(), proto::GeoGrid_Location::contactcenters_size(), proto::GeoGrid_Location::coordinate(), proto::GeoGrid_Location::id(), gengeopop::GeoGridReader::m_commutes, proto::GeoGrid_Location::name(), ParseContactCenter(), ParseCoordinate(), proto::GeoGrid_Location::population(), proto::GeoGrid_Location_Commute::proportion(), proto::GeoGrid_Location::province(), and proto::GeoGrid_Location_Commute::to().
Referenced by Read().
Coordinate gengeopop::GeoGridProtoReader::ParseCoordinate (const proto::GeoGrid_Location_Coordinate & protoCoordinate) private
Create a Coordinate based on the provided protobuf Coordinate.
Definition at line 127 of file GeoGridProtoReader.cpp.
References proto::GeoGrid_Location_Coordinate::latitude(), and proto::GeoGrid_Location_Coordinate::longitude().
Referenced by ParseLocation().
shared_ptr< ContactCenter > gengeopop::GeoGridProtoReader::ParseContactCenter (const proto::GeoGrid_Location_ContactCenter & protoContactCenter) private
Create a ContactCenter based on protobuf ContactCenter info.
Definition at line 132 of file GeoGridProtoReader.cpp.
References stride::ContactPoolType::College, proto::GeoGrid_Location_ContactCenter_Type_College, proto::GeoGrid_Location_ContactCenter_Type_Household, proto::GeoGrid_Location_ContactCenter_Type_K12School, proto::GeoGrid_Location_ContactCenter_Type_PrimaryCommunity, proto::GeoGrid_Location_ContactCenter_Type_SecondaryCommunity, proto::GeoGrid_Location_ContactCenter_Type_Workplace, stride::ContactPoolType::Household, proto::GeoGrid_Location_ContactCenter::id(), stride::ContactPoolType::K12School, ParseContactPool(), proto::GeoGrid_Location_ContactCenter::pools(), proto::GeoGrid_Location_ContactCenter::pools_size(), stride::ContactPoolType::PrimaryCommunity, stride::ContactPoolType::SecondaryCommunity, proto::GeoGrid_Location_ContactCenter::type(), and stride::ContactPoolType::Work.
Referenced by ParseLocation().
stride::ContactPool * gengeopop::GeoGridProtoReader::ParseContactPool (const proto::GeoGrid_Location_ContactCenter_ContactPool & protoContactPool, stride::ContactPoolType::Id typeId) private
Create a ContactPool based on the provided protobuf ContactPool.
Definition at line 195 of file GeoGridProtoReader.cpp.
References stride::ContactPool::AddMember(), stride::ContactPool::GetId(), m_geoGrid, gengeopop::GeoGridReader::m_people, proto::GeoGrid_Location_ContactCenter_ContactPool::people(), and proto::GeoGrid_Location_ContactCenter_ContactPool::people_size().
Referenced by ParseContactCenter().
stride::Person * gengeopop::GeoGridProtoReader::ParsePerson (const proto::GeoGrid_Person & person) private
Create a Person based on protobuf Person info.
Definition at line 219 of file GeoGridProtoReader.cpp.
References proto::GeoGrid_Person::age(), proto::GeoGrid_Person::id(), and m_geoGrid.
Referenced by Read().
Member Data Documentation
std::shared_ptr<GeoGrid> gengeopop::GeoGridProtoReader::m_geoGrid private
GeoGrid being built.
Definition at line 63 of file GeoGridProtoReader.h.
Referenced by ParseContactPool(), ParsePerson(), and Read().
The documentation for this class was generated from the following files:
GeoGridProtoReader.h
GeoGridProtoReader.cpp