Stride Reference Manual: stride::StanController Class Reference
stride::StanController Class Reference
Runs a simulation multiple times, with different random engine seeds.
#include <StanController.h>
Public Member Functions
StanController (const boost::property_tree::ptree &config, const std::string &name="StanController")
Straight initialization.
void Control ()
Actual run of the simulator.
Additional Inherited Members
Protected Member Functions inherited from stride::ControlHelper
ControlHelper ()
Empty controller: used as target for delegation.
void CheckEnv ()
Check install environment.
void CheckOutputPrefix ()
void InstallLogger ()
Make the appropriate logger for cli environment and register as stride_logger.
void LogStartup ()
Logs info on setup for cli environment to stride_logger.
void RegisterViewers (std::shared_ptr< SimRunner > runner)
Register the viewers of the SimRunner.
void Shutdown ()
Logs info on setup for cli environment to stride_logger.
ControlHelper (const boost::property_tree::ptree &config, std::string name)
Straight initialization.
~ControlHelper ()
Simple destructor.
Protected Attributes inherited from stride::ControlHelper
boost::property_tree::ptree m_config
Main configuration for run and sim.
std::string m_name
Contoller's name.
std::string m_output_prefix
Prefix to output (name prefix or prefix dir)
util::Stopwatch m_run_clock
Stopwatch for timing the computation.
std::shared_ptr< spdlog::logger > m_stride_logger
General logger.
bool m_use_install_dirs
Working dir or install dir mode.
Detailed Description
Runs a simulation multiple times, with different random engine seeds.
The infection count at each day is captured a a text file is produced with the infection counts over time and the associated boxplot data. The runs are in parallel (iff OpenMP available), individuals runs not.
StanController setup functions include (
See also
ControlHelper):
checks the OpenMP environment
checks the file system environment
interprets and executes the ouput prefix
intalls a stride logger
The StanController execution:
produces a random seed for each run
creates a population (
Population) for each run
creates a simulation runner (
SimRunner) for each run
registers the appropriate viewer for each runner
runs the simulations
produces the output.
The procedure implies that the parameters "run.rng_seed" and also "run.num_threads" in the configuration are overriden for the individual runs.
The output is textual and consists of multiple CSV blocks separated by blank lines. The first block has the time evolution of the infection count in rows, the second block has the boxplot data in columns. The format is amenable to the gnuplot plotting tool (so in each CSV block the header row with column labels starts with a '#').
Definition at line 57 of file StanController.h.
Constructor & Destructor Documentation
stride::StanController::StanController (const boost::property_tree::ptree & config, const std::string & name = "StanController") explicit
Straight initialization.
Definition at line 46 of file StanController.cpp.
Member Function Documentation
void stride::StanController::Control ()
Actual run of the simulator.
Definition at line 48 of file StanController.cpp.
References stride::util::FileSys::BuildPath(), stride::ControlHelper::CheckEnv(), stride::ControlHelper::CheckOutputPrefix(), stride::Sim::Create(), stride::Population::Create(), stride::ControlHelper::InstallLogger(), stride::ControlHelper::LogStartup(), stride::ControlHelper::m_config, stride::ControlHelper::m_stride_logger, stride::ContactLogMode::ToString(), and stride::viewers::InfectedViewer::Update().
Referenced by main().
The documentation for this class was generated from the following files:
StanController.h
StanController.cpp