Stride Reference Manual: proto::GeoGrid_Location Class Reference
proto::GeoGrid_Location Class Reference
#include <geogrid.pb.h>
Public Types
typedef GeoGrid_Location_Coordinate Coordinate
typedef GeoGrid_Location_ContactCenter ContactCenter
typedef GeoGrid_Location_Commute Commute
Public Member Functions
GeoGrid_Location ()
virtual ~GeoGrid_Location ()
GeoGrid_Location (const GeoGrid_Location &from)
GeoGrid_Location & operator= (const GeoGrid_Location &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (GeoGrid_Location *other)
GeoGrid_Location * New () const final
GeoGrid_Location * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const GeoGrid_Location &from)
void MergeFrom (const GeoGrid_Location &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int contactcenters_size () const
void clear_contactcenters ()
::proto::GeoGrid_Location_ContactCenter * mutable_contactcenters (int index)
::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_ContactCenter > * mutable_contactcenters ()
const ::proto::GeoGrid_Location_ContactCenter & contactcenters (int index) const
::proto::GeoGrid_Location_ContactCenter * add_contactcenters ()
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_ContactCenter > & contactcenters () const
int commutes_size () const
void clear_commutes ()
::proto::GeoGrid_Location_Commute * mutable_commutes (int index)
::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_Commute > * mutable_commutes ()
const ::proto::GeoGrid_Location_Commute & commutes (int index) const
::proto::GeoGrid_Location_Commute * add_commutes ()
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_Commute > & commutes () const
bool has_name () const
void clear_name ()
const ::std::string & name () const
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
::std::string * mutable_name ()
::std::string * release_name ()
void set_allocated_name (::std::string *name)
bool has_coordinate () const
void clear_coordinate ()
const ::proto::GeoGrid_Location_Coordinate & coordinate () const
::proto::GeoGrid_Location_Coordinate * release_coordinate ()
::proto::GeoGrid_Location_Coordinate * mutable_coordinate ()
void set_allocated_coordinate (::proto::GeoGrid_Location_Coordinate *coordinate)
bool has_id () const
void clear_id ()
::google::protobuf::int64 id () const
void set_id (::google::protobuf::int64 value)
bool has_province () const
void clear_province ()
::google::protobuf::int64 province () const
void set_province (::google::protobuf::int64 value)
bool has_population () const
void clear_population ()
::google::protobuf::int64 population () const
void set_population (::google::protobuf::int64 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const GeoGrid_Location & default_instance ()
static void InitAsDefaultInstance ()
static const GeoGrid_Location * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages = 4
static const int kContactCentersFieldNumber = 6
static const int kCommutesFieldNumber = 7
static const int kNameFieldNumber = 2
static const int kCoordinateFieldNumber = 5
static const int kIdFieldNumber = 1
static const int kProvinceFieldNumber = 3
static const int kPopulationFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const final
void InternalSwap (GeoGrid_Location *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
const ::proto::GeoGrid_Location_Coordinate & _internal_coordinate () const
void set_has_id ()
void clear_has_id ()
void set_has_name ()
void clear_has_name ()
void set_has_province ()
void clear_has_province ()
void set_has_population ()
void clear_has_population ()
void set_has_coordinate ()
void clear_has_coordinate ()
size_t RequiredFieldsByteSizeFallback () const
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
mutable::google::protobuf::internal::CachedSize _cached_size_
::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_ContactCenter > contactcenters_
::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_Commute > commutes_
::google::protobuf::internal::ArenaStringPtr name_
::proto::GeoGrid_Location_Coordinate * coordinate_
::google::protobuf::int64 id_
::google::protobuf::int64 province_
::google::protobuf::int64 population_
Friends
struct ::protobuf_geogrid_2eproto::TableStruct
void swap (GeoGrid_Location &a, GeoGrid_Location &b)
Detailed Description
Definition at line 688 of file geogrid.pb.h.
Member Typedef Documentation
typedef GeoGrid_Location_Coordinate proto::GeoGrid_Location::Coordinate
Definition at line 775 of file geogrid.pb.h.
typedef GeoGrid_Location_ContactCenter proto::GeoGrid_Location::ContactCenter
Definition at line 776 of file geogrid.pb.h.
typedef GeoGrid_Location_Commute proto::GeoGrid_Location::Commute
Definition at line 777 of file geogrid.pb.h.
Constructor & Destructor Documentation
proto::GeoGrid_Location::GeoGrid_Location ()
virtual proto::GeoGrid_Location::~GeoGrid_Location () virtual
proto::GeoGrid_Location::GeoGrid_Location (const GeoGrid_Location & from)
Member Function Documentation
GeoGrid_Location& proto::GeoGrid_Location::operator= (const GeoGrid_Location & from) inline
Definition at line 697 of file geogrid.pb.h.
References GetArenaNoVirtual().
const ::google::protobuf::UnknownFieldSet& proto::GeoGrid_Location::unknown_fields () const inline
Definition at line 716 of file geogrid.pb.h.
inline ::google::protobuf::UnknownFieldSet* proto::GeoGrid_Location::mutable_unknown_fields () inline
Definition at line 720 of file geogrid.pb.h.
static const ::google::protobuf::Descriptor* proto::GeoGrid_Location::descriptor () static
static const GeoGrid_Location& proto::GeoGrid_Location::default_instance () static
static void proto::GeoGrid_Location::InitAsDefaultInstance () static
static const GeoGrid_Location* proto::GeoGrid_Location::internal_default_instance () inline static
Definition at line 729 of file geogrid.pb.h.
References proto::_GeoGrid_Location_default_instance_.
void proto::GeoGrid_Location::Swap (GeoGrid_Location * other)
GeoGrid_Location* proto::GeoGrid_Location::New () const inline final
Definition at line 740 of file geogrid.pb.h.
GeoGrid_Location* proto::GeoGrid_Location::New (::google::protobuf::Arena * arena) const inline final
Definition at line 742 of file geogrid.pb.h.
void proto::GeoGrid_Location::CopyFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Location::MergeFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Location::CopyFrom (const GeoGrid_Location & from)
void proto::GeoGrid_Location::MergeFrom (const GeoGrid_Location & from)
void proto::GeoGrid_Location::Clear () final
bool proto::GeoGrid_Location::IsInitialized () const final
size_t proto::GeoGrid_Location::ByteSizeLong () const final
bool proto::GeoGrid_Location::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
void proto::GeoGrid_Location::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
::google::protobuf::uint8* proto::GeoGrid_Location::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
int proto::GeoGrid_Location::GetCachedSize () const inline final
Definition at line 758 of file geogrid.pb.h.
void proto::GeoGrid_Location::SharedCtor () private
void proto::GeoGrid_Location::SharedDtor () private
void proto::GeoGrid_Location::SetCachedSize (int size) const final private
void proto::GeoGrid_Location::InternalSwap (GeoGrid_Location * other) private
inline ::google::protobuf::Arena* proto::GeoGrid_Location::GetArenaNoVirtual () const inline private
Definition at line 767 of file geogrid.pb.h.
Referenced by operator=().
void* proto::GeoGrid_Location::MaybeArenaPtr () const inline private
Definition at line 768 of file geogrid.pb.h.
::google::protobuf::Metadata proto::GeoGrid_Location::GetMetadata () const final
int proto::GeoGrid_Location::contactcenters_size () const inline
Definition at line 1566 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::clear_contactcenters () inline
Definition at line 1567 of file geogrid.pb.h.
References proto::GeoGrid_Location_Coordinate::Clear().
proto::GeoGrid_Location_ContactCenter * proto::GeoGrid_Location::mutable_contactcenters (int index) inline
Definition at line 1568 of file geogrid.pb.h.
google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_ContactCenter > * proto::GeoGrid_Location::mutable_contactcenters () inline
Definition at line 1574 of file geogrid.pb.h.
const ::proto::GeoGrid_Location_ContactCenter & proto::GeoGrid_Location::contactcenters (int index) const inline
Definition at line 1579 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
proto::GeoGrid_Location_ContactCenter * proto::GeoGrid_Location::add_contactcenters () inline
Definition at line 1584 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_ContactCenter > & proto::GeoGrid_Location::contactcenters () const inline
Definition at line 1590 of file geogrid.pb.h.
int proto::GeoGrid_Location::commutes_size () const inline
Definition at line 1597 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::clear_commutes () inline
Definition at line 1598 of file geogrid.pb.h.
proto::GeoGrid_Location_Commute * proto::GeoGrid_Location::mutable_commutes (int index) inline
Definition at line 1599 of file geogrid.pb.h.
google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_Commute > * proto::GeoGrid_Location::mutable_commutes () inline
Definition at line 1604 of file geogrid.pb.h.
const ::proto::GeoGrid_Location_Commute & proto::GeoGrid_Location::commutes (int index) const inline
Definition at line 1609 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
proto::GeoGrid_Location_Commute * proto::GeoGrid_Location::add_commutes () inline
Definition at line 1614 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_Commute > & proto::GeoGrid_Location::commutes () const inline
Definition at line 1619 of file geogrid.pb.h.
bool proto::GeoGrid_Location::has_name () const inline
Definition at line 1396 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_name () inline
Definition at line 1399 of file geogrid.pb.h.
const ::std::string & proto::GeoGrid_Location::name () const inline
Definition at line 1404 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::set_name (const ::std::string & value) inline
Definition at line 1409 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
void proto::GeoGrid_Location::set_name (const char * value) inline
Definition at line 1423 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_name (const char * value, size_t size) inline
Definition at line 1430 of file geogrid.pb.h.
std::string * proto::GeoGrid_Location::mutable_name () inline
Definition at line 1437 of file geogrid.pb.h.
std::string * proto::GeoGrid_Location::release_name () inline
Definition at line 1443 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_allocated_name (::std::string * name) inline
Definition at line 1452 of file geogrid.pb.h.
bool proto::GeoGrid_Location::has_coordinate () const inline
Definition at line 1506 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_coordinate () inline
Definition at line 1509 of file geogrid.pb.h.
const ::proto::GeoGrid_Location_Coordinate & proto::GeoGrid_Location::_internal_coordinate () const inline private
Definition at line 1515 of file geogrid.pb.h.
const ::proto::GeoGrid_Location_Coordinate & proto::GeoGrid_Location::coordinate () const inline
Definition at line 1519 of file geogrid.pb.h.
References proto::_GeoGrid_Location_Coordinate_default_instance_.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
proto::GeoGrid_Location_Coordinate * proto::GeoGrid_Location::release_coordinate () inline
Definition at line 1527 of file geogrid.pb.h.
proto::GeoGrid_Location_Coordinate * proto::GeoGrid_Location::mutable_coordinate () inline
Definition at line 1535 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_allocated_coordinate (::proto::GeoGrid_Location_Coordinate * coordinate) inline
Definition at line 1545 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
bool proto::GeoGrid_Location::has_id () const inline
Definition at line 1375 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_id () inline
Definition at line 1378 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location::id () const inline
Definition at line 1383 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::set_id (::google::protobuf::int64 value) inline
Definition at line 1388 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
bool proto::GeoGrid_Location::has_province () const inline
Definition at line 1464 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_province () inline
Definition at line 1467 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location::province () const inline
Definition at line 1472 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::set_province (::google::protobuf::int64 value) inline
Definition at line 1477 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
bool proto::GeoGrid_Location::has_population () const inline
Definition at line 1485 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_population () inline
Definition at line 1488 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location::population () const inline
Definition at line 1493 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::set_population (::google::protobuf::int64 value) inline
Definition at line 1498 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteLocation().
void proto::GeoGrid_Location::set_has_id () inline private
Definition at line 1376 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_has_id () inline private
Definition at line 1377 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_has_name () inline private
Definition at line 1397 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_has_name () inline private
Definition at line 1398 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_has_province () inline private
Definition at line 1465 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_has_province () inline private
Definition at line 1466 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_has_population () inline private
Definition at line 1486 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_has_population () inline private
Definition at line 1487 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_has_coordinate () inline private
Definition at line 1507 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_has_coordinate () inline private
Definition at line 1508 of file geogrid.pb.h.
size_t proto::GeoGrid_Location::RequiredFieldsByteSizeFallback () const private
Friends And Related Function Documentation
friend struct ::protobuf_geogrid_2eproto::TableStruct friend
Definition at line 877 of file geogrid.pb.h.
void swap (GeoGrid_Location & a, GeoGrid_Location & b) friend
Definition at line 736 of file geogrid.pb.h.
Member Data Documentation
constexpr int proto::GeoGrid_Location::kIndexInFileMessages = 4 static
Definition at line 733 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kContactCentersFieldNumber = 6 static
Definition at line 784 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kCommutesFieldNumber = 7 static
Definition at line 794 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kNameFieldNumber = 2 static
Definition at line 804 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kCoordinateFieldNumber = 5 static
Definition at line 819 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kIdFieldNumber = 1 static
Definition at line 833 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kProvinceFieldNumber = 3 static
Definition at line 840 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kPopulationFieldNumber = 4 static
Definition at line 847 of file geogrid.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::GeoGrid_Location::_internal_metadata_ private
Definition at line 867 of file geogrid.pb.h.
::google::protobuf::internal::HasBits<1> proto::GeoGrid_Location::_has_bits_ private
Definition at line 868 of file geogrid.pb.h.
mutable ::google::protobuf::internal::CachedSize proto::GeoGrid_Location::_cached_size_ private
Definition at line 869 of file geogrid.pb.h.
::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_ContactCenter> proto::GeoGrid_Location::contactcenters_ private
Definition at line 870 of file geogrid.pb.h.
::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_Commute> proto::GeoGrid_Location::commutes_ private
Definition at line 871 of file geogrid.pb.h.
::google::protobuf::internal::ArenaStringPtr proto::GeoGrid_Location::name_ private
Definition at line 872 of file geogrid.pb.h.
::proto::GeoGrid_Location_Coordinate* proto::GeoGrid_Location::coordinate_ private
Definition at line 873 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Location::id_ private
Definition at line 874 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Location::province_ private
Definition at line 875 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Location::population_ private
Definition at line 876 of file geogrid.pb.h.
The documentation for this class was generated from the following file:
geogrid.pb.h