Stride Reference Manual: stride::util::RnPcg Class Reference
stride::util::RnPcg Class Reference
Manages random number generation in parallel (OpenMP) calculations.
#include <RnPcg.h>
Classes
struct Info
POD representation of the RNManager's state.
Public Types
using EngineType = pcg64
Public Member Functions
RnPcg (const Info &info=Info())
Initializes.
RnPcg (const RnPcg &)=delete
No copying.
RnPcg & operator= (const RnPcg &)=delete
No copy assignment.
Info GetInfo () const
Return the state of the random engine.
template<typename D >
std::function< typename
D::result_type()> GetGenerator (const D &d, size_t i=0)
Produce a random generator out of a distribution bound to sim's random engine.
EngineType & GetEngine (size_t i=0)
Return the generator engine for the ith thread.
const EngineType & GetEngine (size_t i=0) const
Return the generator engine for the ith thread.
void Seed (const Info &info=Info())
Initalize with data in Info.
Static Private Member Functions
static bool CheckAllDigits (const std::string &seed)
Check that the seed string is all digits.
Private Attributes
std::vector< EngineType > m_engines
An random generator engine for each thread.
std::string m_seed_seq_init
Actual seed sequence initializer used with engine.
unsigned int m_stream_count
Number of streams set up with the engine.
Detailed Description
Manages random number generation in parallel (OpenMP) calculations.
Definition at line 34 of file RnPcg.h.
Member Typedef Documentation
using stride::util::RnPcg::EngineType = pcg64
Definition at line 37 of file RnPcg.h.
Constructor & Destructor Documentation
stride::util::RnPcg::RnPcg (const Info & info = Info()) explicit
Initializes.
Definition at line 33 of file RnPcg.cpp.
References Seed().
stride::util::RnPcg::RnPcg (const RnPcg &) delete
No copying.
Member Function Documentation
RnPcg& stride::util::RnPcg::operator= (const RnPcg &) delete
No copy assignment.
RnPcg::Info stride::util::RnPcg::GetInfo () const
Return the state of the random engine.
Definition at line 50 of file RnPcg.cpp.
References m_engines, stride::util::RnPcg::Info::m_seed_seq_init, m_seed_seq_init, stride::util::RnPcg::Info::m_state, stride::util::RnPcg::Info::m_stream_count, and m_stream_count.
template<typename D > std::function<typename D::result_type()> stride::util::RnPcg::GetGenerator (const D & d, size_t i = 0) inline
Produce a random generator out of a distribution bound to sim's random engine.
Parameters
d The distribution object.
i Which thread stream gets sampled, 0 by default.
Returns
The random variate generator g that can be called as g()
Definition at line 73 of file RnPcg.h.
References m_engines.
EngineType& stride::util::RnPcg::GetEngine (size_t i = 0) inline
Return the generator engine for the ith thread.
Definition at line 79 of file RnPcg.h.
References m_engines.
const EngineType& stride::util::RnPcg::GetEngine (size_t i = 0) const inline
Return the generator engine for the ith thread.
Definition at line 82 of file RnPcg.h.
References m_engines.
void stride::util::RnPcg::Seed (const Info & info = Info())
Initalize with data in Info.
Definition at line 63 of file RnPcg.cpp.
References CheckAllDigits(), m_engines, stride::util::RnPcg::Info::m_seed_seq_init, m_seed_seq_init, stride::util::RnPcg::Info::m_state, stride::util::RnPcg::Info::m_stream_count, m_stream_count, and stride::util::Split().
Referenced by RnPcg().
bool stride::util::RnPcg::CheckAllDigits (const std::string & seed) static private
Check that the seed string is all digits.
Definition at line 40 of file RnPcg.cpp.
Referenced by Seed().
Member Data Documentation
std::vector<EngineType> stride::util::RnPcg::m_engines mutable private
An random generator engine for each thread.
Definition at line 92 of file RnPcg.h.
Referenced by GetEngine(), GetGenerator(), GetInfo(), and Seed().
std::string stride::util::RnPcg::m_seed_seq_init private
Actual seed sequence initializer used with engine.
Definition at line 93 of file RnPcg.h.
Referenced by GetInfo(), and Seed().
unsigned int stride::util::RnPcg::m_stream_count private
Number of streams set up with the engine.
Definition at line 94 of file RnPcg.h.
Referenced by GetInfo(), and Seed().
The documentation for this class was generated from the following files:
RnPcg.h
RnPcg.cpp