Stride Reference Manual: stride::util::RnPcg Class Reference
stride::util::RnPcg Class Reference
Manages random number generation in parallel (OpenMP) calculations.
#include <RnPcg.h>
Classes
struct Info
POD representation of the RNManager's state.
Public Types
using EngineType = pcg64
using GeneratorType = randutils::random_generator< pcg64, randutils::seed_seq_fe128 >
using ContainerType = std::vector< randutils::random_generator< pcg64, randutils::seed_seq_fe128 >>
Public Member Functions
RnPcg (const Info &info=Info())
Initializes.
RnPcg (const RnPcg &)=delete
No copying.
RnPcg & operator= (const RnPcg &)=delete
No copy assignment.
bool operator== (const RnPcg &other)
Equality of states.
Info GetInfo () const
Return the state of the random engines.
Private Member Functions
void Seed (const Info &info=Info())
Initalize with data in Info.
Static Private Member Functions
static bool CheckAllDigits (const std::string &seed)
Check that the seed string is all digits.
Private Attributes
std::string m_seed_seq_init
Seed sequence initializer used with engines.
unsigned int m_stream_count
Number of threads/streams set up with the engine.
Detailed Description
Manages random number generation in parallel (OpenMP) calculations.
Definition at line 34 of file RnPcg.h.
Member Typedef Documentation
using stride::util::RnPcg::EngineType = pcg64
Definition at line 37 of file RnPcg.h.
using stride::util::RnPcg::GeneratorType = randutils::random_generator<pcg64, randutils::seed_seq_fe128>
Definition at line 38 of file RnPcg.h.
using stride::util::RnPcg::ContainerType = std::vector<randutils::random_generator<pcg64, randutils::seed_seq_fe128>>
Definition at line 39 of file RnPcg.h.
Constructor & Destructor Documentation
stride::util::RnPcg::RnPcg (const Info & info = Info()) explicit
Initializes.
Definition at line 33 of file RnPcg.cpp.
References Seed().
stride::util::RnPcg::RnPcg (const RnPcg &) delete
No copying.
Member Function Documentation
RnPcg& stride::util::RnPcg::operator= (const RnPcg &) delete
No copy assignment.
bool stride::util::RnPcg::operator== (const RnPcg & other)
Equality of states.
Definition at line 40 of file RnPcg.cpp.
References m_stream_count.
RnPcg::Info stride::util::RnPcg::GetInfo () const
Return the state of the random engines.
Definition at line 62 of file RnPcg.cpp.
References stride::util::RnPcg::Info::m_seed_seq_init, m_seed_seq_init, stride::util::RnPcg::Info::m_state, stride::util::RnPcg::Info::m_stream_count, and m_stream_count.
void stride::util::RnPcg::Seed (const Info & info = Info()) private
Initalize with data in Info.
Definition at line 75 of file RnPcg.cpp.
References CheckAllDigits(), stride::util::RnPcg::Info::m_seed_seq_init, m_seed_seq_init, stride::util::RnPcg::Info::m_state, stride::util::RnPcg::Info::m_stream_count, m_stream_count, and stride::util::Split().
Referenced by RnPcg().
bool stride::util::RnPcg::CheckAllDigits (const std::string & seed) static private
Check that the seed string is all digits.
Definition at line 51 of file RnPcg.cpp.
Referenced by Seed().
Member Data Documentation
std::string stride::util::RnPcg::m_seed_seq_init private
Seed sequence initializer used with engines.
Definition at line 85 of file RnPcg.h.
Referenced by GetInfo(), and Seed().
unsigned int stride::util::RnPcg::m_stream_count private
Number of threads/streams set up with the engine.
Definition at line 86 of file RnPcg.h.
Referenced by GetInfo(), operator==(), and Seed().
The documentation for this class was generated from the following files:
RnPcg.h
RnPcg.cpp