Stride Reference Manual: proto::GeoGrid_Location_Coordinate Class Reference
proto::GeoGrid_Location_Coordinate Class Reference
#include <geogrid.pb.h>
Public Member Functions
GeoGrid_Location_Coordinate ()
virtual ~GeoGrid_Location_Coordinate ()
GeoGrid_Location_Coordinate (const GeoGrid_Location_Coordinate &from)
GeoGrid_Location_Coordinate & operator= (const GeoGrid_Location_Coordinate &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (GeoGrid_Location_Coordinate *other)
GeoGrid_Location_Coordinate * New () const final
GeoGrid_Location_Coordinate * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const GeoGrid_Location_Coordinate &from)
void MergeFrom (const GeoGrid_Location_Coordinate &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_longitude () const
void clear_longitude ()
double longitude () const
void set_longitude (double value)
bool has_latitude () const
void clear_latitude ()
double latitude () const
void set_latitude (double value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const GeoGrid_Location_Coordinate & default_instance ()
static void InitAsDefaultInstance ()
static const GeoGrid_Location_Coordinate * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kLongitudeFieldNumber = 1
static const int kLatitudeFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const final
void InternalSwap (GeoGrid_Location_Coordinate *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_longitude ()
void clear_has_longitude ()
void set_has_latitude ()
void clear_has_latitude ()
size_t RequiredFieldsByteSizeFallback () const
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
mutable::google::protobuf::internal::CachedSize _cached_size_
double longitude_
double latitude_
Friends
struct ::protobuf_geogrid_2eproto::TableStruct
void swap (GeoGrid_Location_Coordinate &a, GeoGrid_Location_Coordinate &b)
Detailed Description
Definition at line 111 of file geogrid.pb.h.
Constructor & Destructor Documentation
proto::GeoGrid_Location_Coordinate::GeoGrid_Location_Coordinate ()
virtual proto::GeoGrid_Location_Coordinate::~GeoGrid_Location_Coordinate () virtual
proto::GeoGrid_Location_Coordinate::GeoGrid_Location_Coordinate (const GeoGrid_Location_Coordinate & from)
Member Function Documentation
GeoGrid_Location_Coordinate& proto::GeoGrid_Location_Coordinate::operator= (const GeoGrid_Location_Coordinate & from) inline
Definition at line 118 of file geogrid.pb.h.
References GetArenaNoVirtual().
const ::google::protobuf::UnknownFieldSet& proto::GeoGrid_Location_Coordinate::unknown_fields () const inline
Definition at line 137 of file geogrid.pb.h.
inline ::google::protobuf::UnknownFieldSet* proto::GeoGrid_Location_Coordinate::mutable_unknown_fields () inline
Definition at line 140 of file geogrid.pb.h.
static const ::google::protobuf::Descriptor* proto::GeoGrid_Location_Coordinate::descriptor () static
static const GeoGrid_Location_Coordinate& proto::GeoGrid_Location_Coordinate::default_instance () static
static void proto::GeoGrid_Location_Coordinate::InitAsDefaultInstance () static
static const GeoGrid_Location_Coordinate* proto::GeoGrid_Location_Coordinate::internal_default_instance () inline static
Definition at line 148 of file geogrid.pb.h.
References proto::_GeoGrid_Location_Coordinate_default_instance_.
void proto::GeoGrid_Location_Coordinate::Swap (GeoGrid_Location_Coordinate * other)
GeoGrid_Location_Coordinate* proto::GeoGrid_Location_Coordinate::New () const inline final
Definition at line 162 of file geogrid.pb.h.
GeoGrid_Location_Coordinate* proto::GeoGrid_Location_Coordinate::New (::google::protobuf::Arena * arena) const inline final
Definition at line 166 of file geogrid.pb.h.
void proto::GeoGrid_Location_Coordinate::CopyFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Location_Coordinate::MergeFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Location_Coordinate::CopyFrom (const GeoGrid_Location_Coordinate & from)
void proto::GeoGrid_Location_Coordinate::MergeFrom (const GeoGrid_Location_Coordinate & from)
void proto::GeoGrid_Location_Coordinate::Clear () final
Referenced by proto::GeoGrid_Location::clear_contactcenters().
bool proto::GeoGrid_Location_Coordinate::IsInitialized () const final
size_t proto::GeoGrid_Location_Coordinate::ByteSizeLong () const final
bool proto::GeoGrid_Location_Coordinate::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
void proto::GeoGrid_Location_Coordinate::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
::google::protobuf::uint8* proto::GeoGrid_Location_Coordinate::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
int proto::GeoGrid_Location_Coordinate::GetCachedSize () const inline final
Definition at line 183 of file geogrid.pb.h.
void proto::GeoGrid_Location_Coordinate::SharedCtor () private
void proto::GeoGrid_Location_Coordinate::SharedDtor () private
void proto::GeoGrid_Location_Coordinate::SetCachedSize (int size) const final private
void proto::GeoGrid_Location_Coordinate::InternalSwap (GeoGrid_Location_Coordinate * other) private
inline ::google::protobuf::Arena* proto::GeoGrid_Location_Coordinate::GetArenaNoVirtual () const inline private
Definition at line 191 of file geogrid.pb.h.
Referenced by operator=().
void* proto::GeoGrid_Location_Coordinate::MaybeArenaPtr () const inline private
Definition at line 194 of file geogrid.pb.h.
::google::protobuf::Metadata proto::GeoGrid_Location_Coordinate::GetMetadata () const final
bool proto::GeoGrid_Location_Coordinate::has_longitude () const inline
Definition at line 1158 of file geogrid.pb.h.
void proto::GeoGrid_Location_Coordinate::clear_longitude () inline
Definition at line 1167 of file geogrid.pb.h.
double proto::GeoGrid_Location_Coordinate::longitude () const inline
Definition at line 1171 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseCoordinate().
void proto::GeoGrid_Location_Coordinate::set_longitude (double value) inline
Definition at line 1175 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteCoordinate().
bool proto::GeoGrid_Location_Coordinate::has_latitude () const inline
Definition at line 1182 of file geogrid.pb.h.
void proto::GeoGrid_Location_Coordinate::clear_latitude () inline
Definition at line 1191 of file geogrid.pb.h.
double proto::GeoGrid_Location_Coordinate::latitude () const inline
Definition at line 1195 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::ParseCoordinate().
void proto::GeoGrid_Location_Coordinate::set_latitude (double value) inline
Definition at line 1199 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::WriteCoordinate().
void proto::GeoGrid_Location_Coordinate::set_has_longitude () inline private
Definition at line 1161 of file geogrid.pb.h.
void proto::GeoGrid_Location_Coordinate::clear_has_longitude () inline private
Definition at line 1164 of file geogrid.pb.h.
void proto::GeoGrid_Location_Coordinate::set_has_latitude () inline private
Definition at line 1185 of file geogrid.pb.h.
void proto::GeoGrid_Location_Coordinate::clear_has_latitude () inline private
Definition at line 1188 of file geogrid.pb.h.
size_t proto::GeoGrid_Location_Coordinate::RequiredFieldsByteSizeFallback () const private
Friends And Related Function Documentation
friend struct ::protobuf_geogrid_2eproto::TableStruct friend
Definition at line 234 of file geogrid.pb.h.
void swap (GeoGrid_Location_Coordinate & a, GeoGrid_Location_Coordinate & b) friend
Definition at line 156 of file geogrid.pb.h.
Member Data Documentation
constexpr int proto::GeoGrid_Location_Coordinate::kIndexInFileMessages static
Initial value:
=
    0
Definition at line 152 of file geogrid.pb.h.
const int proto::GeoGrid_Location_Coordinate::kLongitudeFieldNumber = 1 static
Definition at line 208 of file geogrid.pb.h.
const int proto::GeoGrid_Location_Coordinate::kLatitudeFieldNumber = 2 static
Definition at line 215 of file geogrid.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::GeoGrid_Location_Coordinate::_internal_metadata_ private
Definition at line 229 of file geogrid.pb.h.
::google::protobuf::internal::HasBits<1> proto::GeoGrid_Location_Coordinate::_has_bits_ private
Definition at line 230 of file geogrid.pb.h.
mutable ::google::protobuf::internal::CachedSize proto::GeoGrid_Location_Coordinate::_cached_size_ private
Definition at line 231 of file geogrid.pb.h.
double proto::GeoGrid_Location_Coordinate::longitude_ private
Definition at line 232 of file geogrid.pb.h.
double proto::GeoGrid_Location_Coordinate::latitude_ private
Definition at line 233 of file geogrid.pb.h.
The documentation for this class was generated from the following file:
geogrid.pb.h