Stride Reference Manual: stride::ContactPool Class Reference
stride::ContactPool Class Reference
Represents a group of Persons that potentially have contacts.
#include <ContactPool.h>
Public Types
using iterator = std::vector< stride::Person * >::iterator
Public Member Functions
ContactPool (std::size_t pool_id, ContactPoolType::Id type)
Initializing constructor.
~ContactPool ()=default
void AddMember (Person *p)
Add the given Person.
Person * GetMember (unsigned int index) const
Get member at index.
const std::vector< Person * > & GetPool () const
Get the entire pool of members.
std::size_t GetSize () const
Get size (number of members).
std::size_t GetInfectedCount ()
Get Infected count.
iterator begin ()
Iterator to first person.
iterator end ()
Iterator to end of persons.
std::size_t GetId () const
Get the pool id.
ContactPoolType::Id GetType () const
Get the type of ContactPool, used for logging and tests.
Private Member Functions
std::tuple< bool, size_t > SortMembers ()
Sort w.r.t. health status: order: exposed/infected/recovered, susceptible, immune.
Private Attributes
std::size_t m_pool_id
The ID of the ContactPool (for logging purposes).
ContactPoolType::Id m_pool_type
The type of the ContactPool (for logging and testing purposes).
std::size_t m_index_immune
Index of the first immune member in the ContactPool.
std::vector< Person * > m_members
Pointers to contactpool members (raw pointers intentional).
Friends
template<ContactLogMode::Id LL, bool TIC, bool TO>
class Infector
Infector calculates contacts and transmissions.
Detailed Description
Represents a group of Persons that potentially have contacts.
Definition at line 36 of file ContactPool.h.
Member Typedef Documentation
using stride::ContactPool::iterator = std::vector<stride::Person*>::iterator
Definition at line 59 of file ContactPool.h.
Constructor & Destructor Documentation
stride::ContactPool::ContactPool (std::size_t pool_id, ContactPoolType::Id type)
Initializing constructor.
Definition at line 32 of file ContactPool.cpp.
stride::ContactPool::~ContactPool () default
Member Function Documentation
void stride::ContactPool::AddMember (Person * p)
Add the given Person.
Definition at line 37 of file ContactPool.cpp.
References m_index_immune, and m_members.
Referenced by gengeopop::HouseholdCSVReader::HouseholdCSVReader(), and gengeopop::GeoGridProtoReader::ParseContactPool().
Person* stride::ContactPool::GetMember (unsigned int index) const inline
Get member at index.
Definition at line 48 of file ContactPool.h.
References m_members.
Referenced by stride::Immunizer::Random().
const std::vector<Person*>& stride::ContactPool::GetPool () const inline
Get the entire pool of members.
Definition at line 51 of file ContactPool.h.
References m_members.
std::size_t stride::ContactPool::GetSize () const inline
Get size (number of members).
Definition at line 54 of file ContactPool.h.
References GetInfectedCount(), and m_members.
Referenced by stride::Immunizer::Random().
std::size_t stride::ContactPool::GetInfectedCount ()
Get Infected count.
Definition at line 78 of file ContactPool.cpp.
References m_members.
Referenced by GetSize().
iterator stride::ContactPool::begin () inline
Iterator to first person.
Definition at line 62 of file ContactPool.h.
References m_members.
iterator stride::ContactPool::end () inline
Iterator to end of persons.
Definition at line 65 of file ContactPool.h.
References m_members.
std::size_t stride::ContactPool::GetId () const inline
Get the pool id.
Definition at line 68 of file ContactPool.h.
References m_pool_id.
Referenced by gengeopop::GeoGridProtoReader::ParseContactPool(), gengeopop::GeoGridProtoWriter::WriteContactPool(), and gengeopop::GeoGridJSONWriter::WriteContactPool().
ContactPoolType::Id stride::ContactPool::GetType () const inline
Get the type of ContactPool, used for logging and tests.
Definition at line 71 of file ContactPool.h.
References m_pool_type, and SortMembers().
std::tuple< bool, size_t > stride::ContactPool::SortMembers () private
Sort w.r.t. health status: order: exposed/infected/recovered, susceptible, immune.
Definition at line 43 of file ContactPool.cpp.
References m_index_immune, and m_members.
Referenced by stride::Infector< LL, TIC, true >::Exec(), and GetType().
Friends And Related Function Documentation
template<ContactLogMode::Id LL, bool TIC, bool TO> friend class Infector friend
Infector calculates contacts and transmissions.
Definition at line 79 of file ContactPool.h.
Member Data Documentation
std::size_t stride::ContactPool::m_pool_id private
The ID of the ContactPool (for logging purposes).
Definition at line 82 of file ContactPool.h.
Referenced by GetId().
ContactPoolType::Id stride::ContactPool::m_pool_type private
The type of the ContactPool (for logging and testing purposes).
Definition at line 83 of file ContactPool.h.
Referenced by stride::Infector< LL, TIC, TO >::Exec(), stride::Infector< LL, TIC, true >::Exec(), and GetType().
std::size_t stride::ContactPool::m_index_immune private
Index of the first immune member in the ContactPool.
Definition at line 84 of file ContactPool.h.
Referenced by AddMember(), stride::Infector< LL, TIC, true >::Exec(), and SortMembers().
std::vector<Person*> stride::ContactPool::m_members private
Pointers to contactpool members (raw pointers intentional).
Definition at line 85 of file ContactPool.h.
Referenced by AddMember(), begin(), end(), stride::Infector< LL, TIC, TO >::Exec(), stride::Infector< LL, TIC, true >::Exec(), GetInfectedCount(), GetMember(), GetPool(), GetSize(), and SortMembers().
The documentation for this class was generated from the following files:
ContactPool.h
ContactPool.cpp