Stride Reference Manual: proto::GeoGrid_Location_ContactPools Class Reference
proto::GeoGrid_Location_ContactPools Class Reference final
#include <geogrid.pb.h>
Public Types
typedef GeoGrid_Location_ContactPools_ContactPool ContactPool
typedef GeoGrid_Location_ContactPools_Type Type
Public Member Functions
GeoGrid_Location_ContactPools ()
virtual ~GeoGrid_Location_ContactPools ()
GeoGrid_Location_ContactPools (const GeoGrid_Location_ContactPools &from)
GeoGrid_Location_ContactPools & operator= (const GeoGrid_Location_ContactPools &from)
void Swap (GeoGrid_Location_ContactPools *other)
GeoGrid_Location_ContactPools * New () const final
GeoGrid_Location_ContactPools * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const GeoGrid_Location_ContactPools &from)
void MergeFrom (const GeoGrid_Location_ContactPools &from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int pools_size () const
void clear_pools ()
::proto::GeoGrid_Location_ContactPools_ContactPool * mutable_pools (int index)
::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location_ContactPools_ContactPool > * mutable_pools ()
const ::proto::GeoGrid_Location_ContactPools_ContactPool & pools (int index) const
::proto::GeoGrid_Location_ContactPools_ContactPool * add_pools ()
const ::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location_ContactPools_ContactPool > & pools () const
void clear_id ()
::google::protobuf::int64 id () const
void set_id (::google::protobuf::int64 value)
void clear_type ()
::proto::GeoGrid_Location_ContactPools_Type type () const
void set_type (::proto::GeoGrid_Location_ContactPools_Type value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const GeoGrid_Location_ContactPools & default_instance ()
static void InitAsDefaultInstance ()
static const GeoGrid_Location_ContactPools * internal_default_instance ()
static bool Type_IsValid (int value)
static const ::google::protobuf::EnumDescriptor * Type_descriptor ()
static const ::std::string & Type_Name (Type value)
static bool Type_Parse (const ::std::string &name, Type *value)
Static Public Attributes
static constexpr int kIndexInFileMessages
static const Type K12School
static const Type PrimaryCommunity
static const Type SecondaryCommunity
static const Type College
static const Type Household
static const Type Workplace
static const Type Type_MIN
static const Type Type_MAX
static const int Type_ARRAYSIZE
static const int kPoolsFieldNumber = 3
static const int kIdFieldNumber = 1
static const int kTypeFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const final
void InternalSwap (GeoGrid_Location_ContactPools *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location_ContactPools_ContactPool > pools_
::google::protobuf::int64 id_
int type_
mutable::google::protobuf::internal::CachedSize _cached_size_
Friends
struct ::TableStruct_geogrid_2eproto
void swap (GeoGrid_Location_ContactPools &a, GeoGrid_Location_ContactPools &b)
Detailed Description
Definition at line 360 of file geogrid.pb.h.
Member Typedef Documentation
typedef GeoGrid_Location_ContactPools_ContactPool proto::GeoGrid_Location_ContactPools::ContactPool
Definition at line 453 of file geogrid.pb.h.
typedef GeoGrid_Location_ContactPools_Type proto::GeoGrid_Location_ContactPools::Type
Definition at line 455 of file geogrid.pb.h.
Constructor & Destructor Documentation
proto::GeoGrid_Location_ContactPools::GeoGrid_Location_ContactPools ()
virtual proto::GeoGrid_Location_ContactPools::~GeoGrid_Location_ContactPools () virtual
proto::GeoGrid_Location_ContactPools::GeoGrid_Location_ContactPools (const GeoGrid_Location_ContactPools & from)
Member Function Documentation
GeoGrid_Location_ContactPools& proto::GeoGrid_Location_ContactPools::operator= (const GeoGrid_Location_ContactPools & from) inline
Definition at line 368 of file geogrid.pb.h.
References GetArenaNoVirtual().
static const ::google::protobuf::Descriptor* proto::GeoGrid_Location_ContactPools::descriptor () inline static
Definition at line 387 of file geogrid.pb.h.
static const GeoGrid_Location_ContactPools& proto::GeoGrid_Location_ContactPools::default_instance () static
static void proto::GeoGrid_Location_ContactPools::InitAsDefaultInstance () static
static const GeoGrid_Location_ContactPools* proto::GeoGrid_Location_ContactPools::internal_default_instance () inline static
Definition at line 393 of file geogrid.pb.h.
References proto::_GeoGrid_Location_ContactPools_default_instance_.
void proto::GeoGrid_Location_ContactPools::Swap (GeoGrid_Location_ContactPools * other)
GeoGrid_Location_ContactPools* proto::GeoGrid_Location_ContactPools::New () const inline final
Definition at line 407 of file geogrid.pb.h.
GeoGrid_Location_ContactPools* proto::GeoGrid_Location_ContactPools::New (::google::protobuf::Arena * arena) const inline final
Definition at line 411 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactPools::CopyFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Location_ContactPools::MergeFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Location_ContactPools::CopyFrom (const GeoGrid_Location_ContactPools & from)
void proto::GeoGrid_Location_ContactPools::MergeFrom (const GeoGrid_Location_ContactPools & from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void proto::GeoGrid_Location_ContactPools::Clear () final
bool proto::GeoGrid_Location_ContactPools::IsInitialized () const final
size_t proto::GeoGrid_Location_ContactPools::ByteSizeLong () const final
bool proto::GeoGrid_Location_ContactPools::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
void proto::GeoGrid_Location_ContactPools::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
::google::protobuf::uint8* proto::GeoGrid_Location_ContactPools::InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 * target) const final
int proto::GeoGrid_Location_ContactPools::GetCachedSize () const inline final
Definition at line 433 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactPools::SharedCtor () private
void proto::GeoGrid_Location_ContactPools::SharedDtor () private
void proto::GeoGrid_Location_ContactPools::SetCachedSize (int size) const final private
void proto::GeoGrid_Location_ContactPools::InternalSwap (GeoGrid_Location_ContactPools * other) private
inline ::google::protobuf::Arena* proto::GeoGrid_Location_ContactPools::GetArenaNoVirtual () const inline private
Definition at line 441 of file geogrid.pb.h.
Referenced by operator=().
void* proto::GeoGrid_Location_ContactPools::MaybeArenaPtr () const inline private
Definition at line 444 of file geogrid.pb.h.
::google::protobuf::Metadata proto::GeoGrid_Location_ContactPools::GetMetadata () const final
static bool proto::GeoGrid_Location_ContactPools::Type_IsValid (int value) inline static
Definition at line 468 of file geogrid.pb.h.
References proto::GeoGrid_Location_ContactPools_Type_IsValid().
static const ::google::protobuf::EnumDescriptor* proto::GeoGrid_Location_ContactPools::Type_descriptor () inline static
Definition at line 478 of file geogrid.pb.h.
References proto::GeoGrid_Location_ContactPools_Type_descriptor().
static const ::std::string& proto::GeoGrid_Location_ContactPools::Type_Name (Type value) inline static
Definition at line 481 of file geogrid.pb.h.
References proto::GeoGrid_Location_ContactPools_Type_Name().
static bool proto::GeoGrid_Location_ContactPools::Type_Parse (const ::std::string & name, Type * value) inline static
Definition at line 484 of file geogrid.pb.h.
References proto::GeoGrid_Location_ContactPools_Type_Parse().
int proto::GeoGrid_Location_ContactPools::pools_size () const inline
Definition at line 1199 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseContactPools().
void proto::GeoGrid_Location_ContactPools::clear_pools () inline
Definition at line 1202 of file geogrid.pb.h.
proto::GeoGrid_Location_ContactPools_ContactPool * proto::GeoGrid_Location_ContactPools::mutable_pools (int index) inline
Definition at line 1205 of file geogrid.pb.h.
google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_ContactPools_ContactPool > * proto::GeoGrid_Location_ContactPools::mutable_pools () inline
Definition at line 1210 of file geogrid.pb.h.
const ::proto::GeoGrid_Location_ContactPools_ContactPool & proto::GeoGrid_Location_ContactPools::pools (int index) const inline
Definition at line 1214 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseContactPools().
proto::GeoGrid_Location_ContactPools_ContactPool * proto::GeoGrid_Location_ContactPools::add_pools () inline
Definition at line 1218 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WriteContactPools().
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_ContactPools_ContactPool > & proto::GeoGrid_Location_ContactPools::pools () const inline
Definition at line 1223 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactPools::clear_id () inline
Definition at line 1171 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location_ContactPools::id () const inline
Definition at line 1174 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactPools::set_id (::google::protobuf::int64 value) inline
Definition at line 1178 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactPools::clear_type () inline
Definition at line 1185 of file geogrid.pb.h.
proto::GeoGrid_Location_ContactPools_Type proto::GeoGrid_Location_ContactPools::type () const inline
Definition at line 1188 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseContactPools().
void proto::GeoGrid_Location_ContactPools::set_type (::proto::GeoGrid_Location_ContactPools_Type value) inline
Definition at line 1192 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WriteContactPools().
Friends And Related Function Documentation
friend struct ::TableStruct_geogrid_2eproto friend
Definition at line 524 of file geogrid.pb.h.
void swap (GeoGrid_Location_ContactPools & a, GeoGrid_Location_ContactPools & b) friend
Definition at line 401 of file geogrid.pb.h.
Member Data Documentation
constexpr int proto::GeoGrid_Location_ContactPools::kIndexInFileMessages static
Initial value:
=
    2
Definition at line 397 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactPools::K12School static
Initial value:
=
    GeoGrid_Location_ContactPools_Type_K12School
Definition at line 456 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactPools::PrimaryCommunity static
Initial value:
=
    GeoGrid_Location_ContactPools_Type_PrimaryCommunity
Definition at line 458 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactPools::SecondaryCommunity static
Initial value:
=
    GeoGrid_Location_ContactPools_Type_SecondaryCommunity
Definition at line 460 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactPools::College static
Initial value:
=
    GeoGrid_Location_ContactPools_Type_College
Definition at line 462 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactPools::Household static
Initial value:
=
    GeoGrid_Location_ContactPools_Type_Household
Definition at line 464 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactPools::Workplace static
Initial value:
=
    GeoGrid_Location_ContactPools_Type_Workplace
Definition at line 466 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactPools::Type_MIN static
Initial value:
=
    GeoGrid_Location_ContactPools_Type_Type_MIN
Definition at line 471 of file geogrid.pb.h.
const Type proto::GeoGrid_Location_ContactPools::Type_MAX static
Initial value:
=
    GeoGrid_Location_ContactPools_Type_Type_MAX
Definition at line 473 of file geogrid.pb.h.
const int proto::GeoGrid_Location_ContactPools::Type_ARRAYSIZE static
Initial value:
=
    GeoGrid_Location_ContactPools_Type_Type_ARRAYSIZE
Definition at line 475 of file geogrid.pb.h.
const int proto::GeoGrid_Location_ContactPools::kPoolsFieldNumber = 3 static
Definition at line 494 of file geogrid.pb.h.
const int proto::GeoGrid_Location_ContactPools::kIdFieldNumber = 1 static
Definition at line 505 of file geogrid.pb.h.
const int proto::GeoGrid_Location_ContactPools::kTypeFieldNumber = 2 static
Definition at line 511 of file geogrid.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::GeoGrid_Location_ContactPools::_internal_metadata_ private
Definition at line 517 of file geogrid.pb.h.
::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location_ContactPools_ContactPool > proto::GeoGrid_Location_ContactPools::pools_ private
Definition at line 520 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Location_ContactPools::id_ private
Definition at line 521 of file geogrid.pb.h.
int proto::GeoGrid_Location_ContactPools::type_ private
Definition at line 522 of file geogrid.pb.h.
mutable ::google::protobuf::internal::CachedSize proto::GeoGrid_Location_ContactPools::_cached_size_ private
Definition at line 523 of file geogrid.pb.h.
The documentation for this class was generated from the following file:
geogrid.pb.h