Stride Reference Manual: gengeopop::GeoGridProtoWriter Class Reference
gengeopop::GeoGridProtoWriter Class Reference
An implementation of the GeoGridWriter using Protocol Buffers This class is used to write a GeoGrid to a Proto file.
#include <GeoGridProtoWriter.h>
Public Member Functions
GeoGridProtoWriter ()
Construct the GeoGridProtoWriter.
void Write (std::shared_ptr< GeoGrid > geoGrid, std::ostream &stream) override
Write the provided GeoGrid to the proved ostream in Protobuf format.
Public Member Functions inherited from gengeopop::GeoGridWriter
virtual ~GeoGridWriter ()=default
Construct the Writer.
Private Member Functions
void WriteLocation (std::shared_ptr< Location > location, proto::GeoGrid_Location *protoLocation)
Create a ProtoBuf Location containing all the information needed to reconstruct a Location.
void WriteCoordinate (const Coordinate &coordinate, proto::GeoGrid_Location_Coordinate *protoCoordinate)
Create a ProtoBuf Coordinate containing all the information needed to reconstruct a Coordinate.
void WriteContactCenter (std::shared_ptr< ContactCenter > contactCenter, proto::GeoGrid_Location_ContactCenter *protoContactCenter)
Create a ProtoBuf ContactCenter containing all the information needed to reconstruct a ContactCenter.
void WriteContactPool (stride::ContactPool *contactPool, proto::GeoGrid_Location_ContactCenter_ContactPool *protoContactPool)
Create a ProtoBuf ContactPool containing all the information needed to reconstruct a ContactPool.
void WritePerson (stride::Person *person, proto::GeoGrid_Person *protoPerson)
Create a ProtoBuf Person containing all the information needed to reconstruct a Person.
Private Attributes
std::set< stride::Person * > m_persons_found
The persons found when looping over the ContactPools.
Detailed Description
An implementation of the GeoGridWriter using Protocol Buffers This class is used to write a GeoGrid to a Proto file.
Definition at line 29 of file GeoGridProtoWriter.h.
Constructor & Destructor Documentation
gengeopop::GeoGridProtoWriter::GeoGridProtoWriter ()
Construct the GeoGridProtoWriter.
Definition at line 27 of file GeoGridProtoWriter.cpp.
Member Function Documentation
void gengeopop::GeoGridProtoWriter::Write (std::shared_ptr< GeoGrid > geoGrid, std::ostream & stream) override virtual
Write the provided GeoGrid to the proved ostream in Protobuf format.
Implements gengeopop::GeoGridWriter.
Definition at line 29 of file GeoGridProtoWriter.cpp.
References proto::GeoGrid::add_locations(), proto::GeoGrid::add_persons(), m_persons_found, WriteLocation(), and WritePerson().
void gengeopop::GeoGridProtoWriter::WriteLocation (std::shared_ptr< Location > location, proto::GeoGrid_Location * protoLocation) private
Create a ProtoBuf Location containing all the information needed to reconstruct a Location.
Definition at line 49 of file GeoGridProtoWriter.cpp.
References proto::GeoGrid_Location::add_commutes(), proto::GeoGrid_Location::add_contactcenters(), proto::GeoGrid_Location::set_allocated_coordinate(), proto::GeoGrid_Location::set_id(), proto::GeoGrid_Location::set_name(), proto::GeoGrid_Location::set_population(), proto::GeoGrid_Location::set_province(), proto::GeoGrid_Location_Commute::set_to(), WriteContactCenter(), and WriteCoordinate().
Referenced by Write().
void gengeopop::GeoGridProtoWriter::WriteCoordinate (const Coordinate & coordinate, proto::GeoGrid_Location_Coordinate * protoCoordinate) private
Create a ProtoBuf Coordinate containing all the information needed to reconstruct a Coordinate.
Definition at line 71 of file GeoGridProtoWriter.cpp.
References proto::GeoGrid_Location_Coordinate::set_latitude(), and proto::GeoGrid_Location_Coordinate::set_longitude().
Referenced by WriteLocation().
void gengeopop::GeoGridProtoWriter::WriteContactCenter (std::shared_ptr< ContactCenter > contactCenter, proto::GeoGrid_Location_ContactCenter * protoContactCenter) private
Create a ProtoBuf ContactCenter containing all the information needed to reconstruct a ContactCenter.
Definition at line 79 of file GeoGridProtoWriter.cpp.
References proto::GeoGrid_Location_ContactCenter::add_pools(), proto::GeoGrid_Location_ContactCenter_Type_College, proto::GeoGrid_Location_ContactCenter_Type_Community, proto::GeoGrid_Location_ContactCenter_Type_Household, proto::GeoGrid_Location_ContactCenter_Type_K12School, proto::GeoGrid_Location_ContactCenter_Type_PrimaryCommunity, proto::GeoGrid_Location_ContactCenter_Type_SecondaryCommunity, proto::GeoGrid_Location_ContactCenter_Type_Workplace, proto::GeoGrid_Location_ContactCenter::set_id(), proto::GeoGrid_Location_ContactCenter::set_type(), and WriteContactPool().
Referenced by WriteLocation().
void gengeopop::GeoGridProtoWriter::WriteContactPool (stride::ContactPool * contactPool, proto::GeoGrid_Location_ContactCenter_ContactPool * protoContactPool) private
Create a ProtoBuf ContactPool containing all the information needed to reconstruct a ContactPool.
Definition at line 98 of file GeoGridProtoWriter.cpp.
References proto::GeoGrid_Location_ContactCenter_ContactPool::add_people(), stride::ContactPool::GetId(), m_persons_found, and proto::GeoGrid_Location_ContactCenter_ContactPool::set_id().
Referenced by WriteContactCenter().
void gengeopop::GeoGridProtoWriter::WritePerson (stride::Person * person, proto::GeoGrid_Person * protoPerson) private
Create a ProtoBuf Person containing all the information needed to reconstruct a Person.
Definition at line 108 of file GeoGridProtoWriter.cpp.
References stride::Person::GetAge(), stride::Person::GetGender(), stride::Person::GetId(), proto::GeoGrid_Person::set_age(), proto::GeoGrid_Person::set_gender(), and proto::GeoGrid_Person::set_id().
Referenced by Write().
Member Data Documentation
std::set<stride::Person*> gengeopop::GeoGridProtoWriter::m_persons_found private
The persons found when looping over the ContactPools.
Definition at line 56 of file GeoGridProtoWriter.h.
Referenced by Write(), and WriteContactPool().
The documentation for this class was generated from the following files:
GeoGridProtoWriter.h
GeoGridProtoWriter.cpp