Stride Reference Manual: gengeopop::GeoGridJSONReader Class Reference
gengeopop::GeoGridJSONReader Class Reference
An implementation of the GeoGridReader using JSON This class is used to read a GeoGrid from a JSON file.
#include <GeoGridJSONReader.h>
Public Member Functions
GeoGridJSONReader (std::unique_ptr< std::istream > inputStream, stride::Population *pop)
Construct the GeoGridJSONReader with the istream which contains the JSON.
std::shared_ptr< GeoGrid > Read ()
Actually perform the read and return the GeoGrid.
GeoGridJSONReader (const GeoGridJSONReader &)=delete
No copy constructor.
GeoGridJSONReader operator= (const GeoGridJSONReader &)=delete
No copy assignement.
Public Member Functions inherited from gengeopop::GeoGridReader
GeoGridReader (std::unique_ptr< std::istream > inputStream, stride::Population *pop)
Parametrized constructor.
GeoGridReader (const GeoGridReader &)=delete
No copy constructor.
GeoGridReader & operator= (const GeoGridReader &)=delete
No copy assignment.
virtual ~GeoGridReader ()=default
Default destructor.
Private Member Functions
std::shared_ptr< Location > ParseLocation (boost::property_tree::ptree &location)
Create a Location based on the information stored in the provided boost property tree.
Coordinate ParseCoordinate (boost::property_tree::ptree &coordinate)
Create a Coordinate based on the information stored in the provided boost property tree.
std::shared_ptr< ContactCenter > ParseContactCenter (boost::property_tree::ptree &contactCenter)
Create a ContactCenter based on the information stored in the provided boost property tree.
stride::ContactPool * ParseContactPool (boost::property_tree::ptree &contactPool, stride::ContactPoolType::Id typeId)
Create a ContactCenter based on the information stored in the provided boost property tree.
stride::Person * ParsePerson (boost::property_tree::ptree &person)
Create a Person based on the information stored in the provided boost property tree.
Private Attributes
std::shared_ptr< GeoGrid > m_geoGrid
The GeoGrid which is being built.
Additional Inherited Members
Protected Member Functions inherited from gengeopop::GeoGridReader
void AddCommutes (std::shared_ptr< GeoGrid > geoGrid)
Add the commutes that were found to their respective Locations symmetrically.
Protected Attributes inherited from gengeopop::GeoGridReader
std::map< unsigned int, stride::Person * > m_people
Commutes from, to, number.
std::vector< std::tuple< unsigned int, unsigned int, double > > m_commutes
std::unique_ptr< std::istream > m_inputStream
file to read.
stride::Population * m_population
population to use in the GeoGrid may be nullptr.
Detailed Description
An implementation of the GeoGridReader using JSON This class is used to read a GeoGrid from a JSON file.
Definition at line 26 of file GeoGridJSONReader.h.
Constructor & Destructor Documentation
gengeopop::GeoGridJSONReader::GeoGridJSONReader (std::unique_ptr< std::istream > inputStream, stride::Population * pop)
Construct the GeoGridJSONReader with the istream which contains the JSON.
Definition at line 36 of file GeoGridJSONReader.cpp.
gengeopop::GeoGridJSONReader::GeoGridJSONReader (const GeoGridJSONReader &) delete
No copy constructor.
Member Function Documentation
shared_ptr< GeoGrid > gengeopop::GeoGridJSONReader::Read () virtual
Actually perform the read and return the GeoGrid.
Implements gengeopop::GeoGridReader.
Definition at line 41 of file GeoGridJSONReader.cpp.
References gengeopop::GeoGridReader::AddCommutes(), stride::Person::GetId(), gengeopop::GeoGridReader::m_commutes, m_geoGrid, gengeopop::GeoGridReader::m_inputStream, gengeopop::GeoGridReader::m_people, gengeopop::GeoGridReader::m_population, ParseLocation(), and ParsePerson().
GeoGridJSONReader gengeopop::GeoGridJSONReader::operator= (const GeoGridJSONReader &) delete
No copy assignement.
shared_ptr< Location > gengeopop::GeoGridJSONReader::ParseLocation (boost::property_tree::ptree & location) private
Create a Location based on the information stored in the provided boost property tree.
Definition at line 91 of file GeoGridJSONReader.cpp.
References gengeopop::GeoGridReader::m_commutes, ParseContactCenter(), and ParseCoordinate().
Referenced by Read().
Coordinate gengeopop::GeoGridJSONReader::ParseCoordinate (boost::property_tree::ptree & coordinate) private
Create a Coordinate based on the information stored in the provided boost property tree.
Definition at line 133 of file GeoGridJSONReader.cpp.
Referenced by ParseLocation().
shared_ptr< ContactCenter > gengeopop::GeoGridJSONReader::ParseContactCenter (boost::property_tree::ptree & contactCenter) private
Create a ContactCenter based on the information stored in the provided boost property tree.
Definition at line 140 of file GeoGridJSONReader.cpp.
References stride::ContactPoolType::College, stride::ContactPoolType::Household, stride::ContactPoolType::K12School, ParseContactPool(), stride::ContactPoolType::PrimaryCommunity, stride::ContactPoolType::SecondaryCommunity, and stride::ContactPoolType::Work.
Referenced by ParseLocation().
stride::ContactPool * gengeopop::GeoGridJSONReader::ParseContactPool (boost::property_tree::ptree & contactPool, stride::ContactPoolType::Id typeId) private
Create a ContactCenter based on the information stored in the provided boost property tree.
Definition at line 193 of file GeoGridJSONReader.cpp.
References m_geoGrid, and gengeopop::GeoGridReader::m_people.
Referenced by ParseContactCenter().
stride::Person * gengeopop::GeoGridJSONReader::ParsePerson (boost::property_tree::ptree & person) private
Create a Person based on the information stored in the provided boost property tree.
Definition at line 212 of file GeoGridJSONReader.cpp.
References m_geoGrid.
Referenced by Read().
Member Data Documentation
std::shared_ptr<GeoGrid> gengeopop::GeoGridJSONReader::m_geoGrid private
The GeoGrid which is being built.
Definition at line 59 of file GeoGridJSONReader.h.
Referenced by ParseContactPool(), ParsePerson(), and Read().
The documentation for this class was generated from the following files:
GeoGridJSONReader.h
GeoGridJSONReader.cpp