Stride Reference Manual: stride::util::RunConfigManager Class Reference
stride::util::RunConfigManager Class Reference
Produce run config ptree.
#include <RunConfigManager.h>
Static Public Member Functions
static void AddGeoPopConfig (boost::property_tree::ptree &pt)
Adapt the configuration by adding the gengeopop data items.
static void CleanConfigFile (boost::property_tree::ptree pt)
Clean (i.e. indent, sort and produde the sha1) the ptree config file.
static boost::property_tree::ptree Create (const std::string &configName)
Produce property tree for config with given name.
static std::vector< unsigned int > CreateNumThreads (unsigned int maxNum=ConfigInfo::NumberAvailableThreads())
Set of threadcounts to use for tests based an nomber of available OpenMP threads.
static boost::property_tree::ptree FromString (const std::string &s)
Reconstitute property tree from string representation.
static std::string ToString (const boost::property_tree::ptree &pt)
Produce string representation of property tree.
static std::string ToSha1 (const boost::property_tree::ptree &pt)
Produce the sha1 hash of property tree (of it's string representation).
static std::string ToShortSha1 (const boost::property_tree::ptree &pt, unsigned int n=7U)
Produce the short sha1 hash of property tree (of it's string representation).
Static Private Member Functions
static std::string CreateBenchInfluenza ()
Produce Influenza config for Benchmarking.
static std::string CreateBenchMeasles ()
Produce Measles config for Benchmarking.
static std::string CreateDefault ()
Produce the deefault config.
static std::string CreateTestsInfluenza ()
Produce Influenza config for scenario tests.
static std::string CreateTestsMeasles ()
Produce Measles config for scenario tests.
Detailed Description
Produce run config ptree.
Definition at line 35 of file RunConfigManager.h.
Member Function Documentation
void stride::util::RunConfigManager::AddGeoPopConfig (boost::property_tree::ptree & pt) static
Adapt the configuration by adding the gengeopop data items.
Definition at line 62 of file RunConfigManager.cpp.
References stride::util::FromString().
void stride::util::RunConfigManager::CleanConfigFile (boost::property_tree::ptree pt) static
Clean (i.e. indent, sort and produde the sha1) the ptree config file.
Definition at line 40 of file RunConfigManager.cpp.
ptree stride::util::RunConfigManager::Create (const std::string & configName) static
Produce property tree for config with given name.
Definition at line 49 of file RunConfigManager.cpp.
References stride::util::FromString().
vector< unsigned int > stride::util::RunConfigManager::CreateNumThreads (unsigned int maxNum = ConfigInfo::NumberAvailableThreads()) static
Set of threadcounts to use for tests based an nomber of available OpenMP threads.
Definition at line 192 of file RunConfigManager.cpp.
ptree stride::util::RunConfigManager::FromString (const std::string & s) static
Reconstitute property tree from string representation.
Definition at line 290 of file RunConfigManager.cpp.
Referenced by stride::Sim::Create(), and stride::Population::Create().
string stride::util::RunConfigManager::ToString (const boost::property_tree::ptree & pt) static
Produce string representation of property tree.
Definition at line 298 of file RunConfigManager.cpp.
std::string stride::util::RunConfigManager::ToSha1 (const boost::property_tree::ptree & pt) static
Produce the sha1 hash of property tree (of it's string representation).
Definition at line 305 of file RunConfigManager.cpp.
References stride::ContactLogMode::ToString().
std::string stride::util::RunConfigManager::ToShortSha1 (const boost::property_tree::ptree & pt, unsigned int n = 7U) static
Produce the short sha1 hash of property tree (of it's string representation).
Definition at line 307 of file RunConfigManager.cpp.
string stride::util::RunConfigManager::CreateBenchInfluenza () static private
Produce Influenza config for Benchmarking.
Definition at line 86 of file RunConfigManager.cpp.
string stride::util::RunConfigManager::CreateBenchMeasles () static private
Produce Measles config for Benchmarking.
Definition at line 119 of file RunConfigManager.cpp.
string stride::util::RunConfigManager::CreateDefault () static private
Produce the deefault config.
Definition at line 153 of file RunConfigManager.cpp.
string stride::util::RunConfigManager::CreateTestsInfluenza () static private
Produce Influenza config for scenario tests.
Definition at line 224 of file RunConfigManager.cpp.
string stride::util::RunConfigManager::CreateTestsMeasles () static private
Produce Measles config for scenario tests.
Definition at line 257 of file RunConfigManager.cpp.
The documentation for this class was generated from the following files:
RunConfigManager.h
RunConfigManager.cpp