Stride Reference Manual: stride::Person Class Reference
stride::Person Class Reference
Store and handle person data.
#include <Person.h>
Public Member Functions
Person ()
Default construction (for population vector).
Person (unsigned int id, double age, unsigned int householdId, unsigned int k12SchoolId, unsigned int collegeId, unsigned int workId, unsigned int primaryCommunityId, unsigned int secondaryCommunityId)
Constructor: set the person data.
bool operator!= (const Person &p) const
Is this person not equal to the given person?
double GetAge () const
Get the age.
Belief * GetBelief ()
Return belief info.
const Belief * GetBelief () const
Return belief info.
unsigned int GetPoolId (const ContactPoolType::Id &poolType) const
Get ID of contactpool_type.
char GetGender () const
Return person's gender.
Health & GetHealth ()
Return person's health status.
const Health & GetHealth () const
Return person's health status.
unsigned int GetId () const
Get the id.
void SetId (unsigned int id)
Set the id.
bool IsInPool (const ContactPoolType::Id &poolType) const
Check if a person is present today in a given contact pool.
bool IsSurveyParticipant () const
Does this person participates in the social contact study?
void ParticipateInSurvey ()
Participate in social contact study and log person details.
void SetBelief (Belief *belief)
Set the beliefs. Pointer into Population's beliefcontainer.
void Update (bool isWorkOff, bool isSchoolOff, bool adaptiveSymptomaticBehavior)
Update the health status and presence in contact pools.
void Update (Person *p)
void SetAge (unsigned int newAge)
Set the age of the person.
unsigned int GetHouseholdId ()
void SetHouseholdId (unsigned int household_id)
unsigned int GetK12SchoolId () const
Returns the id of the K12School CP.
void SetK12SchoolId (unsigned int k12school_id)
Sets the id of the K12School CP.
unsigned int GetCollegeId () const
Returns the id of the College CP.
void SetCollegeId (unsigned int college_id)
Sets the id of the College CP.
unsigned int GetWorkId () const
Gets the id of the Work CP.
void SetWorkId (unsigned int work_id)
Sets the id of the Work CP.
unsigned int GetPrimaryCommunityId () const
Returns the id of the PrimaryCommunity CP.
void SetPrimaryCommunityId (unsigned int primary_community_id)
Sets the id of the PrimaryCommunity CP.
unsigned int GetSecondaryCommunityId () const
Returns the id of the SecondaryCommunity CP.
void SetSecondaryCommunityId (unsigned int secondary_community_id)
Sets the id of the SecondaryCommunity CP.
void SetPoolId (ContactPoolType::Id type, unsigned int poolId)
Sets the id of the type CP.
bool IsStudentCandidate () const
Returns whether this person may be a K12School student.
bool IsCollegeStudentCandidate () const
Returns whether this person may be a college student.
bool IsWorkableCandidate () const
Returns whether this person may be a college worker.
Private Attributes
double m_age
The age.
Belief * m_belief
Health beliefs related data (raw pointer intentional).
char m_gender
Health m_health
Health info for this person.
unsigned int m_id
The id.
bool m_is_participant
Is participating in the social contact study.
ContactPoolType::IdSubscriptArray< unsigned int > m_pool_ids
Is person present/absent in pools of each of the types (school, work, etc)?
ContactPoolType::IdSubscriptArray< bool > m_in_pools
Detailed Description
Store and handle person data.
Definition at line 36 of file Person.h.
Constructor & Destructor Documentation
stride::Person::Person () inline
Default construction (for population vector).
Definition at line 40 of file Person.h.
stride::Person::Person (unsigned int id, double age, unsigned int householdId, unsigned int k12SchoolId, unsigned int collegeId, unsigned int workId, unsigned int primaryCommunityId, unsigned int secondaryCommunityId) inline
Constructor: set the person data.
Definition at line 47 of file Person.h.
References m_in_pools.
Member Function Documentation
bool stride::Person::operator!= (const Person & p) const inline
Is this person not equal to the given person?
Definition at line 57 of file Person.h.
References m_id.
double stride::Person::GetAge () const inline
Get the age.
Definition at line 60 of file Person.h.
References m_age.
Referenced by stride::Immunizer::Random(), stride::SurveySeeder::Seed(), stride::DiseaseSeeder::Seed(), gengeopop::GeoGridJSONWriter::WritePerson(), and gengeopop::GeoGridProtoWriter::WritePerson().
Belief* stride::Person::GetBelief () inline
Return belief info.
Definition at line 63 of file Person.h.
References m_belief.
const Belief* stride::Person::GetBelief () const inline
Return belief info.
Definition at line 66 of file Person.h.
References m_belief.
unsigned int stride::Person::GetPoolId (const ContactPoolType::Id & poolType) const inline
Get ID of contactpool_type.
Definition at line 69 of file Person.h.
References m_pool_ids.
Referenced by GetCollegeId(), GetHouseholdId(), GetK12SchoolId(), GetPrimaryCommunityId(), GetSecondaryCommunityId(), GetWorkId(), and stride::SurveySeeder::Seed().
char stride::Person::GetGender () const inline
Return person's gender.
Definition at line 72 of file Person.h.
References m_gender.
Referenced by stride::SurveySeeder::Seed(), gengeopop::GeoGridJSONWriter::WritePerson(), and gengeopop::GeoGridProtoWriter::WritePerson().
Health& stride::Person::GetHealth () inline
Return person's health status.
Definition at line 75 of file Person.h.
References m_health.
Referenced by stride::Infector< LL, TIC, TO >::Exec(), stride::Infector< LL, TIC, true >::Exec(), stride::Immunizer::Random(), stride::DiseaseSeeder::Seed(), and stride::SurveySeeder::Seed().
const Health& stride::Person::GetHealth () const inline
Return person's health status.
Definition at line 78 of file Person.h.
References m_health.
unsigned int stride::Person::GetId () const inline
Get the id.
Definition at line 81 of file Person.h.
References m_id.
Referenced by gengeopop::GeoGridProtoReader::Read(), stride::SurveySeeder::Seed(), stride::DiseaseSeeder::Seed(), gengeopop::GeoGridJSONWriter::WritePerson(), and gengeopop::GeoGridProtoWriter::WritePerson().
void stride::Person::SetId (unsigned int id) inline
Set the id.
Definition at line 84 of file Person.h.
References m_id.
bool stride::Person::IsInPool (const ContactPoolType::Id & poolType) const inline
Check if a person is present today in a given contact pool.
Definition at line 87 of file Person.h.
References m_in_pools.
Referenced by stride::Infector< LL, TIC, TO >::Exec(), and stride::Infector< LL, TIC, true >::Exec().
bool stride::Person::IsSurveyParticipant () const inline
Does this person participates in the social contact study?
Definition at line 90 of file Person.h.
References m_is_participant.
Referenced by stride::SurveySeeder::Seed().
void stride::Person::ParticipateInSurvey () inline
Participate in social contact study and log person details.
Definition at line 93 of file Person.h.
References m_is_participant.
Referenced by stride::SurveySeeder::Seed().
void stride::Person::SetBelief (Belief * belief) inline
Set the beliefs. Pointer into Population's beliefcontainer.
Definition at line 96 of file Person.h.
References m_belief, and Update().
void stride::Person::Update (bool isWorkOff, bool isSchoolOff, bool adaptiveSymptomaticBehavior)
Update the health status and presence in contact pools.
Definition at line 31 of file Person.cpp.
References stride::MinAdultAge().
Referenced by SetBelief().
void stride::Person::Update (Person * p)
Definition at line 58 of file Person.cpp.
void stride::Person::SetAge (unsigned int newAge) inline
Set the age of the person.
Definition at line 105 of file Person.h.
References m_age.
Referenced by gengeopop::HouseholdCSVReader::SetReferenceHouseholds().
unsigned int stride::Person::GetHouseholdId () inline
Definition at line 107 of file Person.h.
References GetPoolId(), and stride::ContactPoolType::Household.
Referenced by gengeopop::GeoGridJSONWriter::WritePerson().
void stride::Person::SetHouseholdId (unsigned int household_id) inline
Definition at line 109 of file Person.h.
References stride::ContactPoolType::Household, and SetPoolId().
unsigned int stride::Person::GetK12SchoolId () const inline
Returns the id of the K12School CP.
Definition at line 112 of file Person.h.
References GetPoolId(), and stride::ContactPoolType::K12School.
Referenced by gengeopop::GeoGridJSONWriter::WritePerson().
void stride::Person::SetK12SchoolId (unsigned int k12school_id) inline
Sets the id of the K12School CP.
Definition at line 115 of file Person.h.
References stride::ContactPoolType::K12School, and SetPoolId().
unsigned int stride::Person::GetCollegeId () const inline
Returns the id of the College CP.
Definition at line 118 of file Person.h.
References stride::ContactPoolType::College, and GetPoolId().
Referenced by gengeopop::GeoGridJSONWriter::WritePerson().
void stride::Person::SetCollegeId (unsigned int college_id) inline
Sets the id of the College CP.
Definition at line 121 of file Person.h.
References stride::ContactPoolType::College, and SetPoolId().
unsigned int stride::Person::GetWorkId () const inline
Gets the id of the Work CP.
Definition at line 124 of file Person.h.
References GetPoolId(), and stride::ContactPoolType::Work.
Referenced by gengeopop::GeoGridJSONWriter::WritePerson().
void stride::Person::SetWorkId (unsigned int work_id) inline
Sets the id of the Work CP.
Definition at line 127 of file Person.h.
References SetPoolId(), and stride::ContactPoolType::Work.
Referenced by gengeopop::WorkplacePopulator::AssignActive().
unsigned int stride::Person::GetPrimaryCommunityId () const inline
Returns the id of the PrimaryCommunity CP.
Definition at line 130 of file Person.h.
References GetPoolId(), and stride::ContactPoolType::PrimaryCommunity.
Referenced by gengeopop::GeoGridJSONWriter::WritePerson().
void stride::Person::SetPrimaryCommunityId (unsigned int primary_community_id) inline
Sets the id of the PrimaryCommunity CP.
Definition at line 133 of file Person.h.
References stride::ContactPoolType::PrimaryCommunity, and SetPoolId().
unsigned int stride::Person::GetSecondaryCommunityId () const inline
Returns the id of the SecondaryCommunity CP.
Definition at line 139 of file Person.h.
References GetPoolId(), and stride::ContactPoolType::SecondaryCommunity.
Referenced by gengeopop::GeoGridJSONWriter::WritePerson().
void stride::Person::SetSecondaryCommunityId (unsigned int secondary_community_id) inline
Sets the id of the SecondaryCommunity CP.
Definition at line 142 of file Person.h.
References stride::ContactPoolType::SecondaryCommunity, and SetPoolId().
void stride::Person::SetPoolId (ContactPoolType::Id type, unsigned int poolId) inline
Sets the id of the type CP.
Definition at line 148 of file Person.h.
References m_in_pools, and m_pool_ids.
Referenced by SetCollegeId(), SetHouseholdId(), SetK12SchoolId(), SetPrimaryCommunityId(), SetSecondaryCommunityId(), and SetWorkId().
bool stride::Person::IsStudentCandidate () const inline
Returns whether this person may be a K12School student.
Definition at line 155 of file Person.h.
bool stride::Person::IsCollegeStudentCandidate () const inline
Returns whether this person may be a college student.
Definition at line 158 of file Person.h.
References m_age.
bool stride::Person::IsWorkableCandidate () const inline
Returns whether this person may be a college worker.
Definition at line 161 of file Person.h.
References m_age.
Member Data Documentation
double stride::Person::m_age private
The age.
Definition at line 164 of file Person.h.
Referenced by GetAge(), IsCollegeStudentCandidate(), IsWorkableCandidate(), and SetAge().
Belief* stride::Person::m_belief private
Health beliefs related data (raw pointer intentional).
Definition at line 165 of file Person.h.
Referenced by GetBelief(), and SetBelief().
char stride::Person::m_gender private
Definition at line 166 of file Person.h.
Referenced by GetGender().
Health stride::Person::m_health private
Health info for this person.
Definition at line 167 of file Person.h.
Referenced by GetHealth().
unsigned int stride::Person::m_id private
The id.
Definition at line 168 of file Person.h.
Referenced by GetId(), operator!=(), and SetId().
bool stride::Person::m_is_participant private
Is participating in the social contact study.
Ids (school, work, etc) of pools you belong to Id value 0 means you do not belong to any pool of that type (e.g. school and work are mutually exclusive.
Definition at line 169 of file Person.h.
Referenced by IsSurveyParticipant(), and ParticipateInSurvey().
ContactPoolType::IdSubscriptArray<unsigned int> stride::Person::m_pool_ids private
Is person present/absent in pools of each of the types (school, work, etc)?
Definition at line 173 of file Person.h.
Referenced by GetPoolId(), and SetPoolId().
ContactPoolType::IdSubscriptArray<bool> stride::Person::m_in_pools private
Definition at line 176 of file Person.h.
Referenced by IsInPool(), Person(), and SetPoolId().
The documentation for this class was generated from the following files:
Person.h
Person.cpp