Stride Reference Manual: stride::viewers::PersonsFileViewer Class Reference
stride::viewers::PersonsFileViewer Class Reference
Viewer of Simulator for cases output.
#include <PersonsFileViewer.h>
Public Member Functions
PersonsFileViewer (std::shared_ptr< SimRunner > runner, const std::string &output_prefix)
Instantiate cases viewer.
void Update (sim_event::Id id)
Let viewer perform update.
Private Attributes
output::PersonsFile m_persons_file
std::shared_ptr< SimRunner > m_runner
Detailed Description
Viewer of Simulator for cases output.
Definition at line 35 of file PersonsFileViewer.h.
Constructor & Destructor Documentation
stride::viewers::PersonsFileViewer::PersonsFileViewer (std::shared_ptr< SimRunner > runner, const std::string & output_prefix) inline
Instantiate cases viewer.
Definition at line 39 of file PersonsFileViewer.h.
References Update().
Member Function Documentation
void stride::viewers::PersonsFileViewer::Update (sim_event::Id id)
Let viewer perform update.
Definition at line 31 of file PersonsFileViewer.cpp.
Referenced by PersonsFileViewer(), and stride::ControlHelper::RegisterViewers().
Member Data Documentation
output::PersonsFile stride::viewers::PersonsFileViewer::m_persons_file private
Definition at line 48 of file PersonsFileViewer.h.
std::shared_ptr<SimRunner> stride::viewers::PersonsFileViewer::m_runner private
Definition at line 49 of file PersonsFileViewer.h.
The documentation for this class was generated from the following files:
PersonsFileViewer.h
PersonsFileViewer.cpp