Stride Reference Manual: stride::ContactLogMode Namespace Reference
stride::ContactLogMode Namespace Reference
Enum specifiying the level of logging required:
Enumerations
enum Id { Id::None = 0U, Id::Transmissions = 1U, Id::All = 2U, Id::Susceptibles = 3U }
Functions
string ToString (ContactLogMode::Id w)
Converts a LogMode value to corresponding name.
Id ToMode (const std::string &s)
Converts a string with name to LogMode value.
bool IsMode (const std::string &s)
Check whether string is name of LogMode value.
Detailed Description
Enum specifiying the level of logging required:
none at all
only contacts where transmission occurs
all contacts.
Enumeration Type Documentation
enum stride::ContactLogMode::Id strong
Enumerator
None
Transmissions
All
Susceptibles
Definition at line 34 of file ContactLogMode.h.
Function Documentation
std::string stride::ContactLogMode::ToString (Id l)
Converts a LogMode value to corresponding name.
Definition at line 32 of file ContactLogMode.cpp.
References All, None, Susceptibles, and Transmissions.
Referenced by stride::ControlHelper::LogStartup(), geopop::GeoGridJSONReader::ParseContactCenter(), stride::PublicHealthAgency::PerformCaseFinding(), stride::util::RunConfigManager::ToSha1(), and geopop::GeoGridJSONWriter::WriteContactCenter().
ContactLogMode::Id stride::ContactLogMode::ToMode (const string & s)
Converts a string with name to LogMode value.
Definition at line 39 of file ContactLogMode.cpp.
References All, None, Susceptibles, and Transmissions.
Referenced by stride::SimBuilder::Build().
bool stride::ContactLogMode::IsMode (const std::string & s)
Check whether string is name of LogMode value.