Stride Reference Manual: gengeopop::GeoGrid Class Reference
gengeopop::GeoGrid Class Reference
A Geographic information grid for a single region.
#include <GeoGrid.h>
Public Types
using iterator = std::vector< std::shared_ptr< Location >>::iterator
using const_iterator = std::vector< std::shared_ptr< Location >>::const_iterator
Public Member Functions
GeoGrid (stride::Population *population)
Construct with information about population.
GeoGrid (const GeoGrid &)=delete
No copy constructor.
GeoGrid operator= (const GeoGrid &)=delete
No copy assignment.
void AddLocation (std::shared_ptr< Location > location)
Adds a location to this GeoGrid.
void Finalize ()
Disables the addLocation method and builds the kdtree.
std::vector< std::shared_ptr< Location > > FindLocationsInRadius (std::shared_ptr< Location > start, double radius) const
Search for locations in radius around start.
std::vector< std::shared_ptr< Location > > TopK (size_t k) const
Gets the K biggest Location of this GeoGrid.
std::set< std::shared_ptr< Location > > InBox (double long1, double lat1, double long2, double lat2) const
Gets the locations in a rectangle determined by the two coordinates (long1, lat1) and (long2, lat2).
std::set< std::shared_ptr< Location > > InBox (const std::shared_ptr< Location > &loc1, const std::shared_ptr< Location > &loc2) const
Gets the location in a rectangle defined by the two locations.
size_t size () const
Gets amount of Location.
void remove (const std::shared_ptr< Location > &location)
Remove element of GeoGrid.
std::shared_ptr< Location > operator[] (size_t index)
Gets a Location by index, doesn't performs a range check.
std::shared_ptr< Location > Get (size_t index)
Gets a Location by index, doesn't performs a range check.
std::shared_ptr< Location > GetById (unsigned int id)
Gets a Location by id and check if the id exists.
template<typename... Args>
stride::Person * CreatePerson (Args &&...args)
Create and store a Person in the GeoGrid and return a pointer to it, which works until deletion of the GeoGrid.
stride::ContactPool * CreateContactPool (stride::ContactPoolType::Id type)
Create a ContactPool of the given type and return a non-owning pointer.
stride::Population * GetPopulation ()
Get the population of this GeoGrid.
template<typename Policy , typename F >
GeoAggregator< Policy, F > BuildAggregator (F functor, typename Policy::Args &&args) const
Build a GeoAggregator with a predefined functor and given args for the Policy.
template<typename Policy >
GeoAggregator< Policy > BuildAggregator (typename Policy::Args &&args) const
Build a GeoAggregator that gets its functor when calling, with given args for the Policy.
iterator begin ()
Iterator to first Location.
iterator end ()
Iterator to the end of the Location storage.
const_iterator cbegin () const
Const Iterator to first Location.
const_iterator cend () const
Const iterator to the end of the Location storage.
Private Member Functions
void CheckFinalized (const std::string &functionName) const
Checks whether the GeoGrid is finalized and thus certain operations can(not) be used.
Private Attributes
std::vector< std::shared_ptr< Location > > m_locations
Locations in this geoGrid.
std::unordered_map< unsigned int, std::shared_ptr< Location > > m_locationsToIdIndex
Locations in this geoGrid indexed by Id.
stride::Population * m_population
Stores, but does not take ownership.
bool m_finalized
Is this finalized yet?
KdTree< geogrid_detail::KdTree2DPoint > m_tree
Internal KdTree for quick spatial lookup.
Detailed Description
A Geographic information grid for a single region.
Definition at line 107 of file GeoGrid.h.
Member Typedef Documentation
using gengeopop::GeoGrid::iterator = std::vector<std::shared_ptr<Location>>::iterator
Definition at line 192 of file GeoGrid.h.
using gengeopop::GeoGrid::const_iterator = std::vector<std::shared_ptr<Location>>::const_iterator
Definition at line 193 of file GeoGrid.h.
Constructor & Destructor Documentation
gengeopop::GeoGrid::GeoGrid (stride::Population * population) explicit
Construct with information about population.
Definition at line 26 of file GeoGrid.cpp.
gengeopop::GeoGrid::GeoGrid (const GeoGrid &) delete
No copy constructor.
Member Function Documentation
GeoGrid gengeopop::GeoGrid::operator= (const GeoGrid &) delete
No copy assignment.
void gengeopop::GeoGrid::AddLocation (std::shared_ptr< Location > location)
Adds a location to this GeoGrid.
Definition at line 32 of file GeoGrid.cpp.
References m_finalized, m_locations, and m_locationsToIdIndex.
void gengeopop::GeoGrid::Finalize ()
Disables the addLocation method and builds the kdtree.
Definition at line 83 of file GeoGrid.cpp.
References begin(), gengeopop::KdTree< P >::Build(), end(), m_finalized, and m_tree.
std::vector< std::shared_ptr< Location > > gengeopop::GeoGrid::FindLocationsInRadius (std::shared_ptr< Location > start, double radius) const
Search for locations in radius around start.
Definition at line 106 of file GeoGrid.cpp.
References CheckFinalized(), and gengeopop::MakeCollector().
std::vector< std::shared_ptr< Location > > gengeopop::GeoGrid::TopK (size_t k) const
Gets the K biggest Location of this GeoGrid.
Definition at line 46 of file GeoGrid.cpp.
References cbegin(), and cend().
std::set< std::shared_ptr< Location > > gengeopop::GeoGrid::InBox (double long1, double lat1, double long2, double lat2) const
Gets the locations in a rectangle determined by the two coordinates (long1, lat1) and (long2, lat2).
The coordinates must be position on the diagonal, i.e:
p1 --—+ +----—p1 | | | | | | or | | | | | | +----—p2 p2---—+
Definition at line 94 of file GeoGrid.cpp.
References CheckFinalized(), and gengeopop::MakeCollector().
std::set<std::shared_ptr<Location> > gengeopop::GeoGrid::InBox (const std::shared_ptr< Location > & loc1, const std::shared_ptr< Location > & loc2) const inline
Gets the location in a rectangle defined by the two locations.
Definition at line 146 of file GeoGrid.h.
References gengeopop::geogrid_detail::KdTree2DPoint::Get(), and gengeopop::geogrid_detail::KdTree2DPoint::InBox().
size_t gengeopop::GeoGrid::size () const
Gets amount of Location.
Definition at line 73 of file GeoGrid.cpp.
References m_locations.
void gengeopop::GeoGrid::remove (const std::shared_ptr< Location > & location)
Remove element of GeoGrid.
Definition at line 77 of file GeoGrid.cpp.
References m_locations, and m_locationsToIdIndex.
std::shared_ptr< Location > gengeopop::GeoGrid::operator[] (size_t index)
Gets a Location by index, doesn't performs a range check.
Definition at line 42 of file GeoGrid.cpp.
References begin().
std::shared_ptr< Location > gengeopop::GeoGrid::Get (size_t index)
Gets a Location by index, doesn't performs a range check.
Definition at line 44 of file GeoGrid.cpp.
std::shared_ptr< Location > gengeopop::GeoGrid::GetById (unsigned int id)
Gets a Location by id and check if the id exists.
Definition at line 75 of file GeoGrid.cpp.
References m_locationsToIdIndex.
template<typename... Args> stride::Person* gengeopop::GeoGrid::CreatePerson (Args &&... args) inline
Create and store a Person in the GeoGrid and return a pointer to it, which works until deletion of the GeoGrid.
Definition at line 172 of file GeoGrid.h.
stride::ContactPool * gengeopop::GeoGrid::CreateContactPool (stride::ContactPoolType::Id type)
Create a ContactPool of the given type and return a non-owning pointer.
Definition at line 130 of file GeoGrid.cpp.
References stride::Population::CreateContactPool(), and m_population.
stride::Population * gengeopop::GeoGrid::GetPopulation ()
Get the population of this GeoGrid.
Definition at line 120 of file GeoGrid.cpp.
References m_population.
template<typename Policy , typename F > GeoAggregator< Policy, F > gengeopop::GeoGrid::BuildAggregator (F functor, typename Policy::Args && args) const
Build a GeoAggregator with a predefined functor and given args for the Policy.
Definition at line 230 of file GeoGrid.h.
template<typename Policy > GeoAggregator< Policy > gengeopop::GeoGrid::BuildAggregator (typename Policy::Args && args) const
Build a GeoAggregator that gets its functor when calling, with given args for the Policy.
Definition at line 236 of file GeoGrid.h.
iterator gengeopop::GeoGrid::begin () inline
Iterator to first Location.
Definition at line 196 of file GeoGrid.h.
Referenced by Finalize(), and operator[]().
iterator gengeopop::GeoGrid::end () inline
Iterator to the end of the Location storage.
Definition at line 199 of file GeoGrid.h.
Referenced by Finalize().
const_iterator gengeopop::GeoGrid::cbegin () const inline
Const Iterator to first Location.
Definition at line 202 of file GeoGrid.h.
Referenced by TopK().
const_iterator gengeopop::GeoGrid::cend () const inline
Const iterator to the end of the Location storage.
Definition at line 205 of file GeoGrid.h.
Referenced by TopK().
void gengeopop::GeoGrid::CheckFinalized (const std::string & functionName) const private
Checks whether the GeoGrid is finalized and thus certain operations can(not) be used.
Definition at line 122 of file GeoGrid.cpp.
References m_finalized.
Referenced by FindLocationsInRadius(), and InBox().
Member Data Documentation
std::vector<std::shared_ptr<Location> > gengeopop::GeoGrid::m_locations private
Locations in this geoGrid.
Definition at line 212 of file GeoGrid.h.
Referenced by AddLocation(), remove(), and size().
std::unordered_map<unsigned int, std::shared_ptr<Location> > gengeopop::GeoGrid::m_locationsToIdIndex private
Locations in this geoGrid indexed by Id.
Definition at line 214 of file GeoGrid.h.
Referenced by AddLocation(), GetById(), and remove().
stride::Population* gengeopop::GeoGrid::m_population private
Stores, but does not take ownership.
Definition at line 216 of file GeoGrid.h.
Referenced by CreateContactPool(), and GetPopulation().
bool gengeopop::GeoGrid::m_finalized private
Is this finalized yet?
Definition at line 218 of file GeoGrid.h.
Referenced by AddLocation(), CheckFinalized(), and Finalize().
KdTree<geogrid_detail::KdTree2DPoint> gengeopop::GeoGrid::m_tree private
Internal KdTree for quick spatial lookup.
Definition at line 220 of file GeoGrid.h.
Referenced by Finalize().
The documentation for this class was generated from the following files:
GeoGrid.h
GeoGrid.cpp