Stride Reference Manual: geopop::Generator< ID > Class Template Reference
geopop::Generator< ID > Class Template Reference
Generator uses geo & pop data to construct ContactPools in the GeoGrid.
#include <Generator.h>
Public Member Functions
Generator (stride::util::RnMan rnMan, std::shared_ptr< spdlog::logger > logger=nullptr)
Constructor with random number manager and logger.
~Generator ()=default
Default is OK.
void Apply (GeoGrid &, const GeoGridConfig &)
Generate ContactPools for ContactType::Id as sepcified by data in GeoGridConfig.
void AddPools (Location &loc, stride::Population *pop, const GeoGridConfig &ggConfig)
Create a given number ContactPools in the GeoGrid.
template<>
void Apply (GeoGrid &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid &geoGrid, const GeoGridConfig &ggConfig)
Protected Attributes
stride::util::RnMan m_rn_man
RnManager used by generators.
std::shared_ptr< spdlog::logger > m_logger
Logger used by generators.
Detailed Description
template<typename stride::ContactType::Id ID>
class geopop::Generator< ID >
Generator uses geo & pop data to construct ContactPools in the GeoGrid.
Definition at line 37 of file Generator.h.
Constructor & Destructor Documentation
template<typename stride::ContactType::Id ID> geopop::Generator< ID >::Generator (stride::util::RnMan rnMan, std::shared_ptr< spdlog::logger > logger = nullptr) inline explicit
Constructor with random number manager and logger.
Definition at line 41 of file Generator.h.
References stride::util::LogUtils::CreateNullLogger(), geopop::Generator< ID >::m_logger, and geopop::Generator< ID >::~Generator().
template<typename stride::ContactType::Id ID> geopop::Generator< ID >::~Generator () default
Default is OK.
Referenced by geopop::Generator< ID >::Generator().
Member Function Documentation
template<typename stride::ContactType::Id ID> void geopop::Generator< ID >::Apply (GeoGrid & , const GeoGridConfig &) inline
Generate ContactPools for ContactType::Id as sepcified by data in GeoGridConfig.
Definition at line 52 of file Generator.h.
template<typename stride::ContactType::Id ID> void geopop::Generator< ID >::AddPools (Location & loc, stride::Population * pop, const GeoGridConfig & ggConfig) inline
Create a given number ContactPools in the GeoGrid.
Definition at line 55 of file Generator.h.
References stride::ContactPoolSys::CreateContactPool(), geopop::GeoGridConfig::pools, stride::Population::RefPoolSys(), and geopop::Location::RegisterPool().
template<> void geopop::Generator< stride::ContactType::Id::College >::Apply (GeoGrid & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 27 of file CollegeGenerator.cpp.
References AssertThrow, geopop::GeoGrid::GetPopulation(), geopop::GeoGridConfig::info, geopop::GeoGridConfig::people, geopop::GeoGridConfig::popcount_college, and geopop::GeoGrid::TopK().
template<> void geopop::Generator< stride::ContactType::Id::K12School >::Apply (GeoGrid & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Generator< stride::ContactType::Id::College >::Apply (GeoGrid & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Generator< stride::ContactType::Id::Workplace >::Apply (GeoGrid & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Generator< stride::ContactType::Id::Household >::Apply (GeoGrid & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Generator< stride::ContactType::Id::PrimaryCommunity >::Apply (GeoGrid & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Generator< stride::ContactType::Id::SecondaryCommunity >::Apply (GeoGrid & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Generator< stride::ContactType::Id::Household >::Apply (GeoGrid & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 25 of file HouseholdGenerator.cpp.
References geopop::GeoGridConfig::count_households, and geopop::GeoGridConfig::info.
template<> void geopop::Generator< stride::ContactType::Id::K12School >::Apply (GeoGrid & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 25 of file K12SchoolGenerator.cpp.
References geopop::GeoGridConfig::info, geopop::GeoGridConfig::people, and geopop::GeoGridConfig::popcount_k12school.
template<> void geopop::Generator< stride::ContactType::Id::PrimaryCommunity >::Apply (GeoGrid & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 31 of file PrimaryCommunityGenerator.cpp.
References AssertThrow, geopop::GeoGridConfig::param, geopop::GeoGridConfig::people, and geopop::GeoGridConfig::pop_size.
template<> void geopop::Generator< stride::ContactType::Id::SecondaryCommunity >::Apply (GeoGrid & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 31 of file SecondaryCommunityGenerator.cpp.
References AssertThrow, geopop::GeoGridConfig::param, geopop::GeoGridConfig::people, and geopop::GeoGridConfig::pop_size.
template<> void geopop::Generator< stride::ContactType::Id::Workplace >::Apply (GeoGrid & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 27 of file WorkplaceGenerator.cpp.
References AssertThrow, geopop::GeoGridConfig::fraction_workplace_commuters, geopop::GeoGridConfig::info, geopop::GeoGridConfig::param, geopop::GeoGridConfig::particpation_workplace, geopop::GeoGridConfig::people, and geopop::GeoGridConfig::popcount_workplace.
Member Data Documentation
template<typename stride::ContactType::Id ID> stride::util::RnMan geopop::Generator< ID >::m_rn_man protected
RnManager used by generators.
Definition at line 65 of file Generator.h.
template<typename stride::ContactType::Id ID> std::shared_ptr<spdlog::logger> geopop::Generator< ID >::m_logger protected
Logger used by generators.
Definition at line 66 of file Generator.h.
Referenced by geopop::Generator< ID >::Generator().
The documentation for this class was generated from the following file:
Generator.h