Stride Reference Manual: stride::GenPopController Class Reference
stride::GenPopController Class Reference
Controls a geo-population generation run initiated with the command line interface (cli).
#include <GenPopController.h>
Public Member Functions
GenPopController (const boost::property_tree::ptree &config, const std::string &name="GenPopController")
Straight initialization.
void Control ()
Actual run of the simulator.
Additional Inherited Members
Protected Member Functions inherited from stride::ControlHelper
ControlHelper ()
Empty controller: used as target for delegation.
void CheckEnv ()
Check install environment.
void CheckOutputPrefix ()
void InstallLogger ()
Make the appropriate logger for cli environment and register as stride_logger.
void LogStartup ()
Logs info on setup for cli environment to stride_logger.
void RegisterViewers (std::shared_ptr< SimRunner > runner)
Register the viewers of the SimRunner.
void Shutdown ()
Logs info on setup for cli environment to stride_logger.
ControlHelper (const boost::property_tree::ptree &config, std::string name)
Straight initialization.
~ControlHelper ()
Simple destructor.
Protected Attributes inherited from stride::ControlHelper
boost::property_tree::ptree m_config
Main configuration for run and sim.
std::string m_name
Contoller's name.
std::string m_output_prefix
Prefix to output (name prefix or prefix dir)
util::Stopwatch m_run_clock
Stopwatch for timing the computation.
std::shared_ptr< spdlog::logger > m_stride_logger
General logger.
bool m_use_install_dirs
Working dir or install dir mode.
Detailed Description
Controls a geo-population generation run initiated with the command line interface (cli).
GeoPopController setup functions include (
See also
ControlHelper):
checks the OpenMP environment
checks the file system environment
interprets and executes the ouput prefix
intalls a stride logger
The GeoPopController execution:
creates a population (
Population)
creates a simulation runner (
SimRunner)
registers the appropriate viewers
runs the simulation
Definition at line 44 of file GenPopController.h.
Constructor & Destructor Documentation
stride::GenPopController::GenPopController (const boost::property_tree::ptree & config, const std::string & name = "GenPopController") explicit
Straight initialization.
Definition at line 52 of file GenPopController.cpp.
Member Function Documentation
void stride::GenPopController::Control ()
Actual run of the simulator.
Definition at line 54 of file GenPopController.cpp.
References stride::GeoPopBuilder::Build(), stride::util::FileSys::BuildPath(), stride::ControlHelper::CheckEnv(), stride::ControlHelper::CheckOutputPrefix(), stride::Population::Create(), geopop::GeoGridWriterFactory::CreateGeoGridWriter(), stride::ControlHelper::InstallLogger(), stride::ControlHelper::LogStartup(), stride::ControlHelper::m_config, and stride::ControlHelper::m_stride_logger.
Referenced by main().
The documentation for this class was generated from the following files:
GenPopController.h
GenPopController.cpp