Stride Reference Manual: stride::Immunizer Class Reference
stride::Immunizer Class Reference
Deals with immunization strategies.
#include <Immunizer.h>
Public Member Functions
Immunizer (util::RnMan &rnManager)
template<typename T >
void Random (T &pools, std::vector< double > &immunityDistribution, double immunityLinkProbability)
Random immunization.
template<typename T >
void Cocoon (const T &, std::vector< double > &, double)
Cocoon immunization.
Private Attributes
util::RnMan & m_rn_manager
Random number manager.
Detailed Description
Deals with immunization strategies.
Definition at line 36 of file Immunizer.h.
Constructor & Destructor Documentation
stride::Immunizer::Immunizer (util::RnMan & rnManager) inline explicit
Definition at line 40 of file Immunizer.h.
Member Function Documentation
template<typename T > void stride::Immunizer::Random (T & pools, std::vector< double > & immunityDistribution, double immunityLinkProbability) inline
Random immunization.
Definition at line 44 of file Immunizer.h.
References stride::Person::GetAge(), stride::Person::GetHealth(), stride::ContactPool::GetMember(), stride::ContactPool::GetSize(), stride::Health::IsImmune(), m_rn_manager, and stride::Health::SetSusceptible().
Referenced by stride::DiseaseSeeder::Vaccinate().
template<typename T > void stride::Immunizer::Cocoon (const T & , std::vector< double > & , double) inline
Cocoon immunization.
Definition at line 102 of file Immunizer.h.
Referenced by stride::DiseaseSeeder::Vaccinate().
Member Data Documentation
util::RnMan& stride::Immunizer::m_rn_manager private
Random number manager.
Definition at line 133 of file Immunizer.h.
Referenced by Random().
The documentation for this class was generated from the following files:
Immunizer.h
Immunizer.cpp