Stride Reference Manual: gengeopop::ReaderFactory Class Reference
gengeopop::ReaderFactory Class Reference
A Factory for creating the correct implementation of the different Readers which parse the information needed to construct a GeoGrid, based on the file extension.
#include <ReaderFactory.h>
Public Member Functions
std::shared_ptr< CitiesReader > CreateCitiesReader (const filesys::path &path)
Create a CitiesReader based on an absolute Filesystem Path pointing to the input file.
std::shared_ptr< CitiesReader > CreateCitiesReader (const std::string &filename)
Create a CitiesReader based on the filename of the input file, relative to the data directory.
std::shared_ptr< CommutesReader > CreateCommutesReader (const std::string &filename)
Create a CommutesReader based on an absolute Filesystem Path pointing to the input file.
std::shared_ptr< CommutesReader > CreateCommutesReader (const filesys::path &path)
Create a CommutesReader based on the filename of the input file, relative to the data directory.
std::shared_ptr< HouseholdReader > CreateHouseholdReader (const std::string &filename)
Create a HouseholdReader based on the filename of the input file, relative to the data directory.
std::shared_ptr< HouseholdReader > CreateHouseholdReader (const filesys::path &path)
Create a HouseholdReader based on an absolute Filesystem Path pointing to the input file.
Private Member Functions
std::unique_ptr< std::istream > OpenFile (const filesys::path &path) const
Create an istream based on the provided Filesystem Path.
Detailed Description
A Factory for creating the correct implementation of the different Readers which parse the information needed to construct a GeoGrid, based on the file extension.
Currently only CSV Readers are implemented.
Definition at line 42 of file ReaderFactory.h.
Member Function Documentation
shared_ptr< CitiesReader > gengeopop::ReaderFactory::CreateCitiesReader (const filesys::path & path)
Create a CitiesReader based on an absolute Filesystem Path pointing to the input file.
Definition at line 37 of file ReaderFactory.cpp.
shared_ptr< CitiesReader > gengeopop::ReaderFactory::CreateCitiesReader (const std::string & filename)
Create a CitiesReader based on the filename of the input file, relative to the data directory.
Definition at line 32 of file ReaderFactory.cpp.
References stride::util::FileSys::GetDataDir().
shared_ptr< CommutesReader > gengeopop::ReaderFactory::CreateCommutesReader (const std::string & filename)
Create a CommutesReader based on an absolute Filesystem Path pointing to the input file.
Definition at line 42 of file ReaderFactory.cpp.
References stride::util::FileSys::GetDataDir().
shared_ptr< CommutesReader > gengeopop::ReaderFactory::CreateCommutesReader (const filesys::path & path)
Create a CommutesReader based on the filename of the input file, relative to the data directory.
Definition at line 47 of file ReaderFactory.cpp.
shared_ptr< HouseholdReader > gengeopop::ReaderFactory::CreateHouseholdReader (const std::string & filename)
Create a HouseholdReader based on the filename of the input file, relative to the data directory.
Definition at line 52 of file ReaderFactory.cpp.
References stride::util::FileSys::GetDataDir().
shared_ptr< HouseholdReader > gengeopop::ReaderFactory::CreateHouseholdReader (const filesys::path & path)
Create a HouseholdReader based on an absolute Filesystem Path pointing to the input file.
Definition at line 57 of file ReaderFactory.cpp.
unique_ptr< istream > gengeopop::ReaderFactory::OpenFile (const filesys::path & path) const private
Create an istream based on the provided Filesystem Path.
Definition at line 62 of file ReaderFactory.cpp.
The documentation for this class was generated from the following files:
ReaderFactory.h
ReaderFactory.cpp