Stride Reference Manual: stride::SimBuilder Class Reference
stride::SimBuilder Class Reference
Builds a simulator (.
#include <SimBuilder.h>
Public Member Functions
SimBuilder (const boost::property_tree::ptree &configPt)
Initializing SimBuilder.
std::shared_ptr< Sim > Build (std::shared_ptr< Sim > sim, std::shared_ptr< Population > pop)
Build the simulator and return it afterwards.
Private Member Functions
boost::property_tree::ptree ReadAgeContactPtree ()
Get the contact configuration data.
boost::property_tree::ptree ReadDiseasePtree ()
Get the disease configuration data.
Private Attributes
boost::property_tree::ptree m_config_pt
Run config in ptree.
Detailed Description
Builds a simulator (.
See Also
Sim) based a configuration property tree. It
reads any additional configuration files (disease, contact, ...)
initializes calendar and random number manager for the simulator
builds a population and contact pool system (
PopulationBuilder)
deals with health and immunity (
HealthSeeder,
DiseaseBuilder)
Definition at line 38 of file SimBuilder.h.
Constructor & Destructor Documentation
stride::SimBuilder::SimBuilder (const boost::property_tree::ptree & configPt) explicit
Initializing SimBuilder.
Definition at line 41 of file SimBuilder.cpp.
Member Function Documentation
shared_ptr< Sim > stride::SimBuilder::Build (std::shared_ptr< Sim > sim, std::shared_ptr< Population > pop)
Build the simulator and return it afterwards.
Definition at line 43 of file SimBuilder.cpp.
References stride::ContactPoolType::IdList, m_config_pt, ReadAgeContactPtree(), ReadDiseasePtree(), stride::BeliefSeeder::Seed(), stride::DiseaseSeeder::Seed(), stride::HealthSeeder::Seed(), and stride::ContactLogMode::ToMode().
ptree stride::SimBuilder::ReadAgeContactPtree () private
Get the contact configuration data.
Definition at line 105 of file SimBuilder.cpp.
References stride::util::FileSys::GetDataDir(), m_config_pt, and stride::util::FileSys::ReadPtreeFile().
Referenced by Build().
ptree stride::SimBuilder::ReadDiseasePtree () private
Get the disease configuration data.
Definition at line 112 of file SimBuilder.cpp.
References stride::util::FileSys::GetDataDir(), m_config_pt, and stride::util::FileSys::ReadPtreeFile().
Referenced by Build().
Member Data Documentation
boost::property_tree::ptree stride::SimBuilder::m_config_pt private
Run config in ptree.
Definition at line 55 of file SimBuilder.h.
Referenced by Build(), ReadAgeContactPtree(), and ReadDiseasePtree().
The documentation for this class was generated from the following files:
SimBuilder.h
SimBuilder.cpp