Stride Reference Manual: stride::util::SegmentedVector< T, N > Class Template Reference
stride::util::SegmentedVector< T, N > Class Template Reference
Container that stores objects "almost contiguously" (in a chain of blocks) and guarantees that pointers/iterators are not invalidated when the container grows.
#include <SegmentedVector.h>
Public Types
using value_type = T
using size_type = std::size_t
using self_type = SegmentedVector< T, N >
using iterator = SVIterator< T, N, T *, T &, false >
using const_iterator = SVIterator< T, N >
Public Member Functions
SegmentedVector (size_type i=0)
Construct with given number of elements but DO NOT INITIALIZE them.
SegmentedVector (const self_type &other)
Copy constructor.
SegmentedVector (self_type &&other) noexcept
Move constructor.
SegmentedVector & operator= (const self_type &other)
Copy assignment.
SegmentedVector & operator= (self_type &&other) noexcept
Move assignment.
~SegmentedVector ()
Destructor.
T & at (std::size_t pos)
Access specified element with bounds checking.
const T & at (std::size_t pos) const
Access specified element with bounds checking.
T & back ()
Access the last element.
const T & back () const
Access the last element.
T & operator[] (size_t pos)
Access specified element (no bounds checking).
const T & operator[] (size_t pos) const
Access specified element (no bounds checking).
iterator begin ()
Returns an iterator to the beginning of the container.
const_iterator begin () const
Returns a const_iterator to the beginning of the container.
const_iterator cbegin () const
Returns a const_iterator to the beginning of the container.
iterator end ()
Returns an iterator to the end of the container.
const_iterator end () const
Returns a const_iterator to the end of the container.
const_iterator cend () const
Returns a const_iterator to the end.
std::size_t capacity () const
Returns number of elements that can be stored without allocating additional blocks.
bool empty () const
Checks whether container is empty.
std::size_t get_block_count () const
Returns number of currently allocated blocks.
std::size_t get_elements_per_block () const
Returns number of elements block (template parameter 'N').
std::size_t size () const
Returns the number of elements.
void resize (size_type new_size)
Increases the number of elements (but DOES NOT INITIALIZE the additional elements) or pops elements (and DOES RUN those element's destructor).
void clear ()
Clears the content.
template<class... Args>
T * emplace (size_type pos, Args &&...args)
Constructs element in-place at position pos.
template<class... Args>
T * emplace_back (Args &&...args)
Constructs element in-place at the end.
void pop_back ()
Removes the last element.
T * push_back (const T &obj)
Adds element to end.
T * push_back (T &&obj)
Adds element to end.
Private Types
using Chunk = typename std::aligned_storage< sizeof(T), std::alignment_of< T >::value >::type
POD type with same alignment requirement as for T's.
Private Member Functions
T * get_chunk ()
Get next available chunk for element construction with placement new.
Private Attributes
std::vector< Chunk * > m_blocks
Vector registers pointers to blocks of chunks.
size_t m_size
Index of first free chunk when indexed contiguously.
Friends
class SVIterator< T, N >
class SVIterator< T, N, T *, T &, false >
Detailed Description
template<typename T, size_t N = 512>
class stride::util::SegmentedVector< T, N >
Container that stores objects "almost contiguously" (in a chain of blocks) and guarantees that pointers/iterators are not invalidated when the container grows.
Elements are assigned to the container either sequentially through push_back and emplace_back or through direct adressing with emplace, at or the subscript operator. It supports most familiar operators except reserve (no need for advance reservation of capacity to avoid re-allocation that invalidates pointers as in std::vector) and insertion/deletion.
Template parameters: T type of elements stored in the container N block size i.e. number of elements per block
Definition at line 50 of file SegmentedVector.h.
Member Typedef Documentation
template<typename T, size_t N = 512> using stride::util::SegmentedVector< T, N >::value_type = T
Definition at line 56 of file SegmentedVector.h.
template<typename T, size_t N = 512> using stride::util::SegmentedVector< T, N >::size_type = std::size_t
Definition at line 57 of file SegmentedVector.h.
template<typename T, size_t N = 512> using stride::util::SegmentedVector< T, N >::self_type = SegmentedVector<T, N>
Definition at line 58 of file SegmentedVector.h.
template<typename T, size_t N = 512> using stride::util::SegmentedVector< T, N >::iterator = SVIterator<T, N, T*, T&, false>
Definition at line 59 of file SegmentedVector.h.
template<typename T, size_t N = 512> using stride::util::SegmentedVector< T, N >::const_iterator = SVIterator<T, N>
Definition at line 60 of file SegmentedVector.h.
template<typename T, size_t N = 512> using stride::util::SegmentedVector< T, N >::Chunk = typename std::aligned_storage<sizeof(T), std::alignment_of<T>::value>::type private
POD type with same alignment requirement as for T's.
Definition at line 286 of file SegmentedVector.h.
Constructor & Destructor Documentation
template<typename T, size_t N = 512> stride::util::SegmentedVector< T, N >::SegmentedVector (size_type i = 0) inline explicit
Construct with given number of elements but DO NOT INITIALIZE them.
Definition at line 67 of file SegmentedVector.h.
template<typename T, size_t N = 512> stride::util::SegmentedVector< T, N >::SegmentedVector (const self_type & other) inline
Copy constructor.
Definition at line 70 of file SegmentedVector.h.
template<typename T, size_t N = 512> stride::util::SegmentedVector< T, N >::SegmentedVector (self_type && other) inline noexcept
Move constructor.
Definition at line 80 of file SegmentedVector.h.
template<typename T, size_t N = 512> stride::util::SegmentedVector< T, N >::~SegmentedVector () inline
Destructor.
Definition at line 112 of file SegmentedVector.h.
Member Function Documentation
template<typename T, size_t N = 512> SegmentedVector& stride::util::SegmentedVector< T, N >::operator= (const self_type & other) inline
Copy assignment.
Definition at line 86 of file SegmentedVector.h.
template<typename T, size_t N = 512> SegmentedVector& stride::util::SegmentedVector< T, N >::operator= (self_type && other) inline noexcept
Move assignment.
Definition at line 101 of file SegmentedVector.h.
template<typename T, size_t N = 512> T& stride::util::SegmentedVector< T, N >::at (std::size_t pos) inline
Access specified element with bounds checking.
Definition at line 119 of file SegmentedVector.h.
Referenced by stride::util::SegmentedVector< Person >::pop_back().
template<typename T, size_t N = 512> const T& stride::util::SegmentedVector< T, N >::at (std::size_t pos) const inline
Access specified element with bounds checking.
Definition at line 130 of file SegmentedVector.h.
template<typename T, size_t N = 512> T& stride::util::SegmentedVector< T, N >::back () inline
Access the last element.
Definition at line 141 of file SegmentedVector.h.
template<typename T, size_t N = 512> const T& stride::util::SegmentedVector< T, N >::back () const inline
Access the last element.
Definition at line 144 of file SegmentedVector.h.
template<typename T, size_t N = 512> T& stride::util::SegmentedVector< T, N >::operator[] (size_t pos) inline
Access specified element (no bounds checking).
Definition at line 150 of file SegmentedVector.h.
template<typename T, size_t N = 512> const T& stride::util::SegmentedVector< T, N >::operator[] (size_t pos) const inline
Access specified element (no bounds checking).
Definition at line 153 of file SegmentedVector.h.
template<typename T, size_t N = 512> iterator stride::util::SegmentedVector< T, N >::begin () inline
Returns an iterator to the beginning of the container.
Definition at line 163 of file SegmentedVector.h.
template<typename T, size_t N = 512> const_iterator stride::util::SegmentedVector< T, N >::begin () const inline
Returns a const_iterator to the beginning of the container.
Definition at line 166 of file SegmentedVector.h.
template<typename T, size_t N = 512> const_iterator stride::util::SegmentedVector< T, N >::cbegin () const inline
Returns a const_iterator to the beginning of the container.
Definition at line 169 of file SegmentedVector.h.
template<typename T, size_t N = 512> iterator stride::util::SegmentedVector< T, N >::end () inline
Returns an iterator to the end of the container.
Definition at line 172 of file SegmentedVector.h.
Referenced by stride::util::SegmentedVector< Person >::begin(), and stride::util::SegmentedVector< Person >::cbegin().
template<typename T, size_t N = 512> const_iterator stride::util::SegmentedVector< T, N >::end () const inline
Returns a const_iterator to the end of the container.
Definition at line 175 of file SegmentedVector.h.
template<typename T, size_t N = 512> const_iterator stride::util::SegmentedVector< T, N >::cend () const inline
Returns a const_iterator to the end.
Definition at line 178 of file SegmentedVector.h.
template<typename T, size_t N = 512> std::size_t stride::util::SegmentedVector< T, N >::capacity () const inline
Returns number of elements that can be stored without allocating additional blocks.
Definition at line 185 of file SegmentedVector.h.
Referenced by stride::util::SegmentedVector< Person >::operator=(), and stride::util::SegmentedVector< Person >::resize().
template<typename T, size_t N = 512> bool stride::util::SegmentedVector< T, N >::empty () const inline
Checks whether container is empty.
Definition at line 188 of file SegmentedVector.h.
template<typename T, size_t N = 512> std::size_t stride::util::SegmentedVector< T, N >::get_block_count () const inline
Returns number of currently allocated blocks.
Definition at line 191 of file SegmentedVector.h.
template<typename T, size_t N = 512> std::size_t stride::util::SegmentedVector< T, N >::get_elements_per_block () const inline
Returns number of elements block (template parameter 'N').
Definition at line 194 of file SegmentedVector.h.
template<typename T, size_t N = 512> std::size_t stride::util::SegmentedVector< T, N >::size () const inline
Returns the number of elements.
Definition at line 197 of file SegmentedVector.h.
Referenced by stride::util::SegmentedVector< Person >::resize(), stride::SurveySeeder::Seed(), and stride::Sim::TimeStep().
template<typename T, size_t N = 512> void stride::util::SegmentedVector< T, N >::resize (size_type new_size) inline
Increases the number of elements (but DOES NOT INITIALIZE the additional elements) or pops elements (and DOES RUN those element's destructor).
Definition at line 205 of file SegmentedVector.h.
Referenced by stride::util::SegmentedVector< Person >::SegmentedVector().
template<typename T, size_t N = 512> void stride::util::SegmentedVector< T, N >::clear () inline
Clears the content.
Definition at line 222 of file SegmentedVector.h.
Referenced by stride::util::SegmentedVector< Person >::operator=(), and stride::util::SegmentedVector< Person >::~SegmentedVector().
template<typename T, size_t N = 512> template<class... Args> T* stride::util::SegmentedVector< T, N >::emplace (size_type pos, Args &&... args) inline
Constructs element in-place at position pos.
Definition at line 236 of file SegmentedVector.h.
Referenced by stride::Population::SetBeliefPolicy().
template<typename T, size_t N = 512> template<class... Args> T* stride::util::SegmentedVector< T, N >::emplace_back (Args &&... args) inline
Constructs element in-place at the end.
Definition at line 244 of file SegmentedVector.h.
template<typename T, size_t N = 512> void stride::util::SegmentedVector< T, N >::pop_back () inline
Removes the last element.
Definition at line 251 of file SegmentedVector.h.
Referenced by stride::util::SegmentedVector< Person >::resize().
template<typename T, size_t N = 512> T* stride::util::SegmentedVector< T, N >::push_back (const T & obj) inline
Adds element to end.
Definition at line 271 of file SegmentedVector.h.
Referenced by stride::util::SegmentedVector< Person >::operator=(), and stride::util::SegmentedVector< Person >::SegmentedVector().
template<typename T, size_t N = 512> T* stride::util::SegmentedVector< T, N >::push_back (T && obj) inline
Adds element to end.
Definition at line 278 of file SegmentedVector.h.
template<typename T, size_t N = 512> T* stride::util::SegmentedVector< T, N >::get_chunk () inline private
Get next available chunk for element construction with placement new.
Definition at line 294 of file SegmentedVector.h.
Referenced by stride::util::SegmentedVector< Person >::emplace_back(), and stride::util::SegmentedVector< Person >::push_back().
Friends And Related Function Documentation
template<typename T, size_t N = 512> friend class SVIterator< T, N > friend
Definition at line 289 of file SegmentedVector.h.
template<typename T, size_t N = 512> friend class SVIterator< T, N, T *, T &, false > friend
Definition at line 290 of file SegmentedVector.h.
Member Data Documentation
template<typename T, size_t N = 512> std::vector<Chunk*> stride::util::SegmentedVector< T, N >::m_blocks private
Vector registers pointers to blocks of chunks.
Definition at line 308 of file SegmentedVector.h.
Referenced by stride::util::SegmentedVector< Person >::at(), stride::util::SegmentedVector< Person >::back(), stride::util::SegmentedVector< Person >::capacity(), stride::util::SegmentedVector< Person >::clear(), stride::util::SegmentedVector< Person >::emplace(), stride::util::SegmentedVector< Person >::get_block_count(), stride::util::SegmentedVector< Person >::get_chunk(), stride::util::SegmentedVector< Person >::operator=(), stride::util::SegmentedVector< Person >::operator[](), stride::util::SegmentedVector< Person >::pop_back(), stride::util::SegmentedVector< Person >::resize(), and stride::util::SegmentedVector< Person >::SegmentedVector().
template<typename T, size_t N = 512> size_t stride::util::SegmentedVector< T, N >::m_size private
Index of first free chunk when indexed contiguously.
Definition at line 309 of file SegmentedVector.h.
Referenced by stride::util::SegmentedVector< Person >::at(), stride::util::SegmentedVector< Person >::back(), stride::util::SegmentedVector< Person >::begin(), stride::util::SegmentedVector< Person >::cbegin(), stride::util::SegmentedVector< Person >::clear(), stride::util::SegmentedVector< Person >::empty(), stride::util::SegmentedVector< Person >::get_chunk(), stride::util::SegmentedVector< Person >::operator=(), stride::util::SegmentedVector< Person >::pop_back(), stride::util::SegmentedVector< Person >::resize(), stride::util::SegmentedVector< Person >::SegmentedVector(), and stride::util::SegmentedVector< Person >::size().
The documentation for this class was generated from the following file:
SegmentedVector.h