Stride Reference Manual: gengeopop::GenPopController Class Reference
gengeopop::GenPopController Class Reference
Controls the complete generation and population of a GeoGrid.
#include <GenPopController.h>
Public Member Functions
GenPopController (std::shared_ptr< spdlog::logger > logger, GeoGridConfig &geoGridConfig, stride::util::RnMan &rnManager)
Create a GenGeoPopController.
void ReadDataFiles (const std::string &citiesFileName, const std::string &commutingFileName, const std::string &householdsFileName)
Reads the data files.
void GenGeo ()
Build and store the Geo part of the GeoGrid.
void GenPop ()
Build and store the Pop part of the GeoGrid.
std::shared_ptr< GeoGrid > GetGeoGrid ()
Get the generated GeoGrid.
void UsePopulation (std::shared_ptr< stride::Population > pop)
Use a specified population storage during generation.
Private Attributes
GeoGridConfig & m_geoGridConfig
The GeoGridConfig used to generate the grid.
stride::util::RnMan & m_rnManager
The random number generation manager.
std::shared_ptr< GeoGrid > m_geoGrid
The generated GeoGrid.
std::shared_ptr< stride::Population > m_population
The generated GeoGrid.
std::shared_ptr< CitiesReader > m_citiesReader
The CitiesReader.
std::shared_ptr< CommutesReader > m_commutesReader
The CommutesReader.
std::shared_ptr< HouseholdReader > m_householdsReader
The HouseholdsReader.
std::shared_ptr< spdlog::logger > m_logger
The logger.
Detailed Description
Controls the complete generation and population of a GeoGrid.
Definition at line 30 of file GenPopController.h.
Constructor & Destructor Documentation
gengeopop::GenPopController::GenPopController (std::shared_ptr< spdlog::logger > logger, GeoGridConfig & geoGridConfig, stride::util::RnMan & rnManager)
Create a GenGeoPopController.
Definition at line 41 of file GenPopController.cpp.
Member Function Documentation
void gengeopop::GenPopController::ReadDataFiles (const std::string & citiesFileName, const std::string & commutingFileName, const std::string & householdsFileName)
Reads the data files.
Definition at line 49 of file GenPopController.cpp.
References gengeopop::GeoGridConfig::Calculate(), m_citiesReader, m_commutesReader, m_geoGrid, m_geoGridConfig, m_householdsReader, and m_population.
Referenced by main().
void gengeopop::GenPopController::GenGeo ()
Build and store the Geo part of the GeoGrid.
Definition at line 85 of file GenPopController.cpp.
References gengeopop::GeoGridPoolBuilder::AddGenerator(), gengeopop::GeoGridPoolBuilder::BuildPools(), m_geoGrid, m_geoGridConfig, m_logger, and m_rnManager.
Referenced by main().
void gengeopop::GenPopController::GenPop ()
Build and store the Pop part of the GeoGrid.
Definition at line 96 of file GenPopController.cpp.
References gengeopop::GeoGridPopBuilder::AddPartialPopulator(), gengeopop::GeoGridPopBuilder::BuildPop(), m_geoGrid, m_geoGridConfig, m_logger, and m_rnManager.
Referenced by main().
shared_ptr< GeoGrid > gengeopop::GenPopController::GetGeoGrid ()
Get the generated GeoGrid.
Definition at line 108 of file GenPopController.cpp.
References m_geoGrid.
Referenced by main().
void gengeopop::GenPopController::UsePopulation (std::shared_ptr< stride::Population > pop)
Use a specified population storage during generation.
Definition at line 110 of file GenPopController.cpp.
References m_population.
Member Data Documentation
GeoGridConfig& gengeopop::GenPopController::m_geoGridConfig private
The GeoGridConfig used to generate the grid.
Definition at line 54 of file GenPopController.h.
Referenced by GenGeo(), GenPop(), and ReadDataFiles().
stride::util::RnMan& gengeopop::GenPopController::m_rnManager private
The random number generation manager.
Definition at line 56 of file GenPopController.h.
Referenced by GenGeo(), and GenPop().
std::shared_ptr<GeoGrid> gengeopop::GenPopController::m_geoGrid private
The generated GeoGrid.
Definition at line 58 of file GenPopController.h.
Referenced by GenGeo(), GenPop(), GetGeoGrid(), and ReadDataFiles().
std::shared_ptr<stride::Population> gengeopop::GenPopController::m_population private
The generated GeoGrid.
Definition at line 60 of file GenPopController.h.
Referenced by ReadDataFiles(), and UsePopulation().
std::shared_ptr<CitiesReader> gengeopop::GenPopController::m_citiesReader private
The CitiesReader.
Definition at line 62 of file GenPopController.h.
Referenced by ReadDataFiles().
std::shared_ptr<CommutesReader> gengeopop::GenPopController::m_commutesReader private
The CommutesReader.
Definition at line 63 of file GenPopController.h.
Referenced by ReadDataFiles().
std::shared_ptr<HouseholdReader> gengeopop::GenPopController::m_householdsReader private
The HouseholdsReader.
Definition at line 64 of file GenPopController.h.
Referenced by ReadDataFiles().
std::shared_ptr<spdlog::logger> gengeopop::GenPopController::m_logger private
The logger.
Definition at line 65 of file GenPopController.h.
Referenced by GenGeo(), and GenPop().
The documentation for this class was generated from the following files:
GenPopController.h
GenPopController.cpp