Stride Reference Manual: stride::Person Class Reference
stride::Person Class Reference
Store and handle person data.
#include <Person.h>
Public Member Functions
Person ()
Default construction (for population vector).
Person (unsigned int id, double age, unsigned int householdId, unsigned int schoolId, unsigned int workId, unsigned int primaryCommunityId, unsigned int secondaryCommunityId)
Constructor: set the person data.
bool operator!= (const Person &p) const
Is this person not equal to the given person?
double GetAge () const
Get the age.
Belief * GetBelief ()
Return belief info.
const Belief * GetBelief () const
Return belief info.
unsigned int GetPoolId (const ContactPoolType::Id &poolType) const
Get ID of contactpool_type.
char GetGender () const
Return person's gender.
Health & GetHealth ()
Return person's health status.
const Health & GetHealth () const
Return person's health status.
unsigned int GetId () const
Get the id.
bool IsInPool (const ContactPoolType::Id &poolType) const
Check if a person is present today in a given contactpool.
bool IsSurveyParticipant () const
Does this person participates in the social contact study?
void ParticipateInSurvey ()
Participate in social contact study and log person details.
void SetBelief (Belief *belief)
Set the beliefs. Pointer into Population's beliefcontainer.
void Update (bool isWorkOff, bool isSchoolOff)
Update the health status and presence in contactpools.
void Update (Person *p)
Private Attributes
double m_age
The age.
Belief * m_belief
Health beliefs related data (raw pointer intentional).
char m_gender
Health m_health
Health info for this person.
unsigned int m_id
The id.
bool m_is_participant
Is participating in the social contact study.
ContactPoolType::IdSubscriptArray
< unsigned int > m_pool_ids
Is person present/absent in pools of each of the types (school, work, etc)?
ContactPoolType::IdSubscriptArray
< bool > m_in_pools
Detailed Description
Store and handle person data.
Definition at line 35 of file Person.h.
Constructor & Destructor Documentation
stride::Person::Person () inline
Default construction (for population vector).
Definition at line 39 of file Person.h.
stride::Person::Person (unsigned int id, double age, unsigned int householdId, unsigned int schoolId, unsigned int workId, unsigned int primaryCommunityId, unsigned int secondaryCommunityId) inline
Constructor: set the person data.
Definition at line 46 of file Person.h.
Member Function Documentation
bool stride::Person::operator!= (const Person & p) const inline
Is this person not equal to the given person?
Definition at line 56 of file Person.h.
References m_id.
double stride::Person::GetAge () const inline
Get the age.
Definition at line 59 of file Person.h.
References m_age.
Referenced by stride::Immunizer::Random(), stride::SurveySeeder::Seed(), and stride::DiseaseSeeder::Seed().
Belief* stride::Person::GetBelief () inline
Return belief info.
Definition at line 62 of file Person.h.
References m_belief.
const Belief* stride::Person::GetBelief () const inline
Return belief info.
Definition at line 65 of file Person.h.
References m_belief.
unsigned int stride::Person::GetPoolId (const ContactPoolType::Id & poolType) const inline
Get ID of contactpool_type.
Definition at line 68 of file Person.h.
References m_pool_ids.
Referenced by stride::SurveySeeder::Seed().
char stride::Person::GetGender () const inline
Return person's gender.
Definition at line 71 of file Person.h.
References m_gender.
Referenced by stride::SurveySeeder::Seed().
Health& stride::Person::GetHealth () inline
Return person's health status.
Definition at line 74 of file Person.h.
References m_health.
Referenced by stride::Infector< LL, TIC, LIP, TO >::Exec(), stride::Infector< LL, TIC, NoLocalInformation, true >::Exec(), stride::Immunizer::Random(), and stride::DiseaseSeeder::Seed().
const Health& stride::Person::GetHealth () const inline
Return person's health status.
Definition at line 77 of file Person.h.
References m_health.
unsigned int stride::Person::GetId () const inline
Get the id.
Definition at line 80 of file Person.h.
References m_id.
Referenced by stride::DiseaseSeeder::Seed(), and stride::SurveySeeder::Seed().
bool stride::Person::IsInPool (const ContactPoolType::Id & poolType) const inline
Check if a person is present today in a given contactpool.
Definition at line 83 of file Person.h.
References m_in_pools.
Referenced by stride::Infector< LL, TIC, LIP, TO >::Exec(), and stride::Infector< LL, TIC, NoLocalInformation, true >::Exec().
bool stride::Person::IsSurveyParticipant () const inline
Does this person participates in the social contact study?
Definition at line 86 of file Person.h.
References m_is_participant.
Referenced by stride::SurveySeeder::Seed().
void stride::Person::ParticipateInSurvey () inline
Participate in social contact study and log person details.
Definition at line 89 of file Person.h.
References m_is_participant.
Referenced by stride::SurveySeeder::Seed().
void stride::Person::SetBelief (Belief * belief) inline
Set the beliefs. Pointer into Population's beliefcontainer.
Definition at line 92 of file Person.h.
References m_belief.
void stride::Person::Update (bool isWorkOff, bool isSchoolOff)
Update the health status and presence in contactpools.
Definition at line 31 of file Person.cpp.
References stride::MinAdultAge().
void stride::Person::Update (Person * p)
Definition at line 54 of file Person.cpp.
Member Data Documentation
double stride::Person::m_age private
The age.
Definition at line 101 of file Person.h.
Referenced by GetAge().
Belief* stride::Person::m_belief private
Health beliefs related data (raw pointer intentional).
Definition at line 102 of file Person.h.
Referenced by GetBelief(), and SetBelief().
char stride::Person::m_gender private
Definition at line 103 of file Person.h.
Referenced by GetGender().
Health stride::Person::m_health private
Health info for this person.
Definition at line 104 of file Person.h.
Referenced by GetHealth().
unsigned int stride::Person::m_id private
The id.
Definition at line 105 of file Person.h.
Referenced by GetId(), and operator!=().
bool stride::Person::m_is_participant private
Is participating in the social contact study.
Ids (school, work, etc) of pools you belong to Id value 0 means you do not belong to any pool of that type (e.g. school and work are mutually exclusive.
Definition at line 106 of file Person.h.
Referenced by IsSurveyParticipant(), and ParticipateInSurvey().
ContactPoolType::IdSubscriptArray<unsigned int> stride::Person::m_pool_ids private
Is person present/absent in pools of each of the types (school, work, etc)?
Definition at line 110 of file Person.h.
Referenced by GetPoolId().
ContactPoolType::IdSubscriptArray<bool> stride::Person::m_in_pools private
Definition at line 113 of file Person.h.
Referenced by IsInPool().
The documentation for this class was generated from the following files:
Person.h
Person.cpp