Stride Reference Manual: proto::GeoGrid_Person Class Reference
proto::GeoGrid_Person Class Reference
#include <geogrid.pb.h>
Public Member Functions
GeoGrid_Person ()
virtual ~GeoGrid_Person ()
GeoGrid_Person (const GeoGrid_Person &from)
GeoGrid_Person & operator= (const GeoGrid_Person &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (GeoGrid_Person *other)
GeoGrid_Person * New () const final
GeoGrid_Person * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const GeoGrid_Person &from)
void MergeFrom (const GeoGrid_Person &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_gender () const
void clear_gender ()
const ::std::string & gender () const
void set_gender (const ::std::string &value)
void set_gender (const char *value)
void set_gender (const char *value, size_t size)
::std::string * mutable_gender ()
::std::string * release_gender ()
void set_allocated_gender (::std::string *gender)
bool has_id () const
void clear_id ()
::google::protobuf::int64 id () const
void set_id (::google::protobuf::int64 value)
bool has_age () const
void clear_age ()
::google::protobuf::int64 age () const
void set_age (::google::protobuf::int64 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const GeoGrid_Person & default_instance ()
static void InitAsDefaultInstance ()
static const GeoGrid_Person * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages = 5
static const int kGenderFieldNumber = 3
static const int kIdFieldNumber = 1
static const int kAgeFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const final
void InternalSwap (GeoGrid_Person *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_id ()
void clear_has_id ()
void set_has_age ()
void clear_has_age ()
void set_has_gender ()
void clear_has_gender ()
size_t RequiredFieldsByteSizeFallback () const
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
mutable::google::protobuf::internal::CachedSize _cached_size_
::google::protobuf::internal::ArenaStringPtr gender_
::google::protobuf::int64 id_
::google::protobuf::int64 age_
Friends
struct ::protobuf_geogrid_2eproto::TableStruct
void swap (GeoGrid_Person &a, GeoGrid_Person &b)
Detailed Description
Definition at line 881 of file geogrid.pb.h.
Constructor & Destructor Documentation
proto::GeoGrid_Person::GeoGrid_Person ()
virtual proto::GeoGrid_Person::~GeoGrid_Person () virtual
proto::GeoGrid_Person::GeoGrid_Person (const GeoGrid_Person & from)
Member Function Documentation
GeoGrid_Person& proto::GeoGrid_Person::operator= (const GeoGrid_Person & from) inline
Definition at line 890 of file geogrid.pb.h.
References GetArenaNoVirtual().
const ::google::protobuf::UnknownFieldSet& proto::GeoGrid_Person::unknown_fields () const inline
Definition at line 909 of file geogrid.pb.h.
inline ::google::protobuf::UnknownFieldSet* proto::GeoGrid_Person::mutable_unknown_fields () inline
Definition at line 913 of file geogrid.pb.h.
static const ::google::protobuf::Descriptor* proto::GeoGrid_Person::descriptor () static
static const GeoGrid_Person& proto::GeoGrid_Person::default_instance () static
static void proto::GeoGrid_Person::InitAsDefaultInstance () static
static const GeoGrid_Person* proto::GeoGrid_Person::internal_default_instance () inline static
Definition at line 922 of file geogrid.pb.h.
References proto::_GeoGrid_Person_default_instance_.
void proto::GeoGrid_Person::Swap (GeoGrid_Person * other)
GeoGrid_Person* proto::GeoGrid_Person::New () const inline final
Definition at line 933 of file geogrid.pb.h.
GeoGrid_Person* proto::GeoGrid_Person::New (::google::protobuf::Arena * arena) const inline final
Definition at line 935 of file geogrid.pb.h.
void proto::GeoGrid_Person::CopyFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Person::MergeFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Person::CopyFrom (const GeoGrid_Person & from)
void proto::GeoGrid_Person::MergeFrom (const GeoGrid_Person & from)
void proto::GeoGrid_Person::Clear () final
bool proto::GeoGrid_Person::IsInitialized () const final
size_t proto::GeoGrid_Person::ByteSizeLong () const final
bool proto::GeoGrid_Person::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
void proto::GeoGrid_Person::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
::google::protobuf::uint8* proto::GeoGrid_Person::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
int proto::GeoGrid_Person::GetCachedSize () const inline final
Definition at line 951 of file geogrid.pb.h.
void proto::GeoGrid_Person::SharedCtor () private
void proto::GeoGrid_Person::SharedDtor () private
void proto::GeoGrid_Person::SetCachedSize (int size) const final private
void proto::GeoGrid_Person::InternalSwap (GeoGrid_Person * other) private
inline ::google::protobuf::Arena* proto::GeoGrid_Person::GetArenaNoVirtual () const inline private
Definition at line 960 of file geogrid.pb.h.
Referenced by operator=().
void* proto::GeoGrid_Person::MaybeArenaPtr () const inline private
Definition at line 961 of file geogrid.pb.h.
::google::protobuf::Metadata proto::GeoGrid_Person::GetMetadata () const final
bool proto::GeoGrid_Person::has_gender () const inline
Definition at line 1672 of file geogrid.pb.h.
void proto::GeoGrid_Person::clear_gender () inline
Definition at line 1675 of file geogrid.pb.h.
const ::std::string & proto::GeoGrid_Person::gender () const inline
Definition at line 1680 of file geogrid.pb.h.
void proto::GeoGrid_Person::set_gender (const ::std::string & value) inline
Definition at line 1685 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WritePerson().
void proto::GeoGrid_Person::set_gender (const char * value) inline
Definition at line 1699 of file geogrid.pb.h.
void proto::GeoGrid_Person::set_gender (const char * value, size_t size) inline
Definition at line 1706 of file geogrid.pb.h.
std::string * proto::GeoGrid_Person::mutable_gender () inline
Definition at line 1713 of file geogrid.pb.h.
std::string * proto::GeoGrid_Person::release_gender () inline
Definition at line 1719 of file geogrid.pb.h.
void proto::GeoGrid_Person::set_allocated_gender (::std::string * gender) inline
Definition at line 1728 of file geogrid.pb.h.
bool proto::GeoGrid_Person::has_id () const inline
Definition at line 1630 of file geogrid.pb.h.
void proto::GeoGrid_Person::clear_id () inline
Definition at line 1633 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Person::id () const inline
Definition at line 1638 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParsePerson().
void proto::GeoGrid_Person::set_id (::google::protobuf::int64 value) inline
Definition at line 1643 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WritePerson().
bool proto::GeoGrid_Person::has_age () const inline
Definition at line 1651 of file geogrid.pb.h.
void proto::GeoGrid_Person::clear_age () inline
Definition at line 1654 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Person::age () const inline
Definition at line 1659 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParsePerson().
void proto::GeoGrid_Person::set_age (::google::protobuf::int64 value) inline
Definition at line 1664 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WritePerson().
void proto::GeoGrid_Person::set_has_id () inline private
Definition at line 1631 of file geogrid.pb.h.
void proto::GeoGrid_Person::clear_has_id () inline private
Definition at line 1632 of file geogrid.pb.h.
void proto::GeoGrid_Person::set_has_age () inline private
Definition at line 1652 of file geogrid.pb.h.
void proto::GeoGrid_Person::clear_has_age () inline private
Definition at line 1653 of file geogrid.pb.h.
void proto::GeoGrid_Person::set_has_gender () inline private
Definition at line 1673 of file geogrid.pb.h.
void proto::GeoGrid_Person::clear_has_gender () inline private
Definition at line 1674 of file geogrid.pb.h.
size_t proto::GeoGrid_Person::RequiredFieldsByteSizeFallback () const private
Friends And Related Function Documentation
friend struct ::protobuf_geogrid_2eproto::TableStruct friend
Definition at line 1017 of file geogrid.pb.h.
void swap (GeoGrid_Person & a, GeoGrid_Person & b) friend
Definition at line 929 of file geogrid.pb.h.
Member Data Documentation
constexpr int proto::GeoGrid_Person::kIndexInFileMessages = 5 static
Definition at line 926 of file geogrid.pb.h.
const int proto::GeoGrid_Person::kGenderFieldNumber = 3 static
Definition at line 973 of file geogrid.pb.h.
const int proto::GeoGrid_Person::kIdFieldNumber = 1 static
Definition at line 988 of file geogrid.pb.h.
const int proto::GeoGrid_Person::kAgeFieldNumber = 2 static
Definition at line 995 of file geogrid.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::GeoGrid_Person::_internal_metadata_ private
Definition at line 1011 of file geogrid.pb.h.
::google::protobuf::internal::HasBits<1> proto::GeoGrid_Person::_has_bits_ private
Definition at line 1012 of file geogrid.pb.h.
mutable ::google::protobuf::internal::CachedSize proto::GeoGrid_Person::_cached_size_ private
Definition at line 1013 of file geogrid.pb.h.
::google::protobuf::internal::ArenaStringPtr proto::GeoGrid_Person::gender_ private
Definition at line 1014 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Person::id_ private
Definition at line 1015 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Person::age_ private
Definition at line 1016 of file geogrid.pb.h.
The documentation for this class was generated from the following file:
geogrid.pb.h