Stride Reference Manual: geopop::GeoGridProtoReader Class Reference
geopop::GeoGridProtoReader Class Reference
An implementation of the GeoGridReader using Protocol Buffers.
#include <GeoGridProtoReader.h>
Public Member Functions
GeoGridProtoReader (std::unique_ptr< std::istream > inputStream, stride::Population *pop)
Construct the GeoGridJSONReader with the istream which contains the Protobuf info.
GeoGridProtoReader (const GeoGridProtoReader &)=delete
No copy constructor.
GeoGridProtoReader operator= (const GeoGridProtoReader &)=delete
No copy assignement.
void Read () override
Actually perform the read and return the GeoGrid.
Public Member Functions inherited from geopop::GeoGridReader
GeoGridReader (std::unique_ptr< std::istream > inputStream, stride::Population *pop)
Parametrized constructor.
GeoGridReader (const GeoGridReader &)=delete
No copy constructor.
GeoGridReader & operator= (const GeoGridReader &)=delete
No copy assignment.
virtual ~GeoGridReader ()=default
Default destructor.
Private Member Functions
std::shared_ptr< ContactCenter > ParseContactCenter (const proto::GeoGrid_Location_ContactCenter &protoContactCenter)
Create a ContactCenter based on protobuf ContactCenter info.
stride::ContactPool * ParseContactPool (const proto::GeoGrid_Location_ContactCenter_ContactPool &protoContactPool, stride::ContactType::Id typeId)
Create a ContactPool based on the provided protobuf ContactPool.
Coordinate ParseCoordinate (const proto::GeoGrid_Location_Coordinate &protoCoordinate)
Create a Coordinate based on the provided protobuf Coordinate.
std::shared_ptr< Location > ParseLocation (const proto::GeoGrid_Location &protoLocation)
Create a Location based on protobuf Location info.
stride::Person * ParsePerson (const proto::GeoGrid_Person &person)
Create a Person based on protobuf Person info.
Additional Inherited Members
Protected Member Functions inherited from geopop::GeoGridReader
void AddCommutes (GeoGrid &geoGrid)
Add the commutes that were found to their respective Locations symmetrically.
Protected Attributes inherited from geopop::GeoGridReader
std::map< unsigned int, stride::Person * > m_people
< Store the persons (id->person) that were found while loping over the ContactPools.
std::vector< std::tuple< unsigned int, unsigned int, double > > m_commutes
std::unique_ptr< std::istream > m_inputStream
File to read.
stride::Population * m_population
Population to use in the GeoGrid may be nullptr.
Detailed Description
An implementation of the GeoGridReader using Protocol Buffers.
This class is used to read a GeoGrid from a Proto file.
Definition at line 39 of file GeoGridProtoReader.h.
Constructor & Destructor Documentation
geopop::GeoGridProtoReader::GeoGridProtoReader (std::unique_ptr< std::istream > inputStream, stride::Population * pop)
Construct the GeoGridJSONReader with the istream which contains the Protobuf info.
Definition at line 38 of file GeoGridProtoReader.cpp.
geopop::GeoGridProtoReader::GeoGridProtoReader (const GeoGridProtoReader &) delete
No copy constructor.
Member Function Documentation
GeoGridProtoReader geopop::GeoGridProtoReader::operator= (const GeoGridProtoReader &) delete
No copy assignement.
void geopop::GeoGridProtoReader::Read () override virtual
Actually perform the read and return the GeoGrid.
Implements geopop::GeoGridReader.
Definition at line 43 of file GeoGridProtoReader.cpp.
References geopop::GeoGridReader::AddCommutes(), stride::Person::GetId(), proto::GeoGrid::locations(), proto::GeoGrid::locations_size(), geopop::GeoGridReader::m_commutes, geopop::GeoGridReader::m_inputStream, geopop::GeoGridReader::m_people, geopop::GeoGridReader::m_population, ParseLocation(), ParsePerson(), proto::GeoGrid::persons(), proto::GeoGrid::persons_size(), and stride::Population::RefGeoGrid().
shared_ptr< ContactCenter > geopop::GeoGridProtoReader::ParseContactCenter (const proto::GeoGrid_Location_ContactCenter & protoContactCenter) private
Create a ContactCenter based on protobuf ContactCenter info.
Definition at line 90 of file GeoGridProtoReader.cpp.
References stride::ContactType::College, proto::GeoGrid_Location_ContactCenter_Type_College, proto::GeoGrid_Location_ContactCenter_Type_Household, proto::GeoGrid_Location_ContactCenter_Type_K12School, proto::GeoGrid_Location_ContactCenter_Type_PrimaryCommunity, proto::GeoGrid_Location_ContactCenter_Type_SecondaryCommunity, proto::GeoGrid_Location_ContactCenter_Type_Workplace, stride::ContactType::Household, proto::GeoGrid_Location_ContactCenter::id(), stride::ContactType::K12School, ParseContactPool(), proto::GeoGrid_Location_ContactCenter::pools(), proto::GeoGrid_Location_ContactCenter::pools_size(), stride::ContactType::PrimaryCommunity, stride::ContactType::SecondaryCommunity, proto::GeoGrid_Location_ContactCenter::type(), and stride::ContactType::Workplace.
Referenced by ParseLocation().
stride::ContactPool * geopop::GeoGridProtoReader::ParseContactPool (const proto::GeoGrid_Location_ContactCenter_ContactPool & protoContactPool, stride::ContactType::Id typeId) private
Create a ContactPool based on the provided protobuf ContactPool.
Definition at line 158 of file GeoGridProtoReader.cpp.
References stride::ContactPool::AddMember(), stride::ContactPoolSys::CreateContactPool(), stride::ContactPool::GetId(), geopop::GeoGridReader::m_people, geopop::GeoGridReader::m_population, proto::GeoGrid_Location_ContactCenter_ContactPool::people(), proto::GeoGrid_Location_ContactCenter_ContactPool::people_size(), and stride::Population::RefPoolSys().
Referenced by ParseContactCenter().
Coordinate geopop::GeoGridProtoReader::ParseCoordinate (const proto::GeoGrid_Location_Coordinate & protoCoordinate) private
Create a Coordinate based on the provided protobuf Coordinate.
Definition at line 153 of file GeoGridProtoReader.cpp.
References proto::GeoGrid_Location_Coordinate::latitude(), and proto::GeoGrid_Location_Coordinate::longitude().
Referenced by ParseLocation().
shared_ptr< Location > geopop::GeoGridProtoReader::ParseLocation (const proto::GeoGrid_Location & protoLocation) private
Create a Location based on protobuf Location info.
Definition at line 182 of file GeoGridProtoReader.cpp.
References proto::GeoGrid_Location::commutes(), proto::GeoGrid_Location::commutes_size(), proto::GeoGrid_Location::contactcenters(), proto::GeoGrid_Location::contactcenters_size(), proto::GeoGrid_Location::coordinate(), proto::GeoGrid_Location::id(), geopop::GeoGridReader::m_commutes, proto::GeoGrid_Location::name(), ParseContactCenter(), ParseCoordinate(), proto::GeoGrid_Location::population(), proto::GeoGrid_Location_Commute::proportion(), proto::GeoGrid_Location::province(), and proto::GeoGrid_Location_Commute::to().
Referenced by Read().
stride::Person * geopop::GeoGridProtoReader::ParsePerson (const proto::GeoGrid_Person & person) private
Create a Person based on protobuf Person info.
Definition at line 220 of file GeoGridProtoReader.cpp.
References proto::GeoGrid_Person::age(), stride::Population::CreatePerson(), proto::GeoGrid_Person::id(), and geopop::GeoGridReader::m_population.
Referenced by Read().
The documentation for this class was generated from the following files:
GeoGridProtoReader.h
GeoGridProtoReader.cpp