Stride Reference Manual: stride::HealthSeeder Class Reference
stride::HealthSeeder Class Reference
Seeds the population with Health data.
#include <HealthSeeder.h>
Public Member Functions
HealthSeeder (const boost::property_tree::ptree &diseasePt)
Constructor requires diease data.
void Seed (const std::shared_ptr< Population > &pop, std::vector< ContactHandler > &handlers)
Seeds the population with Health data.
Private Member Functions
void GetDistribution (std::vector< double > &distribution, const boost::property_tree::ptree &rootPt, const std::string &xmlTag)
Utility method to etract distribution from data in ptree.
unsigned short int Sample (const std::vector< double > &distribution, double random01)
Sample for each of the health data item individually.
Private Attributes
std::vector< double > m_distrib_start_symptomatic
std::vector< double > m_distrib_time_asymptomatic
std::vector< double > m_distrib_time_infectious
std::vector< double > m_distrib_time_symptomatic
Detailed Description
Seeds the population with Health data.
Definition at line 39 of file HealthSeeder.h.
Constructor & Destructor Documentation
stride::HealthSeeder::HealthSeeder (const boost::property_tree::ptree & diseasePt) explicit
Constructor requires diease data.
Definition at line 35 of file HealthSeeder.cpp.
References GetDistribution(), m_distrib_start_symptomatic, m_distrib_time_asymptomatic, m_distrib_time_infectious, and m_distrib_time_symptomatic.
Member Function Documentation
void stride::HealthSeeder::Seed (const std::shared_ptr< Population > & pop, std::vector< ContactHandler > & handlers)
Seeds the population with Health data.
Definition at line 74 of file HealthSeeder.cpp.
References m_distrib_start_symptomatic, m_distrib_time_asymptomatic, m_distrib_time_infectious, m_distrib_time_symptomatic, and Sample().
Referenced by stride::SimBuilder::Build().
void stride::HealthSeeder::GetDistribution (std::vector< double > & distribution, const boost::property_tree::ptree & rootPt, const std::string & xmlTag) private
Utility method to etract distribution from data in ptree.
Definition at line 54 of file HealthSeeder.cpp.
Referenced by HealthSeeder().
unsigned short int stride::HealthSeeder::Sample (const std::vector< double > & distribution, double random01) private
Sample for each of the health data item individually.
Definition at line 62 of file HealthSeeder.cpp.
Referenced by Seed().
Member Data Documentation
std::vector<double> stride::HealthSeeder::m_distrib_start_symptomatic private
Definition at line 57 of file HealthSeeder.h.
Referenced by HealthSeeder(), and Seed().
std::vector<double> stride::HealthSeeder::m_distrib_time_asymptomatic private
Definition at line 58 of file HealthSeeder.h.
Referenced by HealthSeeder(), and Seed().
std::vector<double> stride::HealthSeeder::m_distrib_time_infectious private
Definition at line 59 of file HealthSeeder.h.
Referenced by HealthSeeder(), and Seed().
std::vector<double> stride::HealthSeeder::m_distrib_time_symptomatic private
Definition at line 60 of file HealthSeeder.h.
Referenced by HealthSeeder(), and Seed().
The documentation for this class was generated from the following files:
HealthSeeder.h
HealthSeeder.cpp