Stride Reference Manual: gengeopop::KdTree< P > Class Template Reference
gengeopop::KdTree< P > Class Template Reference
A k-d tree: a k-dimensional generalization of binary search trees This data structure allows for efficient lookup of points and range queries with an Axis-Aligned Bounding Box (when balanced).
#include <KdNode.h>
Public Member Functions
KdTree ()
Constructor: builds an empty tree.
void Apply (std::function< bool(const P &)> f) const
Calls a function with each of the points in the tree.
void Apply (std::function< bool(const P &)> f, const AABBox< P > &box) const
Calls a function with every point contained in box
bool Contains (const P &point) const
Test wether a point is contained in the tree.
bool Empty () const
Is the tree empty.
std::size_t GetHeight () const
Get the height of the tree (mostly for testing purposes).
void Insert (P point)
Insert a new point into the tree, using this often may result in an unbalanced tree.
std::vector< P > Query (const AABBox< P > &box) const
Get all points in the tree that lie within box.
std::size_t Size () const
Get the size of the tree.
Static Public Member Functions
static KdTree Build (const std::vector< P > &points)
Build a balanced tree from the given set of points efficiently.
Static Private Member Functions
template<std::size_t D>
static std::unique_ptr< kd::Node< P, D > > Construct (const std::vector< P > &points)
Private Attributes
std::size_t m_size
The number of points in the tree.
std::unique_ptr< kd::Node< P, 0 > > m_root
The root node of the tree.
Detailed Description
template<typename P>
class gengeopop::KdTree< P >
A k-d tree: a k-dimensional generalization of binary search trees This data structure allows for efficient lookup of points and range queries with an Axis-Aligned Bounding Box (when balanced).
The template parameter P should have the following attributes and operations:
A static constexpr std::size_t dim: the number of dimensions of the point type.
A template <std::size_d D> get() const returns the coordinate of the Dth dimension of the point.
A nested template <std::size_t D> struct dimension_type has a member type type with return type for Get<D>.
A default constructor and a copy constructor
The individual dimensions should each have a total order and equality
A method bool InBox(const AABB<P>& box) const indicates if a point falls withing the bounding box (only for range queries)
Definition at line 25 of file KdNode.h.
Constructor & Destructor Documentation
template<typename P > gengeopop::KdTree< P >::KdTree ()
Constructor: builds an empty tree.
Definition at line 35 of file KdTree_def.h.
Member Function Documentation
template<typename P> KdTree< P > gengeopop::KdTree< P >::Build (const std::vector< P > & points) static
Build a balanced tree from the given set of points efficiently.
Parameters
points The points to insert in the resulting tree.
Returns
A balanced KdTree containing the given points.
Definition at line 40 of file KdTree_def.h.
References gengeopop::KdTree< P >::m_root, and gengeopop::KdTree< P >::m_size.
template<typename P> void gengeopop::KdTree< P >::Apply (std::function< bool(const P &)> f) const
Calls a function with each of the points in the tree.
Parameters
f A function that will be called with each point, if f returns false, traversal stops.
Definition at line 49 of file KdTree_def.h.
References gengeopop::kd::BaseNode< P >::BorrowLeft(), gengeopop::kd::BaseNode< P >::BorrowRight(), gengeopop::kd::BaseNode< P >::GetPoint(), and gengeopop::KdTree< P >::m_root.
Referenced by gengeopop::KdTree< P >::Contains(), and gengeopop::KdTree< P >::Query().
template<typename P> void gengeopop::KdTree< P >::Apply (std::function< bool(const P &)> f, const AABBox< P > & box) const
Calls a function with every point contained in box
Parameters
f A function that will be called with each point within box, if f returns false, traversal stops.
box The containing Axis-Aligned Bounding Box to search for points
Definition at line 76 of file KdTree_def.h.
References gengeopop::kd::BaseNode< P >::BorrowSplitChild(), gengeopop::kd::BaseNode< P >::GetPoint(), gengeopop::AABBox< P >::lower, gengeopop::KdTree< P >::m_root, and gengeopop::AABBox< P >::upper.
template<typename P> bool gengeopop::KdTree< P >::Contains (const P & point) const
Test wether a point is contained in the tree.
Parameters
point The point to test. P should support bool operator==(const P&) const.
Returns
Whether the point is found in the tree.
Definition at line 100 of file KdTree_def.h.
References gengeopop::KdTree< P >::Apply().
template<typename P > bool gengeopop::KdTree< P >::Empty () const
Is the tree empty.
Definition at line 114 of file KdTree_def.h.
References gengeopop::KdTree< P >::Size().
template<typename P > std::size_t gengeopop::KdTree< P >::GetHeight () const
Get the height of the tree (mostly for testing purposes).
Definition at line 120 of file KdTree_def.h.
References gengeopop::kd::BaseNode< P >::BorrowLeft(), gengeopop::kd::BaseNode< P >::BorrowRight(), and gengeopop::KdTree< P >::m_root.
template<typename P> void gengeopop::KdTree< P >::Insert (P point)
Insert a new point into the tree, using this often may result in an unbalanced tree.
Parameters
point The point to insert into the tree.
Definition at line 139 of file KdTree_def.h.
References gengeopop::kd::BaseNode< P >::AddChild(), gengeopop::kd::BaseNode< P >::BorrowSplitChild(), gengeopop::KdTree< P >::m_root, and gengeopop::KdTree< P >::m_size.
template<typename P> std::vector< P > gengeopop::KdTree< P >::Query (const AABBox< P > & box) const
Get all points in the tree that lie within box.
Parameters
box The limiting AABB to search for points.
Returns
A collection of points found within box.
Definition at line 158 of file KdTree_def.h.
References gengeopop::KdTree< P >::Apply().
template<typename P > std::size_t gengeopop::KdTree< P >::Size () const
Get the size of the tree.
Definition at line 171 of file KdTree_def.h.
References gengeopop::KdTree< P >::m_size.
Referenced by gengeopop::KdTree< P >::Empty().
template<typename P> template<std::size_t D> std::unique_ptr< kd::Node< P, D > > gengeopop::KdTree< P >::Construct (const std::vector< P > & points) static private
Definition at line 178 of file KdTree_def.h.
Member Data Documentation
template<typename P> std::size_t gengeopop::KdTree< P >::m_size private
The number of points in the tree.
Definition at line 108 of file KdTree.h.
Referenced by gengeopop::KdTree< P >::Build(), gengeopop::KdTree< P >::Insert(), and gengeopop::KdTree< P >::Size().
template<typename P> std::unique_ptr<kd::Node<P, 0> > gengeopop::KdTree< P >::m_root private
The root node of the tree.
Definition at line 109 of file KdTree.h.
Referenced by gengeopop::KdTree< P >::Apply(), gengeopop::KdTree< P >::Build(), gengeopop::KdTree< P >::GetHeight(), and gengeopop::KdTree< P >::Insert().
The documentation for this class was generated from the following files:
KdNode.h
KdTree.h
KdTree_def.h