Stride Reference Manual: stride::util::Stopwatch< T > Class Template Reference
stride::util::Stopwatch< T > Class Template Reference
Provides a stopwatch interface to time: it accumulates time between start/stop pairs.
#include <Stopwatch.h>
Public Types
using TClock = T
Public Member Functions
Stopwatch (std::string name="stopwatch", bool running=false)
Constructor initializes stopwatch.
Stopwatch & Start ()
Starts stopwatch if it was stopped.
Stopwatch & Stop ()
Stops the stopwatch if it was running.
Stopwatch & Reset ()
Resets stopwatch i.e. stopwatch is stopped and time accumulator is cleared.
bool IsRunning () const
Reports whether stopwatch has been started.
std::string GetName () const
Return name of this stopwatch.
T::duration Get () const
Returns the accumulated value without altering the stopwatch state.
std::string ToString () const
Returns string representation of readout.
Private Attributes
T::duration m_accumulated
T::time_point m_last_start
std::string m_name
bool m_running
Detailed Description
template<typename T = std::chrono::steady_clock>
class stride::util::Stopwatch< T >
Provides a stopwatch interface to time: it accumulates time between start/stop pairs.
Definition at line 35 of file Stopwatch.h.
Member Typedef Documentation
template<typename T = std::chrono::steady_clock> using stride::util::Stopwatch< T >::TClock = T
Definition at line 38 of file Stopwatch.h.
Constructor & Destructor Documentation
template<typename T = std::chrono::steady_clock> stride::util::Stopwatch< T >::Stopwatch (std::string name = "stopwatch", bool running = false) inline explicit
Constructor initializes stopwatch.
Definition at line 41 of file Stopwatch.h.
References stride::util::Stopwatch< T >::m_last_start, and stride::util::Stopwatch< T >::m_running.
Member Function Documentation
template<typename T = std::chrono::steady_clock> Stopwatch& stride::util::Stopwatch< T >::Start () inline
Starts stopwatch if it was stopped.
Definition at line 50 of file Stopwatch.h.
References stride::util::Stopwatch< T >::m_last_start, and stride::util::Stopwatch< T >::m_running.
Referenced by stride::ControlHelper::ControlHelper(), stride::SimRunner::Run(), and stride::SimRunner::SimRunner().
template<typename T = std::chrono::steady_clock> Stopwatch& stride::util::Stopwatch< T >::Stop () inline
Stops the stopwatch if it was running.
Definition at line 60 of file Stopwatch.h.
References stride::util::Stopwatch< T >::m_accumulated, stride::util::Stopwatch< T >::m_last_start, and stride::util::Stopwatch< T >::m_running.
Referenced by stride::ControlHelper::LogShutdown(), stride::SimRunner::Run(), and stride::SimRunner::SimRunner().
template<typename T = std::chrono::steady_clock> Stopwatch& stride::util::Stopwatch< T >::Reset () inline
Resets stopwatch i.e. stopwatch is stopped and time accumulator is cleared.
Definition at line 70 of file Stopwatch.h.
References stride::util::Stopwatch< T >::m_accumulated, and stride::util::Stopwatch< T >::m_running.
template<typename T = std::chrono::steady_clock> bool stride::util::Stopwatch< T >::IsRunning () const inline
Reports whether stopwatch has been started.
Definition at line 78 of file Stopwatch.h.
References stride::util::Stopwatch< T >::m_running.
template<typename T = std::chrono::steady_clock> std::string stride::util::Stopwatch< T >::GetName () const inline
Return name of this stopwatch.
Definition at line 81 of file Stopwatch.h.
References stride::util::Stopwatch< T >::m_name.
template<typename T = std::chrono::steady_clock> T::duration stride::util::Stopwatch< T >::Get () const inline
Returns the accumulated value without altering the stopwatch state.
Definition at line 84 of file Stopwatch.h.
References stride::util::Stopwatch< T >::m_accumulated, stride::util::Stopwatch< T >::m_last_start, and stride::util::Stopwatch< T >::m_running.
Referenced by stride::util::Stopwatch< T >::ToString().
template<typename T = std::chrono::steady_clock> std::string stride::util::Stopwatch< T >::ToString () const inline
Returns string representation of readout.
Definition at line 94 of file Stopwatch.h.
References stride::util::Stopwatch< T >::Get(), and stride::util::TimeToString::ToColonString().
Referenced by stride::ControlHelper::LogShutdown().
Member Data Documentation
template<typename T = std::chrono::steady_clock> T::duration stride::util::Stopwatch< T >::m_accumulated private
Definition at line 115 of file Stopwatch.h.
Referenced by stride::util::Stopwatch< T >::Get(), stride::util::Stopwatch< T >::Reset(), and stride::util::Stopwatch< T >::Stop().
template<typename T = std::chrono::steady_clock> T::time_point stride::util::Stopwatch< T >::m_last_start private
Definition at line 116 of file Stopwatch.h.
Referenced by stride::util::Stopwatch< T >::Get(), stride::util::Stopwatch< T >::Start(), stride::util::Stopwatch< T >::Stop(), and stride::util::Stopwatch< T >::Stopwatch().
template<typename T = std::chrono::steady_clock> std::string stride::util::Stopwatch< T >::m_name private
Definition at line 117 of file Stopwatch.h.
Referenced by stride::util::Stopwatch< T >::GetName().
template<typename T = std::chrono::steady_clock> bool stride::util::Stopwatch< T >::m_running private
Definition at line 118 of file Stopwatch.h.
Referenced by stride::util::Stopwatch< T >::Get(), stride::util::Stopwatch< T >::IsRunning(), stride::util::Stopwatch< T >::Reset(), stride::util::Stopwatch< T >::Start(), stride::util::Stopwatch< T >::Stop(), and stride::util::Stopwatch< T >::Stopwatch().
The documentation for this class was generated from the following file:
Stopwatch.h