Stride Reference Manual: proto::GeoGrid_Location_ContactCenter_ContactPool Class Reference
proto::GeoGrid_Location_ContactCenter_ContactPool Class Reference
#include <geogrid.pb.h>
Public Member Functions
GeoGrid_Location_ContactCenter_ContactPool ()
virtual ~GeoGrid_Location_ContactCenter_ContactPool ()
GeoGrid_Location_ContactCenter_ContactPool (const GeoGrid_Location_ContactCenter_ContactPool &from)
GeoGrid_Location_ContactCenter_ContactPool & operator= (const GeoGrid_Location_ContactCenter_ContactPool &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (GeoGrid_Location_ContactCenter_ContactPool *other)
GeoGrid_Location_ContactCenter_ContactPool * New () const final
GeoGrid_Location_ContactCenter_ContactPool * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const GeoGrid_Location_ContactCenter_ContactPool &from)
void MergeFrom (const GeoGrid_Location_ContactCenter_ContactPool &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int people_size () const
void clear_people ()
::google::protobuf::int64 people (int index) const
void set_people (int index,::google::protobuf::int64 value)
void add_people (::google::protobuf::int64 value)
const ::google::protobuf::RepeatedField<::google::protobuf::int64 > & people () const
::google::protobuf::RepeatedField<::google::protobuf::int64 > * mutable_people ()
bool has_id () const
void clear_id ()
::google::protobuf::int64 id () const
void set_id (::google::protobuf::int64 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const GeoGrid_Location_ContactCenter_ContactPool & default_instance ()
static void InitAsDefaultInstance ()
static const GeoGrid_Location_ContactCenter_ContactPool * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages = 1
static const int kPeopleFieldNumber = 2
static const int kIdFieldNumber = 1
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const final
void InternalSwap (GeoGrid_Location_ContactCenter_ContactPool *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
void set_has_id ()
void clear_has_id ()
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
mutable::google::protobuf::internal::CachedSize _cached_size_
::google::protobuf::RepeatedField<::google::protobuf::int64 > people_
::google::protobuf::int64 id_
Friends
struct ::protobuf_geogrid_2eproto::TableStruct
void swap (GeoGrid_Location_ContactCenter_ContactPool &a, GeoGrid_Location_ContactCenter_ContactPool &b)
Detailed Description
Definition at line 255 of file geogrid.pb.h.
Constructor & Destructor Documentation
proto::GeoGrid_Location_ContactCenter_ContactPool::GeoGrid_Location_ContactCenter_ContactPool ()
virtual proto::GeoGrid_Location_ContactCenter_ContactPool::~GeoGrid_Location_ContactCenter_ContactPool () virtual
proto::GeoGrid_Location_ContactCenter_ContactPool::GeoGrid_Location_ContactCenter_ContactPool (const GeoGrid_Location_ContactCenter_ContactPool & from)
Member Function Documentation
GeoGrid_Location_ContactCenter_ContactPool& proto::GeoGrid_Location_ContactCenter_ContactPool::operator= (const GeoGrid_Location_ContactCenter_ContactPool & from) inline
Definition at line 266 of file geogrid.pb.h.
References GetArenaNoVirtual().
const ::google::protobuf::UnknownFieldSet& proto::GeoGrid_Location_ContactCenter_ContactPool::unknown_fields () const inline
Definition at line 291 of file geogrid.pb.h.
inline ::google::protobuf::UnknownFieldSet* proto::GeoGrid_Location_ContactCenter_ContactPool::mutable_unknown_fields () inline
Definition at line 295 of file geogrid.pb.h.
static const ::google::protobuf::Descriptor* proto::GeoGrid_Location_ContactCenter_ContactPool::descriptor () static
static const GeoGrid_Location_ContactCenter_ContactPool& proto::GeoGrid_Location_ContactCenter_ContactPool::default_instance () static
static void proto::GeoGrid_Location_ContactCenter_ContactPool::InitAsDefaultInstance () static
static const GeoGrid_Location_ContactCenter_ContactPool* proto::GeoGrid_Location_ContactCenter_ContactPool::internal_default_instance () inline static
Definition at line 304 of file geogrid.pb.h.
References proto::_GeoGrid_Location_ContactCenter_ContactPool_default_instance_.
void proto::GeoGrid_Location_ContactCenter_ContactPool::Swap (GeoGrid_Location_ContactCenter_ContactPool * other)
GeoGrid_Location_ContactCenter_ContactPool* proto::GeoGrid_Location_ContactCenter_ContactPool::New () const inline final
Definition at line 319 of file geogrid.pb.h.
GeoGrid_Location_ContactCenter_ContactPool* proto::GeoGrid_Location_ContactCenter_ContactPool::New (::google::protobuf::Arena * arena) const inline final
Definition at line 324 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter_ContactPool::CopyFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Location_ContactCenter_ContactPool::MergeFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Location_ContactCenter_ContactPool::CopyFrom (const GeoGrid_Location_ContactCenter_ContactPool & from)
void proto::GeoGrid_Location_ContactCenter_ContactPool::MergeFrom (const GeoGrid_Location_ContactCenter_ContactPool & from)
void proto::GeoGrid_Location_ContactCenter_ContactPool::Clear () final
bool proto::GeoGrid_Location_ContactCenter_ContactPool::IsInitialized () const final
size_t proto::GeoGrid_Location_ContactCenter_ContactPool::ByteSizeLong () const final
bool proto::GeoGrid_Location_ContactCenter_ContactPool::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
void proto::GeoGrid_Location_ContactCenter_ContactPool::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
::google::protobuf::uint8* proto::GeoGrid_Location_ContactCenter_ContactPool::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
int proto::GeoGrid_Location_ContactCenter_ContactPool::GetCachedSize () const inline final
Definition at line 340 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter_ContactPool::SharedCtor () private
void proto::GeoGrid_Location_ContactCenter_ContactPool::SharedDtor () private
void proto::GeoGrid_Location_ContactCenter_ContactPool::SetCachedSize (int size) const final private
void proto::GeoGrid_Location_ContactCenter_ContactPool::InternalSwap (GeoGrid_Location_ContactCenter_ContactPool * other) private
inline ::google::protobuf::Arena* proto::GeoGrid_Location_ContactCenter_ContactPool::GetArenaNoVirtual () const inline private
Definition at line 349 of file geogrid.pb.h.
Referenced by operator=().
void* proto::GeoGrid_Location_ContactCenter_ContactPool::MaybeArenaPtr () const inline private
Definition at line 350 of file geogrid.pb.h.
::google::protobuf::Metadata proto::GeoGrid_Location_ContactCenter_ContactPool::GetMetadata () const final
int proto::GeoGrid_Location_ContactCenter_ContactPool::people_size () const inline
Definition at line 1216 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseContactPool().
void proto::GeoGrid_Location_ContactCenter_ContactPool::clear_people () inline
Definition at line 1217 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location_ContactCenter_ContactPool::people (int index) const inline
Definition at line 1218 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseContactPool().
void proto::GeoGrid_Location_ContactCenter_ContactPool::set_people (int index, ::google::protobuf::int64 value) inline
Definition at line 1223 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter_ContactPool::add_people (::google::protobuf::int64 value) inline
Definition at line 1228 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WriteContactPool().
const ::google::protobuf::RepeatedField<::google::protobuf::int64 > & proto::GeoGrid_Location_ContactCenter_ContactPool::people () const inline
Definition at line 1234 of file geogrid.pb.h.
google::protobuf::RepeatedField<::google::protobuf::int64 > * proto::GeoGrid_Location_ContactCenter_ContactPool::mutable_people () inline
Definition at line 1240 of file geogrid.pb.h.
bool proto::GeoGrid_Location_ContactCenter_ContactPool::has_id () const inline
Definition at line 1195 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter_ContactPool::clear_id () inline
Definition at line 1198 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location_ContactCenter_ContactPool::id () const inline
Definition at line 1203 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter_ContactPool::set_id (::google::protobuf::int64 value) inline
Definition at line 1208 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WriteContactPool().
void proto::GeoGrid_Location_ContactCenter_ContactPool::set_has_id () inline private
Definition at line 1196 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter_ContactPool::clear_has_id () inline private
Definition at line 1197 of file geogrid.pb.h.
Friends And Related Function Documentation
friend struct ::protobuf_geogrid_2eproto::TableStruct friend
Definition at line 386 of file geogrid.pb.h.
void swap (GeoGrid_Location_ContactCenter_ContactPool & a, GeoGrid_Location_ContactCenter_ContactPool & b) friend
Definition at line 312 of file geogrid.pb.h.
Member Data Documentation
constexpr int proto::GeoGrid_Location_ContactCenter_ContactPool::kIndexInFileMessages = 1 static
Definition at line 309 of file geogrid.pb.h.
const int proto::GeoGrid_Location_ContactCenter_ContactPool::kPeopleFieldNumber = 2 static
Definition at line 362 of file geogrid.pb.h.
const int proto::GeoGrid_Location_ContactCenter_ContactPool::kIdFieldNumber = 1 static
Definition at line 372 of file geogrid.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::GeoGrid_Location_ContactCenter_ContactPool::_internal_metadata_ private
Definition at line 381 of file geogrid.pb.h.
::google::protobuf::internal::HasBits<1> proto::GeoGrid_Location_ContactCenter_ContactPool::_has_bits_ private
Definition at line 382 of file geogrid.pb.h.
mutable ::google::protobuf::internal::CachedSize proto::GeoGrid_Location_ContactCenter_ContactPool::_cached_size_ private
Definition at line 383 of file geogrid.pb.h.
::google::protobuf::RepeatedField<::google::protobuf::int64> proto::GeoGrid_Location_ContactCenter_ContactPool::people_ private
Definition at line 384 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Location_ContactCenter_ContactPool::id_ private
Definition at line 385 of file geogrid.pb.h.
The documentation for this class was generated from the following file:
geogrid.pb.h