Stride Reference Manual: stride.cpp File Reference
stride.cpp File Reference
Main program: command line handling.
#include "GenPopController.h"
#include "SimController.h"
#include "StanController.h"
#include "util/FileSys.h"
#include "util/RunConfigManager.h"
#include "util/StringUtils.h"
#include "util/TimeStamp.h"
#include <boost/property_tree/ptree.hpp>
#include <tclap/CmdLine.h>
#include <iostream>
#include <regex>
#include <string>
#include <vector>
Functions
int main (int argc, char **argv)
Main program of the stride simulator.
Detailed Description
Main program: command line handling.
Definition in file stride.cpp.
Function Documentation
int main (int argc, char ** argv)
Main program of the stride simulator.
Definition at line 44 of file stride.cpp.
References stride::SimController::Control(), stride::GenPopController::Control(), stride::StanController::Control(), and stride::util::Tokenize().