Stride Reference Manual: geopop Namespace Reference
geopop Namespace Reference
Namespace for the geographic and demograhic classes.
Namespaces
geogrid_detail
kd
Classes
struct AABBox
AxisAlignedBoundingBox (hyperrectangle defined by lower and upper bound for every dimension).
class BoxPolicy
GeoAggregator Policy that aggregates over an axis aligned bounding box.
class Collector
Aggregates into a vector that must should remain alive for the usage duration of the Collector.
class CommutesCSVReader
Create a Reader that fills a GeoGrid with the commute info from CSV file.
class CommutesReader
Create an abstract Reader that fills a GeoGrid with the commute info from file.
class Generator
Generator uses geo & pop data to construct ContactPools in the GeoGrid.
class GeoAggregator
A GeoAggregator can either be instantiated with a functor, or be called with one every time.
class GeoAggregator< Policy >
A GeoAggregator that has to be called with a functor.
class GeoAggregator< Policy, F >
A GeoAggregator constructed with a functor.
class GeoGrid
A Geographic grid of simulation region contains Locations that in turn contain an index to the ContactPools situated at that Location.
class GeoGridConfig
Configuration data mostly for generating a population, but also for computing the required number of schools, workplaces, communities etc.
class GeoGridJSONReader
An implementation of the GeoGridReader using JSON.
class GeoGridJSONWriter
Writes a GeoGrid to a JSON file.
class GeoGridProtoReader
An implementation of the GeoGridReader using Protocol Buffers.
class GeoGridProtoWriter
An implementation of the GeoGridWriter using Protocol Buffers This class is used to write a GeoGrid to a Proto file.
class GeoGridReader
An abstract base class for creating a GeoGrid that was read from a file, can be implemented using multiple file types (proto and json are currently implemented)
class GeoGridReaderFactory
A Factory for creating the correct implementation of a GeoGridReader based on the filename extension.
class GeoGridWriter
An interface for writing the GeoGrid to a file, can be implemented with multiple file types.
class GeoGridWriterFactory
Factory creates the correct implementation of a GeoGridWriter based on the filename extension.
class HouseholdCSVReader
Creates a Reader that retrieves the different Household profiles from a given CSV file.
class HouseholdReader
Retrieves the reference Household profiles from file.
class KdTree
A k-d tree: a k-dimensional generalization of binary search trees This data structure allows for efficient lookup of points and range queries with an Axis-Aligned Bounding Box (when balanced).
class Location
Location for use within the GeoGrid, contains Coordinate and index to ContactPools.
class LocationsCSVReader
Create a Reader that fills a GeoGrid with the Location data found in a CSV input stream.
class LocationsReader
Create an abstract Reader which fills a GeoGrid with the cities found in file.
class PolygonPolicy
A GeoAggregator Policy that aggregates over a (clockwise) polygon.
class Populator
Populator uses geo & pop data to populate ContactPools in the GeoGrid.
class RadiusPolicy
GeoAggregator Policy that aggregates locations within a radius (in km) of a center point.
class ReaderFactory
A Factory for creating the correct implementation of the different Readers which parse the information needed to construct a GeoGrid, based on the file extension.
Typedefs
using Coordinate = boost::geometry::model::point< double, 2, boost::geometry::cs::geographic< boost::geometry::degree >>
using K12SchoolGenerator = Generator< stride::ContactType::Id::K12School >
using CollegeGenerator = Generator< stride::ContactType::Id::College >
using WorkplaceGenerator = Generator< stride::ContactType::Id::Workplace >
using HouseholdGenerator = Generator< stride::ContactType::Id::Household >
using PrimaryCommunityGenerator = Generator< stride::ContactType::Id::PrimaryCommunity >
using SecondaryCommunityGenerator = Generator< stride::ContactType::Id::SecondaryCommunity >
using GeoGridKdTree = KdTree< geogrid_detail::KdTree2DPoint >
using K12SchoolPopulator = Populator< stride::ContactType::Id::K12School >
using CollegePopulator = Populator< stride::ContactType::Id::College >
using WorkplacePopulator = Populator< stride::ContactType::Id::Workplace >
using HouseholdPopulator = Populator< stride::ContactType::Id::Household >
using PrimaryCommunityPopulator = Populator< stride::ContactType::Id::PrimaryCommunity >
using SecondaryCommunityPopulator = Populator< stride::ContactType::Id::SecondaryCommunity >
Functions
template<typename InsertIter , typename T = typename InsertIter::container_type::value_type>
Collector< InsertIter, T > MakeCollector (const InsertIter &ins)
Build a Collector, useful for type inference.
ostream & operator<< (ostream &out, const GeoGridConfig &config)
Detailed Description
Namespace for the geographic and demograhic classes.
Typedef Documentation
using geopop::Coordinate = typedef boost::geometry::model::point<double, 2, boost::geometry::cs::geographic<boost::geometry::degree>>
Definition at line 23 of file Coordinate.h.
using geopop::K12SchoolGenerator = typedef Generator<stride::ContactType::Id::K12School>
Definition at line 93 of file Generator.h.
using geopop::CollegeGenerator = typedef Generator<stride::ContactType::Id::College>
Definition at line 94 of file Generator.h.
using geopop::WorkplaceGenerator = typedef Generator<stride::ContactType::Id::Workplace>
Definition at line 95 of file Generator.h.
using geopop::HouseholdGenerator = typedef Generator<stride::ContactType::Id::Household>
Definition at line 96 of file Generator.h.
using geopop::PrimaryCommunityGenerator = typedef Generator<stride::ContactType::Id::PrimaryCommunity>
Definition at line 97 of file Generator.h.
using geopop::SecondaryCommunityGenerator = typedef Generator<stride::ContactType::Id::SecondaryCommunity>
Definition at line 98 of file Generator.h.
using geopop::GeoGridKdTree = typedef KdTree<geogrid_detail::KdTree2DPoint>
Definition at line 25 of file GeoGridKdTree.h.
using geopop::K12SchoolPopulator = typedef Populator<stride::ContactType::Id::K12School>
Definition at line 82 of file Populator.h.
using geopop::CollegePopulator = typedef Populator<stride::ContactType::Id::College>
Definition at line 83 of file Populator.h.
using geopop::WorkplacePopulator = typedef Populator<stride::ContactType::Id::Workplace>
Definition at line 84 of file Populator.h.
using geopop::HouseholdPopulator = typedef Populator<stride::ContactType::Id::Household>
Definition at line 85 of file Populator.h.
using geopop::PrimaryCommunityPopulator = typedef Populator<stride::ContactType::Id::PrimaryCommunity>
Definition at line 86 of file Populator.h.
using geopop::SecondaryCommunityPopulator = typedef Populator<stride::ContactType::Id::SecondaryCommunity>
Definition at line 87 of file Populator.h.
Function Documentation
template<typename InsertIter , typename T = typename InsertIter::container_type::value_type> Collector<InsertIter, T> geopop::MakeCollector (const InsertIter & ins)
Build a Collector, useful for type inference.
Definition at line 59 of file GeoAggregator.h.
Referenced by geopop::GeoGrid::LocationsInBox(), and geopop::GeoGrid::LocationsInRadius().
ostream& geopop::operator<< (ostream & out, const GeoGridConfig & config)
Definition at line 106 of file GeoGridConfig.cpp.
References geopop::GeoGridConfig::fraction_college_commuters, geopop::GeoGridConfig::fraction_workplace_commuters, geopop::GeoGridConfig::info, stride::util::intToDottedString(), geopop::GeoGridConfig::param, geopop::GeoGridConfig::participation_college, geopop::GeoGridConfig::particpation_workplace, geopop::GeoGridConfig::pop_size, geopop::GeoGridConfig::popcount_college, geopop::GeoGridConfig::popcount_k12school, and geopop::GeoGridConfig::popcount_workplace.