Stride Reference Manual: geopop::ContactCenter Class Reference
geopop::ContactCenter Class Reference abstract
A ContactCenter represents a number of ContactPools of same ContactType::Id that are related.
#include <ContactCenter.h>
Public Types
using iterator = std::vector< stride::ContactPool * >::iterator
using const_iterator = std::vector< stride::ContactPool * >::const_iterator
Public Member Functions
ContactCenter (unsigned int id)
Construct ContactCenter with assigned ID.
virtual ~ContactCenter ()=default
Default destructor, but virtual.
unsigned int GetId () const
Return the ID of this ContactCenter.
std::pair< unsigned int, unsigned int > GetPopulationAndInfectedCount () const
Get a count of total population (first) and total number of infections (second).
virtual stride::ContactType::Id GetContactPoolType () const =0
Get the the type of ContactPools this ContactCenter contains.
void RegisterPool (stride::ContactPool *pool)
Register a ContactPool with this ContactCenter.
virtual void SetupPools (const GeoGridConfig &geoGridConfig, stride::Population *pop)=0
Create ContactPools in the GeoGrid and register them with the ContactCenter.
iterator begin ()
Iterator to first Location.
iterator end ()
Iterator to the end of the Location storage.
const_iterator cbegin () const
Const Iterator to first Location.
const_iterator cend () const
Const iterator to the end of the Location storage.
stride::ContactPool *const & operator[] (size_t index) const
Gets a ContactPool by index, doesn't performs a range check.
size_t size () const
Gets current size of Location storage.
Protected Attributes
std::vector< stride::ContactPool * > m_pools
ContactPools for this ContactCenter.
unsigned int m_id
The Id of this ContactCenter.
Detailed Description
A ContactCenter represents a number of ContactPools of same ContactType::Id that are related.
Examples are classes (Pools with ID value K12School) vs school (ContactCenter K12School) or teams (Pools with Id value Workplace) vs company (ContactCenter WorkPlace).
Definition at line 38 of file ContactCenter.h.
Member Typedef Documentation
using geopop::ContactCenter::iterator = std::vector<stride::ContactPool*>::iterator
Definition at line 63 of file ContactCenter.h.
using geopop::ContactCenter::const_iterator = std::vector<stride::ContactPool*>::const_iterator
Definition at line 64 of file ContactCenter.h.
Constructor & Destructor Documentation
geopop::ContactCenter::ContactCenter (unsigned int id) inline explicit
Construct ContactCenter with assigned ID.
Definition at line 42 of file ContactCenter.h.
References ~ContactCenter().
virtual geopop::ContactCenter::~ContactCenter () virtual default
Default destructor, but virtual.
Referenced by ContactCenter().
Member Function Documentation
unsigned int geopop::ContactCenter::GetId () const inline
Return the ID of this ContactCenter.
Definition at line 48 of file ContactCenter.h.
References GetContactPoolType(), GetPopulationAndInfectedCount(), and m_id.
std::pair< unsigned int, unsigned int > geopop::ContactCenter::GetPopulationAndInfectedCount () const
Get a count of total population (first) and total number of infections (second).
Definition at line 22 of file ContactCenter.cpp.
References m_pools.
Referenced by GetId().
virtual stride::ContactType::Id geopop::ContactCenter::GetContactPoolType () const pure virtual
Get the the type of ContactPools this ContactCenter contains.
Implemented in geopop::CollegeCenter, geopop::HouseholdCenter, geopop::K12SchoolCenter, geopop::PrimaryCommunityCenter, geopop::SecondaryCommunityCenter, and geopop::WorkplaceCenter.
Referenced by GetId().
void geopop::ContactCenter::RegisterPool (stride::ContactPool * pool) inline
Register a ContactPool with this ContactCenter.
Definition at line 57 of file ContactCenter.h.
References m_pools, and SetupPools().
Referenced by geopop::K12SchoolCenter::SetupPools(), and geopop::WorkplaceCenter::SetupPools().
virtual void geopop::ContactCenter::SetupPools (const GeoGridConfig & geoGridConfig, stride::Population * pop) pure virtual
Create ContactPools in the GeoGrid and register them with the ContactCenter.
Implemented in geopop::CollegeCenter, geopop::HouseholdCenter, geopop::K12SchoolCenter, geopop::PrimaryCommunityCenter, geopop::SecondaryCommunityCenter, and geopop::WorkplaceCenter.
Referenced by RegisterPool().
iterator geopop::ContactCenter::begin () inline
Iterator to first Location.
Definition at line 67 of file ContactCenter.h.
References m_pools.
iterator geopop::ContactCenter::end () inline
Iterator to the end of the Location storage.
Definition at line 70 of file ContactCenter.h.
References m_pools.
const_iterator geopop::ContactCenter::cbegin () const inline
Const Iterator to first Location.
Definition at line 73 of file ContactCenter.h.
References m_pools.
const_iterator geopop::ContactCenter::cend () const inline
Const iterator to the end of the Location storage.
Definition at line 76 of file ContactCenter.h.
References m_pools.
stride::ContactPool* const& geopop::ContactCenter::operator[] (size_t index) const inline
Gets a ContactPool by index, doesn't performs a range check.
Definition at line 79 of file ContactCenter.h.
References m_pools.
size_t geopop::ContactCenter::size () const inline
Gets current size of Location storage.
Definition at line 82 of file ContactCenter.h.
References m_pools.
Member Data Documentation
std::vector<stride::ContactPool*> geopop::ContactCenter::m_pools protected
ContactPools for this ContactCenter.
Definition at line 85 of file ContactCenter.h.
Referenced by begin(), cbegin(), cend(), end(), GetPopulationAndInfectedCount(), operator[](), RegisterPool(), and size().
unsigned int geopop::ContactCenter::m_id protected
The Id of this ContactCenter.
Definition at line 86 of file ContactCenter.h.
Referenced by GetId().
The documentation for this class was generated from the following files:
ContactCenter.h
ContactCenter.cpp