Stride Reference Manual: stride::ControlHelper Class Reference
stride::ControlHelper Class Reference
Controls a simulation run initiated with the command line interface (cli).
#include <ControlHelper.h>
Public Member Functions
ControlHelper (std::string name, const boost::property_tree::ptree &configPt)
Straight initialization.
Protected Member Functions
ControlHelper ()
Empty controller: used as target for delegation.
void CheckEnv ()
Check install environment.
void CheckOutputPrefix ()
void InstallLogger ()
Make the appropriate logger for cli environment and register as stride_logger.
void LogShutdown ()
Logs info on setup for cli environment to stride_logger.
void LogStartup ()
Logs info on setup for cli environment to stride_logger.
void RegisterViewers (std::shared_ptr< SimRunner > runner)
Register the viewers of the SimRunner.
Protected Attributes
boost::property_tree::ptree m_config_pt
Main configuration for run and sim.
std::string m_name
Contoller's name.
std::string m_output_prefix
Prefix to output (name prefix or prefix dir)
util::RnMan m_rn_manager
The manager for random numbers.
util::Stopwatch m_run_clock
Stopwatch for timing the computation.
std::shared_ptr< spdlog::logger > m_stride_logger
General logger.
bool m_use_install_dirs
Working dir or install dir mode.
Detailed Description
Controls a simulation run initiated with the command line interface (cli).
ControlHelper functions effected on behalf of the controller include:
checks the OpenMP environment
checks the file system environment
interprets and executes the ouput prefix
install a stride logger)
a utility method to register the appropriate viewers
Definition at line 45 of file ControlHelper.h.
Constructor & Destructor Documentation
stride::ControlHelper::ControlHelper (std::string name, const boost::property_tree::ptree & configPt) explicit
Straight initialization.
stride::ControlHelper::ControlHelper () explicit protected
Empty controller: used as target for delegation.
Definition at line 43 of file ControlHelper.cpp.
References stride::util::Rn< E >::Initialize(), m_config_pt, m_name, m_output_prefix, m_rn_manager, m_run_clock, m_use_install_dirs, and stride::util::Stopwatch< T >::Start().
Member Function Documentation
void stride::ControlHelper::CheckEnv () protected
Check install environment.
Definition at line 62 of file ControlHelper.cpp.
References stride::util::FileSys::CheckInstallEnv(), and m_use_install_dirs.
Referenced by stride::GenPopController::Control(), stride::SimController::Control(), and stride::StanController::Control().
void stride::ControlHelper::CheckOutputPrefix () protected
Definition at line 72 of file ControlHelper.cpp.
References stride::util::FileSys::CreateDirectory(), stride::util::FileSys::IsDirectoryString(), and m_output_prefix.
Referenced by stride::GenPopController::Control(), stride::SimController::Control(), and stride::StanController::Control().
void stride::ControlHelper::InstallLogger () protected
Make the appropriate logger for cli environment and register as stride_logger.
Definition at line 79 of file ControlHelper.cpp.
References stride::util::FileSys::BuildPath(), stride::util::LogUtils::CreateCliLogger(), m_config_pt, m_output_prefix, and m_stride_logger.
Referenced by stride::GenPopController::Control(), stride::SimController::Control(), and stride::StanController::Control().
void stride::ControlHelper::LogShutdown () protected
Logs info on setup for cli environment to stride_logger.
Definition at line 90 of file ControlHelper.cpp.
References m_name, m_run_clock, m_stride_logger, stride::util::Stopwatch< T >::Stop(), and stride::util::Stopwatch< T >::ToString().
Referenced by stride::GenPopController::Control(), stride::SimController::Control(), and stride::StanController::Control().
void stride::ControlHelper::LogStartup () protected
Logs info on setup for cli environment to stride_logger.
Definition at line 96 of file ControlHelper.cpp.
References stride::util::FileSys::GetConfigDir(), stride::util::FileSys::GetCurrentDir(), stride::util::FileSys::GetDataDir(), stride::util::FileSys::GetExecPath(), stride::util::FileSys::GetRootDir(), stride::util::ConfigInfo::GitRevision(), stride::util::ConfigInfo::HaveOpenMP(), m_config_pt, m_name, m_output_prefix, m_stride_logger, m_use_install_dirs, stride::util::ConfigInfo::NumberAvailableThreads(), and stride::ContactLogMode::ToString().
Referenced by stride::GenPopController::Control(), stride::SimController::Control(), and stride::StanController::Control().
void stride::ControlHelper::RegisterViewers (std::shared_ptr< SimRunner > runner) protected
Register the viewers of the SimRunner.
Definition at line 118 of file ControlHelper.cpp.
References m_config_pt, m_output_prefix, m_stride_logger, stride::viewers::CliViewer::Update(), stride::viewers::SummaryFileViewer::Update(), stride::viewers::PersonsFileViewer::Update(), and stride::viewers::InfectedFileViewer::Update().
Referenced by stride::SimController::Control().
Member Data Documentation
boost::property_tree::ptree stride::ControlHelper::m_config_pt protected
Main configuration for run and sim.
Definition at line 75 of file ControlHelper.h.
Referenced by stride::GenPopController::Control(), stride::SimController::Control(), stride::StanController::Control(), ControlHelper(), InstallLogger(), LogStartup(), and RegisterViewers().
std::string stride::ControlHelper::m_name protected
Contoller's name.
Definition at line 76 of file ControlHelper.h.
Referenced by ControlHelper(), LogShutdown(), and LogStartup().
std::string stride::ControlHelper::m_output_prefix protected
Prefix to output (name prefix or prefix dir)
Definition at line 77 of file ControlHelper.h.
Referenced by CheckOutputPrefix(), ControlHelper(), InstallLogger(), LogStartup(), and RegisterViewers().
util::RnMan stride::ControlHelper::m_rn_manager protected
The manager for random numbers.
Definition at line 78 of file ControlHelper.h.
Referenced by stride::GenPopController::Control(), stride::SimController::Control(), stride::StanController::Control(), and ControlHelper().
util::Stopwatch stride::ControlHelper::m_run_clock protected
Stopwatch for timing the computation.
Definition at line 79 of file ControlHelper.h.
Referenced by ControlHelper(), and LogShutdown().
std::shared_ptr<spdlog::logger> stride::ControlHelper::m_stride_logger protected
General logger.
Definition at line 80 of file ControlHelper.h.
Referenced by stride::GenPopController::Control(), stride::SimController::Control(), stride::StanController::Control(), InstallLogger(), LogShutdown(), LogStartup(), and RegisterViewers().
bool stride::ControlHelper::m_use_install_dirs protected
Working dir or install dir mode.
Definition at line 81 of file ControlHelper.h.
Referenced by CheckEnv(), ControlHelper(), and LogStartup().
The documentation for this class was generated from the following files:
ControlHelper.h
ControlHelper.cpp