Stride Reference Manual: stride::Population Class Reference
stride::Population Class Reference
Key Data structure: container for (a) all individuals in the population (b) the ContactPoolSys wchich is used to loop over ContactPools of each type (c) (if present) geographical grid of Locations with ContactCenters at that location.
#include <Population.h>
Public Member Functions
ContactPool * CreateContactPool (ContactPoolType::Id typeId)
Add a new contact pool of a given type.
Person * CreatePerson (unsigned int id, double age, unsigned int householdId, unsigned int k12SchoolId, unsigned int college, unsigned int workId, unsigned int primaryCommunityId, unsigned int secondaryCommunityId)
Create Person in the population.
unsigned int GetInfectedCount () const
Get the cumulative number of cases.
std::shared_ptr< spdlog::logger > & GetContactLogger ()
Return the contactlogger.
ContactPoolSys & GetContactPoolSys ()
The ContactPoolSys of the simulator.
const ContactPoolSys & GetContactPoolSys () const
The ContactPoolSys of the simulator.
std::shared_ptr< gengeopop::GeoGrid > GetGeoGrid () const
Get the GeoGrid associated with this population (may be a nullptr).
Public Member Functions inherited from stride::util::SegmentedVector< Person >
SegmentedVector ()
Construct empty SegmentedVector.
SegmentedVector (size_type i)
Construct with given number of elements but DO NOT INITIALIZE them.
SegmentedVector (size_type i, const value_type &value)
Construct with given number of elements and INITIALIZE them with value.
SegmentedVector (const self_type &other)
Copy constructor.
SegmentedVector (self_type &&other) noexcept
Move constructor.
SegmentedVector & operator= (const self_type &other)
Copy assignment.
SegmentedVector & operator= (self_type &&other) noexcept
Move assignment.
~SegmentedVector ()
Destructor.
Person & at (std::size_t pos)
Access specified element with bounds checking.
const Person & at (std::size_t pos) const
Access specified element with bounds checking.
Person & back ()
Access the last element.
const Person & back () const
Access the last element.
Person & operator[] (size_t pos)
Access specified element (no bounds checking).
const Person & operator[] (size_t pos) const
Access specified element (no bounds checking).
iterator begin ()
Returns an iterator to the beginning of the container.
const_iterator begin () const
Returns a const_iterator to the beginning of the container.
const_iterator cbegin () const
Returns a const_iterator to the beginning of the container.
iterator end ()
Returns an iterator to the end of the container.
const_iterator end () const
Returns a const_iterator to the end of the container.
const_iterator cend () const
Returns a const_iterator to the end.
std::size_t capacity () const
Returns number of elements that can be stored without allocating additional blocks.
bool empty () const
Checks whether container is empty.
std::size_t get_block_count () const
Returns number of currently allocated blocks.
std::size_t get_elements_per_block () const
Returns number of elements block (template parameter 'N').
std::size_t size () const
Returns the number of elements.
void resize (size_type new_size)
Increases the number of elements (but DOES NOT INITIALIZE the additional elements) or pops elements (and DOES RUN those element's destructor).
void resize (size_type new_size, const value_type &value)
void clear ()
Clears the content.
Person * emplace (size_type pos, Args &&...args)
Constructs element in-place at position pos.
Person * emplace_back (Args &&...args)
Constructs element in-place at the end.
void pop_back ()
Removes the last element.
Person * push_back (const Person &obj)
Adds element to end.
Person * push_back (Person &&obj)
Adds element to end.
Static Public Member Functions
static std::shared_ptr< Population > Create (const boost::property_tree::ptree &configPt, util::RnMan &rnManager, std::shared_ptr< spdlog::logger > stride_logger=nullptr)
Create a population initialized by the configuration in property tree.
static std::shared_ptr< Population > Create (const std::string &configString, util::RnMan &rnManager, std::shared_ptr< spdlog::logger > stride_logger=nullptr)
For use in python environment: create using configuration string i.o ptree.
static std::shared_ptr< Population > Create ()
Create an empty Population, used in gengeopop.
Private Member Functions
Population ()
Private Attributes
ContactPoolSys m_pool_sys
Holds vector of ContactPools of different types.
std::shared_ptr< spdlog::logger > m_contact_logger
Logger for contact/transmission.
std::shared_ptr< gengeopop::GeoGrid > m_geoGrid
Associated geoGrid may be nullptr.
std::size_t m_currentContactPoolId = 1
The contact pool counter for assigning pool IDs.
Friends
class DefaultPopBuilder
class GeoPopBuilder
class ImportPopBuilder
Additional Inherited Members
Public Types inherited from stride::util::SegmentedVector< Person >
using value_type = Person
using size_type = std::size_t
using self_type = SegmentedVector< Person, 512 >
using iterator = SVIterator< Person, 512, true, Person *, Person &, false >
using const_iterator = SVIterator< Person, 512, true >
Detailed Description
Key Data structure: container for (a) all individuals in the population (b) the ContactPoolSys wchich is used to loop over ContactPools of each type (c) (if present) geographical grid of Locations with ContactCenters at that location.
Definition at line 44 of file Population.h.
Constructor & Destructor Documentation
stride::Population::Population () inline private
Definition at line 83 of file Population.h.
Member Function Documentation
std::shared_ptr< Population > stride::Population::Create (const boost::property_tree::ptree & configPt, util::RnMan & rnManager, std::shared_ptr< spdlog::logger > stride_logger = nullptr) static
Create a population initialized by the configuration in property tree.
Definition at line 42 of file Population.cpp.
References stride::ImportPopBuilder::Build(), stride::GeoPopBuilder::Build(), and stride::DefaultPopBuilder::Build().
std::shared_ptr< Population > stride::Population::Create (const std::string & configString, util::RnMan & rnManager, std::shared_ptr< spdlog::logger > stride_logger = nullptr) static
For use in python environment: create using configuration string i.o ptree.
Definition at line 85 of file Population.cpp.
References stride::util::FromString().
std::shared_ptr< Population > stride::Population::Create () static
Create an empty Population, used in gengeopop.
Definition at line 91 of file Population.cpp.
Referenced by stride::GenPopController::Control(), stride::SimController::Control(), and stride::StanController::Control().
ContactPool * stride::Population::CreateContactPool (ContactPoolType::Id typeId)
Add a new contact pool of a given type.
Definition at line 121 of file Population.cpp.
Referenced by gengeopop::GeoGrid::CreateContactPool().
Person * stride::Population::CreatePerson (unsigned int id, double age, unsigned int householdId, unsigned int k12SchoolId, unsigned int college, unsigned int workId, unsigned int primaryCommunityId, unsigned int secondaryCommunityId)
Create Person in the population.
Definition at line 113 of file Population.cpp.
Referenced by gengeopop::GeoGrid::CreatePerson().
unsigned int stride::Population::GetInfectedCount () const
Get the cumulative number of cases.
Definition at line 103 of file Population.cpp.
std::shared_ptr<spdlog::logger>& stride::Population::GetContactLogger () inline
Return the contactlogger.
Definition at line 70 of file Population.h.
References m_contact_logger.
Referenced by stride::SurveySeeder::Seed(), and stride::Sim::TimeStep().
ContactPoolSys& stride::Population::GetContactPoolSys () inline
The ContactPoolSys of the simulator.
Definition at line 73 of file Population.h.
References m_pool_sys.
Referenced by stride::SurveySeeder::Seed(), and stride::Sim::TimeStep().
const ContactPoolSys& stride::Population::GetContactPoolSys () const inline
The ContactPoolSys of the simulator.
Definition at line 76 of file Population.h.
References m_pool_sys.
std::shared_ptr<gengeopop::GeoGrid> stride::Population::GetGeoGrid () const inline
Get the GeoGrid associated with this population (may be a nullptr).
Definition at line 79 of file Population.h.
References m_geoGrid.
Friends And Related Function Documentation
friend class DefaultPopBuilder friend
Definition at line 85 of file Population.h.
friend class GeoPopBuilder friend
Definition at line 86 of file Population.h.
friend class ImportPopBuilder friend
Definition at line 87 of file Population.h.
Member Data Documentation
ContactPoolSys stride::Population::m_pool_sys private
Holds vector of ContactPools of different types.
Definition at line 90 of file Population.h.
Referenced by GetContactPoolSys().
std::shared_ptr<spdlog::logger> stride::Population::m_contact_logger private
Logger for contact/transmission.
Definition at line 91 of file Population.h.
Referenced by GetContactLogger().
std::shared_ptr<gengeopop::GeoGrid> stride::Population::m_geoGrid private
Associated geoGrid may be nullptr.
Definition at line 92 of file Population.h.
Referenced by GetGeoGrid().
std::size_t stride::Population::m_currentContactPoolId = 1 private
The contact pool counter for assigning pool IDs.
Definition at line 95 of file Population.h.
The documentation for this class was generated from the following files:
Population.h
Population.cpp