Stride Reference Manual: stride::SimController Class Reference
stride::SimController Class Reference
Controls a simulation run initiated with the command line interface (cli).
#include <SimController.h>
Public Member Functions
SimController (const boost::property_tree::ptree &config)
Straight initialization.
void Control ()
Actual run of the simulator.
Additional Inherited Members
Protected Member Functions inherited from stride::ControlHelper
ControlHelper ()
Empty controller: used as target for delegation.
void CheckEnv ()
Check install environment.
void CheckOutputPrefix ()
void InstallLogger ()
Make the appropriate logger for cli environment and register as stride_logger.
void LogShutdown ()
Logs info on setup for cli environment to stride_logger.
void LogStartup ()
Logs info on setup for cli environment to stride_logger.
void RegisterViewers (std::shared_ptr< SimRunner > runner)
Register the viewers of the SimRunner.
ControlHelper (std::string name, const boost::property_tree::ptree &config)
Straight initialization.
Protected Attributes inherited from stride::ControlHelper
boost::property_tree::ptree m_config
Main configuration for run and sim.
std::string m_name
Contoller's name.
std::string m_output_prefix
Prefix to output (name prefix or prefix dir)
util::RnMan m_rn_man
Manager for random numbers.
util::Stopwatch m_run_clock
Stopwatch for timing the computation.
std::shared_ptr< spdlog::logger > m_stride_logger
General logger.
bool m_use_install_dirs
Working dir or install dir mode.
Detailed Description
Controls a simulation run initiated with the command line interface (cli).
SimController setup functions include (
See also
ControlHelper):
checks the OpenMP environment
checks the file system environment
interprets and executes the ouput prefix
intalls a stride logger
The SimController execution:
creates a population (
Population)
creates a simulation runner (
SimRunner)
registers the appropriate viewers
runs the simulation
Definition at line 44 of file SimController.h.
Constructor & Destructor Documentation
stride::SimController::SimController (const boost::property_tree::ptree & config) explicit
Straight initialization.
Definition at line 34 of file SimController.cpp.
Member Function Documentation
void stride::SimController::Control ()
Actual run of the simulator.
Definition at line 36 of file SimController.cpp.
References stride::ControlHelper::CheckEnv(), stride::ControlHelper::CheckOutputPrefix(), stride::Population::Create(), stride::ControlHelper::InstallLogger(), stride::ControlHelper::LogShutdown(), stride::ControlHelper::LogStartup(), stride::ControlHelper::m_config, stride::ControlHelper::m_rn_man, stride::ControlHelper::m_stride_logger, and stride::ControlHelper::RegisterViewers().
Referenced by main().
The documentation for this class was generated from the following files:
SimController.h
SimController.cpp