Stride Reference Manual: stride::GeoPopBuilder Class Reference
stride::GeoPopBuilder Class Reference
Builds poulation of a geographic grid.
#include <GeoPopBuilder.h>
Public Member Functions
GeoPopBuilder (const boost::property_tree::ptree &config, util::RnMan &rnMan, std::shared_ptr< spdlog::logger > strideLogger=nullptr)
Use constructor of base.
std::shared_ptr< Population > Build (std::shared_ptr< Population > pop) override
Generates a synthetic population.
Public Member Functions inherited from stride::AbstractPopBuilder
AbstractPopBuilder (const boost::property_tree::ptree &config, util::RnMan &rnMan, std::shared_ptr< spdlog::logger > strideLogger=nullptr)
Initializing constructor.
virtual ~AbstractPopBuilder ()=default
Has to be virtual.
Private Member Functions
void MakeLocations (geopop::GeoGrid &geoGrid, const geopop::GeoGridConfig &geoGridConfig, const std::string &citiesFileName, const std::string &commutingFileName)
Read files with location data and constructs GeoGrid config.
void MakePools (geopop::GeoGrid &geoGrid, const geopop::GeoGridConfig &geoGridConfig)
Build and store the Geo part of the GeoGrid.
void MakePersons (geopop::GeoGrid &geoGrid, const geopop::GeoGridConfig &geoGridConfig)
Build and store the Pop part of the GeoGrid.
Additional Inherited Members
Protected Attributes inherited from stride::AbstractPopBuilder
const boost::property_tree::ptree & m_config
Configuration property tree.
util::RnMan & m_rn_man
Random number generation management.
std::shared_ptr< spdlog::logger > m_stride_logger
Detailed Description
Builds poulation of a geographic grid.
Definition at line 41 of file GeoPopBuilder.h.
Constructor & Destructor Documentation
stride::GeoPopBuilder::GeoPopBuilder (const boost::property_tree::ptree & config, util::RnMan & rnMan, std::shared_ptr< spdlog::logger > strideLogger = nullptr)
Use constructor of base.
Initializing constructor.
Parameters
config Property_tree with general configuration settings.
rnMan Random number manager for pop build process.
strideLogger Logging.
Definition at line 48 of file GeoPopBuilder.cpp.
Member Function Documentation
shared_ptr< Population > stride::GeoPopBuilder::Build (std::shared_ptr< Population > pop) override virtual
Generates a synthetic population.
Implements stride::AbstractPopBuilder.
Definition at line 53 of file GeoPopBuilder.cpp.
References stride::AbstractPopBuilder::m_config, stride::AbstractPopBuilder::m_stride_logger, MakeLocations(), MakePersons(), MakePools(), and geopop::GeoGridConfig::SetData().
Referenced by stride::GenPopController::Control(), and stride::Population::Create().
void stride::GeoPopBuilder::MakeLocations (geopop::GeoGrid & geoGrid, const geopop::GeoGridConfig & geoGridConfig, const std::string & citiesFileName, const std::string & commutingFileName) private
Read files with location data and constructs GeoGrid config.
Definition at line 103 of file GeoPopBuilder.cpp.
References geopop::ReaderFactory::CreateCommutesReader(), geopop::ReaderFactory::CreateLocationsReader(), geopop::GeoGridConfig::param, and geopop::GeoGridConfig::pop_size.
Referenced by Build().
void stride::GeoPopBuilder::MakePools (geopop::GeoGrid & geoGrid, const geopop::GeoGridConfig & geoGridConfig) private
Build and store the Geo part of the GeoGrid.
Definition at line 120 of file GeoPopBuilder.cpp.
References stride::AbstractPopBuilder::m_rn_man, and stride::AbstractPopBuilder::m_stride_logger.
Referenced by Build().
void stride::GeoPopBuilder::MakePersons (geopop::GeoGrid & geoGrid, const geopop::GeoGridConfig & geoGridConfig) private
Build and store the Pop part of the GeoGrid.
Definition at line 135 of file GeoPopBuilder.cpp.
References stride::AbstractPopBuilder::m_rn_man, and stride::AbstractPopBuilder::m_stride_logger.
Referenced by Build().
The documentation for this class was generated from the following files:
GeoPopBuilder.h
GeoPopBuilder.cpp