Stride Reference Manual: stride::util::SliceIndexer< T, Id > Class Template Reference
stride::util::SliceIndexer< T, Id > Class Template Reference
Datastructure to index a container (supporting RandomAccessIterators) with slices.
#include <SliceIndexer.h>
Public Types
using range_type = boost::sliced_range< T >
Public Member Functions
SliceIndexer (T &t)
SliceIndexer holds a reference to the conatiner that it indexes.
range_type & Get (const Id &s)
Retrieve reference to a range by its Id.
const range_type & Get (const Id &s) const
Retrieve const reference to a range by its Id.
const std::vector< range_type > & Get ()
Retrieve all the ranges,.
range_type & Set (std::size_t ibegin, std::size_t iend, const Id &name)
Set a range. Warning: range is [ibegin, iend) i.e. half-open, iend not included!
range_type & Set (std::size_t ibegin, const Id &name)
Set a range, where the end is the end of the container.
Private Member Functions
void check (const Id &name)
Check Id map for duplicate; throw iff duplicate.
Private Attributes
std::map< Id, std::size_t > m_map
Maps Id values to subscripts.
std::vector< range_type > m_slices
Contains the slices.
T & m_t
Refernec to container that gets sliced into ranges.
Detailed Description
template<typename T, typename Id = std::string>
class stride::util::SliceIndexer< T, Id >
Datastructure to index a container (supporting RandomAccessIterators) with slices.
We store those slices in order in a vector and expose the vector because processing effiency may dictate that we retrieve the in that order. They can also be retrieved by identifier (defaults to a string).
Template Parameters
T Type of the container in whom the ranges are indexed.
Id Type of Id that can be useld to retrieve the ranges.
Definition at line 40 of file SliceIndexer.h.
Member Typedef Documentation
template<typename T , typename Id = std::string> using stride::util::SliceIndexer< T, Id >::range_type = boost::sliced_range<T>
Definition at line 43 of file SliceIndexer.h.
Constructor & Destructor Documentation
template<typename T , typename Id = std::string> stride::util::SliceIndexer< T, Id >::SliceIndexer (T & t) inline explicit
SliceIndexer holds a reference to the conatiner that it indexes.
Definition at line 47 of file SliceIndexer.h.
Member Function Documentation
template<typename T , typename Id = std::string> range_type& stride::util::SliceIndexer< T, Id >::Get (const Id & s) inline
Retrieve reference to a range by its Id.
Definition at line 50 of file SliceIndexer.h.
References stride::util::SliceIndexer< T, Id >::m_map, and stride::util::SliceIndexer< T, Id >::m_slices.
template<typename T , typename Id = std::string> const range_type& stride::util::SliceIndexer< T, Id >::Get (const Id & s) const inline
Retrieve const reference to a range by its Id.
Definition at line 53 of file SliceIndexer.h.
References stride::util::SliceIndexer< T, Id >::m_map, and stride::util::SliceIndexer< T, Id >::m_slices.
template<typename T , typename Id = std::string> const std::vector<range_type>& stride::util::SliceIndexer< T, Id >::Get () inline
Retrieve all the ranges,.
Definition at line 56 of file SliceIndexer.h.
References stride::util::SliceIndexer< T, Id >::m_slices.
template<typename T , typename Id = std::string> range_type& stride::util::SliceIndexer< T, Id >::Set (std::size_t ibegin, std::size_t iend, const Id & name) inline
Set a range. Warning: range is [ibegin, iend) i.e. half-open, iend not included!
Definition at line 59 of file SliceIndexer.h.
References stride::util::SliceIndexer< T, Id >::check(), stride::util::SliceIndexer< T, Id >::m_map, stride::util::SliceIndexer< T, Id >::m_slices, and stride::util::SliceIndexer< T, Id >::m_t.
template<typename T , typename Id = std::string> range_type& stride::util::SliceIndexer< T, Id >::Set (std::size_t ibegin, const Id & name) inline
Set a range, where the end is the end of the container.
Definition at line 68 of file SliceIndexer.h.
References stride::util::SliceIndexer< T, Id >::check(), stride::util::SliceIndexer< T, Id >::m_map, stride::util::SliceIndexer< T, Id >::m_slices, and stride::util::SliceIndexer< T, Id >::m_t.
template<typename T , typename Id = std::string> void stride::util::SliceIndexer< T, Id >::check (const Id & name) inline private
Check Id map for duplicate; throw iff duplicate.
Definition at line 78 of file SliceIndexer.h.
References stride::util::SliceIndexer< T, Id >::m_map.
Referenced by stride::util::SliceIndexer< T, Id >::Set().
Member Data Documentation
template<typename T , typename Id = std::string> std::map<Id, std::size_t> stride::util::SliceIndexer< T, Id >::m_map private
Maps Id values to subscripts.
Definition at line 86 of file SliceIndexer.h.
Referenced by stride::util::SliceIndexer< T, Id >::check(), stride::util::SliceIndexer< T, Id >::Get(), and stride::util::SliceIndexer< T, Id >::Set().
template<typename T , typename Id = std::string> std::vector<range_type> stride::util::SliceIndexer< T, Id >::m_slices private
Contains the slices.
Definition at line 87 of file SliceIndexer.h.
Referenced by stride::util::SliceIndexer< T, Id >::Get(), and stride::util::SliceIndexer< T, Id >::Set().
template<typename T , typename Id = std::string> T& stride::util::SliceIndexer< T, Id >::m_t private
Refernec to container that gets sliced into ranges.
Definition at line 88 of file SliceIndexer.h.
Referenced by stride::util::SliceIndexer< T, Id >::Set().
The documentation for this class was generated from the following file:
SliceIndexer.h