Stride Reference Manual: gengeopop::ThreadException Class Reference
gengeopop::ThreadException Class Reference
Create a wrapper for capturing the exceptions thrown in a multi-threaded environment This caught exception can then later be re-thrown in the main thread.
#include <ThreadException.h>
Classes
struct RunType
The used for executing a function with a return type.
struct RunType< void >
Public Types
template<typename T >
using RunType_t = typename RunType< T >::type
Public Member Functions
ThreadException ()
Create the ThreadException.
~ThreadException ()=default
Destructor.
void Rethrow ()
Re-throw the exception if one was caught.
void CaptureException ()
Capture the current exception and save it.
template<typename Function , typename... Parameters>
auto Run (Function f, Parameters...params)
Run the given function and capture any exception that may be thrown.
bool HasError () const
Returns if an exception was caught.
Private Attributes
std::exception_ptr m_ptr
The caught exception (if none was caught, contains a nullptr)
std::mutex m_lock
A lock used to prevent two exceptions being caught at the same time.
Detailed Description
Create a wrapper for capturing the exceptions thrown in a multi-threaded environment This caught exception can then later be re-thrown in the main thread.
Based on https://stackoverflow.com/a/13978507/1393103
Definition at line 28 of file ThreadException.h.
Member Typedef Documentation
template<typename T > using gengeopop::ThreadException::RunType_t = typename RunType<T>::type
Definition at line 60 of file ThreadException.h.
Constructor & Destructor Documentation
gengeopop::ThreadException::ThreadException () inline
Create the ThreadException.
Definition at line 32 of file ThreadException.h.
References ~ThreadException().
gengeopop::ThreadException::~ThreadException () default
Destructor.
Referenced by ThreadException().
Member Function Documentation
void gengeopop::ThreadException::Rethrow () inline
Re-throw the exception if one was caught.
Definition at line 38 of file ThreadException.h.
References m_ptr.
void gengeopop::ThreadException::CaptureException () inline
Capture the current exception and save it.
Definition at line 46 of file ThreadException.h.
References m_lock, and m_ptr.
Referenced by Run().
template<typename Function , typename... Parameters> auto gengeopop::ThreadException::Run (Function f, Parameters... params) inline
Run the given function and capture any exception that may be thrown.
Definition at line 64 of file ThreadException.h.
References CaptureException().
bool gengeopop::ThreadException::HasError () const inline
Returns if an exception was caught.
Definition at line 75 of file ThreadException.h.
References m_ptr.
Member Data Documentation
std::exception_ptr gengeopop::ThreadException::m_ptr private
The caught exception (if none was caught, contains a nullptr)
Definition at line 78 of file ThreadException.h.
Referenced by CaptureException(), HasError(), and Rethrow().
std::mutex gengeopop::ThreadException::m_lock private
A lock used to prevent two exceptions being caught at the same time.
Definition at line 79 of file ThreadException.h.
Referenced by CaptureException().
The documentation for this class was generated from the following file:
ThreadException.h