Stride Reference Manual: stride::Health Class Reference
stride::Health Class Reference
Holds a person's health data.
#include <Health.h>
Public Member Functions
Health (unsigned short int start_infectiousness=0U, unsigned int short start_symptomatic=0U, unsigned short int time_infectious=0U, unsigned short int time_symptomatic=0U)
unsigned short int GetEndInfectiousness () const
unsigned short int GetEndSymptomatic () const
unsigned short int GetStartInfectiousness () const
unsigned short int GetStartSymptomatic () const
bool IsImmune () const
bool IsInfected () const
bool IsInfectious () const
bool IsRecovered () const
bool IsSusceptible () const
Is this person susceptible?
bool IsSymptomatic () const
Is this person symptomatic?
void SetImmune ()
Set health state to immune.
void SetSusceptible ()
Set health state to susceptible.
void StartInfection ()
Start the infection.
void StopInfection ()
Stop the infection.
void Update ()
Update progress of the disease.
Private Member Functions
unsigned short int GetDiseaseCounter () const
Get the disease counter.
void IncrementDiseaseCounter ()
Increment disease counter.
void ResetDiseaseCounter ()
Reset the disease counter.
Private Attributes
unsigned short int m_disease_counter
The disease counter.
HealthStatus m_status
The current status of the person w.r.t. the disease.
unsigned short int m_start_infectiousness
Days after infection to become infectious.
unsigned short int m_start_symptomatic
Days after infection to become symptomatic.
unsigned short int m_end_infectiousness
Days after infection to end infectious state.
unsigned short int m_end_symptomatic
Days after infection to end symptomatic state.
Detailed Description
Holds a person's health data.
Definition at line 37 of file Health.h.
Constructor & Destructor Documentation
stride::Health::Health (unsigned short int start_infectiousness = 0U, unsigned int short start_symptomatic = 0U, unsigned short int time_infectious = 0U, unsigned short int time_symptomatic = 0U) explicit
Definition at line 27 of file Health.cpp.
References stride::Susceptible.
Member Function Documentation
unsigned short int stride::Health::GetEndInfectiousness () const inline
Definition at line 45 of file Health.h.
unsigned short int stride::Health::GetEndSymptomatic () const inline
Definition at line 48 of file Health.h.
unsigned short int stride::Health::GetStartInfectiousness () const inline
Definition at line 51 of file Health.h.
unsigned short int stride::Health::GetStartSymptomatic () const inline
Definition at line 54 of file Health.h.
bool stride::Health::IsImmune () const inline
Definition at line 57 of file Health.h.
References stride::Immune.
Referenced by stride::Immunizer::Random(), and stride::SurveySeeder::Seed().
bool stride::Health::IsInfected () const inline
Definition at line 60 of file Health.h.
References stride::Exposed, stride::Infectious, stride::InfectiousAndSymptomatic, and stride::Symptomatic.
Referenced by stride::SurveySeeder::Seed().
bool stride::Health::IsInfectious () const inline
Definition at line 67 of file Health.h.
References stride::Infectious, and stride::InfectiousAndSymptomatic.
Referenced by stride::SurveySeeder::Seed().
bool stride::Health::IsRecovered () const inline
Definition at line 73 of file Health.h.
References stride::Recovered.
Referenced by stride::SurveySeeder::Seed().
bool stride::Health::IsSusceptible () const inline
Is this person susceptible?
Definition at line 76 of file Health.h.
References stride::Susceptible.
Referenced by stride::DiseaseSeeder::Seed(), and stride::SurveySeeder::Seed().
bool stride::Health::IsSymptomatic () const inline
Is this person symptomatic?
Definition at line 79 of file Health.h.
References stride::InfectiousAndSymptomatic, and stride::Symptomatic.
void stride::Health::SetImmune ()
Set health state to immune.
Definition at line 35 of file Health.cpp.
References stride::Immune, and m_status.
void stride::Health::SetSusceptible ()
Set health state to susceptible.
Definition at line 37 of file Health.cpp.
References m_status, and stride::Susceptible.
Referenced by stride::Immunizer::Random().
void stride::Health::StartInfection ()
Start the infection.
Definition at line 39 of file Health.cpp.
References stride::Exposed, m_status, ResetDiseaseCounter(), and stride::Susceptible.
Referenced by stride::Infector< LL, TIC, NoLocalInformation, true >::Exec(), and stride::DiseaseSeeder::Seed().
void stride::Health::StopInfection ()
Stop the infection.
Definition at line 47 of file Health.cpp.
References stride::Exposed, stride::Infectious, stride::InfectiousAndSymptomatic, m_status, stride::Recovered, and stride::Symptomatic.
Referenced by Update().
void stride::Health::Update ()
Update progress of the disease.
Definition at line 55 of file Health.cpp.
References stride::Exposed, GetDiseaseCounter(), IncrementDiseaseCounter(), stride::Infectious, stride::InfectiousAndSymptomatic, m_end_infectiousness, m_end_symptomatic, m_start_infectiousness, m_start_symptomatic, m_status, StopInfection(), and stride::Symptomatic.
unsigned short int stride::Health::GetDiseaseCounter () const inline private
Get the disease counter.
Definition at line 101 of file Health.h.
Referenced by Update().
void stride::Health::IncrementDiseaseCounter () inline private
Increment disease counter.
Definition at line 104 of file Health.h.
Referenced by Update().
void stride::Health::ResetDiseaseCounter () inline private
Reset the disease counter.
Definition at line 107 of file Health.h.
Referenced by StartInfection().
Member Data Documentation
unsigned short int stride::Health::m_disease_counter private
The disease counter.
Definition at line 110 of file Health.h.
HealthStatus stride::Health::m_status private
The current status of the person w.r.t. the disease.
Definition at line 111 of file Health.h.
Referenced by SetImmune(), SetSusceptible(), StartInfection(), StopInfection(), and Update().
unsigned short int stride::Health::m_start_infectiousness private
Days after infection to become infectious.
Definition at line 113 of file Health.h.
Referenced by Update().
unsigned short int stride::Health::m_start_symptomatic private
Days after infection to become symptomatic.
Definition at line 114 of file Health.h.
Referenced by Update().
unsigned short int stride::Health::m_end_infectiousness private
Days after infection to end infectious state.
Definition at line 115 of file Health.h.
Referenced by Update().
unsigned short int stride::Health::m_end_symptomatic private
Days after infection to end symptomatic state.
Definition at line 116 of file Health.h.
Referenced by Update().
The documentation for this class was generated from the following files:
Health.h
Health.cpp