Stride Reference Manual: geopop::WorkplacePopulator Class Reference
geopop::WorkplacePopulator Class Reference
Populate the workplaces.
#include <WorkplacePopulator.h>
Public Member Functions
WorkplacePopulator (stride::util::RnMan &rnMan, std::shared_ptr< spdlog::logger > logger=nullptr)
Constructor.
void Apply (GeoGrid &geoGrid, const GeoGridConfig &geoGridConfig) override
Populates the workplaces in geogrid with persons.
Public Member Functions inherited from geopop::Populator
Populator (stride::util::RnMan &rnMan, std::shared_ptr< spdlog::logger > logger=nullptr)
Construct with a RnMan and a logger.
virtual ~Populator ()=default
Virtual destructor for inheritance.
Private Member Functions
void AssignActive (stride::Person *person)
Assign a workplace to an active person.
void CommutingLocations (const std::shared_ptr< Location > &loc, double fractionCommuteStudents)
Calculates the workplaces to which persons at this Location may commute to.
double FractionCommutingStudents ()
Calculates the fraction of student population that commutes.
void NearbyWorkspacePools (GeoGrid &geoGrid, std::shared_ptr< Location > loc)
Calculates the workplaces which are nearby Location loc.
void WorkplacePoolsAtLocation (GeoGrid &geoGrid)
Determines workplace pools at each Wocation.
Private Attributes
GeoGridConfig m_geogrid_config
The GeoGridConfig used during populating.
std::unordered_map< Location *, std::pair< std::vector< stride::ContactPool * >, std::function< int()> > > m_wp_at_location
For each location store workplaces and a distribution fot random selection.
std::vector< stride::ContactPool * > m_nearby_wp
Workplaces near current location.
std::function< int()> m_gen_non_commute
Genrator to select nerby workplace.
std::vector< Location * > m_commuting_locations
Workplaces one may commute to from current loaction.
std::function< int()> m_gen_commute
Generator to select commuting workplace.
Additional Inherited Members
Protected Member Functions inherited from geopop::Populator
std::vector< stride::ContactPool * > GetNearbyPools (stride::ContactType::Id id, const GeoGrid &geoGrid, const Location &start, double startRadius=10.0) const
Find contactpools in startRadius (in km) around start and, if none are found, double the radius and search again until the radius gets infinite.
bool MakeChoice (double fraction)
Binary selection corresponding to fraction% true en (1-fraction)% false.
Protected Attributes inherited from geopop::Populator
stride::util::RnMan & m_rn_man
RnManager used by populators.
std::shared_ptr< spdlog::logger > m_logger
Logger used by populators.
Detailed Description
Populate the workplaces.
Definition at line 30 of file WorkplacePopulator.h.
Constructor & Destructor Documentation
geopop::WorkplacePopulator::WorkplacePopulator (stride::util::RnMan & rnMan, std::shared_ptr< spdlog::logger > logger = nullptr) explicit
Constructor.
Definition at line 34 of file WorkplacePopulator.cpp.
Member Function Documentation
void geopop::WorkplacePopulator::Apply (GeoGrid & geoGrid, const GeoGridConfig & geoGridConfig) override virtual
Populates the workplaces in geogrid with persons.
Implements geopop::Populator.
Definition at line 40 of file WorkplacePopulator.cpp.
References AssignActive(), CommutingLocations(), FractionCommutingStudents(), geopop::GeoGridConfig::input, m_commuting_locations, m_gen_commute, m_gen_non_commute, m_geogrid_config, geopop::Populator::m_logger, m_nearby_wp, m_wp_at_location, geopop::Populator::MakeChoice(), NearbyWorkspacePools(), geopop::GeoGridConfig::participation_college, geopop::GeoGridConfig::particpation_workplace, and WorkplacePoolsAtLocation().
void geopop::WorkplacePopulator::AssignActive (stride::Person * person) private
Assign a workplace to an active person.
Definition at line 86 of file WorkplacePopulator.cpp.
References geopop::GeoGridConfig::fraction_workplace_commuters, geopop::GeoGridConfig::input, m_commuting_locations, m_gen_commute, m_gen_non_commute, m_geogrid_config, m_nearby_wp, m_wp_at_location, geopop::Populator::MakeChoice(), and stride::Person::SetPoolId().
Referenced by Apply().
void geopop::WorkplacePopulator::CommutingLocations (const std::shared_ptr< Location > & loc, double fractionCommuteStudents) private
Calculates the workplaces to which persons at this Location may commute to.
Definition at line 103 of file WorkplacePopulator.cpp.
References AssertThrow, stride::util::RnMan::GetDiscreteGenerator(), m_commuting_locations, m_gen_commute, geopop::Populator::m_logger, and geopop::Populator::m_rn_man.
Referenced by Apply().
double geopop::WorkplacePopulator::FractionCommutingStudents () private
Calculates the fraction of student population that commutes.
Definition at line 126 of file WorkplacePopulator.cpp.
References geopop::GeoGridConfig::fraction_college_commuters, geopop::GeoGridConfig::fraction_workplace_commuters, geopop::GeoGridConfig::input, m_geogrid_config, geopop::GeoGridConfig::popcount_college, geopop::GeoGridConfig::popcount_workplace, and geopop::GeoGridConfig::popInfo.
Referenced by Apply().
void geopop::WorkplacePopulator::NearbyWorkspacePools (GeoGrid & geoGrid, std::shared_ptr< Location > loc) private
Calculates the workplaces which are nearby Location loc.
Definition at line 138 of file WorkplacePopulator.cpp.
References geopop::Populator::GetNearbyPools(), stride::util::RnMan::GetUniformIntGenerator(), m_gen_non_commute, m_nearby_wp, and geopop::Populator::m_rn_man.
Referenced by Apply().
void geopop::WorkplacePopulator::WorkplacePoolsAtLocation (GeoGrid & geoGrid) private
Determines workplace pools at each Wocation.
Definition at line 144 of file WorkplacePopulator.cpp.
References stride::util::RnMan::GetUniformIntGenerator(), geopop::Populator::m_rn_man, and m_wp_at_location.
Referenced by Apply().
Member Data Documentation
GeoGridConfig geopop::WorkplacePopulator::m_geogrid_config private
The GeoGridConfig used during populating.
Definition at line 56 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and FractionCommutingStudents().
std::unordered_map<Location*, std::pair<std::vector<stride::ContactPool*>, std::function<int()> > > geopop::WorkplacePopulator::m_wp_at_location private
For each location store workplaces and a distribution fot random selection.
Definition at line 59 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and WorkplacePoolsAtLocation().
std::vector<stride::ContactPool*> geopop::WorkplacePopulator::m_nearby_wp private
Workplaces near current location.
Definition at line 61 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and NearbyWorkspacePools().
std::function<int()> geopop::WorkplacePopulator::m_gen_non_commute private
Genrator to select nerby workplace.
Definition at line 62 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and NearbyWorkspacePools().
std::vector<Location*> geopop::WorkplacePopulator::m_commuting_locations private
Workplaces one may commute to from current loaction.
Definition at line 64 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CommutingLocations().
std::function<int()> geopop::WorkplacePopulator::m_gen_commute private
Generator to select commuting workplace.
Definition at line 65 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CommutingLocations().
The documentation for this class was generated from the following files:
WorkplacePopulator.h
WorkplacePopulator.cpp