Stride Reference Manual: stride::viewers::CliViewer Class Reference
stride::viewers::CliViewer Class Reference
Viewer of Simulator for commandline interface.
#include <CliViewer.h>
Public Member Functions
CliViewer (std::shared_ptr< SimRunner > runner, std::shared_ptr< spdlog::logger > logger)
Instantiate cli viewer.
void Update (sim_event::Id id)
Let viewer perform update.
Private Attributes
std::shared_ptr< spdlog::logger > m_logger
std::shared_ptr< SimRunner > m_runner
Detailed Description
Viewer of Simulator for commandline interface.
Definition at line 33 of file CliViewer.h.
Constructor & Destructor Documentation
stride::viewers::CliViewer::CliViewer (std::shared_ptr< SimRunner > runner, std::shared_ptr< spdlog::logger > logger) inline
Instantiate cli viewer.
Definition at line 37 of file CliViewer.h.
References Update().
Member Function Documentation
void stride::viewers::CliViewer::Update (sim_event::Id id)
Let viewer perform update.
Definition at line 39 of file CliViewer.cpp.
Referenced by CliViewer(), and stride::ControlHelper::RegisterViewers().
Member Data Documentation
std::shared_ptr<spdlog::logger> stride::viewers::CliViewer::m_logger private
Definition at line 46 of file CliViewer.h.
std::shared_ptr<SimRunner> stride::viewers::CliViewer::m_runner private
Definition at line 47 of file CliViewer.h.
The documentation for this class was generated from the following files:
CliViewer.h
CliViewer.cpp