Stride Reference Manual: stride::Calendar Class Reference
stride::Calendar Class Reference
Class that keeps track of the 'state' of simulated world.
#include <Calendar.h>
Public Member Functions
Calendar (const boost::property_tree::ptree &configPt)
Constructor.
void AdvanceDay ()
Advance the simulated calendar by one day.
std::size_t GetDay () const
Current day of the month in the simulated calendar.
std::size_t GetDayOfTheWeek () const
Current day of the week (0 (Sunday), ..., 6 (Saturday)) in the simulated calendar.
std::size_t GetMonth () const
Current month in the simulated calendar.
unsigned short int GetSimulationDay () const
Current simulated day since the start of the simulation.
std::size_t GetYear () const
Current year in the simulated calendar.
bool IsHoliday () const
Check if it's a holiday.
bool IsSchoolHoliday () const
Check if it's a school holiday.
bool IsWeekend () const
Check if it's the weekend.
Private Member Functions
void InitializeHolidays (const boost::property_tree::ptree &configPt)
Private Attributes
date::year_month_day m_date
Current simulated date.
std::vector< date::year_month_day > m_holidays
Vector of general holidays.
std::vector< date::year_month_day > m_school_holidays
Vector of school holidays.
unsigned short int m_day
Current day since start of simulation.
Detailed Description
Class that keeps track of the 'state' of simulated world.
E.g. what day it is, holidays, quarantines, ...
Definition at line 42 of file Calendar.h.
Constructor & Destructor Documentation
stride::Calendar::Calendar (const boost::property_tree::ptree & configPt) explicit
Constructor.
Definition at line 106 of file Calendar.cpp.
References stride::ConvertFromString(), InitializeHolidays(), and m_date.
Member Function Documentation
void stride::Calendar::AdvanceDay ()
Advance the simulated calendar by one day.
Definition at line 116 of file Calendar.cpp.
References m_date, and m_day.
std::size_t stride::Calendar::GetDay () const
Current day of the month in the simulated calendar.
Definition at line 160 of file Calendar.cpp.
References m_date.
std::size_t stride::Calendar::GetDayOfTheWeek () const
Current day of the week (0 (Sunday), ..., 6 (Saturday)) in the simulated calendar.
Definition at line 162 of file Calendar.cpp.
References m_date.
Referenced by IsWeekend().
std::size_t stride::Calendar::GetMonth () const
Current month in the simulated calendar.
Definition at line 167 of file Calendar.cpp.
References m_date.
unsigned short int stride::Calendar::GetSimulationDay () const
Current simulated day since the start of the simulation.
Definition at line 169 of file Calendar.cpp.
References m_day.
std::size_t stride::Calendar::GetYear () const
Current year in the simulated calendar.
Definition at line 171 of file Calendar.cpp.
References m_date.
bool stride::Calendar::IsHoliday () const inline
Check if it's a holiday.
Definition at line 67 of file Calendar.h.
References m_date, and m_holidays.
bool stride::Calendar::IsSchoolHoliday () const inline
Check if it's a school holiday.
Definition at line 70 of file Calendar.h.
References m_date, and m_school_holidays.
bool stride::Calendar::IsWeekend () const inline
Check if it's the weekend.
Definition at line 77 of file Calendar.h.
References GetDayOfTheWeek(), InitializeHolidays(), m_date, m_holidays, and m_school_holidays.
void stride::Calendar::InitializeHolidays (const boost::property_tree::ptree & configPt) private
Append zero's due to a bug in stdc++ https://gcc.gnu.org/bugzilla/show_bug.cgi?id=45896
Append zero's due to a bug in stdc++ https://gcc.gnu.org/bugzilla/show_bug.cgi?id=45896
Definition at line 122 of file Calendar.cpp.
References stride::ConvertFromString(), stride::util::FileSys::GetDataDir(), m_holidays, and m_school_holidays.
Referenced by Calendar(), and IsWeekend().
Member Data Documentation
date::year_month_day stride::Calendar::m_date private
Current simulated date.
Definition at line 89 of file Calendar.h.
Referenced by AdvanceDay(), Calendar(), GetDay(), GetDayOfTheWeek(), GetMonth(), GetYear(), IsHoliday(), IsSchoolHoliday(), and IsWeekend().
std::vector<date::year_month_day> stride::Calendar::m_holidays private
Vector of general holidays.
Definition at line 90 of file Calendar.h.
Referenced by InitializeHolidays(), IsHoliday(), and IsWeekend().
std::vector<date::year_month_day> stride::Calendar::m_school_holidays private
Vector of school holidays.
Definition at line 91 of file Calendar.h.
Referenced by InitializeHolidays(), IsSchoolHoliday(), and IsWeekend().
unsigned short int stride::Calendar::m_day private
Current day since start of simulation.
Definition at line 93 of file Calendar.h.
Referenced by AdvanceDay(), and GetSimulationDay().
The documentation for this class was generated from the following files:
Calendar.h
Calendar.cpp