Stride Reference Manual: stride::ContactType::IdSubscriptArray< bool > Class Template Reference
stride::ContactType::IdSubscriptArray< bool > Class Template Reference
Specialisation of IdSubscriptArray foor booleans.
#include <IdSubscriptArray.h>
Public Member Functions
IdSubscriptArray (bool t=bool())
What we 'll use most often and where we can have a default and initialize all array elements to the same value.
IdSubscriptArray (std::initializer_list< bool > l)
When we want to use an initializer list the elements is the (possibly emty) initializer list are applied to the first elements in order; any remaininig elements are default initialized.
std::bitset< NumOfTypes()>::reference operator[] (ContactType::Id id)
Subscripting with pool typ id as argument.
bool operator[] (ContactType::Id id) const
Subscripting with pool typ id as argument.
bitset< NumOfTypes()>::reference at (ContactType::Id id)
Subscripting with pool typ id as argument.
bool at (ContactType::Id id) const
Subscripting with pool typ id as argument.
Detailed Description
template<>
class stride::ContactType::IdSubscriptArray< bool >
Specialisation of IdSubscriptArray foor booleans.
Definition at line 133 of file IdSubscriptArray.h.
Constructor & Destructor Documentation
stride::ContactType::IdSubscriptArray< bool >::IdSubscriptArray (bool t = bool()) inline explicit
What we 'll use most often and where we can have a default and initialize all array elements to the same value.
e.g. IdSubscriptArray<bool> m(true);
Definition at line 139 of file IdSubscriptArray.h.
stride::ContactType::IdSubscriptArray< bool >::IdSubscriptArray (std::initializer_list< bool > l) inline
When we want to use an initializer list the elements is the (possibly emty) initializer list are applied to the first elements in order; any remaininig elements are default initialized.
e.g. IdSubscriptArray<bool> mm {true, false, true};
Definition at line 151 of file IdSubscriptArray.h.
References stride::ContactType::IdList, and stride::ContactType::IdSubscriptArray< T >::operator[]().
Member Function Documentation
std::bitset<NumOfTypes()>::reference stride::ContactType::IdSubscriptArray< bool >::operator[] (ContactType::Id id) inline
Subscripting with pool typ id as argument.
Definition at line 165 of file IdSubscriptArray.h.
References stride::ContactType::ToSizeT().
bool stride::ContactType::IdSubscriptArray< bool >::operator[] (ContactType::Id id) const inline
Subscripting with pool typ id as argument.
Definition at line 171 of file IdSubscriptArray.h.
References stride::ContactType::ToSizeT().
bitset<NumOfTypes()>::reference stride::ContactType::IdSubscriptArray< bool >::at (ContactType::Id id) inline
Subscripting with pool typ id as argument.
Definition at line 177 of file IdSubscriptArray.h.
References stride::ContactType::NumOfTypes(), and stride::ContactType::ToSizeT().
bool stride::ContactType::IdSubscriptArray< bool >::at (ContactType::Id id) const inline
Subscripting with pool typ id as argument.
Definition at line 186 of file IdSubscriptArray.h.
References stride::ContactType::NumOfTypes(), and stride::ContactType::ToSizeT().
The documentation for this class was generated from the following file:
IdSubscriptArray.h