Stride Reference Manual: proto::GeoGrid_Location_ContactCenter_ContactPool Class Reference
proto::GeoGrid_Location_ContactCenter_ContactPool Class Reference final
#include <geogrid.pb.h>
Public Member Functions
GeoGrid_Location_ContactCenter_ContactPool ()
virtual ~GeoGrid_Location_ContactCenter_ContactPool ()
GeoGrid_Location_ContactCenter_ContactPool (const GeoGrid_Location_ContactCenter_ContactPool &from)
GeoGrid_Location_ContactCenter_ContactPool & operator= (const GeoGrid_Location_ContactCenter_ContactPool &from)
void Swap (GeoGrid_Location_ContactCenter_ContactPool *other)
GeoGrid_Location_ContactCenter_ContactPool * New () const final
GeoGrid_Location_ContactCenter_ContactPool * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const GeoGrid_Location_ContactCenter_ContactPool &from)
void MergeFrom (const GeoGrid_Location_ContactCenter_ContactPool &from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int people_size () const
void clear_people ()
::google::protobuf::int64 people (int index) const
void set_people (int index,::google::protobuf::int64 value)
void add_people (::google::protobuf::int64 value)
const ::google::protobuf::RepeatedField< ::google::protobuf::int64 > & people () const
::google::protobuf::RepeatedField< ::google::protobuf::int64 > * mutable_people ()
void clear_id ()
::google::protobuf::int64 id () const
void set_id (::google::protobuf::int64 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const GeoGrid_Location_ContactCenter_ContactPool & default_instance ()
static void InitAsDefaultInstance ()
static const GeoGrid_Location_ContactCenter_ContactPool * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kPeopleFieldNumber = 2
static const int kIdFieldNumber = 1
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const final
void InternalSwap (GeoGrid_Location_ContactCenter_ContactPool *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::RepeatedField< ::google::protobuf::int64 > people_
std::atomic< int > _people_cached_byte_size_
::google::protobuf::int64 id_
mutable::google::protobuf::internal::CachedSize _cached_size_
Friends
struct ::TableStruct_geogrid_2eproto
void swap (GeoGrid_Location_ContactCenter_ContactPool &a, GeoGrid_Location_ContactCenter_ContactPool &b)
Detailed Description
Definition at line 234 of file geogrid.pb.h.
Constructor & Destructor Documentation
proto::GeoGrid_Location_ContactCenter_ContactPool::GeoGrid_Location_ContactCenter_ContactPool ()
virtual proto::GeoGrid_Location_ContactCenter_ContactPool::~GeoGrid_Location_ContactCenter_ContactPool () virtual
proto::GeoGrid_Location_ContactCenter_ContactPool::GeoGrid_Location_ContactCenter_ContactPool (const GeoGrid_Location_ContactCenter_ContactPool & from)
Member Function Documentation
GeoGrid_Location_ContactCenter_ContactPool& proto::GeoGrid_Location_ContactCenter_ContactPool::operator= (const GeoGrid_Location_ContactCenter_ContactPool & from) inline
Definition at line 242 of file geogrid.pb.h.
References GetArenaNoVirtual().
static const ::google::protobuf::Descriptor* proto::GeoGrid_Location_ContactCenter_ContactPool::descriptor () inline static
Definition at line 261 of file geogrid.pb.h.
static const GeoGrid_Location_ContactCenter_ContactPool& proto::GeoGrid_Location_ContactCenter_ContactPool::default_instance () static
static void proto::GeoGrid_Location_ContactCenter_ContactPool::InitAsDefaultInstance () static
static const GeoGrid_Location_ContactCenter_ContactPool* proto::GeoGrid_Location_ContactCenter_ContactPool::internal_default_instance () inline static
Definition at line 267 of file geogrid.pb.h.
References proto::_GeoGrid_Location_ContactCenter_ContactPool_default_instance_.
void proto::GeoGrid_Location_ContactCenter_ContactPool::Swap (GeoGrid_Location_ContactCenter_ContactPool * other)
GeoGrid_Location_ContactCenter_ContactPool* proto::GeoGrid_Location_ContactCenter_ContactPool::New () const inline final
Definition at line 281 of file geogrid.pb.h.
GeoGrid_Location_ContactCenter_ContactPool* proto::GeoGrid_Location_ContactCenter_ContactPool::New (::google::protobuf::Arena * arena) const inline final
Definition at line 285 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter_ContactPool::CopyFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Location_ContactCenter_ContactPool::MergeFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Location_ContactCenter_ContactPool::CopyFrom (const GeoGrid_Location_ContactCenter_ContactPool & from)
void proto::GeoGrid_Location_ContactCenter_ContactPool::MergeFrom (const GeoGrid_Location_ContactCenter_ContactPool & from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void proto::GeoGrid_Location_ContactCenter_ContactPool::Clear () final
bool proto::GeoGrid_Location_ContactCenter_ContactPool::IsInitialized () const final
size_t proto::GeoGrid_Location_ContactCenter_ContactPool::ByteSizeLong () const final
bool proto::GeoGrid_Location_ContactCenter_ContactPool::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
void proto::GeoGrid_Location_ContactCenter_ContactPool::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
::google::protobuf::uint8* proto::GeoGrid_Location_ContactCenter_ContactPool::InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 * target) const final
int proto::GeoGrid_Location_ContactCenter_ContactPool::GetCachedSize () const inline final
Definition at line 307 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter_ContactPool::SharedCtor () private
void proto::GeoGrid_Location_ContactCenter_ContactPool::SharedDtor () private
void proto::GeoGrid_Location_ContactCenter_ContactPool::SetCachedSize (int size) const final private
void proto::GeoGrid_Location_ContactCenter_ContactPool::InternalSwap (GeoGrid_Location_ContactCenter_ContactPool * other) private
inline ::google::protobuf::Arena* proto::GeoGrid_Location_ContactCenter_ContactPool::GetArenaNoVirtual () const inline private
Definition at line 315 of file geogrid.pb.h.
Referenced by operator=().
void* proto::GeoGrid_Location_ContactCenter_ContactPool::MaybeArenaPtr () const inline private
Definition at line 318 of file geogrid.pb.h.
::google::protobuf::Metadata proto::GeoGrid_Location_ContactCenter_ContactPool::GetMetadata () const final
int proto::GeoGrid_Location_ContactCenter_ContactPool::people_size () const inline
Definition at line 1137 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseContactPool().
void proto::GeoGrid_Location_ContactCenter_ContactPool::clear_people () inline
Definition at line 1140 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location_ContactCenter_ContactPool::people (int index) const inline
Definition at line 1143 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseContactPool().
void proto::GeoGrid_Location_ContactCenter_ContactPool::set_people (int index, ::google::protobuf::int64 value) inline
Definition at line 1147 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter_ContactPool::add_people (::google::protobuf::int64 value) inline
Definition at line 1151 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WriteContactPool().
const ::google::protobuf::RepeatedField<::google::protobuf::int64 > & proto::GeoGrid_Location_ContactCenter_ContactPool::people () const inline
Definition at line 1156 of file geogrid.pb.h.
google::protobuf::RepeatedField<::google::protobuf::int64 > * proto::GeoGrid_Location_ContactCenter_ContactPool::mutable_people () inline
Definition at line 1161 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter_ContactPool::clear_id () inline
Definition at line 1123 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location_ContactCenter_ContactPool::id () const inline
Definition at line 1126 of file geogrid.pb.h.
void proto::GeoGrid_Location_ContactCenter_ContactPool::set_id (::google::protobuf::int64 value) inline
Definition at line 1130 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WriteContactPool().
Friends And Related Function Documentation
friend struct ::TableStruct_geogrid_2eproto friend
Definition at line 356 of file geogrid.pb.h.
void swap (GeoGrid_Location_ContactCenter_ContactPool & a, GeoGrid_Location_ContactCenter_ContactPool & b) friend
Definition at line 275 of file geogrid.pb.h.
Member Data Documentation
constexpr int proto::GeoGrid_Location_ContactCenter_ContactPool::kIndexInFileMessages static
Initial value:
=
    1
Definition at line 271 of file geogrid.pb.h.
const int proto::GeoGrid_Location_ContactCenter_ContactPool::kPeopleFieldNumber = 2 static
Definition at line 332 of file geogrid.pb.h.
const int proto::GeoGrid_Location_ContactCenter_ContactPool::kIdFieldNumber = 1 static
Definition at line 343 of file geogrid.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::GeoGrid_Location_ContactCenter_ContactPool::_internal_metadata_ private
Definition at line 349 of file geogrid.pb.h.
::google::protobuf::RepeatedField< ::google::protobuf::int64 > proto::GeoGrid_Location_ContactCenter_ContactPool::people_ private
Definition at line 352 of file geogrid.pb.h.
std::atomic<int> proto::GeoGrid_Location_ContactCenter_ContactPool::_people_cached_byte_size_ mutable private
Definition at line 353 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Location_ContactCenter_ContactPool::id_ private
Definition at line 354 of file geogrid.pb.h.
mutable ::google::protobuf::internal::CachedSize proto::GeoGrid_Location_ContactCenter_ContactPool::_cached_size_ private
Definition at line 355 of file geogrid.pb.h.
The documentation for this class was generated from the following file:
geogrid.pb.h