Stride Reference Manual: proto::GeoGrid_Location_Commute Class Reference
proto::GeoGrid_Location_Commute Class Reference final
#include <geogrid.pb.h>
Public Member Functions
GeoGrid_Location_Commute ()
virtual ~GeoGrid_Location_Commute ()
GeoGrid_Location_Commute (const GeoGrid_Location_Commute &from)
GeoGrid_Location_Commute & operator= (const GeoGrid_Location_Commute &from)
void Swap (GeoGrid_Location_Commute *other)
GeoGrid_Location_Commute * New () const final
GeoGrid_Location_Commute * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const GeoGrid_Location_Commute &from)
void MergeFrom (const GeoGrid_Location_Commute &from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_to ()
::google::protobuf::int64 to () const
void set_to (::google::protobuf::int64 value)
void clear_proportion ()
double proportion () const
void set_proportion (double value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const GeoGrid_Location_Commute & default_instance ()
static void InitAsDefaultInstance ()
static const GeoGrid_Location_Commute * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kToFieldNumber = 1
static const int kProportionFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const final
void InternalSwap (GeoGrid_Location_Commute *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::int64 to_
double proportion_
mutable::google::protobuf::internal::CachedSize _cached_size_
Friends
struct ::TableStruct_geogrid_2eproto
void swap (GeoGrid_Location_Commute &a, GeoGrid_Location_Commute &b)
Detailed Description
Definition at line 528 of file geogrid.pb.h.
Constructor & Destructor Documentation
proto::GeoGrid_Location_Commute::GeoGrid_Location_Commute ()
virtual proto::GeoGrid_Location_Commute::~GeoGrid_Location_Commute () virtual
proto::GeoGrid_Location_Commute::GeoGrid_Location_Commute (const GeoGrid_Location_Commute & from)
Member Function Documentation
GeoGrid_Location_Commute& proto::GeoGrid_Location_Commute::operator= (const GeoGrid_Location_Commute & from) inline
Definition at line 536 of file geogrid.pb.h.
References GetArenaNoVirtual().
static const ::google::protobuf::Descriptor* proto::GeoGrid_Location_Commute::descriptor () inline static
Definition at line 555 of file geogrid.pb.h.
static const GeoGrid_Location_Commute& proto::GeoGrid_Location_Commute::default_instance () static
static void proto::GeoGrid_Location_Commute::InitAsDefaultInstance () static
static const GeoGrid_Location_Commute* proto::GeoGrid_Location_Commute::internal_default_instance () inline static
Definition at line 561 of file geogrid.pb.h.
References proto::_GeoGrid_Location_Commute_default_instance_.
void proto::GeoGrid_Location_Commute::Swap (GeoGrid_Location_Commute * other)
GeoGrid_Location_Commute* proto::GeoGrid_Location_Commute::New () const inline final
Definition at line 575 of file geogrid.pb.h.
GeoGrid_Location_Commute* proto::GeoGrid_Location_Commute::New (::google::protobuf::Arena * arena) const inline final
Definition at line 579 of file geogrid.pb.h.
void proto::GeoGrid_Location_Commute::CopyFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Location_Commute::MergeFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Location_Commute::CopyFrom (const GeoGrid_Location_Commute & from)
void proto::GeoGrid_Location_Commute::MergeFrom (const GeoGrid_Location_Commute & from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void proto::GeoGrid_Location_Commute::Clear () final
bool proto::GeoGrid_Location_Commute::IsInitialized () const final
size_t proto::GeoGrid_Location_Commute::ByteSizeLong () const final
bool proto::GeoGrid_Location_Commute::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
void proto::GeoGrid_Location_Commute::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
::google::protobuf::uint8* proto::GeoGrid_Location_Commute::InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 * target) const final
int proto::GeoGrid_Location_Commute::GetCachedSize () const inline final
Definition at line 601 of file geogrid.pb.h.
void proto::GeoGrid_Location_Commute::SharedCtor () private
void proto::GeoGrid_Location_Commute::SharedDtor () private
void proto::GeoGrid_Location_Commute::SetCachedSize (int size) const final private
void proto::GeoGrid_Location_Commute::InternalSwap (GeoGrid_Location_Commute * other) private
inline ::google::protobuf::Arena* proto::GeoGrid_Location_Commute::GetArenaNoVirtual () const inline private
Definition at line 609 of file geogrid.pb.h.
Referenced by operator=().
void* proto::GeoGrid_Location_Commute::MaybeArenaPtr () const inline private
Definition at line 612 of file geogrid.pb.h.
::google::protobuf::Metadata proto::GeoGrid_Location_Commute::GetMetadata () const final
void proto::GeoGrid_Location_Commute::clear_to () inline
Definition at line 1233 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location_Commute::to () const inline
Definition at line 1236 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location_Commute::set_to (::google::protobuf::int64 value) inline
Definition at line 1240 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WriteLocation().
void proto::GeoGrid_Location_Commute::clear_proportion () inline
Definition at line 1247 of file geogrid.pb.h.
double proto::GeoGrid_Location_Commute::proportion () const inline
Definition at line 1250 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location_Commute::set_proportion (double value) inline
Definition at line 1254 of file geogrid.pb.h.
Friends And Related Function Documentation
friend struct ::TableStruct_geogrid_2eproto friend
Definition at line 643 of file geogrid.pb.h.
void swap (GeoGrid_Location_Commute & a, GeoGrid_Location_Commute & b) friend
Definition at line 569 of file geogrid.pb.h.
Member Data Documentation
constexpr int proto::GeoGrid_Location_Commute::kIndexInFileMessages static
Initial value:
=
    3
Definition at line 565 of file geogrid.pb.h.
const int proto::GeoGrid_Location_Commute::kToFieldNumber = 1 static
Definition at line 625 of file geogrid.pb.h.
const int proto::GeoGrid_Location_Commute::kProportionFieldNumber = 2 static
Definition at line 631 of file geogrid.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::GeoGrid_Location_Commute::_internal_metadata_ private
Definition at line 637 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Location_Commute::to_ private
Definition at line 640 of file geogrid.pb.h.
double proto::GeoGrid_Location_Commute::proportion_ private
Definition at line 641 of file geogrid.pb.h.
mutable ::google::protobuf::internal::CachedSize proto::GeoGrid_Location_Commute::_cached_size_ private
Definition at line 642 of file geogrid.pb.h.
The documentation for this class was generated from the following file:
geogrid.pb.h