Stride Reference Manual: stride Namespace Reference
stride Namespace Reference
Namespace for the simulator and related classes.
Namespaces
AgeBrackets
AgeBrackets that determine participation in type of ContactPool.
ContactLogMode
Enum specifiying the level of logging required:
ContactType
Namespace to manage types of ContactPool.
output
Utilities for the output files.
RNEngineType
Namespace to manage types of random engines.
sim_event
Namespace to manage events signalled by the SimRunner.
util
Utilities for the project.
viewers
Namespace for MVC-viewers that may be registered with SimRunner.
Classes
class AbstractPopBuilder
Base Class for PopBuilders.
class AgeContactProfile
Contact rates as a function of age.
class Calendar
Class that keeps track of the 'state' of simulated world.
class ContactHandler
Processes the contacts between persons and determines whether transmission occurs.
class ContactPool
Represents a group of Persons that potentially have contacts.
class ControlHelper
Controls a simulation run initiated with the command line interface (cli).
class DaysOffAll
No days off work or school.
class DaysOffInterface
Interface definition.
class DaysOffNone
No days off work or school.
class DaysOffSchool
Schools closed.
class DaysOffStandard
Standard situation for days off from work and school.
class DefaultPopBuilder
Initializes Population objects.
class DiseaseSeeder
Seeds population w.r.t immunity (natural immunity, vaccination, ...) and infection.
class GenPopController
Controls a geo-population generation run initiated with the command line interface (cli).
class GeoPopBuilder
Builds poulation of a geographic grid.
class Health
Holds a person's health data.
class HealthSeeder
Seeds the population with Health data.
class Immunizer
Deals with immunization strategies.
class ImportPopBuilder
Initializes Population objects.
class Infector
Actual contacts and transmission in contactpool (primary template).
class Infector< LL, TIC, true >
Time-optimized version (For NoLocalInformation && (None || Transmission logging)).
class InfectorMap
Simulator can time step and reveal some of the key data.
class Person
Store and handle person data.
class Population
Key Data structure: container for (a) all individuals in the population (b) the ContactPoolSys wchich is used to loop over ContactPools of each type (c) (if present) geographical grid of Locations with ContactCenters at that location.
class PublicHealthAgency
class Sim
Simulator can time step and reveal some of the key data.
class SimBuilder
Builds a simulator based a configuration property tree.
class SimController
Controls a simulation run initiated with the command line interface (cli).
class SimRunner
The simulation runner drive simulator throufgh time steps.
class StanController
Runs a simulation multiple times, with different random engine seeds.
class SurveySeeder
Seeds the population with survey participants.
class TransmissionProfile
Transmission rates from disease data.
Typedefs
using AgeContactProfiles = ContactType::IdSubscriptArray< AgeContactProfile >
using ContactPoolSys = ContactType::IdSubscriptArray< util::SegmentedVector< ContactPool >>
ContactPoolSys contains for each of the type of pools (household, school, ...) a vector of with all of the contcatpools of the type.
typedef void(InfectorExec) (ContactPool &pool, const AgeContactProfile &profile, const TransmissionProfile &trans_profile, ContactHandler &c_handler, unsigned short int sim_day, std::shared_ptr< spdlog::logger > c_logger)
For use in the InfectorMap and Sim; executes infector.
Enumerations
enum HealthStatus : unsigned short int {
HealthStatus::Susceptible = 0U, HealthStatus::Exposed = 1U, HealthStatus::Infectious = 2U, HealthStatus::Symptomatic = 3U,
HealthStatus::InfectiousAndSymptomatic = 4U, HealthStatus::Recovered = 5U, HealthStatus::Immune = 6U
}
Enumerate the various health states with respect to the infection.
Functions
date::year_month_day ConvertFromString (const string &day)
constexpr unsigned int MaximumAge ()
Maximum age for Persons.
constexpr unsigned int MinAdultAge ()
Maximum age for Person's.
unsigned int EffectiveAge (unsigned int age)
Effective age (topping of at maximum).
Detailed Description
Namespace for the simulator and related classes.
Typedef Documentation
using stride::AgeContactProfiles = typedef ContactType::IdSubscriptArray<AgeContactProfile>
Definition at line 29 of file AgeContactProfiles.h.
using stride::ContactPoolSys = typedef ContactType::IdSubscriptArray<util::SegmentedVector<ContactPool>>
ContactPoolSys contains for each of the type of pools (household, school, ...) a vector of with all of the contcatpools of the type.
The ContactPoolSys container is an std::array extended to be subscriptable with the enum class of the pool types.
Definition at line 34 of file ContactPoolSys.h.
typedef void(stride::InfectorExec) (ContactPool &pool, const AgeContactProfile &profile, const TransmissionProfile &trans_profile, ContactHandler &c_handler, unsigned short int sim_day, std::shared_ptr< spdlog::logger > c_logger)
For use in the InfectorMap and Sim; executes infector.
Definition at line 33 of file InfectorExec.h.
Enumeration Type Documentation
enum stride::HealthStatus : unsigned short int strong
Enumerate the various health states with respect to the infection.
Enumerator
Susceptible
Exposed
Infectious
Symptomatic
InfectiousAndSymptomatic
Recovered
Immune
Definition at line 26 of file Health.h.
Function Documentation
date::year_month_day stride::ConvertFromString (const string & day)
Definition at line 97 of file Calendar.cpp.
Referenced by stride::Calendar::Calendar(), and stride::Calendar::InitializeHolidays().
constexpr unsigned int stride::MaximumAge () inline
Maximum age for Persons.
Definition at line 26 of file Age.h.
Referenced by EffectiveAge().
constexpr unsigned int stride::MinAdultAge () inline
Maximum age for Person's.
Definition at line 29 of file Age.h.
Referenced by stride::Person::Update().
unsigned int stride::EffectiveAge (unsigned int age) inline
Effective age (topping of at maximum).
Definition at line 32 of file Age.h.
References MaximumAge().