Stride Reference Manual: gengeopop::GeoGrid Class Reference
gengeopop::GeoGrid Class Reference
A Geographic grid of simulation region contains Locations that in turn contains ContactCenters.
#include <GeoGrid.h>
Public Types
using iterator = std::vector< std::shared_ptr< Location >>::iterator
using const_iterator = std::vector< std::shared_ptr< Location >>::const_iterator
Public Member Functions
GeoGrid (stride::Population *population)
Construct with information about population.
GeoGrid (const GeoGrid &)=delete
No copy constructor.
GeoGrid operator= (const GeoGrid &)=delete
No copy assignment.
void AddLocation (std::shared_ptr< Location > location)
Adds a location to this GeoGrid.
stride::ContactPool * CreateContactPool (stride::ContactPoolType::Id type)
Create ContactPool of type in the Population associated withis GeoGrid.
template<typename... Args>
stride::Person * CreatePerson (Args &&...args)
Create Person in the Population associated withis Grid.
void Finalize ()
Disables the addLocation method and builds the kdtree.
std::shared_ptr< Location > Get (size_t index) const
Gets a Location by index, doesn't performs a range check.
std::shared_ptr< Location > GetById (unsigned int id) const
Gets a Location by Id and check if the Id exists.
const GeoGridKdTree & KdTree ()
Provide access to the GeoGridKdTree spatial lookup structure.
stride::Population * GetPopulation () const
Get the Population associated with this GeoGrid.
std::vector< std::shared_ptr< Location > > LocationsInRadius (std::shared_ptr< Location > start, double radius) const
Search for locations in radius (in km) around start.
std::set< std::shared_ptr< Location > > LocationsInBox (double long1, double lat1, double long2, double lat2) const
Gets the locations in a rectangle determined by the two coordinates (long1, lat1) and (long2, lat2).
std::set< std::shared_ptr< Location > > LocationsInBox (const std::shared_ptr< Location > &loc1, const std::shared_ptr< Location > &loc2) const
Gets the location in a rectangle defined by the two Locations.
std::vector< std::shared_ptr< Location > > TopK (size_t k) const
Gets the K biggest (in population count) locations of this GeoGrid.
void Remove (const std::shared_ptr< Location > &location)
Remove element of GeoGrid.
template<typename Policy , typename F >
GeoAggregator< Policy, F > BuildAggregator (F functor, typename Policy::Args &&args) const
Build a GeoAggregator with a predefined functor and given args for the Policy.
template<typename Policy >
GeoAggregator< Policy > BuildAggregator (typename Policy::Args &&args) const
Build a GeoAggregator that gets its functor when calling, with given args for the Policy.
iterator begin ()
Iterator to first Location.
iterator end ()
Iterator to the end of the Location storage.
const_iterator cbegin () const
Const Iterator to first Location.
const_iterator cend () const
Const iterator to the end of the Location storage.
std::shared_ptr< Location > & operator[] (size_t index)
Gets a Location by index, doesn't performs a range check.
const std::shared_ptr< Location > & operator[] (size_t index) const
Gets a Location by index, doesn't performs a range check.
size_t size () const
Gets current size of Location storage.
Private Member Functions
void CheckFinalized (const std::string &functionName) const
< Checks whether the GeoGrid is finalized i.e. certain operations can(not) be used.
Private Attributes
std::vector< std::shared_ptr< Location > > m_locations
< Container for Locations in GeoGrid.
std::unordered_map< unsigned int, std::shared_ptr< Location > > m_locationsToIdIndex
Stores pointer to Popluation, but does not take ownership.
stride::Population * m_population
Is the GeoGrid finalized (ready for use) yet?
bool m_finalized
Internal KdTree for quick spatial lookup.
GeoGridKdTree m_tree
Detailed Description
A Geographic grid of simulation region contains Locations that in turn contains ContactCenters.
Definition at line 36 of file GeoGrid.h.
Member Typedef Documentation
using gengeopop::GeoGrid::iterator = std::vector<std::shared_ptr<Location>>::iterator
Definition at line 111 of file GeoGrid.h.
using gengeopop::GeoGrid::const_iterator = std::vector<std::shared_ptr<Location>>::const_iterator
Definition at line 112 of file GeoGrid.h.
Constructor & Destructor Documentation
gengeopop::GeoGrid::GeoGrid (stride::Population * population) explicit
Construct with information about population.
Definition at line 30 of file GeoGrid.cpp.
gengeopop::GeoGrid::GeoGrid (const GeoGrid &) delete
No copy constructor.
Member Function Documentation
GeoGrid gengeopop::GeoGrid::operator= (const GeoGrid &) delete
No copy assignment.
void gengeopop::GeoGrid::AddLocation (std::shared_ptr< Location > location)
Adds a location to this GeoGrid.
Definition at line 35 of file GeoGrid.cpp.
References m_finalized, m_locations, and m_locationsToIdIndex.
stride::ContactPool * gengeopop::GeoGrid::CreateContactPool (stride::ContactPoolType::Id type)
Create ContactPool of type in the Population associated withis GeoGrid.
Definition at line 63 of file GeoGrid.cpp.
References stride::Population::CreateContactPool(), and m_population.
template<typename... Args> stride::Person* gengeopop::GeoGrid::CreatePerson (Args &&... args) inline
Create Person in the Population associated withis Grid.
Definition at line 56 of file GeoGrid.h.
References stride::Population::CreatePerson(), Finalize(), and m_population.
void gengeopop::GeoGrid::Finalize ()
Disables the addLocation method and builds the kdtree.
Definition at line 68 of file GeoGrid.cpp.
References gengeopop::KdTree< geogrid_detail::KdTree2DPoint >::Build(), m_finalized, m_locations, and m_tree.
Referenced by CreatePerson().
std::shared_ptr<Location> gengeopop::GeoGrid::Get (size_t index) const inline
Gets a Location by index, doesn't performs a range check.
Definition at line 65 of file GeoGrid.h.
std::shared_ptr<Location> gengeopop::GeoGrid::GetById (unsigned int id) const inline
Gets a Location by Id and check if the Id exists.
Definition at line 68 of file GeoGrid.h.
References m_locationsToIdIndex.
const GeoGridKdTree& gengeopop::GeoGrid::KdTree () inline
Provide access to the GeoGridKdTree spatial lookup structure.
Definition at line 71 of file GeoGrid.h.
References m_tree.
stride::Population* gengeopop::GeoGrid::GetPopulation () const inline
Get the Population associated with this GeoGrid.
Definition at line 74 of file GeoGrid.h.
References BuildAggregator(), LocationsInBox(), LocationsInRadius(), m_population, Remove(), and TopK().
vector< shared_ptr< Location > > gengeopop::GeoGrid::LocationsInRadius (std::shared_ptr< Location > start, double radius) const
Search for locations in radius (in km) around start.
Definition at line 100 of file GeoGrid.cpp.
References CheckFinalized(), and gengeopop::MakeCollector().
Referenced by GetPopulation().
set< shared_ptr< Location > > gengeopop::GeoGrid::LocationsInBox (double long1, double lat1, double long2, double lat2) const
Gets the locations in a rectangle determined by the two coordinates (long1, lat1) and (long2, lat2).
The coordinates must be position on the diagonal, i.e:
p1 --—+ +----—p1 | | | | | | or | | | | | | +----—p2 p2---—+
Definition at line 78 of file GeoGrid.cpp.
References CheckFinalized(), and gengeopop::MakeCollector().
Referenced by GetPopulation(), and LocationsInBox().
std::set< std::shared_ptr< Location > > gengeopop::GeoGrid::LocationsInBox (const std::shared_ptr< Location > & loc1, const std::shared_ptr< Location > & loc2) const
Gets the location in a rectangle defined by the two Locations.
Definition at line 92 of file GeoGrid.cpp.
References LocationsInBox().
vector< shared_ptr< Location > > gengeopop::GeoGrid::TopK (size_t k) const
Gets the K biggest (in population count) locations of this GeoGrid.
Definition at line 114 of file GeoGrid.cpp.
References m_locations.
Referenced by GetPopulation().
void gengeopop::GeoGrid::Remove (const std::shared_ptr< Location > & location)
Remove element of GeoGrid.
Definition at line 138 of file GeoGrid.cpp.
References m_locations, and m_locationsToIdIndex.
Referenced by GetPopulation().
template<typename Policy , typename F > GeoAggregator< Policy, F > gengeopop::GeoGrid::BuildAggregator (F functor, typename Policy::Args && args) const
Build a GeoAggregator with a predefined functor and given args for the Policy.
Definition at line 45 of file GeoGrid.cpp.
References m_tree.
Referenced by GetPopulation().
template<typename Policy > GeoAggregator< Policy > gengeopop::GeoGrid::BuildAggregator (typename Policy::Args && args) const
Build a GeoAggregator that gets its functor when calling, with given args for the Policy.
Definition at line 51 of file GeoGrid.cpp.
References m_tree.
iterator gengeopop::GeoGrid::begin () inline
Iterator to first Location.
Definition at line 115 of file GeoGrid.h.
References m_locations.
iterator gengeopop::GeoGrid::end () inline
Iterator to the end of the Location storage.
Definition at line 118 of file GeoGrid.h.
References m_locations.
const_iterator gengeopop::GeoGrid::cbegin () const inline
Const Iterator to first Location.
Definition at line 121 of file GeoGrid.h.
References m_locations.
const_iterator gengeopop::GeoGrid::cend () const inline
Const iterator to the end of the Location storage.
Definition at line 124 of file GeoGrid.h.
References m_locations.
std::shared_ptr<Location>& gengeopop::GeoGrid::operator[] (size_t index) inline
Gets a Location by index, doesn't performs a range check.
Definition at line 127 of file GeoGrid.h.
References m_locations.
const std::shared_ptr<Location>& gengeopop::GeoGrid::operator[] (size_t index) const inline
Gets a Location by index, doesn't performs a range check.
Definition at line 130 of file GeoGrid.h.
References m_locations.
size_t gengeopop::GeoGrid::size () const inline
Gets current size of Location storage.
Definition at line 133 of file GeoGrid.h.
References CheckFinalized(), and m_locations.
void gengeopop::GeoGrid::CheckFinalized (const std::string & functionName) const private
< Checks whether the GeoGrid is finalized i.e. certain operations can(not) be used.
Definition at line 56 of file GeoGrid.cpp.
References m_finalized.
Referenced by LocationsInBox(), LocationsInRadius(), and size().
Member Data Documentation
std::vector<std::shared_ptr<Location> > gengeopop::GeoGrid::m_locations private
< Container for Locations in GeoGrid.
Associative container by Id for Locations in the GeoGrid.
Definition at line 141 of file GeoGrid.h.
Referenced by AddLocation(), begin(), cbegin(), cend(), end(), Finalize(), operator[](), Remove(), size(), and TopK().
std::unordered_map<unsigned int, std::shared_ptr<Location> > gengeopop::GeoGrid::m_locationsToIdIndex private
Stores pointer to Popluation, but does not take ownership.
Definition at line 144 of file GeoGrid.h.
Referenced by AddLocation(), GetById(), and Remove().
stride::Population* gengeopop::GeoGrid::m_population private
Is the GeoGrid finalized (ready for use) yet?
Definition at line 147 of file GeoGrid.h.
Referenced by CreateContactPool(), CreatePerson(), and GetPopulation().
bool gengeopop::GeoGrid::m_finalized private
Internal KdTree for quick spatial lookup.
Definition at line 150 of file GeoGrid.h.
Referenced by AddLocation(), CheckFinalized(), and Finalize().
GeoGridKdTree gengeopop::GeoGrid::m_tree private
Definition at line 153 of file GeoGrid.h.
Referenced by BuildAggregator(), Finalize(), and KdTree().
The documentation for this class was generated from the following files:
GeoGrid.h
GeoGrid.cpp