Stride Reference Manual: stride::ContactPoolType Namespace Reference
stride::ContactPoolType Namespace Reference
Namespace to manage types of ContactPool.
Classes
class IdSubscriptArray
An std::array modified to enable subscripting with the constact pool type indentifiers.
class IdSubscriptArray< bool >
Specialisation of IdSubscriptArray foor booleans.
Enumerations
enum Id : std::size_t {
Id::Household, Id::School, Id::Work, Id::PrimaryCommunity,
Id::SecondaryCommunity
}
Enumerates the ContactPool types.
Functions
bool IsType (const std::string &s)
Check whether string is name of a ContactPoolType::Id.
string ToString (Id w)
Converts a ContactPoolType::Id value to corresponding name.
Id ToType (const std::string &s)
Converts a string with name to Id.
constexpr unsigned int NumOfTypes ()
Number of ContactPool types.
constexpr std::size_t ToSizeT (Id id)
Cast to size_t for indexing.
Variables
constexpr
std::initializer_list< Id > IdList
To allow iteration over the type ids.
Detailed Description
Namespace to manage types of ContactPool.
Enumeration Type Documentation
enum stride::ContactPoolType::Id : std::size_t strong
Enumerates the ContactPool types.
Enumerator
Household
School
Work
PrimaryCommunity
SecondaryCommunity
Definition at line 33 of file ContactPoolType.h.
Function Documentation
bool stride::ContactPoolType::IsType (const string & s)
Check whether string is name of a ContactPoolType::Id.
Definition at line 32 of file ContactPoolType.cpp.
References Household, PrimaryCommunity, School, SecondaryCommunity, and Work.
std::string stride::ContactPoolType::ToString (Id c)
Converts a ContactPoolType::Id value to corresponding name.
Definition at line 46 of file ContactPoolType.cpp.
References Household, PrimaryCommunity, School, SecondaryCommunity, and Work.
Id stride::ContactPoolType::ToType (const string & s)
Converts a string with name to Id.
Definition at line 58 of file ContactPoolType.cpp.
References Household, PrimaryCommunity, School, SecondaryCommunity, and Work.
Referenced by stride::util::RNManager::Initialize().
constexpr unsigned int stride::ContactPoolType::NumOfTypes () inline
Number of ContactPool types.
Definition at line 43 of file ContactPoolType.h.
Referenced by stride::ContactPoolType::IdSubscriptArray< AgeContactProfile >::at(), and stride::ContactPoolType::IdSubscriptArray< bool >::at().
constexpr std::size_t stride::ContactPoolType::ToSizeT (Id id) inline
Cast to size_t for indexing.
Definition at line 49 of file ContactPoolType.h.
Referenced by stride::ContactPoolType::IdSubscriptArray< AgeContactProfile >::at(), stride::ContactPoolType::IdSubscriptArray< bool >::at(), stride::ContactPoolType::IdSubscriptArray< AgeContactProfile >::operator[](), and stride::ContactPoolType::IdSubscriptArray< bool >::operator[]().
Variable Documentation
constexpr std::initializer_list<Id> stride::ContactPoolType::IdList
Initial value:
{Id::Household, Id::School, Id::Work, Id::PrimaryCommunity,
                                           Id::SecondaryCommunity}
To allow iteration over the type ids.
Definition at line 58 of file ContactPoolType.h.
Referenced by stride::SimBuilder::Build(), stride::ContactPoolType::IdSubscriptArray< AgeContactProfile >::IdSubscriptArray(), stride::ContactPoolType::IdSubscriptArray< bool >::IdSubscriptArray(), stride::PopBuilder::MakePoolSys(), and stride::Sim::TimeStep().