Stride Reference Manual: stride::Population Class Reference
stride::Population Class Reference
Container for persons in population.
#include <Population.h>
Public Member Functions
unsigned int GetAdoptedCount () const
unsigned int GetInfectedCount () const
Get the cumulative number of cases.
std::shared_ptr< spdlog::logger > & GetContactLogger ()
ContactPoolSys & GetContactPoolSys ()
The ContactPoolSys of the simulator.
const ContactPoolSys & GetContactPoolSys () const
The ContactPoolSys of the simulator.
Public Member Functions inherited from stride::util::SegmentedVector< Person >
SegmentedVector ()
Construct empty SegmentedVector.
SegmentedVector (size_type i)
Construct with given number of elements but DO NOT INITIALIZE them.
SegmentedVector (size_type i, const value_type &value)
Construct with given number of elements and INITIALIZE them with value.
SegmentedVector (const self_type &other)
Copy constructor.
SegmentedVector (self_type &&other) noexcept
Move constructor.
SegmentedVector & operator= (const self_type &other)
Copy assignment.
SegmentedVector & operator= (self_type &&other) noexcept
Move assignment.
~SegmentedVector ()
Destructor.
Person & at (std::size_t pos)
Access specified element with bounds checking.
const Person & at (std::size_t pos) const
Access specified element with bounds checking.
Person & back ()
Access the last element.
const Person & back () const
Access the last element.
Person & operator[] (size_t pos)
Access specified element (no bounds checking).
const Person & operator[] (size_t pos) const
Access specified element (no bounds checking).
iterator begin ()
Returns an iterator to the beginning of the container.
const_iterator begin () const
Returns a const_iterator to the beginning of the container.
const_iterator cbegin () const
Returns a const_iterator to the beginning of the container.
iterator end ()
Returns an iterator to the end of the container.
const_iterator end () const
Returns a const_iterator to the end of the container.
const_iterator cend () const
Returns a const_iterator to the end.
std::size_t capacity () const
Returns number of elements that can be stored without allocating additional blocks.
bool empty () const
Checks whether container is empty.
std::size_t get_block_count () const
Returns number of currently allocated blocks.
std::size_t get_elements_per_block () const
Returns number of elements block (template parameter 'N').
std::size_t size () const
Returns the number of elements.
void resize (size_type new_size)
Increases the number of elements (but DOES NOT INITIALIZE the additional elements) or pops elements (and DOES RUN those element's destructor).
void resize (size_type new_size, const value_type &value)
void clear ()
Clears the content.
Person * emplace (size_type pos, Args &&...args)
Constructs element in-place at position pos.
Person * emplace_back (Args &&...args)
Constructs element in-place at the end.
void pop_back ()
Removes the last element.
Person * push_back (const Person &obj)
Adds element to end.
Person * push_back (Person &&obj)
Adds element to end.
Static Public Member Functions
static std::shared_ptr
< Population > Create (const boost::property_tree::ptree &configPt)
Create a population initialized by the configuration in property tree.
static std::shared_ptr
< Population > Create (const std::string &configString)
For use in python environment: create using configuration string i.o ptree.
Private Member Functions
Population ()
void CreatePerson (unsigned int id, double age, unsigned int householdId, unsigned int schoolId, unsigned int workId, unsigned int primaryCommunityId, unsigned int secondaryCommunityId)
Create Person in the population.
template<typename BeliefPolicy >
void InitBeliefPolicy ()
Initialize beliefs container (including this in SetBeliefPolicy function slows you down due to guarding aginst data races in parallel use of SetBeliefPolicy.
template<typename BeliefPolicy >
void SetBeliefPolicy (std::size_t i, const BeliefPolicy &belief=BeliefPolicy())
Assign the belief policy.
Private Attributes
util::Any m_beliefs
Container holds belief data for the persons.
ContactPoolSys m_pool_sys
Holds vector of ContactPools of different types.
std::shared_ptr< spdlog::logger > m_contact_logger
Logger for contact/transmission.
Friends
class PopBuilder
class BeliefSeeder
Additional Inherited Members
Public Types inherited from stride::util::SegmentedVector< Person >
using value_type = Person
using size_type = std::size_t
using self_type = SegmentedVector< Person, 512 >
using iterator = SVIterator< Person, 512, true, Person *, Person &, false >
using const_iterator = SVIterator< Person, 512, true >
Detailed Description
Container for persons in population.
Definition at line 37 of file Population.h.
Constructor & Destructor Documentation
stride::Population::Population () inline private
Definition at line 63 of file Population.h.
Member Function Documentation
std::shared_ptr< Population > stride::Population::Create (const boost::property_tree::ptree & configPt) static
Create a population initialized by the configuration in property tree.
Definition at line 42 of file Population.cpp.
References stride::PopBuilder::Build().
Referenced by stride::CliController::Control(), and stride::StanController::Control().
std::shared_ptr< Population > stride::Population::Create (const std::string & configString) static
For use in python environment: create using configuration string i.o ptree.
Definition at line 73 of file Population.cpp.
References stride::util::FromString().
unsigned int stride::Population::GetAdoptedCount () const
Definition at line 78 of file Population.cpp.
unsigned int stride::Population::GetInfectedCount () const
Get the cumulative number of cases.
Definition at line 89 of file Population.cpp.
std::shared_ptr<spdlog::logger>& stride::Population::GetContactLogger () inline
Definition at line 53 of file Population.h.
References m_contact_logger.
Referenced by stride::SurveySeeder::Seed(), and stride::Sim::TimeStep().
ContactPoolSys& stride::Population::GetContactPoolSys () inline
The ContactPoolSys of the simulator.
Definition at line 56 of file Population.h.
References m_pool_sys.
Referenced by stride::Sim::TimeStep().
const ContactPoolSys& stride::Population::GetContactPoolSys () const inline
The ContactPoolSys of the simulator.
Definition at line 59 of file Population.h.
References m_pool_sys.
void stride::Population::CreatePerson (unsigned int id, double age, unsigned int householdId, unsigned int schoolId, unsigned int workId, unsigned int primaryCommunityId, unsigned int secondaryCommunityId) private
Create Person in the population.
Definition at line 99 of file Population.cpp.
template<typename BeliefPolicy > void stride::Population::InitBeliefPolicy () inline private
Initialize beliefs container (including this in SetBeliefPolicy function slows you down due to guarding aginst data races in parallel use of SetBeliefPolicy.
The DoubleChecked locking did not work in OpenMP parallel for's on Mac OSX.
Definition at line 73 of file Population.h.
References stride::util::Any::emplace(), m_beliefs, and stride::util::SegmentedVector< Person >::size().
Referenced by stride::BeliefSeeder::Seed().
template<typename BeliefPolicy > void stride::Population::SetBeliefPolicy (std::size_t i, const BeliefPolicy & belief = BeliefPolicy()) inline private
Assign the belief policy.
Template Parameters
BeliefPolicy Template type param (we could use plain overloading here, i guess)
Parameters
belief belief object that wille be associated with the person
i subscript to person associated with this belief object
Definition at line 89 of file Population.h.
References stride::util::Any::cast(), stride::util::SegmentedVector< T, N, Safe >::emplace(), and m_beliefs.
Friends And Related Function Documentation
friend class PopBuilder friend
Definition at line 94 of file Population.h.
friend class BeliefSeeder friend
Definition at line 95 of file Population.h.
Member Data Documentation
util::Any stride::Population::m_beliefs private
Container holds belief data for the persons.
Definition at line 98 of file Population.h.
Referenced by InitBeliefPolicy(), and SetBeliefPolicy().
ContactPoolSys stride::Population::m_pool_sys private
Holds vector of ContactPools of different types.
Definition at line 99 of file Population.h.
Referenced by GetContactPoolSys().
std::shared_ptr<spdlog::logger> stride::Population::m_contact_logger private
Logger for contact/transmission.
Definition at line 100 of file Population.h.
Referenced by GetContactLogger().
The documentation for this class was generated from the following files:
Population.h
Population.cpp