Stride Reference Manual: gengeopop::ContactCenter Class Reference
gengeopop::ContactCenter Class Reference abstract
A ContactCenter contains multiple ContactPools.
#include <ContactCenter.h>
Public Types
using iterator = std::vector< stride::ContactPool * >::iterator
Allow range-based iteration.
Public Member Functions
ContactCenter (unsigned int id)
Constructor.
virtual std::string GetType () const =0
Get the name of the type of contact center (e.g. College)
virtual unsigned int GetPoolSize () const =0
Get the size of a pool.
virtual unsigned int GetMaxPools () const =0
Get the maximal number of pools for this center.
virtual void Fill (const std::shared_ptr< GeoGrid > &geoGrid)=0
Apply this ContactCenter to the GeoGrid.
unsigned int GetId () const
Get the ID back.
std::pair< unsigned int, unsigned int > GetPopulationAndInfectedCount () const
Get a count of total population (first) and total number of infections (second)
void AddPool (stride::ContactPool *pool)
Add a ContactPool.
const std::vector< stride::ContactPool * > & GetPools () const
Get the pools.
iterator begin ()
Allow range-based iteration.
iterator end ()
Allow range-based iteration.
virtual ~ContactCenter ()=default
Default destructor, but virtual.
Protected Attributes
std::vector< stride::ContactPool * > m_pools
Our pools.
unsigned int m_id
The id of this ContactCenter.
Detailed Description
A ContactCenter contains multiple ContactPools.
Definition at line 24 of file ContactCenter.h.
Member Typedef Documentation
using gengeopop::ContactCenter::iterator = std::vector<stride::ContactPool*>::iterator
Allow range-based iteration.
Definition at line 28 of file ContactCenter.h.
Constructor & Destructor Documentation
gengeopop::ContactCenter::ContactCenter (unsigned int id) explicit
Constructor.
Definition at line 20 of file ContactCenter.cpp.
virtual gengeopop::ContactCenter::~ContactCenter () virtual default
Default destructor, but virtual.
Member Function Documentation
virtual std::string gengeopop::ContactCenter::GetType () const pure virtual
Get the name of the type of contact center (e.g. College)
Implemented in gengeopop::Community, gengeopop::Workplace, gengeopop::Household, gengeopop::K12School, gengeopop::PrimaryCommunity, gengeopop::College, and gengeopop::SecondaryCommunity.
virtual unsigned int gengeopop::ContactCenter::GetPoolSize () const pure virtual
Get the size of a pool.
Implemented in gengeopop::Community, gengeopop::Household, gengeopop::K12School, gengeopop::College, and gengeopop::Workplace.
virtual unsigned int gengeopop::ContactCenter::GetMaxPools () const pure virtual
Get the maximal number of pools for this center.
Implemented in gengeopop::Community, gengeopop::College, gengeopop::Household, gengeopop::K12School, and gengeopop::Workplace.
virtual void gengeopop::ContactCenter::Fill (const std::shared_ptr< GeoGrid > & geoGrid) pure virtual
Apply this ContactCenter to the GeoGrid.
Implemented in gengeopop::Household, gengeopop::K12School, gengeopop::College, gengeopop::Workplace, gengeopop::PrimaryCommunity, and gengeopop::SecondaryCommunity.
unsigned int gengeopop::ContactCenter::GetId () const
Get the ID back.
Definition at line 30 of file ContactCenter.cpp.
References m_id.
std::pair< unsigned int, unsigned int > gengeopop::ContactCenter::GetPopulationAndInfectedCount () const
Get a count of total population (first) and total number of infections (second)
Definition at line 32 of file ContactCenter.cpp.
References m_pools.
void gengeopop::ContactCenter::AddPool (stride::ContactPool * pool)
Add a ContactPool.
Definition at line 22 of file ContactCenter.cpp.
References m_pools.
Referenced by gengeopop::SecondaryCommunity::Fill(), gengeopop::PrimaryCommunity::Fill(), gengeopop::College::Fill(), gengeopop::Workplace::Fill(), gengeopop::Household::Fill(), and gengeopop::K12School::Fill().
const std::vector< stride::ContactPool * > & gengeopop::ContactCenter::GetPools () const
Get the pools.
Definition at line 28 of file ContactCenter.cpp.
References m_pools.
ContactCenter::iterator gengeopop::ContactCenter::begin ()
Allow range-based iteration.
Definition at line 24 of file ContactCenter.cpp.
References m_pools.
Referenced by gengeopop::WorkplacePopulator::CalculateWorkplacesInCity().
ContactCenter::iterator gengeopop::ContactCenter::end ()
Allow range-based iteration.
Definition at line 26 of file ContactCenter.cpp.
References m_pools.
Referenced by gengeopop::WorkplacePopulator::CalculateWorkplacesInCity().
Member Data Documentation
std::vector<stride::ContactPool*> gengeopop::ContactCenter::m_pools protected
Our pools.
Definition at line 66 of file ContactCenter.h.
Referenced by gengeopop::Community::AddHouseHold(), AddPool(), begin(), end(), gengeopop::SecondaryCommunity::Fill(), gengeopop::PrimaryCommunity::Fill(), GetPools(), and GetPopulationAndInfectedCount().
unsigned int gengeopop::ContactCenter::m_id protected
The id of this ContactCenter.
Definition at line 67 of file ContactCenter.h.
Referenced by GetId().
The documentation for this class was generated from the following files:
ContactCenter.h
ContactCenter.cpp