Stride Reference Manual: stride::Sim Class Reference
stride::Sim Class Reference
Simulator can time step and reveal some of the key data.
#include <Sim.h>
Public Member Functions
std::shared_ptr< Calendar > GetCalendar () const
Calendar for the simulated world.
const TransmissionProfile & GetTransmissionProfile () const
Get the transmission profile.
std::shared_ptr< Population > GetPopulation ()
Get the population.
util::RnMan & GetRnManager ()
Get the random number manager.
void TimeStep ()
Run one time step, computing full simulation (default) or only index case.
std::string GetConfigValue (const std::string &attribute) const
Get the Sim configuration for the given attribute.
double GetTransmissionRate () const
Get the stored transmission rate.
Static Public Member Functions
static std::shared_ptr< Sim > Create (const boost::property_tree::ptree &configPt, std::shared_ptr< Population > pop, util::RnMan &rnManager)
Create Sim initialized by the configuration in property tree and population.
static std::shared_ptr< Sim > Create (const boost::property_tree::ptree &configPt, std::shared_ptr< Population > pop, std::shared_ptr< util::RnMan > rnManager)
For use in SWIG: use shared_ptr to an rnManager and make the Sim have ownership so it won't be destroyed.
Private Member Functions
Sim (util::RnMan &)
Constructor for empty Simulator.
Sim (std::shared_ptr< util::RnMan > rnMan)
Constructor for empty Simulator, used in Python environment.
Private Attributes
boost::property_tree::ptree m_config_pt
Configuration property tree.
ContactLogMode::Id m_contact_log_mode
Specifies contact/transmission logging mode.
unsigned int m_num_threads
The number of (OpenMP) threads.
bool m_track_index_case
General simulation or tracking index case.
bool m_adaptive_symptomatic_behavior
Should symptomatic cases stay home?
std::shared_ptr< Calendar > m_calendar
Management of calendar.
AgeContactProfiles m_contact_profiles
Contact profiles w.r.t age.
std::vector< ContactHandler > m_handlers
Contact handlers (rng & rates).
InfectorExec * m_infector
Executes contacts/transmission loops in contact pool.
std::shared_ptr< Population > m_population
Pointer to the Population.
util::RnMan & m_rn_manager
Random number generation management.
std::shared_ptr< util::RnMan > m_rn_manager_ptr
Used when created from the Python environment to keep it from being destructed.
TransmissionProfile m_transmission_profile
Profile of disease.
PublicHealthAgency m_public_health_agency
Agency to implement reactive strategies.
Friends
class SimBuilder
SimBuilder accesses the default constructor to build Sim using config.
Detailed Description
Simulator can time step and reveal some of the key data.
The Subject base class used for the interaction with the python environment only.
Definition at line 43 of file Sim.h.
Constructor & Destructor Documentation
stride::Sim::Sim (util::RnMan & rnMan) explicit private
Constructor for empty Simulator.
Definition at line 39 of file Sim.cpp.
References stride::ContactLogMode::None.
Referenced by GetTransmissionRate(), and Sim().
stride::Sim::Sim (std::shared_ptr< util::RnMan > rnMan) explicit private
Constructor for empty Simulator, used in Python environment.
Definition at line 46 of file Sim.cpp.
References Create(), m_rn_manager_ptr, Sim(), and SimBuilder.
Member Function Documentation
static std::shared_ptr<Sim> stride::Sim::Create (const boost::property_tree::ptree & configPt, std::shared_ptr< Population > pop, util::RnMan & rnManager) static
Create Sim initialized by the configuration in property tree and population.
Referenced by Sim(), and stride::SimRunner::SimRunner().
static std::shared_ptr<Sim> stride::Sim::Create (const boost::property_tree::ptree & configPt, std::shared_ptr< Population > pop, std::shared_ptr< util::RnMan > rnManager) static
For use in SWIG: use shared_ptr to an rnManager and make the Sim have ownership so it won't be destroyed.
It cannot be owned by the python environment since SWIG cannot handle the RnMan.
std::shared_ptr<Calendar> stride::Sim::GetCalendar () const inline
Calendar for the simulated world.
Initialized with the start date in the simulation world. Use GetCalendar()->GetSimulationDay() for the number of days simulated.
Definition at line 57 of file Sim.h.
References m_calendar.
const TransmissionProfile& stride::Sim::GetTransmissionProfile () const inline
Get the transmission profile.
Definition at line 60 of file Sim.h.
References m_transmission_profile.
std::shared_ptr<Population> stride::Sim::GetPopulation () inline
Get the population.
Definition at line 63 of file Sim.h.
References m_population.
util::RnMan& stride::Sim::GetRnManager () inline
Get the random number manager.
Definition at line 66 of file Sim.h.
References m_rn_manager, and TimeStep().
void stride::Sim::TimeStep ()
Run one time step, computing full simulation (default) or only index case.
Definition at line 72 of file Sim.cpp.
References stride::ContactPoolType::College, stride::PublicHealthAgency::Exec(), stride::Population::GetContactLogger(), stride::Population::GetContactPoolSys(), stride::ContactPoolType::IdList, stride::ContactPoolType::K12School, m_adaptive_symptomatic_behavior, m_calendar, m_contact_profiles, m_handlers, m_infector, m_population, m_public_health_agency, m_rn_manager, m_transmission_profile, stride::util::SegmentedVector< T, N, Safe >::size(), and stride::ContactPoolType::Workplace.
Referenced by GetRnManager().
std::string stride::Sim::GetConfigValue (const std::string & attribute) const inline
Get the Sim configuration for the given attribute.
Definition at line 72 of file Sim.h.
References m_config_pt.
double stride::Sim::GetTransmissionRate () const inline
Get the stored transmission rate.
Definition at line 78 of file Sim.h.
References stride::TransmissionProfile::GetRate(), m_transmission_profile, and Sim().
Friends And Related Function Documentation
friend class SimBuilder friend
SimBuilder accesses the default constructor to build Sim using config.
Definition at line 88 of file Sim.h.
Referenced by Sim().
Member Data Documentation
boost::property_tree::ptree stride::Sim::m_config_pt private
Configuration property tree.
Definition at line 91 of file Sim.h.
Referenced by GetConfigValue().
ContactLogMode::Id stride::Sim::m_contact_log_mode private
Specifies contact/transmission logging mode.
Definition at line 92 of file Sim.h.
unsigned int stride::Sim::m_num_threads private
The number of (OpenMP) threads.
Definition at line 93 of file Sim.h.
bool stride::Sim::m_track_index_case private
General simulation or tracking index case.
Definition at line 94 of file Sim.h.
bool stride::Sim::m_adaptive_symptomatic_behavior private
Should symptomatic cases stay home?
Definition at line 95 of file Sim.h.
Referenced by TimeStep().
std::shared_ptr<Calendar> stride::Sim::m_calendar private
Management of calendar.
Definition at line 97 of file Sim.h.
Referenced by GetCalendar(), and TimeStep().
AgeContactProfiles stride::Sim::m_contact_profiles private
Contact profiles w.r.t age.
Definition at line 98 of file Sim.h.
Referenced by TimeStep().
std::vector<ContactHandler> stride::Sim::m_handlers private
Contact handlers (rng & rates).
Definition at line 99 of file Sim.h.
Referenced by TimeStep().
InfectorExec* stride::Sim::m_infector private
Executes contacts/transmission loops in contact pool.
Definition at line 100 of file Sim.h.
Referenced by TimeStep().
std::shared_ptr<Population> stride::Sim::m_population private
Pointer to the Population.
Definition at line 101 of file Sim.h.
Referenced by GetPopulation(), and TimeStep().
util::RnMan& stride::Sim::m_rn_manager private
Random number generation management.
Definition at line 102 of file Sim.h.
Referenced by GetRnManager(), and TimeStep().
std::shared_ptr<util::RnMan> stride::Sim::m_rn_manager_ptr private
Initial value:
=
            nullptr
Used when created from the Python environment to keep it from being destructed.
Definition at line 103 of file Sim.h.
Referenced by Sim().
TransmissionProfile stride::Sim::m_transmission_profile private
Profile of disease.
Definition at line 105 of file Sim.h.
Referenced by GetTransmissionProfile(), GetTransmissionRate(), and TimeStep().
PublicHealthAgency stride::Sim::m_public_health_agency private
Agency to implement reactive strategies.
Definition at line 106 of file Sim.h.
Referenced by TimeStep().
The documentation for this class was generated from the following files:
Sim.h
Sim.cpp