Stride Reference Manual: stride::ContactType Namespace Reference
stride::ContactType Namespace Reference
Namespace to manage types of ContactPool.
Classes
struct IDPack
Keeps all available Ids in a template pack and exposes it as a std::initialize_list Useful when initializing a IdSubscriptArray with a type that is not default constructible.
class IdSubscriptArray
An std::array modified to enable subscripting with the constact pool type indentifiers.
class IdSubscriptArray< bool >
Specialisation of IdSubscriptArray foor booleans.
Typedefs
using IdPack_t = IDPack< Id::Household, Id::K12School, Id::College, Id::Workplace, Id::PrimaryCommunity, Id::SecondaryCommunity >
Placed separately to please swig and avoid syntax errors there.
Enumerations
enum Id : std::size_t {
Id::Household = static_cast<size_t>(0), Id::K12School, Id::College, Id::Workplace,
Id::PrimaryCommunity, Id::SecondaryCommunity
}
Enumerates the ContactPool types.
Functions
bool IsId (const std::string &s)
Check whether string is name of a ContactPoolType::Id.
Id ToId (const std::string &s)
Converts a string with name to Id.
string ToString (Id w)
Converts a ContactPoolType::Id value to corresponding name.
constexpr unsigned int NumOfTypes ()
Number of ContactPool types.
constexpr std::size_t ToSizeT (Id id)
Cast to size_t for indexing.
Variables
constexpr IdPack_t IdPack
A constexpr global variable that gives access to the available Ids.
constexpr std::initializer_list< Id > IdList = IdPack_t::AsInitializerList
To allow iteration over the type ids.
Detailed Description
Namespace to manage types of ContactPool.
Typedef Documentation
using stride::ContactType::IdPack_t = typedef IDPack<Id::Household, Id::K12School, Id::College, Id::Workplace, Id::PrimaryCommunity, Id::SecondaryCommunity>
Placed separately to please swig and avoid syntax errors there.
Definition at line 70 of file ContactType.h.
Enumeration Type Documentation
enum stride::ContactType::Id : std::size_t strong
Enumerates the ContactPool types.
Enumerator
Household
K12School
College
Workplace
PrimaryCommunity
SecondaryCommunity
Definition at line 35 of file ContactType.h.
Function Documentation
bool stride::ContactType::IsId (const string & s)
Check whether string is name of a ContactPoolType::Id.
Definition at line 33 of file ContactType.cpp.
References College, Household, K12School, PrimaryCommunity, SecondaryCommunity, and Workplace.
Referenced by NumOfTypes().
Id stride::ContactType::ToId (const string & s)
Converts a string with name to Id.
Definition at line 48 of file ContactType.cpp.
References College, Household, K12School, PrimaryCommunity, SecondaryCommunity, and Workplace.
Referenced by NumOfTypes().
std::string stride::ContactType::ToString (Id c)
Converts a ContactPoolType::Id value to corresponding name.
Definition at line 63 of file ContactType.cpp.
References College, Household, K12School, PrimaryCommunity, SecondaryCommunity, and Workplace.
Referenced by ToSizeT().
constexpr unsigned int stride::ContactType::NumOfTypes () inline
Number of ContactPool types.
Definition at line 46 of file ContactType.h.
References IsId(), and ToId().
Referenced by stride::ContactType::IdSubscriptArray< AgeContactProfile >::at(), and stride::ContactType::IdSubscriptArray< bool >::at().
constexpr std::size_t stride::ContactType::ToSizeT (Id id) inline
Cast to size_t for indexing.
Definition at line 55 of file ContactType.h.
References ToString().
Referenced by stride::ContactType::IdSubscriptArray< AgeContactProfile >::at(), stride::ContactType::IdSubscriptArray< bool >::at(), stride::ContactType::IdSubscriptArray< AgeContactProfile >::operator[](), and stride::ContactType::IdSubscriptArray< bool >::operator[]().
Variable Documentation
constexpr IdPack_t stride::ContactType::IdPack
A constexpr global variable that gives access to the available Ids.
Definition at line 73 of file ContactType.h.
constexpr std::initializer_list<Id> stride::ContactType::IdList = IdPack_t::AsInitializerList
To allow iteration over the type ids.
Definition at line 76 of file ContactType.h.
Referenced by stride::SimBuilder::Build(), stride::DefaultPopBuilder::Build(), stride::ContactType::IdSubscriptArray< AgeContactProfile >::IdSubscriptArray(), stride::ContactType::IdSubscriptArray< bool >::IdSubscriptArray(), and stride::Sim::TimeStep().