Stride Reference Manual: stride::util::RunConfigManager Class Reference
stride::util::RunConfigManager Class Reference
Produce run config ptree.
#include <RunConfigManager.h>
Static Public Member Functions
static void CleanConfigFile (boost::property_tree::ptree pt)
Clean (i.e. indent, sort and produde the sha1) the ptree config file.
static boost::property_tree::ptree Create (const std::string &configName)
static std::vector< unsigned int > CreateNumThreads (unsigned int max=ConfigInfo::ProcessorCount())
static boost::property_tree::ptree FromString (const std::string &s)
static std::string ToString (const boost::property_tree::ptree &pt)
static std::string ToSha1 (const boost::property_tree::ptree &pt)
static std::string ToShortSha1 (const boost::property_tree::ptree &pt, unsigned int n=7U)
static void ConvertToGenGeoPop (boost::property_tree::ptree &)
Static Private Member Functions
static std::string CreateBenchInfluenza ()
static std::string CreateBenchMeasles ()
static std::string CreateDefault ()
static std::string CreateTestsInfluenza ()
static std::string CreateTestsMeasles ()
Detailed Description
Produce run config ptree.
Definition at line 34 of file RunConfigManager.h.
Member Function Documentation
void stride::util::RunConfigManager::CleanConfigFile (boost::property_tree::ptree pt) static
Clean (i.e. indent, sort and produde the sha1) the ptree config file.
Definition at line 39 of file RunConfigManager.cpp.
ptree stride::util::RunConfigManager::Create (const std::string & configName) static
Definition at line 48 of file RunConfigManager.cpp.
References stride::util::FromString().
Referenced by calibration::ConfigFileCalibrationRunner::ConfigFileCalibrationRunner().
vector< unsigned int > stride::util::RunConfigManager::CreateNumThreads (unsigned int max = ConfigInfo::ProcessorCount()) static
Definition at line 206 of file RunConfigManager.cpp.
ptree stride::util::RunConfigManager::FromString (const std::string & s) static
Definition at line 308 of file RunConfigManager.cpp.
string stride::util::RunConfigManager::ToString (const boost::property_tree::ptree & pt) static
Definition at line 316 of file RunConfigManager.cpp.
std::string stride::util::RunConfigManager::ToSha1 (const boost::property_tree::ptree & pt) static
Definition at line 323 of file RunConfigManager.cpp.
References stride::ContactLogMode::ToString().
std::string stride::util::RunConfigManager::ToShortSha1 (const boost::property_tree::ptree & pt, unsigned int n = 7U) static
Definition at line 325 of file RunConfigManager.cpp.
void stride::util::RunConfigManager::ConvertToGenGeoPop (boost::property_tree::ptree &) static
Definition at line 61 of file RunConfigManager.cpp.
References stride::util::FromString().
string stride::util::RunConfigManager::CreateBenchInfluenza () static private
Definition at line 83 of file RunConfigManager.cpp.
string stride::util::RunConfigManager::CreateBenchMeasles () static private
Definition at line 166 of file RunConfigManager.cpp.
string stride::util::RunConfigManager::CreateDefault () static private
Definition at line 122 of file RunConfigManager.cpp.
string stride::util::RunConfigManager::CreateTestsInfluenza () static private
Definition at line 230 of file RunConfigManager.cpp.
string stride::util::RunConfigManager::CreateTestsMeasles () static private
Definition at line 269 of file RunConfigManager.cpp.
The documentation for this class was generated from the following files:
RunConfigManager.h
RunConfigManager.cpp