Stride Reference Manual: geopop::GeoGridProtoWriter Class Reference
geopop::GeoGridProtoWriter Class Reference
An implementation of the GeoGridWriter using Protocol Buffers This class is used to write a GeoGrid to a Proto file.
#include <GeoGridProtoWriter.h>
Public Member Functions
GeoGridProtoWriter ()
Construct the GeoGridProtoWriter.
void Write (GeoGrid &geoGrid, std::ostream &stream) override
Write the GeoGrid to the ostream in Protobuf format.
Public Member Functions inherited from geopop::GeoGridWriter
virtual ~GeoGridWriter ()=default
Construct the Writer.
Private Member Functions
void WriteContactCenter (std::shared_ptr< ContactCenter > contactCenter, proto::GeoGrid_Location_ContactCenter *protoContactCenter)
Create a ProtoBuf ContactCenter containing all the information needed to reconstruct a ContactCenter.
void WriteContactPool (stride::ContactPool *contactPool, proto::GeoGrid_Location_ContactCenter_ContactPool *protoContactPool)
Create a ProtoBuf ContactPool containing all the info needed to reconstruct a ContactPool.
void WriteCoordinate (const Coordinate &coordinate, proto::GeoGrid_Location_Coordinate *protoCoordinate)
Create a ProtoBuf Coordinate containing all the info needed to reconstruct a Coordinate..
void WriteLocation (std::shared_ptr< Location > location, proto::GeoGrid_Location *protoLocation)
Create a ProtoBuf Location containing all the info needed to reconstruct a Location.
void WritePerson (stride::Person *person, proto::GeoGrid_Person *protoPerson)
Create a ProtoBuf Person containing all the info needed to reconstruct a Person.
Private Attributes
std::set< stride::Person * > m_persons_found
The persons found when looping over the ContactPools.
Detailed Description
An implementation of the GeoGridWriter using Protocol Buffers This class is used to write a GeoGrid to a Proto file.
Definition at line 44 of file GeoGridProtoWriter.h.
Constructor & Destructor Documentation
geopop::GeoGridProtoWriter::GeoGridProtoWriter ()
Construct the GeoGridProtoWriter.
Definition at line 35 of file GeoGridProtoWriter.cpp.
Member Function Documentation
void geopop::GeoGridProtoWriter::Write (GeoGrid & geoGrid, std::ostream & stream) override virtual
Write the GeoGrid to the ostream in Protobuf format.
Implements geopop::GeoGridWriter.
Definition at line 37 of file GeoGridProtoWriter.cpp.
References proto::GeoGrid::add_locations(), proto::GeoGrid::add_persons(), m_persons_found, WriteLocation(), and WritePerson().
void geopop::GeoGridProtoWriter::WriteContactCenter (std::shared_ptr< ContactCenter > contactCenter, proto::GeoGrid_Location_ContactCenter * protoContactCenter) private
Create a ProtoBuf ContactCenter containing all the information needed to reconstruct a ContactCenter.
Definition at line 57 of file GeoGridProtoWriter.cpp.
References proto::GeoGrid_Location_ContactCenter::add_pools(), proto::GeoGrid_Location_ContactCenter_Type_College, proto::GeoGrid_Location_ContactCenter_Type_Household, proto::GeoGrid_Location_ContactCenter_Type_K12School, proto::GeoGrid_Location_ContactCenter_Type_PrimaryCommunity, proto::GeoGrid_Location_ContactCenter_Type_SecondaryCommunity, proto::GeoGrid_Location_ContactCenter_Type_Workplace, proto::GeoGrid_Location_ContactCenter::set_id(), proto::GeoGrid_Location_ContactCenter::set_type(), and WriteContactPool().
Referenced by WriteLocation().
void geopop::GeoGridProtoWriter::WriteContactPool (stride::ContactPool * contactPool, proto::GeoGrid_Location_ContactCenter_ContactPool * protoContactPool) private
Create a ProtoBuf ContactPool containing all the info needed to reconstruct a ContactPool.
Definition at line 75 of file GeoGridProtoWriter.cpp.
References proto::GeoGrid_Location_ContactCenter_ContactPool::add_people(), stride::ContactPool::GetId(), m_persons_found, and proto::GeoGrid_Location_ContactCenter_ContactPool::set_id().
Referenced by WriteContactCenter().
void geopop::GeoGridProtoWriter::WriteCoordinate (const Coordinate & coordinate, proto::GeoGrid_Location_Coordinate * protoCoordinate) private
Create a ProtoBuf Coordinate containing all the info needed to reconstruct a Coordinate..
Definition at line 85 of file GeoGridProtoWriter.cpp.
References proto::GeoGrid_Location_Coordinate::set_latitude(), and proto::GeoGrid_Location_Coordinate::set_longitude().
Referenced by WriteLocation().
void geopop::GeoGridProtoWriter::WriteLocation (std::shared_ptr< Location > location, proto::GeoGrid_Location * protoLocation) private
Create a ProtoBuf Location containing all the info needed to reconstruct a Location.
Definition at line 92 of file GeoGridProtoWriter.cpp.
References proto::GeoGrid_Location::add_commutes(), proto::GeoGrid_Location::add_contactcenters(), stride::ContactType::IdList, proto::GeoGrid_Location::set_allocated_coordinate(), proto::GeoGrid_Location::set_id(), proto::GeoGrid_Location::set_name(), proto::GeoGrid_Location::set_population(), proto::GeoGrid_Location::set_province(), proto::GeoGrid_Location_Commute::set_to(), WriteContactCenter(), and WriteCoordinate().
Referenced by Write().
void geopop::GeoGridProtoWriter::WritePerson (stride::Person * person, proto::GeoGrid_Person * protoPerson) private
Create a ProtoBuf Person containing all the info needed to reconstruct a Person.
Definition at line 116 of file GeoGridProtoWriter.cpp.
References stride::Person::GetAge(), stride::Person::GetId(), proto::GeoGrid_Person::set_age(), and proto::GeoGrid_Person::set_id().
Referenced by Write().
Member Data Documentation
std::set<stride::Person*> geopop::GeoGridProtoWriter::m_persons_found private
The persons found when looping over the ContactPools.
Definition at line 72 of file GeoGridProtoWriter.h.
Referenced by Write(), and WriteContactPool().
The documentation for this class was generated from the following files:
GeoGridProtoWriter.h
GeoGridProtoWriter.cpp