Stride Reference Manual: gengeopop Namespace Reference
gengeopop Namespace Reference
Namespaces
geogrid_detail
kd
Classes
struct AABB
Axis Aligned Bounding Box.
class BoxPolicy
A GeoAggregator Policy that aggregates over an axis aligned bounding box.
class CitiesCSVReader
Create a Reader which fills a GeoGrid with the Cities found in a given CSV file.
class CitiesReader
Create an abstract Reader which fills a GeoGrid with the Cities found in a given file.
class Collector
Aggregates into a vector, if a vector is passed it should remain alive for the usage duration of the Collector.
class College
class CollegeGenerator
Generate Colleges.
class CollegePopulator
Populate Colleges.
class Community
Models a Community as ContactCenter.
class CommunityGenerator
Generate Communities.
class CommutesCSVReader
Create a Reader which fills a GeoGrid with the Commutes found in a given CSV file.
class CommutesReader
Create an abstract Reader which fills a GeoGrid with the Commutes found in a given file.
class ContactCenter
A ContactCenter contains multiple ContactPools.
class GenGeoPopController
Controls the complete generation and population of a GeoGrid.
class GeoAggregator
A GeoAggregator can either be instantiated with a functor, or be called with one every time.
class GeoAggregator< Policy >
A GeoAggregator that has to be called with a functor.
class GeoAggregator< Policy, F >
A GeoAggregator instanciated with a functor.
class GeoGrid
A Geographic information grid for a single region.
class GeoGridConfig
Configuration data for generating a GeoGrid.
class GeoGridGenerator
Generate a GeoGrid out of PartialGenerators (analog to GeoGridPopulator)
class GeoGridJSONReader
An implementation of the GeoGridReader using JSON This class is used to read a GeoGrid from a JSON file.
class GeoGridJSONWriter
An implementation of the GeoGridWriter using JSON This class is used to write a GeoGrid to a JSON file.
class GeoGridPopulator
Add population to a GeoGrid out of PartionPopulators (simliar to GeoGridGenerator).
class GeoGridProtoReader
An implementation of the GeoGridReader using Protocol Buffers.
class GeoGridProtoWriter
An implementation of the GeoGridWriter using Protocol Buffers This class is used to write a GeoGrid to a Proto file.
class GeoGridReader
An abstract base class for creating a GeoGrid that was read from a file, can be implemented using multiple file types (proto and json are currently implemented)
class GeoGridReaderFactory
A Factory for creating the correct implementation of a GeoGridReader based on the filename extension.
class GeoGridWriter
An interface for writing the GeoGrid to a file, can be implemented with multiple file types (protobuf and json are currently implemented)
class GeoGridWriterFactory
Factory creates the correct implementation of a GeoGridWriter based on the filename extension.
class Household
Models a Household as ContactCenter.
class HouseholdCSVReader
Creates a Reader that retrieves the different Household profiles from a given CSV file.
class HouseholdGenerator
Generate Households.
class HouseholdPopulator
Populate Households.
class HouseholdReader
Create a Reader that retrieves the different Household profiles from a given file This can be implemented using different input file types.
class K12School
Models a K12School as ContactCenter.
class K12SchoolGenerator
Generate K12Schools.
class K12SchoolPopulator
Populate K12Schools.
class KdTree
A k-d tree: a k-dimensional generalization of binary search trees This data structure allows for efficient lookup of points and range queries with an Axis-Aligned Bounding Box (when balanced).
class Location
A location for use within the GeoGrid Contains useful information, both spatial and administrative.
class PartialGenerator
An interface for generators that provide a partial solution.
class PartialPopulator
Interface for populators that provide a partial solution.
class PolygonPolicy
A GeoAggregator Policy that aggregates over a (clockwise) polygon.
class PrimaryCommunity
A model of a Primary Community (as a ContactCenter)
class PrimaryCommunityPopulator
Populate primary Communities.
class RadiusPolicy
A policy for GeoAggregator that aggregates locations within a radius (in km) of a center point.
class ReaderFactory
A Factory for creating the correct implementation of the different Readers which parse the information needed to construct a GeoGrid, based on the file extension.
class SecondaryCommunity
A model of a Secondary Community (as a ContactCenter)
class SecondaryCommunityPopulator
Populate secondary Communities.
class ThreadException
Create a wrapper for capturing the exceptions thrown in a multi-threaded environment This caught exception can then later be re-thrown in the main thread.
class Workplace
Models a Workplace as ContactCenter.
class WorkplaceGenerator
Generate Workplaces.
class WorkplacePopulator
Populate Workplaces.
Typedefs
using Coordinate = boost::geometry::model::point< double, 2, boost::geometry::cs::geographic< boost::geometry::degree >>
Functions
template<typename InsertIter , typename T = typename InsertIter::container_type::value_type>
Collector< InsertIter, T > MakeCollector (const InsertIter &ins)
Build a Collector, useful for type inference.
std::ostream & operator<< (std::ostream &out, const GeoGridConfig &config)
Typedef Documentation
using gengeopop::Coordinate = typedef boost::geometry::model::point<double, 2, boost::geometry::cs::geographic<boost::geometry::degree>>
Definition at line 32 of file Location.h.
Function Documentation
template<typename InsertIter , typename T = typename InsertIter::container_type::value_type> Collector<InsertIter, T> gengeopop::MakeCollector (const InsertIter & ins)
Build a Collector, useful for type inference.
Definition at line 55 of file GeoAggregator.h.
Referenced by gengeopop::GeoGrid::FindLocationsInRadius(), and gengeopop::GeoGrid::InBox().
std::ostream& gengeopop::operator<< (std::ostream & out, const GeoGridConfig & config)
Definition at line 52 of file GeoGridConfig.cpp.
References gengeopop::GeoGridConfig::calculated, gengeopop::GeoGridConfig::compulsoryPupils, gengeopop::GeoGridConfig::fraction_1826_years_WhichAreStudents, gengeopop::GeoGridConfig::fraction_1865_years_active, gengeopop::GeoGridConfig::fraction_active_commutingPeople, gengeopop::GeoGridConfig::fraction_student_commutingPeople, gengeopop::GeoGridConfig::input, stride::util::intToDottedString(), gengeopop::GeoGridConfig::popcount_1826_years, gengeopop::GeoGridConfig::popcount_1826_years_and_student, gengeopop::GeoGridConfig::popcount_1865_and_years_active, gengeopop::GeoGridConfig::popcount_1865_years, and gengeopop::GeoGridConfig::populationSize.