Stride Reference Manual: stride::viewers::InfectedFileViewer Class Reference
stride::viewers::InfectedFileViewer Class Reference
Viewer of Simulator for cases output.
#include <InfectedFileViewer.h>
Public Member Functions
InfectedFileViewer (std::shared_ptr< SimRunner > runner, const std::string &output_prefix)
Instantiate cases viewer.
void Update (sim_event::Id id)
Let viewer perform update.
Private Attributes
std::vector< unsigned int > m_infected
output::InfectedFile m_infected_file
std::shared_ptr< SimRunner > m_runner
Detailed Description
Viewer of Simulator for cases output.
Definition at line 33 of file InfectedFileViewer.h.
Constructor & Destructor Documentation
stride::viewers::InfectedFileViewer::InfectedFileViewer (std::shared_ptr< SimRunner > runner, const std::string & output_prefix) inline
Instantiate cases viewer.
Definition at line 37 of file InfectedFileViewer.h.
References Update().
Member Function Documentation
void stride::viewers::InfectedFileViewer::Update (sim_event::Id id)
Let viewer perform update.
Definition at line 33 of file InfectedFileViewer.cpp.
Referenced by InfectedFileViewer(), and stride::ControlHelper::RegisterViewers().
Member Data Documentation
std::vector<unsigned int> stride::viewers::InfectedFileViewer::m_infected private
Definition at line 46 of file InfectedFileViewer.h.
output::InfectedFile stride::viewers::InfectedFileViewer::m_infected_file private
Definition at line 47 of file InfectedFileViewer.h.
std::shared_ptr<SimRunner> stride::viewers::InfectedFileViewer::m_runner private
Definition at line 48 of file InfectedFileViewer.h.
The documentation for this class was generated from the following files:
InfectedFileViewer.h
InfectedFileViewer.cpp