Stride Reference Manual: stride::SurveySeeder Class Reference
stride::SurveySeeder Class Reference
Seeds the population with survey participants.
#include <SurveySeeder.h>
Public Member Functions
SurveySeeder (const boost::property_tree::ptree &configPt, util::RnMan &rnManager)
Initialize Seeder.
std::shared_ptr< Population > Seed (std::shared_ptr< Population > pop)
Seeds the population with survey participants.
Private Attributes
const boost::property_tree::ptree & m_config_pt
Run config.
util::RnMan & m_rn_manager
Random number manager.
Detailed Description
Seeds the population with survey participants.
Definition at line 34 of file SurveySeeder.h.
Constructor & Destructor Documentation
stride::SurveySeeder::SurveySeeder (const boost::property_tree::ptree & configPt, util::RnMan & rnManager)
Initialize Seeder.
Parameters
configPt Configuration parameters.
rnManager Random number manager.
Definition at line 35 of file SurveySeeder.cpp.
Member Function Documentation
shared_ptr< Population > stride::SurveySeeder::Seed (std::shared_ptr< Population > pop)
Seeds the population with survey participants.
Parameters
pop Population.
Definition at line 37 of file SurveySeeder.cpp.
References stride::Person::GetAge(), stride::Population::GetContactLogger(), stride::Person::GetGender(), stride::Person::GetHealth(), stride::Person::GetId(), stride::Person::GetPoolId(), stride::Health::IsImmune(), stride::Health::IsInfected(), stride::Health::IsInfectious(), stride::Health::IsRecovered(), stride::Person::IsSurveyParticipant(), stride::Health::IsSusceptible(), m_config_pt, m_rn_manager, stride::Person::ParticipateInSurvey(), and stride::util::SegmentedVector< T, N, Safe >::size().
Referenced by stride::DefaultPopBuilder::Build(), and stride::SimBuilder::Build().
Member Data Documentation
const boost::property_tree::ptree& stride::SurveySeeder::m_config_pt private
Run config.
Definition at line 47 of file SurveySeeder.h.
Referenced by Seed().
util::RnMan& stride::SurveySeeder::m_rn_manager private
Random number manager.
Definition at line 48 of file SurveySeeder.h.
Referenced by Seed().
The documentation for this class was generated from the following files:
SurveySeeder.h
SurveySeeder.cpp