Stride Reference Manual: myhayai::ConsoleViewer< T > Class Template Reference
myhayai::ConsoleViewer< T > Class Template Reference
Console viewer outputs (on the console) info on the benchmarks as they run.
#include <ConsoleViewer.h>
Public Member Functions
ConsoleViewer (std::ostream &stream=std::cout, bool noColor=false)
Initialize.
void Update (const event::Payload &payload)
Observer method, registered with subject.
Private Attributes
TestDescriptors m_descriptors
std::ostream & m_stream
Detailed Description
template<typename T>
class myhayai::ConsoleViewer< T >
Console viewer outputs (on the console) info on the benchmarks as they run.
Template Parameters
T Time units used in reporting.
Definition at line 37 of file ConsoleViewer.h.
Constructor & Destructor Documentation
template<typename T > myhayai::ConsoleViewer< T >::ConsoleViewer (std::ostream & stream = std::cout, bool noColor = false) inline explicit
Initialize.
Parameters
stream Output stream. Must exist for the duration of the outputter's use.
Definition at line 42 of file ConsoleViewer.h.
References myhayai::console::DisableColor, and myhayai::console::EnableColor.
Member Function Documentation
template<typename T > void myhayai::ConsoleViewer< T >::Update (const event::Payload & payload)
Observer method, registered with subject.
Definition at line 36 of file ConsoleViewer.cpp.
References stride::util::Stopwatch< T >::Get(), myhayai::event::Payload::m_id, myhayai::event::Payload::m_msg, myhayai::TestDescriptor::m_num_runs, myhayai::event::Payload::m_run_times, myhayai::event::Payload::m_test_name, stride::util::Stopwatch< T >::Start(), and stride::util::Stopwatch< T >::Stop().
Member Data Documentation
template<typename T > TestDescriptors myhayai::ConsoleViewer< T >::m_descriptors private
Definition at line 56 of file ConsoleViewer.h.
template<typename T > std::ostream& myhayai::ConsoleViewer< T >::m_stream private
Definition at line 57 of file ConsoleViewer.h.
The documentation for this class was generated from the following files:
ConsoleViewer.h
ConsoleViewer.cpp