Stride Reference Manual: stride::output::AdoptedFile Class Reference
stride::output::AdoptedFile Class Reference
Produces a file with daily count of person having adopted a belief.
#include <AdoptedFile.h>
Public Member Functions
AdoptedFile (const std::string &output_dir="output")
Constructor.
~AdoptedFile ()
Destructor.
void Print (const std::vector< unsigned int > &adopters)
Print the given cases with corresponding tag.
Private Member Functions
void Initialize (const std::string &output_dir)
Generate file name and open the file stream.
Private Attributes
std::ofstream m_fstream
The file stream.
Detailed Description
Produces a file with daily count of person having adopted a belief.
Definition at line 33 of file AdoptedFile.h.
Constructor & Destructor Documentation
stride::output::AdoptedFile::AdoptedFile (const std::string & output_dir = "output") explicit
Constructor.
Definition at line 25 of file AdoptedFile.cpp.
References Initialize().
stride::output::AdoptedFile::~AdoptedFile ()
Destructor.
Definition at line 27 of file AdoptedFile.cpp.
References m_fstream.
Member Function Documentation
void stride::output::AdoptedFile::Print (const std::vector< unsigned int > & adopters)
Print the given cases with corresponding tag.
Definition at line 29 of file AdoptedFile.cpp.
References m_fstream.
void stride::output::AdoptedFile::Initialize (const std::string & output_dir) private
Generate file name and open the file stream.
Definition at line 37 of file AdoptedFile.cpp.
References stride::util::FileSys::BuildPath(), and m_fstream.
Referenced by AdoptedFile().
Member Data Documentation
std::ofstream stride::output::AdoptedFile::m_fstream private
The file stream.
Definition at line 50 of file AdoptedFile.h.
Referenced by Initialize(), Print(), and ~AdoptedFile().
The documentation for this class was generated from the following files:
AdoptedFile.h
AdoptedFile.cpp