Stride Reference Manual: stride::DefaultPopBuilder Class Reference
stride::DefaultPopBuilder Class Reference
Initializes Population objects.
#include <DefaultPopBuilder.h>
Public Member Functions
std::shared_ptr< Population > Build (std::shared_ptr< Population > pop) override
Build Population and return it afterwards.
Public Member Functions inherited from stride::AbstractPopBuilder
AbstractPopBuilder (const boost::property_tree::ptree &configPt, util::RnMan &rnManager)
Initializing constructor.
virtual ~AbstractPopBuilder ()=default
Private Member Functions
std::shared_ptr< Population > MakePersons (std::shared_ptr< Population > pop)
Generates pop's individuals and return pop.
Additional Inherited Members
Protected Attributes inherited from stride::AbstractPopBuilder
const boost::property_tree::ptree & m_config_pt
Configuration property tree.
util::RnMan & m_rn_manager
Random number generation management.
Detailed Description
Initializes Population objects.
Definition at line 35 of file DefaultPopBuilder.h.
Member Function Documentation
shared_ptr< Population > stride::DefaultPopBuilder::Build (std::shared_ptr< Population > pop) override virtual
Build Population and return it afterwards.
The steps are:
Check input data.
Read persons from file and instantiate them.
Fill up the various type of contactpools.
Seed the population with contact survey participants.
Implements stride::AbstractPopBuilder.
Definition at line 83 of file DefaultPopBuilder.cpp.
References stride::ContactPoolType::IdList.
Referenced by stride::Population::Create().
shared_ptr< Population > stride::DefaultPopBuilder::MakePersons (std::shared_ptr< Population > pop) private
Generates pop's individuals and return pop.
Definition at line 43 of file DefaultPopBuilder.cpp.
References stride::util::FileSys::GetDataDir(), and stride::util::Split().
The documentation for this class was generated from the following files:
DefaultPopBuilder.h
DefaultPopBuilder.cpp