Stride Reference Manual: gengeopop Namespace Reference
gengeopop Namespace Reference
Namespaces
geogrid_detail
kd
Classes
struct AABBox
AxisAlignedBoundingBox (hyperrectangle defined by lower and upper bound for every dimension).
class BoxPolicy
GeoAggregator Policy that aggregates over an axis aligned bounding box.
class CitiesCSVReader
Create a Reader that fills a GeoGrid with the cities found in a CSV input stream.
class CitiesReader
Create an abstract Reader which fills a GeoGrid with the cities found in file.
class Collector
Aggregates into a vector that must should remain alive for the usage duration of the Collector.
class College
Models a College (institution of higher education).
class CollegeGenerator
Generator College contact pool types.
class CollegePopulator
Populate the colleges.
class Community
Models a Community as ContactCenter.
class CommunityGenerator
Generator for Community contact pools.
class CommutesCSVReader
Create a Reader that fills a GeoGrid with the commute info from CSV file.
class CommutesReader
Create an abstract Reader that fills a GeoGrid with the commute info from file.
class ContactCenter
A ContactCenter contains multiple ContactPools.
class Generator
An interface base class for generators that provide geo data and apply it onto the GeoGrid.
class GeoAggregator
A GeoAggregator can either be instantiated with a functor, or be called with one every time.
class GeoAggregator< Policy >
A GeoAggregator that has to be called with a functor.
class GeoAggregator< Policy, F >
A GeoAggregator constructed with a functor.
class GeoGrid
A Geographic grid of simulation region contains Locations that in turn contains ContactCenters.
class GeoGridBuilder
Controls the complete generation and population of a GeoGrid.
class GeoGridConfig
Configuration data mostly for generating a population, but also for computing the required number od schools, workplaces, communities etc for that population.
class GeoGridConfigBuilder
Controls the complete generation and population of a GeoGrid.
class GeoGridJSONReader
An implementation of the GeoGridReader using JSON.
class GeoGridJSONWriter
Writes a GeoGrid to a JSON file.
class GeoGridProtoReader
An implementation of the GeoGridReader using Protocol Buffers.
class GeoGridProtoWriter
An implementation of the GeoGridWriter using Protocol Buffers This class is used to write a GeoGrid to a Proto file.
class GeoGridReader
An abstract base class for creating a GeoGrid that was read from a file, can be implemented using multiple file types (proto and json are currently implemented)
class GeoGridReaderFactory
A Factory for creating the correct implementation of a GeoGridReader based on the filename extension.
class GeoGridWriter
An interface for writing the GeoGrid to a file, can be implemented with multiple file types.
class GeoGridWriterFactory
Factory creates the correct implementation of a GeoGridWriter based on the filename extension.
class Household
Models a Household as ContactCenter.
class HouseholdCSVReader
Creates a Reader that retrieves the different Household profiles from a given CSV file.
class HouseholdGenerator
Generator Household contact pools.
class HouseholdPopulator
Populate the households.
class HouseholdReader
Retrieves the reference Household profiles from file.
class K12School
Models a K12School as ContactCenter.
class K12SchoolGenerator
Generate K12Schools.
class K12SchoolPopulator
Populate the K12Schools.
class KdTree
A k-d tree: a k-dimensional generalization of binary search trees This data structure allows for efficient lookup of points and range queries with an Axis-Aligned Bounding Box (when balanced).
class Location
A location for use within the GeoGrid.
class PolygonPolicy
A GeoAggregator Policy that aggregates over a (clockwise) polygon.
class Populator
Interface for populators.
class PrimaryCommunity
A model of a Primary Community (as a ContactCenter)
class PrimaryCommunityPopulator
Populate the primary communities.
class RadiusPolicy
GeoAggregator Policy that aggregates locations within a radius (in km) of a center point.
class ReaderFactory
A Factory for creating the correct implementation of the different Readers which parse the information needed to construct a GeoGrid, based on the file extension.
class SecondaryCommunity
A model of a Secondary Community (as a ContactCenter)
class SecondaryCommunityPopulator
Populate the secondary communities.
class ThreadException
Create a wrapper for capturing exceptions thrown in a multi-threaded environment.
class Workplace
Models a Workplace as ContactCenter.
class WorkplaceGenerator
Generate Workplaces.
class WorkplacePopulator
Populate the workplaces.
Typedefs
using Coordinate = boost::geometry::model::point< double, 2, boost::geometry::cs::geographic< boost::geometry::degree >>
using GeoGridKdTree = KdTree< geogrid_detail::KdTree2DPoint >
Functions
template<typename InsertIter , typename T = typename InsertIter::container_type::value_type>
Collector< InsertIter, T > MakeCollector (const InsertIter &ins)
Build a Collector, useful for type inference.
ostream & operator<< (ostream &out, const GeoGridConfig &config)
Typedef Documentation
using gengeopop::Coordinate = typedef boost::geometry::model::point<double, 2, boost::geometry::cs::geographic<boost::geometry::degree>>
Definition at line 23 of file Coordinate.h.
using gengeopop::GeoGridKdTree = typedef KdTree<geogrid_detail::KdTree2DPoint>
Definition at line 25 of file GeoGridKdTree.h.
Function Documentation
template<typename InsertIter , typename T = typename InsertIter::container_type::value_type> Collector<InsertIter, T> gengeopop::MakeCollector (const InsertIter & ins)
Build a Collector, useful for type inference.
Definition at line 59 of file GeoAggregator.h.
Referenced by gengeopop::GeoGrid::LocationsInBox(), and gengeopop::GeoGrid::LocationsInRadius().
ostream& gengeopop::operator<< (std::ostream & out, const GeoGridConfig & config)
Definition at line 40 of file GeoGridConfig.cpp.
References gengeopop::GeoGridConfig::compulsory_pupils, gengeopop::GeoGridConfig::fraction_1826_student, gengeopop::GeoGridConfig::fraction_1865_active, gengeopop::GeoGridConfig::fraction_active_commuters, gengeopop::GeoGridConfig::fraction_student_commuters, gengeopop::GeoGridConfig::input, stride::util::intToDottedString(), gengeopop::GeoGridConfig::pop_size, gengeopop::GeoGridConfig::popcount_1826, gengeopop::GeoGridConfig::popcount_1826_student, gengeopop::GeoGridConfig::popcount_1865, gengeopop::GeoGridConfig::popcount_1865_active, and gengeopop::GeoGridConfig::popInfo.