Stride Reference Manual: gengeopop::WorkplacePopulator Class Reference
gengeopop::WorkplacePopulator Class Reference
Populate Workplaces.
#include <WorkplacePopulator.h>
Public Member Functions
WorkplacePopulator (stride::util::RnMan &rn_manager, std::shared_ptr< spdlog::logger > logger)
Constructor.
void Apply (std::shared_ptr< GeoGrid > geogrid, GeoGridConfig &geoGridConfig) override
Populates the workplaces in geogrid with persons.
Public Member Functions inherited from gengeopop::PartialPopulator
PartialPopulator (stride::util::RnMan &rn_manager, std::shared_ptr< spdlog::logger > logger)
Construct with a RnMan and a logger.
virtual ~PartialPopulator ()=default
Virtual destructor for inheritance.
Private Member Functions
void CalculateWorkplacesInCity ()
Fills the m_workplacesInCity map.
void CalculateFractionCommutingStudents ()
Calculates m_fractionCommutingStudents.
void CalculateNearbyWorkspaces ()
Calculates the workplaces which are nearby to m_currentLoc.
void CalculateCommutingLocations ()
Calculates the workplaces to which persons from m_currentLoc may commute to.
void AssignActive (stride::Person *person)
Assign a workplace to an active person.
Private Attributes
unsigned int m_assignedTo0 = 0
Number of persons assigned to no workplace.
unsigned int m_assignedCommuting = 0
Number of persons assigned to workplace outside home location.
unsigned int m_assignedNotCommuting = 0
Amount of persons assigned to workplace at the home location.
std::shared_ptr< Location > m_currentLoc
The location for which the workers currently are being assigned.
std::shared_ptr< GeoGrid > m_geoGrid
The GeoGrid which will be populated.
GeoGridConfig m_geoGridConfig
The GeoGridConfig used during populating.
std::unordered_map< Location *, std::pair< std::vector< stride::ContactPool * >, discreteDist > > m_workplacesInCity
For each location store the workplaces and a distribution to choose a random one.
double m_fractionCommutingStudents
Fraction of the commuting people who are a student.
std::vector< stride::ContactPool * > m_nearByWorkplaces
Workplaces which are nearby to the m_currentLoc.
discreteDist m_distNonCommuting
distribution to choose from m_nearByWorkPlaces;
std::vector< Location * > m_commutingLocations
Workplaces which persons from m_currentLoc may commute to.
discreteDist m_disCommuting
distribution to choose from m_commutingLocations
Additional Inherited Members
Protected Member Functions inherited from gengeopop::PartialPopulator
template<typename T >
std::vector< stride::ContactPool * > GetContactPoolInIncreasingRadius (const std::shared_ptr< GeoGrid > &geoGrid, const std::shared_ptr< Location > &start, double startRadius=10) const
Find contactpools in geoGrid in an exponentially increasing radius.
bool MakeChoice (double fraction)
Convenience wrapper around m_rnManager.
Protected Attributes inherited from gengeopop::PartialPopulator
stride::util::RnMan & m_rnManager
RnManager used by populators.
std::shared_ptr< spdlog::logger > m_logger
Logger used by populators.
Detailed Description
Populate Workplaces.
Definition at line 27 of file WorkplacePopulator.h.
Constructor & Destructor Documentation
gengeopop::WorkplacePopulator::WorkplacePopulator (stride::util::RnMan & rn_manager, std::shared_ptr< spdlog::logger > logger)
Constructor.
Definition at line 29 of file WorkplacePopulator.cpp.
Member Function Documentation
void gengeopop::WorkplacePopulator::Apply (std::shared_ptr< GeoGrid > geogrid, GeoGridConfig & geoGridConfig) override virtual
Populates the workplaces in geogrid with persons.
Implements gengeopop::PartialPopulator.
Definition at line 36 of file WorkplacePopulator.cpp.
References AssignActive(), CalculateCommutingLocations(), CalculateFractionCommutingStudents(), CalculateNearbyWorkspaces(), CalculateWorkplacesInCity(), gengeopop::GeoGridConfig::fraction_1826_years_WhichAreStudents, gengeopop::GeoGridConfig::fraction_1865_years_active, gengeopop::GeoGridConfig::input, m_assignedCommuting, m_assignedNotCommuting, m_assignedTo0, m_commutingLocations, m_currentLoc, m_disCommuting, m_distNonCommuting, m_fractionCommutingStudents, m_geoGrid, m_geoGridConfig, gengeopop::PartialPopulator::m_logger, m_nearByWorkplaces, m_workplacesInCity, and gengeopop::PartialPopulator::MakeChoice().
void gengeopop::WorkplacePopulator::CalculateWorkplacesInCity () private
Fills the m_workplacesInCity map.
Definition at line 104 of file WorkplacePopulator.cpp.
References gengeopop::ContactCenter::begin(), gengeopop::ContactCenter::end(), m_geoGrid, gengeopop::PartialPopulator::m_rnManager, and m_workplacesInCity.
Referenced by Apply().
void gengeopop::WorkplacePopulator::CalculateFractionCommutingStudents () private
Calculates m_fractionCommutingStudents.
Definition at line 91 of file WorkplacePopulator.cpp.
References gengeopop::GeoGridConfig::calculated, gengeopop::GeoGridConfig::fraction_active_commutingPeople, gengeopop::GeoGridConfig::fraction_student_commutingPeople, gengeopop::GeoGridConfig::input, m_fractionCommutingStudents, m_geoGridConfig, gengeopop::GeoGridConfig::popcount_1826_years_and_student, and gengeopop::GeoGridConfig::popcount_1865_and_years_active.
Referenced by Apply().
void gengeopop::WorkplacePopulator::CalculateNearbyWorkspaces () private
Calculates the workplaces which are nearby to m_currentLoc.
Definition at line 168 of file WorkplacePopulator.cpp.
References m_currentLoc, m_distNonCommuting, m_geoGrid, m_nearByWorkplaces, and gengeopop::PartialPopulator::m_rnManager.
Referenced by Apply().
void gengeopop::WorkplacePopulator::CalculateCommutingLocations () private
Calculates the workplaces to which persons from m_currentLoc may commute to.
Definition at line 143 of file WorkplacePopulator.cpp.
References ExcAssert(), m_commutingLocations, m_currentLoc, m_disCommuting, m_fractionCommutingStudents, and gengeopop::PartialPopulator::m_rnManager.
Referenced by Apply().
void gengeopop::WorkplacePopulator::AssignActive (stride::Person * person) private
Assign a workplace to an active person.
Definition at line 121 of file WorkplacePopulator.cpp.
References gengeopop::GeoGridConfig::fraction_active_commutingPeople, gengeopop::GeoGridConfig::input, m_assignedCommuting, m_assignedNotCommuting, m_commutingLocations, m_disCommuting, m_distNonCommuting, m_geoGridConfig, m_nearByWorkplaces, m_workplacesInCity, gengeopop::PartialPopulator::MakeChoice(), and stride::Person::SetWorkId().
Referenced by Apply().
Member Data Documentation
unsigned int gengeopop::WorkplacePopulator::m_assignedTo0 = 0 private
Number of persons assigned to no workplace.
Definition at line 53 of file WorkplacePopulator.h.
Referenced by Apply().
unsigned int gengeopop::WorkplacePopulator::m_assignedCommuting = 0 private
Number of persons assigned to workplace outside home location.
Definition at line 54 of file WorkplacePopulator.h.
Referenced by Apply(), and AssignActive().
unsigned int gengeopop::WorkplacePopulator::m_assignedNotCommuting = 0 private
Amount of persons assigned to workplace at the home location.
Definition at line 55 of file WorkplacePopulator.h.
Referenced by Apply(), and AssignActive().
std::shared_ptr<Location> gengeopop::WorkplacePopulator::m_currentLoc private
The location for which the workers currently are being assigned.
Definition at line 57 of file WorkplacePopulator.h.
Referenced by Apply(), CalculateCommutingLocations(), and CalculateNearbyWorkspaces().
std::shared_ptr<GeoGrid> gengeopop::WorkplacePopulator::m_geoGrid private
The GeoGrid which will be populated.
Definition at line 59 of file WorkplacePopulator.h.
Referenced by Apply(), CalculateNearbyWorkspaces(), and CalculateWorkplacesInCity().
GeoGridConfig gengeopop::WorkplacePopulator::m_geoGridConfig private
The GeoGridConfig used during populating.
Definition at line 60 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateFractionCommutingStudents().
std::unordered_map<Location*, std::pair<std::vector<stride::ContactPool*>, discreteDist> > gengeopop::WorkplacePopulator::m_workplacesInCity private
For each location store the workplaces and a distribution to choose a random one.
Definition at line 63 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateWorkplacesInCity().
double gengeopop::WorkplacePopulator::m_fractionCommutingStudents private
Fraction of the commuting people who are a student.
Definition at line 65 of file WorkplacePopulator.h.
Referenced by Apply(), CalculateCommutingLocations(), and CalculateFractionCommutingStudents().
std::vector<stride::ContactPool*> gengeopop::WorkplacePopulator::m_nearByWorkplaces private
Workplaces which are nearby to the m_currentLoc.
Definition at line 67 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateNearbyWorkspaces().
discreteDist gengeopop::WorkplacePopulator::m_distNonCommuting private
distribution to choose from m_nearByWorkPlaces;
Definition at line 68 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateNearbyWorkspaces().
std::vector<Location*> gengeopop::WorkplacePopulator::m_commutingLocations private
Workplaces which persons from m_currentLoc may commute to.
Definition at line 70 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateCommutingLocations().
discreteDist gengeopop::WorkplacePopulator::m_disCommuting private
distribution to choose from m_commutingLocations
Definition at line 71 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateCommutingLocations().
The documentation for this class was generated from the following files:
WorkplacePopulator.h
WorkplacePopulator.cpp