Stride Reference Manual: gengeopop::K12School Class Reference
gengeopop::K12School Class Reference
Models a K12School as ContactCenter.
#include <K12School.h>
Public Member Functions
K12School (unsigned int id)
Construct K12school with assigned ID.
void Fill (const std::shared_ptr< GeoGrid > &geoGrid) override
See ContactCenter::Fill.
unsigned int GetMaxPools () const override
See ContactCenter::GetMaxPools.
unsigned int GetPoolSize () const override
See ContactCenter::GetPoolSize.
std::string GetType () const override
See ContactCenter::GetType.
Public Member Functions inherited from gengeopop::ContactCenter
ContactCenter (unsigned int id)
Construct ContactCenter with assigned ID.
void AddPool (stride::ContactPool *pool)
Add a ContactPool.
unsigned int GetId () const
Return the ID.
const std::vector< stride::ContactPool * > & GetPools () const
Get the pools container.
std::pair< unsigned int, unsigned int > GetPopulationAndInfectedCount () const
Get a count of total population (first) and total number of infections (second).
virtual ~ContactCenter ()=default
Default destructor, but virtual.
iterator begin ()
Allow range-based iteration over pools in contact center.
iterator end ()
Allow range-based iteration over pools in contact center.
Additional Inherited Members
Public Types inherited from gengeopop::ContactCenter
using iterator = std::vector< stride::ContactPool * >::iterator
Allow range-based iteration over pools in contact center.
Protected Attributes inherited from gengeopop::ContactCenter
std::vector< stride::ContactPool * > m_pools
Our pools.
unsigned int m_id
The id of this ContactCenter.
Detailed Description
Models a K12School as ContactCenter.
Definition at line 27 of file K12School.h.
Constructor & Destructor Documentation
gengeopop::K12School::K12School (unsigned int id) inline explicit
Construct K12school with assigned ID.
Definition at line 31 of file K12School.h.
Member Function Documentation
void gengeopop::K12School::Fill (const std::shared_ptr< GeoGrid > & geoGrid) inline override virtual
See ContactCenter::Fill.
Implements gengeopop::ContactCenter.
Definition at line 34 of file K12School.h.
References gengeopop::ContactCenter::AddPool(), GetMaxPools(), and stride::ContactPoolType::K12School.
unsigned int gengeopop::K12School::GetMaxPools () const inline override virtual
See ContactCenter::GetMaxPools.
Implements gengeopop::ContactCenter.
Definition at line 42 of file K12School.h.
Referenced by Fill().
unsigned int gengeopop::K12School::GetPoolSize () const inline override virtual
See ContactCenter::GetPoolSize.
Implements gengeopop::ContactCenter.
Definition at line 45 of file K12School.h.
std::string gengeopop::K12School::GetType () const inline override virtual
See ContactCenter::GetType.
Implements gengeopop::ContactCenter.
Definition at line 48 of file K12School.h.
The documentation for this class was generated from the following file:
K12School.h