Stride Reference Manual: geopop::HouseholdCenter Class Reference
geopop::HouseholdCenter Class Reference
Models a Household as ContactCenter.
#include <HouseholdCenter.h>
Public Member Functions
HouseholdCenter (unsigned int id=0U)
Construct household with assigned ID.
void SetupPools (const GeoGridConfig &geoGridConfig, stride::Population *pop) override
See ContactCenter::Fill.
stride::ContactType::Id GetContactPoolType () const override
See ContactCenter::GetContactPoolType.
Public Member Functions inherited from geopop::ContactCenter
ContactCenter (unsigned int id)
Construct ContactCenter with assigned ID.
virtual ~ContactCenter ()=default
Default destructor, but virtual.
unsigned int GetId () const
Return the ID of this ContactCenter.
std::pair< unsigned int, unsigned int > GetPopulationAndInfectedCount () const
Get a count of total population (first) and total number of infections (second).
void RegisterPool (stride::ContactPool *pool)
Register a ContactPool with this ContactCenter.
iterator begin ()
Iterator to first Location.
iterator end ()
Iterator to the end of the Location storage.
const_iterator cbegin () const
Const Iterator to first Location.
const_iterator cend () const
Const iterator to the end of the Location storage.
stride::ContactPool *const & operator[] (size_t index) const
Gets a ContactPool by index, doesn't performs a range check.
size_t size () const
Gets current size of Location storage.
Additional Inherited Members
Public Types inherited from geopop::ContactCenter
using iterator = std::vector< stride::ContactPool * >::iterator
using const_iterator = std::vector< stride::ContactPool * >::const_iterator
Protected Attributes inherited from geopop::ContactCenter
std::vector< stride::ContactPool * > m_pools
ContactPools for this ContactCenter.
unsigned int m_id
The Id of this ContactCenter.
Detailed Description
Models a Household as ContactCenter.
Definition at line 27 of file HouseholdCenter.h.
Constructor & Destructor Documentation
geopop::HouseholdCenter::HouseholdCenter (unsigned int id = 0U) inline explicit
Construct household with assigned ID.
Definition at line 31 of file HouseholdCenter.h.
References SetupPools().
Member Function Documentation
void geopop::HouseholdCenter::SetupPools (const GeoGridConfig & geoGridConfig, stride::Population * pop) override virtual
See ContactCenter::Fill.
Implements geopop::ContactCenter.
Definition at line 26 of file HouseholdCenter.cpp.
References stride::ContactPoolSys::CreateContactPool(), stride::ContactType::Household, geopop::GeoGridConfig::pools, geopop::GeoGridConfig::pools_per_houselhold, and stride::Population::RefPoolSys().
Referenced by HouseholdCenter().
stride::ContactType::Id geopop::HouseholdCenter::GetContactPoolType () const inline override virtual
See ContactCenter::GetContactPoolType.
Implements geopop::ContactCenter.
Definition at line 37 of file HouseholdCenter.h.
References stride::ContactType::Household.
The documentation for this class was generated from the following files:
HouseholdCenter.h
HouseholdCenter.cpp