Stride Reference Manual: geopop::RadiusPolicy Class Reference
geopop::RadiusPolicy Class Reference
GeoAggregator Policy that aggregates locations within a radius (in km) of a center point.
#include <GeoAggregator.h>
Public Types
using Args = std::tuple< geogrid_detail::KdTree2DPoint, double >
Public Member Functions
RadiusPolicy (Args args)
AABBox< geogrid_detail::KdTree2DPoint > GetBoundingBox () const
bool Contains (const geogrid_detail::KdTree2DPoint &pt) const
Private Attributes
geogrid_detail::KdTree2DPoint m_center
double m_radius
Detailed Description
GeoAggregator Policy that aggregates locations within a radius (in km) of a center point.
Definition at line 136 of file GeoAggregator.h.
Member Typedef Documentation
using geopop::RadiusPolicy::Args = std::tuple<geogrid_detail::KdTree2DPoint, double>
Definition at line 139 of file GeoAggregator.h.
Constructor & Destructor Documentation
geopop::RadiusPolicy::RadiusPolicy (Args args) inline explicit
Definition at line 141 of file GeoAggregator.h.
Member Function Documentation
AABBox<geogrid_detail::KdTree2DPoint> geopop::RadiusPolicy::GetBoundingBox () const inline
Definition at line 143 of file GeoAggregator.h.
References geoaggregator_detail::DegreeToRadian(), and geoaggregator_detail::RadianToDegree().
bool geopop::RadiusPolicy::Contains (const geogrid_detail::KdTree2DPoint & pt) const inline
Definition at line 164 of file GeoAggregator.h.
References geopop::geogrid_detail::KdTree2DPoint::InRadius().
Member Data Documentation
geogrid_detail::KdTree2DPoint geopop::RadiusPolicy::m_center private
Definition at line 167 of file GeoAggregator.h.
double geopop::RadiusPolicy::m_radius private
Definition at line 168 of file GeoAggregator.h.
The documentation for this class was generated from the following file:
GeoAggregator.h