Stride Reference Manual: geopop::WorkplacePopulator Class Reference
geopop::WorkplacePopulator Class Reference
Populate the workplaces.
#include <WorkplacePopulator.h>
Public Member Functions
WorkplacePopulator (stride::util::RnMan &rn_manager, std::shared_ptr< spdlog::logger > logger=nullptr)
Constructor.
void Apply (GeoGrid &geogrid, const GeoGridConfig &geoGridConfig) override
Populates the workplaces in geogrid with persons.
Public Member Functions inherited from geopop::Populator
Populator (stride::util::RnMan &rnMan, std::shared_ptr< spdlog::logger > logger=nullptr)
Construct with a RnMan and a logger.
virtual ~Populator ()=default
Virtual destructor for inheritance.
Private Member Functions
void CalculateWorkplacesInCity (GeoGrid &geogrid)
Fills the m_workplacesInCity map.
void CalculateFractionCommutingStudents ()
Calculates m_fractionCommutingStudents.
void CalculateNearbyWorkspaces (GeoGrid &geogrid)
Calculates the workplaces which are nearby to m_currentLoc.
void CalculateCommutingLocations ()
Calculates the workplaces to which persons from m_currentLoc may commute to.
void AssignActive (stride::Person *person)
Assign a workplace to an active person.
Private Attributes
unsigned int m_assignedTo0 = 0
Number of persons assigned to no workplace.
unsigned int m_assignedCommuting = 0
Number of persons assigned to workplace outside home location.
unsigned int m_assignedNotCommuting = 0
Amount of persons assigned to workplace at the home location.
std::shared_ptr< Location > m_currentLoc
The location for which the workers currently are being assigned..
GeoGridConfig m_geoGridConfig
The GeoGridConfig used during populating.
std::unordered_map< Location *, std::pair< std::vector< stride::ContactPool * >, std::function< int()> > > m_workplacesInCity
For each location store workplaces and a distribution fot random selection.
double m_fractionCommutingStudents
Fraction of the commuting people who are a student.
std::vector< stride::ContactPool * > m_nearByWorkplaces
Workplaces which are nearby to the m_currentLoc.
std::function< int()> m_distNonCommuting
Distribution to choose from m_nearByWorkPlaces.
std::vector< Location * > m_commutingLocations
Workplaces which persons from m_currentLoc may commute to.
std::function< int()> m_disCommuting
Distribution to choose from m_commutingLocations.
Additional Inherited Members
Protected Member Functions inherited from geopop::Populator
std::vector< stride::ContactPool * > GetNearbyPools (stride::ContactType::Id id, const GeoGrid &geoGrid, const Location &start, double startRadius=10.0) const
Find contactpools in startRadius (in km) around start and, if none are found, double the radius and search again until the radius gets infinite.
bool MakeChoice (double fraction)
Convenience wrapper around m_rnManager.
Protected Attributes inherited from geopop::Populator
stride::util::RnMan & m_rn_man
RnManager used by populators.
std::shared_ptr< spdlog::logger > m_logger
Logger used by populators.
Detailed Description
Populate the workplaces.
Definition at line 30 of file WorkplacePopulator.h.
Constructor & Destructor Documentation
geopop::WorkplacePopulator::WorkplacePopulator (stride::util::RnMan & rn_manager, std::shared_ptr< spdlog::logger > logger = nullptr) explicit
Constructor.
Definition at line 36 of file WorkplacePopulator.cpp.
Member Function Documentation
void geopop::WorkplacePopulator::Apply (GeoGrid & geogrid, const GeoGridConfig & geoGridConfig) override virtual
Populates the workplaces in geogrid with persons.
Implements geopop::Populator.
Definition at line 43 of file WorkplacePopulator.cpp.
References AssignActive(), CalculateCommutingLocations(), CalculateFractionCommutingStudents(), CalculateNearbyWorkspaces(), CalculateWorkplacesInCity(), geopop::GeoGridConfig::input, m_assignedCommuting, m_assignedNotCommuting, m_assignedTo0, m_commutingLocations, m_currentLoc, m_disCommuting, m_distNonCommuting, m_fractionCommutingStudents, m_geoGridConfig, geopop::Populator::m_logger, m_nearByWorkplaces, m_workplacesInCity, geopop::Populator::MakeChoice(), geopop::GeoGridConfig::participation_college, and geopop::GeoGridConfig::particpation_workplace.
void geopop::WorkplacePopulator::CalculateWorkplacesInCity (GeoGrid & geogrid) private
Fills the m_workplacesInCity map.
Definition at line 150 of file WorkplacePopulator.cpp.
References stride::util::RnMan::GetUniformIntGenerator(), geopop::Populator::m_rn_man, and m_workplacesInCity.
Referenced by Apply().
void geopop::WorkplacePopulator::CalculateFractionCommutingStudents () private
Calculates m_fractionCommutingStudents.
Definition at line 139 of file WorkplacePopulator.cpp.
References geopop::GeoGridConfig::fraction_college_commuters, geopop::GeoGridConfig::fraction_workplace_commuters, geopop::GeoGridConfig::input, m_fractionCommutingStudents, m_geoGridConfig, geopop::GeoGridConfig::popcount_college, geopop::GeoGridConfig::popcount_workplace, and geopop::GeoGridConfig::popInfo.
Referenced by Apply().
void geopop::WorkplacePopulator::CalculateNearbyWorkspaces (GeoGrid & geogrid) private
Calculates the workplaces which are nearby to m_currentLoc.
Definition at line 164 of file WorkplacePopulator.cpp.
References geopop::Populator::GetNearbyPools(), stride::util::RnMan::GetUniformIntGenerator(), m_currentLoc, m_distNonCommuting, m_nearByWorkplaces, and geopop::Populator::m_rn_man.
Referenced by Apply().
void geopop::WorkplacePopulator::CalculateCommutingLocations () private
Calculates the workplaces to which persons from m_currentLoc may commute to.
Definition at line 116 of file WorkplacePopulator.cpp.
References AssertThrow, stride::util::RnMan::GetDiscreteGenerator(), m_commutingLocations, m_currentLoc, m_disCommuting, m_fractionCommutingStudents, geopop::Populator::m_logger, and geopop::Populator::m_rn_man.
Referenced by Apply().
void geopop::WorkplacePopulator::AssignActive (stride::Person * person) private
Assign a workplace to an active person.
Definition at line 97 of file WorkplacePopulator.cpp.
References geopop::GeoGridConfig::fraction_workplace_commuters, geopop::GeoGridConfig::input, m_assignedCommuting, m_assignedNotCommuting, m_commutingLocations, m_disCommuting, m_distNonCommuting, m_geoGridConfig, m_nearByWorkplaces, m_workplacesInCity, geopop::Populator::MakeChoice(), and stride::Person::SetPoolId().
Referenced by Apply().
Member Data Documentation
unsigned int geopop::WorkplacePopulator::m_assignedTo0 = 0 private
Number of persons assigned to no workplace.
Definition at line 56 of file WorkplacePopulator.h.
Referenced by Apply().
unsigned int geopop::WorkplacePopulator::m_assignedCommuting = 0 private
Number of persons assigned to workplace outside home location.
Definition at line 57 of file WorkplacePopulator.h.
Referenced by Apply(), and AssignActive().
unsigned int geopop::WorkplacePopulator::m_assignedNotCommuting = 0 private
Amount of persons assigned to workplace at the home location.
Definition at line 58 of file WorkplacePopulator.h.
Referenced by Apply(), and AssignActive().
std::shared_ptr<Location> geopop::WorkplacePopulator::m_currentLoc private
The location for which the workers currently are being assigned..
Definition at line 60 of file WorkplacePopulator.h.
Referenced by Apply(), CalculateCommutingLocations(), and CalculateNearbyWorkspaces().
GeoGridConfig geopop::WorkplacePopulator::m_geoGridConfig private
The GeoGridConfig used during populating.
Definition at line 61 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateFractionCommutingStudents().
std::unordered_map<Location*, std::pair<std::vector<stride::ContactPool*>, std::function<int()> > > geopop::WorkplacePopulator::m_workplacesInCity private
For each location store workplaces and a distribution fot random selection.
Definition at line 64 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateWorkplacesInCity().
double geopop::WorkplacePopulator::m_fractionCommutingStudents private
Fraction of the commuting people who are a student.
Definition at line 66 of file WorkplacePopulator.h.
Referenced by Apply(), CalculateCommutingLocations(), and CalculateFractionCommutingStudents().
std::vector<stride::ContactPool*> geopop::WorkplacePopulator::m_nearByWorkplaces private
Workplaces which are nearby to the m_currentLoc.
Definition at line 68 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateNearbyWorkspaces().
std::function<int()> geopop::WorkplacePopulator::m_distNonCommuting private
Distribution to choose from m_nearByWorkPlaces.
Definition at line 69 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateNearbyWorkspaces().
std::vector<Location*> geopop::WorkplacePopulator::m_commutingLocations private
Workplaces which persons from m_currentLoc may commute to.
Definition at line 71 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateCommutingLocations().
std::function<int()> geopop::WorkplacePopulator::m_disCommuting private
Distribution to choose from m_commutingLocations.
Definition at line 72 of file WorkplacePopulator.h.
Referenced by Apply(), AssignActive(), and CalculateCommutingLocations().
The documentation for this class was generated from the following files:
WorkplacePopulator.h
WorkplacePopulator.cpp