Stride Reference Manual: genpop.cpp File Reference
genpop.cpp File Reference
#include "gengeopop/Community.h"
#include "gengeopop/GenPopController.h"
#include "gengeopop/GeoGrid.h"
#include "gengeopop/GeoGridConfig.h"
#include "gengeopop/io/GeoGridProtoWriter.h"
#include "gengeopop/io/GeoGridWriterFactory.h"
#include "gengeopop/io/ReaderFactory.h"
#include "util/LogUtils.h"
#include "util/FileSys.h"
#include "util/RunConfigManager.h"
#include <boost/lexical_cast.hpp>
#include <boost/property_tree/ptree.hpp>
#include <omp.h>
#include <spdlog/common.h>
#include <spdlog/fmt/ostr.h>
#include <tclap/CmdLine.h>
#include <fstream>
#include <iostream>
#include <regex>
#include <string>
#include <utility>
#include <vector>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 47 of file genpop.cpp.
References gengeopop::GeoGridConfig::contactCenters, gengeopop::GeoGridConfig::contactPools, stride::util::RunConfigManager::Create(), stride::util::LogUtils::CreateCliLogger(), gengeopop::GeoGridWriterFactory::CreateWriter(), gengeopop::GeoGridConfig::generated, stride::util::FileSys::GetConfigDir(), stride::util::FileSys::ReadPtreeFile(), and stride::util::Tokenize().