Stride Reference Manual: stride::GeoPopBuilder Class Reference
stride::GeoPopBuilder Class Reference
Builds poulation of a geographic grid.
#include <GeoPopBuilder.h>
Public Member Functions
std::shared_ptr< Population > Build (std::shared_ptr< Population > pop) override
Generates a synthetic population.
Public Member Functions inherited from stride::AbstractPopBuilder
AbstractPopBuilder (const boost::property_tree::ptree &config, util::RnMan &rnMan, std::shared_ptr< spdlog::logger > strideLogger=nullptr)
Initializing constructor.
virtual ~AbstractPopBuilder ()=default
Private Member Functions
void GenCities (const std::shared_ptr< geopop::GeoGrid > &geoGrid, const geopop::GeoGridConfig &geoGridConfig, const std::string &citiesFileName, const std::string &commutingFileName)
Reads the data files.
void GenGeo (const std::shared_ptr< geopop::GeoGrid > &geoGrid, const geopop::GeoGridConfig &geoGridConfig)
Build and store the Geo part of the GeoGrid.
void GenPop (const std::shared_ptr< geopop::GeoGrid > &geoGrid, const geopop::GeoGridConfig &geoGridConfig)
Build and store the Pop part of the GeoGrid.
Private Attributes
unsigned int m_ccCounter = 1
The current number of ContactCenters, used to obtain an Id for a new contactCenter.
Additional Inherited Members
Protected Attributes inherited from stride::AbstractPopBuilder
const boost::property_tree::ptree & m_config
Configuration property tree.
util::RnMan & m_rn_man
Random number generation management.
std::shared_ptr< spdlog::logger > m_stride_logger
Detailed Description
Builds poulation of a geographic grid.
Definition at line 41 of file GeoPopBuilder.h.
Member Function Documentation
shared_ptr< Population > stride::GeoPopBuilder::Build (std::shared_ptr< Population > pop) override virtual
Generates a synthetic population.
Implements stride::AbstractPopBuilder.
Definition at line 54 of file GeoPopBuilder.cpp.
References geopop::GeoGridConfig::SetData().
Referenced by stride::GenPopController::Control(), and stride::Population::Create().
void stride::GeoPopBuilder::GenCities (const std::shared_ptr< geopop::GeoGrid > & geoGrid, const geopop::GeoGridConfig & geoGridConfig, const std::string & citiesFileName, const std::string & commutingFileName) private
Reads the data files.
Definition at line 105 of file GeoPopBuilder.cpp.
References geopop::ReaderFactory::CreateCitiesReader(), geopop::ReaderFactory::CreateCommutesReader(), geopop::GeoGridConfig::input, and geopop::GeoGridConfig::pop_size.
void stride::GeoPopBuilder::GenGeo (const std::shared_ptr< geopop::GeoGrid > & geoGrid, const geopop::GeoGridConfig & geoGridConfig) private
Build and store the Geo part of the GeoGrid.
Definition at line 125 of file GeoPopBuilder.cpp.
void stride::GeoPopBuilder::GenPop (const std::shared_ptr< geopop::GeoGrid > & geoGrid, const geopop::GeoGridConfig & geoGridConfig) private
Build and store the Pop part of the GeoGrid.
Definition at line 138 of file GeoPopBuilder.cpp.
Member Data Documentation
unsigned int stride::GeoPopBuilder::m_ccCounter = 1 private
The current number of ContactCenters, used to obtain an Id for a new contactCenter.
! 0 has special meaning (not assigned)!
Definition at line 64 of file GeoPopBuilder.h.
The documentation for this class was generated from the following files:
GeoPopBuilder.h
GeoPopBuilder.cpp