Stride Reference Manual: proto::GeoGrid Class Reference
proto::GeoGrid Class Reference
#include <geogrid.pb.h>
Public Types
typedef GeoGrid_Location Location
typedef GeoGrid_Person Person
Public Member Functions
GeoGrid ()
virtual ~GeoGrid ()
GeoGrid (const GeoGrid &from)
GeoGrid & operator= (const GeoGrid &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (GeoGrid *other)
GeoGrid * New () const final
GeoGrid * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const GeoGrid &from)
void MergeFrom (const GeoGrid &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic,::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int locations_size () const
void clear_locations ()
::proto::GeoGrid_Location * mutable_locations (int index)
::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location > * mutable_locations ()
const ::proto::GeoGrid_Location & locations (int index) const
::proto::GeoGrid_Location * add_locations ()
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location > & locations () const
int persons_size () const
void clear_persons ()
::proto::GeoGrid_Person * mutable_persons (int index)
::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Person > * mutable_persons ()
const ::proto::GeoGrid_Person & persons (int index) const
::proto::GeoGrid_Person * add_persons ()
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Person > & persons () const
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const GeoGrid & default_instance ()
static void InitAsDefaultInstance ()
static const GeoGrid * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages = 6
static const int kLocationsFieldNumber = 1
static const int kPersonsFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const final
void InternalSwap (GeoGrid *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::internal::HasBits< 1 > _has_bits_
mutable::google::protobuf::internal::CachedSize _cached_size_
::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location > locations_
::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Person > persons_
Friends
struct ::protobuf_geogrid_2eproto::TableStruct
void swap (GeoGrid &a, GeoGrid &b)
Detailed Description
Definition at line 1021 of file geogrid.pb.h.
Member Typedef Documentation
typedef GeoGrid_Location proto::GeoGrid::Location
Definition at line 1104 of file geogrid.pb.h.
typedef GeoGrid_Person proto::GeoGrid::Person
Definition at line 1105 of file geogrid.pb.h.
Constructor & Destructor Documentation
proto::GeoGrid::GeoGrid ()
virtual proto::GeoGrid::~GeoGrid () virtual
proto::GeoGrid::GeoGrid (const GeoGrid & from)
Member Function Documentation
GeoGrid& proto::GeoGrid::operator= (const GeoGrid & from) inline
Definition at line 1029 of file geogrid.pb.h.
References GetArenaNoVirtual().
const ::google::protobuf::UnknownFieldSet& proto::GeoGrid::unknown_fields () const inline
Definition at line 1048 of file geogrid.pb.h.
inline ::google::protobuf::UnknownFieldSet* proto::GeoGrid::mutable_unknown_fields () inline
Definition at line 1052 of file geogrid.pb.h.
static const ::google::protobuf::Descriptor* proto::GeoGrid::descriptor () static
static const GeoGrid& proto::GeoGrid::default_instance () static
static void proto::GeoGrid::InitAsDefaultInstance () static
static const GeoGrid* proto::GeoGrid::internal_default_instance () inline static
Definition at line 1061 of file geogrid.pb.h.
References proto::_GeoGrid_default_instance_.
void proto::GeoGrid::Swap (GeoGrid * other)
GeoGrid* proto::GeoGrid::New () const inline final
Definition at line 1072 of file geogrid.pb.h.
GeoGrid* proto::GeoGrid::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1074 of file geogrid.pb.h.
void proto::GeoGrid::CopyFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid::MergeFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid::CopyFrom (const GeoGrid & from)
void proto::GeoGrid::MergeFrom (const GeoGrid & from)
void proto::GeoGrid::Clear () final
bool proto::GeoGrid::IsInitialized () const final
size_t proto::GeoGrid::ByteSizeLong () const final
bool proto::GeoGrid::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
void proto::GeoGrid::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
::google::protobuf::uint8* proto::GeoGrid::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
int proto::GeoGrid::GetCachedSize () const inline final
Definition at line 1087 of file geogrid.pb.h.
void proto::GeoGrid::SharedCtor () private
void proto::GeoGrid::SharedDtor () private
void proto::GeoGrid::SetCachedSize (int size) const final private
void proto::GeoGrid::InternalSwap (GeoGrid * other) private
inline ::google::protobuf::Arena* proto::GeoGrid::GetArenaNoVirtual () const inline private
Definition at line 1096 of file geogrid.pb.h.
Referenced by operator=().
void* proto::GeoGrid::MaybeArenaPtr () const inline private
Definition at line 1097 of file geogrid.pb.h.
::google::protobuf::Metadata proto::GeoGrid::GetMetadata () const final
int proto::GeoGrid::locations_size () const inline
Definition at line 1744 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::Read().
void proto::GeoGrid::clear_locations () inline
Definition at line 1745 of file geogrid.pb.h.
proto::GeoGrid_Location * proto::GeoGrid::mutable_locations (int index) inline
Definition at line 1746 of file geogrid.pb.h.
google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location > * proto::GeoGrid::mutable_locations () inline
Definition at line 1751 of file geogrid.pb.h.
const ::proto::GeoGrid_Location & proto::GeoGrid::locations (int index) const inline
Definition at line 1756 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::Read().
proto::GeoGrid_Location * proto::GeoGrid::add_locations () inline
Definition at line 1761 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::Write().
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location > & proto::GeoGrid::locations () const inline
Definition at line 1766 of file geogrid.pb.h.
int proto::GeoGrid::persons_size () const inline
Definition at line 1773 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::Read().
void proto::GeoGrid::clear_persons () inline
Definition at line 1774 of file geogrid.pb.h.
proto::GeoGrid_Person * proto::GeoGrid::mutable_persons (int index) inline
Definition at line 1775 of file geogrid.pb.h.
google::protobuf::RepeatedPtrField<::proto::GeoGrid_Person > * proto::GeoGrid::mutable_persons () inline
Definition at line 1780 of file geogrid.pb.h.
const ::proto::GeoGrid_Person & proto::GeoGrid::persons (int index) const inline
Definition at line 1785 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoReader::Read().
proto::GeoGrid_Person * proto::GeoGrid::add_persons () inline
Definition at line 1790 of file geogrid.pb.h.
Referenced by gengeopop::GeoGridProtoWriter::Write().
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Person > & proto::GeoGrid::persons () const inline
Definition at line 1795 of file geogrid.pb.h.
Friends And Related Function Documentation
friend struct ::protobuf_geogrid_2eproto::TableStruct friend
Definition at line 1136 of file geogrid.pb.h.
void swap (GeoGrid & a, GeoGrid & b) friend
Definition at line 1068 of file geogrid.pb.h.
Member Data Documentation
constexpr int proto::GeoGrid::kIndexInFileMessages = 6 static
Definition at line 1065 of file geogrid.pb.h.
const int proto::GeoGrid::kLocationsFieldNumber = 1 static
Definition at line 1112 of file geogrid.pb.h.
const int proto::GeoGrid::kPersonsFieldNumber = 2 static
Definition at line 1122 of file geogrid.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::GeoGrid::_internal_metadata_ private
Definition at line 1131 of file geogrid.pb.h.
::google::protobuf::internal::HasBits<1> proto::GeoGrid::_has_bits_ private
Definition at line 1132 of file geogrid.pb.h.
mutable ::google::protobuf::internal::CachedSize proto::GeoGrid::_cached_size_ private
Definition at line 1133 of file geogrid.pb.h.
::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location> proto::GeoGrid::locations_ private
Definition at line 1134 of file geogrid.pb.h.
::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Person> proto::GeoGrid::persons_ private
Definition at line 1135 of file geogrid.pb.h.
The documentation for this class was generated from the following file:
geogrid.pb.h