Stride Reference Manual: stride::util::RnMan Class Reference
stride::util::RnMan Class Reference
#include <RnMan.h>
Public Member Functions
RnMan ()
Default constructor build empty manager.
RnMan (const RnInfo &info)
Initializes.
bool operator== (const RnMan &other)
Equality of states.
RnInfo GetInfo () const
Return the state of the random engines.
std::function< double()> GetUniform01Generator (unsigned int i=0U)
Return a generator for uniform doubles in [0, 1[ using i-th random stream.
std::function< int()> GetUniformIntGenerator (int a, int b, unsigned int i=0U)
Return a generator for uniform ints in [a, b[ (a < b) using i-th random stream.
std::function< int()> GetDiscreteGenerator (const std::vector< double > &weights, unsigned int i=0U)
Return generator for ints [0, n-1[ with non-negative weights p_j (i=0,..,n-1) using i-th random stream.
void Initialize (const RnInfo &info)
Initalize with data in Info.
bool IsEmpty () const
Is this een empty (i.e. non-initialized Rn)?
void Shuffle (std::vector< unsigned int > &indices, unsigned int i)
Random shuffle of vector of int indices using i-th random stream.
Private Attributes
std::shared_ptr< RnEngine > m_rn
Detailed Description
Definition at line 38 of file RnMan.h.
Constructor & Destructor Documentation
stride::util::RnMan::RnMan ()
Default constructor build empty manager.
Definition at line 64 of file RnMan.cpp.
stride::util::RnMan::RnMan (const RnInfo & info) explicit
Initializes.
Definition at line 66 of file RnMan.cpp.
Member Function Documentation
bool stride::util::RnMan::operator== (const RnMan & other)
Equality of states.
Definition at line 68 of file RnMan.cpp.
References m_rn.
RnInfo stride::util::RnMan::GetInfo () const
Return the state of the random engines.
Definition at line 70 of file RnMan.cpp.
References m_rn.
std::function< double()> stride::util::RnMan::GetUniform01Generator (unsigned int i = 0U)
Return a generator for uniform doubles in [0, 1[ using i-th random stream.
Definition at line 72 of file RnMan.cpp.
References m_rn.
Referenced by stride::PublicHealthAgency::PerformCaseFinding().
std::function< int()> stride::util::RnMan::GetUniformIntGenerator (int a, int b, unsigned int i = 0U)
Return a generator for uniform ints in [a, b[ (a < b) using i-th random stream.
Definition at line 77 of file RnMan.cpp.
References m_rn.
Referenced by geopop::PrimaryCommunityPopulator::Apply(), geopop::WorkplacePopulator::CalculateNearbyWorkspaces(), geopop::WorkplacePopulator::CalculateWorkplacesInCity(), stride::DiseaseSeeder::Seed(), and stride::SurveySeeder::Seed().
std::function< int()> stride::util::RnMan::GetDiscreteGenerator (const std::vector< double > & weights, unsigned int i = 0U)
Return generator for ints [0, n-1[ with non-negative weights p_j (i=0,..,n-1) using i-th random stream.
Definition at line 82 of file RnMan.cpp.
References m_rn.
Referenced by geopop::HouseholdGenerator::Apply(), geopop::WorkplacePopulator::CalculateCommutingLocations(), and geopop::Populator::MakeChoice().
void stride::util::RnMan::Initialize (const RnInfo & info)
Initalize with data in Info.
Definition at line 87 of file RnMan.cpp.
References m_rn.
Referenced by stride::ControlHelper::ControlHelper().
bool stride::util::RnMan::IsEmpty () const
Is this een empty (i.e. non-initialized Rn)?
Definition at line 92 of file RnMan.cpp.
References m_rn.
void stride::util::RnMan::Shuffle (std::vector< unsigned int > & indices, unsigned int i)
Random shuffle of vector of int indices using i-th random stream.
Definition at line 94 of file RnMan.cpp.
References m_rn.
Member Data Documentation
std::shared_ptr<RnEngine> stride::util::RnMan::m_rn private
Definition at line 72 of file RnMan.h.
Referenced by GetDiscreteGenerator(), GetInfo(), GetUniform01Generator(), GetUniformIntGenerator(), Initialize(), IsEmpty(), operator==(), and Shuffle().
The documentation for this class was generated from the following files:
RnMan.h
RnMan.cpp