Stride Reference Manual: proto Namespace Reference
proto Namespace Reference
Classes
class GeoGrid
class GeoGrid_Location
class GeoGrid_Location_Commute
class GeoGrid_Location_ContactCenter
class GeoGrid_Location_ContactCenter_ContactPool
class GeoGrid_Location_Coordinate
class GeoGrid_Person
Enumerations
enum GeoGrid_Location_ContactCenter_Type {
GeoGrid_Location_ContactCenter_Type_K12School = 0, GeoGrid_Location_ContactCenter_Type_PrimaryCommunity = 1, GeoGrid_Location_ContactCenter_Type_SecondaryCommunity = 2, GeoGrid_Location_ContactCenter_Type_College = 3,
GeoGrid_Location_ContactCenter_Type_Household = 4, GeoGrid_Location_ContactCenter_Type_Workplace = 5, GeoGrid_Location_ContactCenter_Type_GeoGrid_Location_ContactCenter_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(), GeoGrid_Location_ContactCenter_Type_GeoGrid_Location_ContactCenter_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
}
Functions
bool GeoGrid_Location_ContactCenter_Type_IsValid (int value)
const ::google::protobuf::EnumDescriptor * GeoGrid_Location_ContactCenter_Type_descriptor ()
const ::std::string & GeoGrid_Location_ContactCenter_Type_Name (GeoGrid_Location_ContactCenter_Type value)
bool GeoGrid_Location_ContactCenter_Type_Parse (const ::std::string &name, GeoGrid_Location_ContactCenter_Type *value)
Variables
GeoGridDefaultTypeInternal _GeoGrid_default_instance_
GeoGrid_LocationDefaultTypeInternal _GeoGrid_Location_default_instance_
GeoGrid_Location_CommuteDefaultTypeInternal _GeoGrid_Location_Commute_default_instance_
GeoGrid_Location_ContactCenterDefaultTypeInternal _GeoGrid_Location_ContactCenter_default_instance_
GeoGrid_Location_ContactCenter_ContactPoolDefaultTypeInternal _GeoGrid_Location_ContactCenter_ContactPool_default_instance_
GeoGrid_Location_CoordinateDefaultTypeInternal _GeoGrid_Location_Coordinate_default_instance_
GeoGrid_PersonDefaultTypeInternal _GeoGrid_Person_default_instance_
const GeoGrid_Location_ContactCenter_Type GeoGrid_Location_ContactCenter_Type_Type_MIN = GeoGrid_Location_ContactCenter_Type_K12School
const GeoGrid_Location_ContactCenter_Type GeoGrid_Location_ContactCenter_Type_Type_MAX = GeoGrid_Location_ContactCenter_Type_Workplace
const int GeoGrid_Location_ContactCenter_Type_Type_ARRAYSIZE = GeoGrid_Location_ContactCenter_Type_Type_MAX + 1
Enumeration Type Documentation
enum proto::GeoGrid_Location_ContactCenter_Type
Enumerator
GeoGrid_Location_ContactCenter_Type_K12School
GeoGrid_Location_ContactCenter_Type_PrimaryCommunity
GeoGrid_Location_ContactCenter_Type_SecondaryCommunity
GeoGrid_Location_ContactCenter_Type_College
GeoGrid_Location_ContactCenter_Type_Household
GeoGrid_Location_ContactCenter_Type_Workplace
GeoGrid_Location_ContactCenter_Type_GeoGrid_Location_ContactCenter_Type_INT_MIN_SENTINEL_DO_NOT_USE_
GeoGrid_Location_ContactCenter_Type_GeoGrid_Location_ContactCenter_Type_INT_MAX_SENTINEL_DO_NOT_USE_
Definition at line 88 of file geogrid.pb.h.
Function Documentation
bool proto::GeoGrid_Location_ContactCenter_Type_IsValid (int value)
Referenced by proto::GeoGrid_Location_ContactCenter::Type_IsValid().
const ::google::protobuf::EnumDescriptor* proto::GeoGrid_Location_ContactCenter_Type_descriptor ()
Referenced by GeoGrid_Location_ContactCenter_Type_Name(), GeoGrid_Location_ContactCenter_Type_Parse(), google::protobuf::GetEnumDescriptor< ::proto::GeoGrid_Location_ContactCenter_Type >(), and proto::GeoGrid_Location_ContactCenter::Type_descriptor().
const ::std::string& proto::GeoGrid_Location_ContactCenter_Type_Name (GeoGrid_Location_ContactCenter_Type value) inline
Definition at line 104 of file geogrid.pb.h.
References GeoGrid_Location_ContactCenter_Type_descriptor().
Referenced by proto::GeoGrid_Location_ContactCenter::Type_Name().
bool proto::GeoGrid_Location_ContactCenter_Type_Parse (const ::std::string & name, GeoGrid_Location_ContactCenter_Type * value) inline
Definition at line 108 of file geogrid.pb.h.
References GeoGrid_Location_ContactCenter_Type_descriptor().
Referenced by proto::GeoGrid_Location_ContactCenter::Type_Parse().
Variable Documentation
GeoGridDefaultTypeInternal proto::_GeoGrid_default_instance_
Referenced by proto::GeoGrid::internal_default_instance().
GeoGrid_LocationDefaultTypeInternal proto::_GeoGrid_Location_default_instance_
Referenced by proto::GeoGrid_Location::internal_default_instance().
GeoGrid_Location_CommuteDefaultTypeInternal proto::_GeoGrid_Location_Commute_default_instance_
Referenced by proto::GeoGrid_Location_Commute::internal_default_instance().
GeoGrid_Location_ContactCenterDefaultTypeInternal proto::_GeoGrid_Location_ContactCenter_default_instance_
Referenced by proto::GeoGrid_Location_ContactCenter::internal_default_instance().
GeoGrid_Location_ContactCenter_ContactPoolDefaultTypeInternal proto::_GeoGrid_Location_ContactCenter_ContactPool_default_instance_
Referenced by proto::GeoGrid_Location_ContactCenter_ContactPool::internal_default_instance().
GeoGrid_Location_CoordinateDefaultTypeInternal proto::_GeoGrid_Location_Coordinate_default_instance_
Referenced by proto::GeoGrid_Location::coordinate(), and proto::GeoGrid_Location_Coordinate::internal_default_instance().
GeoGrid_PersonDefaultTypeInternal proto::_GeoGrid_Person_default_instance_
Referenced by proto::GeoGrid_Person::internal_default_instance().
const GeoGrid_Location_ContactCenter_Type proto::GeoGrid_Location_ContactCenter_Type_Type_MIN = GeoGrid_Location_ContactCenter_Type_K12School
Definition at line 99 of file geogrid.pb.h.
const GeoGrid_Location_ContactCenter_Type proto::GeoGrid_Location_ContactCenter_Type_Type_MAX = GeoGrid_Location_ContactCenter_Type_Workplace
Definition at line 100 of file geogrid.pb.h.
const int proto::GeoGrid_Location_ContactCenter_Type_Type_ARRAYSIZE = GeoGrid_Location_ContactCenter_Type_Type_MAX + 1
Definition at line 101 of file geogrid.pb.h.