Stride Reference Manual: stride Namespace Reference
stride Namespace Reference
Main namespace for the project.
Namespaces
ContactLogMode
Enum specifiying the level of logging required:
ContactPoolType
Namespace to manage types of ContactPool.
output
Utilities for the output files.
RNEngineType
Namespace to manage types of random engines.
sim_event
Namespace to manage events signalled by the SimRunner.
util
Utilities for the project.
viewers
Namespace for MVC-viewers that may be registered with SimRunner.
Classes
class AbstractPopBuilder
Base Class for PopBuilders.
class AgeContactProfile
Contact rates as a function of age.
class Belief
Base class for all belief policies.
class BeliefSeeder
Seeds the population with Health data.
class Calendar
Class that keeps track of the 'state' of simulated world.
class CliController
Controls a simulation run initiated with the command line interface (cli).
class ContactHandler
Processes the contacts between persons and determines whether transmission occurs.
class ContactPool
Represents a group of Persons that potentially have contacts.
class ControlHelper
Controls a simulation run initiated with the command line interface (cli).
class DaysOffAll
No days off work or school.
class DaysOffInterface
Interface definition.
class DaysOffNone
No days off work or school.
class DaysOffSchool
Schools closed.
class DaysOffStandard
Standard situation for days off from work and school.
class DefaultPopBuilder
Initializes Population objects.
class DiseaseSeeder
Seeds population w.r.t immunity (natural immunity, vaccination, ...) and infection.
class GenPopBuilder
Initializes Population objects.
class HBM
class Health
Holds a person's health data.
class HealthSeeder
Seeds the population with Health data.
class Imitation
class Immunizer
Deals with immunization strategies.
class ImportPopBuilder
Initializes Population objects.
class Infector
Actual contacts and transmission in contactpool (primary template).
class Infector< LL, TIC, NoLocalInformation, true >
Time-optimized version (For NoLocalInformation && (None || Transmission logging)).
class InfectorMap
Simulator can time step and reveal some of the key data.
class LocalDiscussion
Class for local information policy 'LocalDiscussion'.
class NoBehaviour
NoBehaviour means that whatever beliefs a person holds, or whatever information they gather, will not result in a change in their behaviour.
class NoBelief
No beliefs w.r.t vaccination.
class NoGlobalInformation
No global information about the disease, number of infected,...
class NoLocalInformation
No information about beliefs or health status is exchanged upon contact.
class Person
Store and handle person data.
class Population
Container for persons in population.
class Sim
Simulator can time step and reveal some of the key data.
class SimBuilder
Builds a simulator based a configuration property tree.
class SimRunner
The simulation runner drive simulator throufgh time steps.
class StanController
Runs a simulation multiple times, with different random engine seeds.
class SurveySeeder
Seeds the population with survey participants.
class Threshold
class TransmissionProfile
Transmission rates from disease data.
class Vaccination
Vaccination beliefs and information have an influence on the vaccination behaviour of an individual.
Typedefs
using AgeContactProfiles = ContactPoolType::IdSubscriptArray< AgeContactProfile >
typedef void(InfectorExec) (ContactPool &pool, const AgeContactProfile &profile, const TransmissionProfile &trans_profile, ContactHandler &c_handler, unsigned short int sim_day, std::shared_ptr< spdlog::logger > c_logger)
For use in the InfectorMap and Sim.
using ContactPoolSys = ContactPoolType::IdSubscriptArray< util::SegmentedVector< ContactPool >>
ContactPoolSys contains for each of the type of pools (household, school, ...) a vector of with all of the contcatpools of the type.
Enumerations
enum VariableState { VariableState::Low = 0U, VariableState::High = 1U }
enum HealthStatus : unsigned short int {
HealthStatus::Susceptible = 0U, HealthStatus::Exposed = 1U, HealthStatus::Infectious = 2U, HealthStatus::Symptomatic = 3U,
HealthStatus::InfectiousAndSymptomatic = 4U, HealthStatus::Recovered = 5U, HealthStatus::Immune = 6U
}
Enumerate the various health states with respect to the infection.
Functions
date::year_month_day ConvertFromString (const std::string &day)
constexpr unsigned int MaximumAge ()
Maximum age for Persons.
constexpr unsigned int MinAdultAge ()
Maximum age for Person's.
unsigned int EffectiveAge (unsigned int age)
Effective age (topping of at maximum).
Detailed Description
Main namespace for the project.
Typedef Documentation
using stride::AgeContactProfiles = typedef ContactPoolType::IdSubscriptArray<AgeContactProfile>
Definition at line 29 of file AgeContactProfiles.h.
typedef void(stride::InfectorExec) (ContactPool &pool, const AgeContactProfile &profile, const TransmissionProfile &trans_profile, ContactHandler &c_handler, unsigned short int sim_day, std::shared_ptr< spdlog::logger > c_logger)
For use in the InfectorMap and Sim.
Definition at line 33 of file InfectorExec.h.
using stride::ContactPoolSys = typedef ContactPoolType::IdSubscriptArray<util::SegmentedVector<ContactPool>>
ContactPoolSys contains for each of the type of pools (household, school, ...) a vector of with all of the contcatpools of the type.
The ContactPoolSys container is an std::array extended to be subscriptable with the enum class of the pool types.
Definition at line 34 of file ContactPoolSys.h.
Enumeration Type Documentation
enum stride::VariableState strong
Enumerator
Low
High
Definition at line 36 of file HBM.h.
enum stride::HealthStatus : unsigned short int strong
Enumerate the various health states with respect to the infection.
Enumerator
Susceptible
Exposed
Infectious
Symptomatic
InfectiousAndSymptomatic
Recovered
Immune
Definition at line 26 of file Health.h.
Function Documentation
date::year_month_day stride::ConvertFromString (const std::string & day)
Definition at line 96 of file Calendar.cpp.
Referenced by stride::Calendar::Calendar(), and stride::Calendar::InitializeHolidays().
constexpr unsigned int stride::MaximumAge () inline
Maximum age for Persons.
Definition at line 26 of file Age.h.
Referenced by EffectiveAge().
constexpr unsigned int stride::MinAdultAge () inline
Maximum age for Person's.
Definition at line 29 of file Age.h.
Referenced by stride::Person::Update().
unsigned int stride::EffectiveAge (unsigned int age) inline
Effective age (topping of at maximum).
Definition at line 32 of file Age.h.
References MaximumAge().