Stride Reference Manual: gengeopop::Location Class Reference
gengeopop::Location Class Reference
A location for use within the GeoGrid.
#include <Location.h>
Public Types
using iterator = std::vector< std::shared_ptr< ContactCenter >>::iterator
To iterate over container with ContactCenters at this Location.
Public Member Functions
Location (unsigned int id, unsigned int province, Coordinate coordinate=Coordinate(0.0, 0.0), std::string name="")
Parametrized constructor without population count.
Location (unsigned int id, unsigned int province, unsigned int popCount, Coordinate coordinate=Coordinate(0.0, 0.0), std::string name="")
Parametrized constructor with population count.
bool operator== (const Location &other) const
Perform a full comparison with the other location.
template<typename T >
void AddContactCenter (std::shared_ptr< T > contactCenter)
Add a ContactCenter.
void AddIncomingCommutingLocation (std::shared_ptr< Location > otherLocation, double fraction)
Adds a Location and a proportion to the incoming commute vector.
void AddOutgoingCommutingLocation (std::shared_ptr< Location > otherLocation, double fraction)
Adds a Location and a fraction to the outgoing commute vector.
const Coordinate & GetCoordinate () const
Gets the Coordinate of this Location.
const std::vector< std::shared_ptr< ContactCenter > > & GetContactCenters () const
Gets all ContactCenters at this location.
template<typename T >
std::vector< std::shared_ptr< ContactCenter > > GetContactCentersOfType ()
Gets the Contact Centers of a specific type (Household, Workplace, ...).
const std::vector< std::pair< Location *, double > > & GetIncomingCommuningCities () const
Gets a vector with the outgoing cities which people are commuting to + the proportion.
unsigned int GetID () const
Gets ID of this Location.
int GetIncomingCommuterCount (double fractionCommuters) const
Calculates number of incomming commuters, given the fraction of the population that commutes.
double GetInfectedCount () const
Gets the amount of people infected in the contactpools of this location.
std::string GetName () const
Gets the name.
const std::vector< std::pair< Location *, double > > & GetOutgoingCommutingCities () const
Returns outgoing cities which people are commuting to + the proportion.
int GetOutgoingCommuterCount (double fractionCommuters) const
Calculates number of outgoing commuters, given the fraction of the population that commutes.
unsigned int GetPopCount () const
Gets the absolute population.
unsigned int GetProvince () const
Gets the province.
double GetRelativePopulationSize () const
Gets the relative population.
void SetCoordinate (const Coordinate &coordinate)
Sets the Coordinate of this Socation.
void SetPopCount (unsigned int totalPopCount)
Calculates this location's population count using its relative population and the total population count.
void SetRelativePopulation (double relativePopulation)
Sets the relative population, which will be later used by.
iterator begin ()
Gets iterator to the first ContacCenter at this Location.
iterator end ()
Gets iterator to the end of the ContactCenters at this Location.
Private Attributes
unsigned int m_id = 0
Id.
std::string m_name
Name.
unsigned int m_province
Province id.
unsigned int m_pop_count
Population count (number of individuals) at this Location.
double m_pop_fraction
Fraction of whole population at thois Location.
Coordinate m_coordinate
Coordinate of the Location.
std::vector< std::shared_ptr< ContactCenter > > m_CC
std::vector< std::pair< Location *, double > > m_inCommuteLocations
Incomming commutes stored as pair of Location and fraction of population at that Location.
std::vector< std::pair< Location *, double > > m_outCommuteLocations
Stores the contact centers indexed by their type.
std::unordered_map< std::type_index, std::vector< std::shared_ptr< ContactCenter > > > m_CC_OfType
Detailed Description
A location for use within the GeoGrid.
Container for ContactCenters.
Definition at line 36 of file Location.h.
Member Typedef Documentation
using gengeopop::Location::iterator = std::vector<std::shared_ptr<ContactCenter>>::iterator
To iterate over container with ContactCenters at this Location.
Definition at line 120 of file Location.h.
Constructor & Destructor Documentation
gengeopop::Location::Location (unsigned int id, unsigned int province, Coordinate coordinate = Coordinate(0.0, 0.0), std::string name = "")
Parametrized constructor without population count.
Definition at line 26 of file Location.cpp.
gengeopop::Location::Location (unsigned int id, unsigned int province, unsigned int popCount, Coordinate coordinate = Coordinate(0.0, 0.0), std::string name = "")
Parametrized constructor with population count.
Definition at line 32 of file Location.cpp.
References m_pop_count.
Member Function Documentation
bool gengeopop::Location::operator== (const Location & other) const
Perform a full comparison with the other location.
Definition at line 38 of file Location.cpp.
References GetContactCenters(), GetCoordinate(), GetID(), GetIncomingCommuningCities(), GetName(), GetOutgoingCommutingCities(), GetPopCount(), and GetProvince().
template<typename T > void gengeopop::Location::AddContactCenter (std::shared_ptr< T > contactCenter) inline
Add a ContactCenter.
Definition at line 52 of file Location.h.
References AddIncomingCommutingLocation(), AddOutgoingCommutingLocation(), m_CC, and m_CC_OfType.
void gengeopop::Location::AddIncomingCommutingLocation (std::shared_ptr< Location > otherLocation, double fraction)
Adds a Location and a proportion to the incoming commute vector.
I.e. fraction of commuting population at otherLocation commuting to this Location.
Definition at line 49 of file Location.cpp.
References m_inCommuteLocations.
Referenced by AddContactCenter().
void gengeopop::Location::AddOutgoingCommutingLocation (std::shared_ptr< Location > otherLocation, double fraction)
Adds a Location and a fraction to the outgoing commute vector.
Definition at line 54 of file Location.cpp.
References m_outCommuteLocations.
Referenced by AddContactCenter().
const Coordinate& gengeopop::Location::GetCoordinate () const inline
Gets the Coordinate of this Location.
Definition at line 67 of file Location.h.
References m_coordinate.
Referenced by operator==().
const std::vector<std::shared_ptr<ContactCenter> >& gengeopop::Location::GetContactCenters () const inline
Gets all ContactCenters at this location.
Definition at line 70 of file Location.h.
References m_CC.
Referenced by operator==().
template<typename T > std::vector<std::shared_ptr<ContactCenter> > gengeopop::Location::GetContactCentersOfType () inline
Gets the Contact Centers of a specific type (Household, Workplace, ...).
Definition at line 74 of file Location.h.
References GetIncomingCommuningCities(), and m_CC_OfType.
const vector< pair< Location *, double > > & gengeopop::Location::GetIncomingCommuningCities () const
Gets a vector with the outgoing cities which people are commuting to + the proportion.
Definition at line 59 of file Location.cpp.
References m_inCommuteLocations.
Referenced by GetContactCentersOfType(), and operator==().
unsigned int gengeopop::Location::GetID () const inline
Gets ID of this Location.
Definition at line 83 of file Location.h.
References GetIncomingCommuterCount(), GetInfectedCount(), and m_id.
Referenced by operator==().
int gengeopop::Location::GetIncomingCommuterCount (double fractionCommuters) const
Calculates number of incomming commuters, given the fraction of the population that commutes.
Definition at line 61 of file Location.cpp.
References m_inCommuteLocations.
Referenced by GetID().
double gengeopop::Location::GetInfectedCount () const
Gets the amount of people infected in the contactpools of this location.
Definition at line 71 of file Location.cpp.
References m_CC.
Referenced by GetID().
std::string gengeopop::Location::GetName () const inline
Gets the name.
Definition at line 92 of file Location.h.
References GetOutgoingCommuterCount(), GetOutgoingCommutingCities(), and m_name.
Referenced by operator==().
const vector< pair< Location *, double > > & gengeopop::Location::GetOutgoingCommutingCities () const
Returns outgoing cities which people are commuting to + the proportion.
Definition at line 83 of file Location.cpp.
References m_outCommuteLocations.
Referenced by GetName(), and operator==().
int gengeopop::Location::GetOutgoingCommuterCount (double fractionCommuters) const
Calculates number of outgoing commuters, given the fraction of the population that commutes.
Definition at line 85 of file Location.cpp.
References m_outCommuteLocations, and m_pop_count.
Referenced by GetName().
unsigned int gengeopop::Location::GetPopCount () const inline
Gets the absolute population.
Definition at line 101 of file Location.h.
References m_pop_count.
Referenced by operator==().
unsigned int gengeopop::Location::GetProvince () const inline
Gets the province.
Definition at line 104 of file Location.h.
References GetRelativePopulationSize(), and m_province.
Referenced by operator==().
double gengeopop::Location::GetRelativePopulationSize () const
Gets the relative population.
Definition at line 95 of file Location.cpp.
References m_pop_fraction.
Referenced by GetProvince().
void gengeopop::Location::SetCoordinate (const Coordinate & coordinate) inline
Sets the Coordinate of this Socation.
Definition at line 110 of file Location.h.
References m_coordinate, SetPopCount(), and SetRelativePopulation().
void gengeopop::Location::SetPopCount (unsigned int totalPopCount)
Calculates this location's population count using its relative population and the total population count.
Definition at line 97 of file Location.cpp.
References m_pop_count, and m_pop_fraction.
Referenced by SetCoordinate().
void gengeopop::Location::SetRelativePopulation (double relativePopulation)
Sets the relative population, which will be later used by.
See also
CalculatePopulation.
Definition at line 101 of file Location.cpp.
References m_pop_fraction.
Referenced by SetCoordinate().
iterator gengeopop::Location::begin () inline
Gets iterator to the first ContacCenter at this Location.
Definition at line 123 of file Location.h.
References m_CC.
iterator gengeopop::Location::end () inline
Gets iterator to the end of the ContactCenters at this Location.
Definition at line 126 of file Location.h.
References m_CC.
Member Data Documentation
unsigned int gengeopop::Location::m_id = 0 private
Id.
Definition at line 129 of file Location.h.
Referenced by GetID().
std::string gengeopop::Location::m_name private
Name.
Definition at line 130 of file Location.h.
Referenced by GetName().
unsigned int gengeopop::Location::m_province private
Province id.
Definition at line 131 of file Location.h.
Referenced by GetProvince().
unsigned int gengeopop::Location::m_pop_count private
Population count (number of individuals) at this Location.
Definition at line 132 of file Location.h.
Referenced by GetOutgoingCommuterCount(), GetPopCount(), Location(), and SetPopCount().
double gengeopop::Location::m_pop_fraction private
Fraction of whole population at thois Location.
Definition at line 133 of file Location.h.
Referenced by GetRelativePopulationSize(), SetPopCount(), and SetRelativePopulation().
Coordinate gengeopop::Location::m_coordinate private
Coordinate of the Location.
All contactCenters at this Location.
Definition at line 134 of file Location.h.
Referenced by GetCoordinate(), and SetCoordinate().
std::vector<std::shared_ptr<ContactCenter> > gengeopop::Location::m_CC private
Definition at line 137 of file Location.h.
Referenced by AddContactCenter(), begin(), end(), GetContactCenters(), and GetInfectedCount().
std::vector<std::pair<Location*, double> > gengeopop::Location::m_inCommuteLocations private
Incomming commutes stored as pair of Location and fraction of population at that Location.
Outgoing commutes stored as pair of Location and fraction of population to this this Location.
Definition at line 140 of file Location.h.
Referenced by AddIncomingCommutingLocation(), GetIncomingCommuningCities(), and GetIncomingCommuterCount().
std::vector<std::pair<Location*, double> > gengeopop::Location::m_outCommuteLocations private
Stores the contact centers indexed by their type.
Definition at line 143 of file Location.h.
Referenced by AddOutgoingCommutingLocation(), GetOutgoingCommuterCount(), and GetOutgoingCommutingCities().
std::unordered_map<std::type_index, std::vector<std::shared_ptr<ContactCenter> > > gengeopop::Location::m_CC_OfType private
Definition at line 146 of file Location.h.
Referenced by AddContactCenter(), and GetContactCentersOfType().
The documentation for this class was generated from the following files:
Location.h
Location.cpp