Stride Reference Manual: stride::PublicHealthAgency Class Reference
stride::PublicHealthAgency Class Reference
#include <PublicHealthAgency.h>
Public Member Functions
PublicHealthAgency ()
Constructs uni-initialized object.
void Exec (std::shared_ptr< Population > pop, util::RnMan &rnManager, unsigned short int sim_day)
Execute.
void Initialize (double detection_probability)
Initialize.
Private Member Functions
void PerformCaseFinding (std::shared_ptr< Population > pop, util::RnMan &rnMan, unsigned short int simDay)
Public Health Strategy: look for symptomatic cases and vaccinate their household.
Private Attributes
double m_detection_probability
Detection probability of symptomatic cases.
Detailed Description
Definition at line 28 of file PublicHealthAgency.h.
Constructor & Destructor Documentation
stride::PublicHealthAgency::PublicHealthAgency () inline explicit
Constructs uni-initialized object.
Definition at line 32 of file PublicHealthAgency.h.
References Exec(), Initialize(), and PerformCaseFinding().
Member Function Documentation
void stride::PublicHealthAgency::Exec (std::shared_ptr< Population > pop, util::RnMan & rnManager, unsigned short int sim_day)
Execute.
Definition at line 34 of file PublicHealthAgency.cpp.
Referenced by PublicHealthAgency(), and stride::Sim::TimeStep().
void stride::PublicHealthAgency::Initialize (double detection_probability)
Initialize.
Definition at line 39 of file PublicHealthAgency.cpp.
Referenced by PublicHealthAgency().
void stride::PublicHealthAgency::PerformCaseFinding (std::shared_ptr< Population > pop, util::RnMan & rnMan, unsigned short int simDay) private
Public Health Strategy: look for symptomatic cases and vaccinate their household.
To allow iteration over pool types for the PublicHealthAgency.
Definition at line 41 of file PublicHealthAgency.cpp.
References stride::util::RnMan::GetUniform01Generator(), and stride::ContactLogMode::ToString().
Referenced by PublicHealthAgency().
Member Data Documentation
double stride::PublicHealthAgency::m_detection_probability private
Detection probability of symptomatic cases.
Definition at line 44 of file PublicHealthAgency.h.
The documentation for this class was generated from the following files:
PublicHealthAgency.h
PublicHealthAgency.cpp