Stride Reference Manual: gengeopop::Location Class Reference
gengeopop::Location Class Reference
A location for use within the GeoGrid Contains useful information, both spatial and administrative.
#include <Location.h>
Public Types
using iterator = std::vector< std::shared_ptr< ContactCenter >>::iterator
Public Member Functions
Location (unsigned int id, unsigned int province, Coordinate coordinate=Coordinate(0.0, 0.0), std::string name="")
Location (unsigned int id, unsigned int province, unsigned int population, Coordinate coordinate=Coordinate(0.0, 0.0), std::string name="")
bool operator== (const Location &other) const
Perform a full compare of the given locations.
template<typename T >
void AddContactCenter (std::shared_ptr< T > contactCenter)
Add a ContactCenter.
template<typename T >
std::vector< std::shared_ptr< ContactCenter > > GetContactCentersOfType ()
Gets the Contact Centers of a specific type T.
std::string GetName () const
Gets the name.
unsigned int GetProvince () const
Gets the province.
unsigned int GetID () const
Gets the ID.
unsigned int GetPopulation () const
Gets the absolute population.
unsigned int GetSimulationPopulation () const
Gets the population amount used in the simulation.
double GetInfectedRatio () const
Gets the ratio of infected persons in all contactPools of this location.
double GetInfectedCount () const
Gets the amount of people infected in the contactpools of this location.
void CalculatePopulation (unsigned int totalPopulation)
Given the total population calculates this location's population using the relative population of this location.
void SetRelativePopulation (double relativePopulation)
Sets the relative population, which will be later used by.
double GetRelativePopulationSize () const
Gets the relative population.
const std::vector< std::pair< Location *, double > > & GetIncomingCommuningCities () const
Gets a vector with the outgoing cities which people are commuting to + the proportion.
void AddIncomingCommutingLocation (std::shared_ptr< Location > location, double proportion)
Adds a Location and a proportion to the incoming commutng vector I.e.
const std::vector< std::pair< Location *, double > > & GetOutgoingCommuningCities () const
void AddOutgoingCommutingLocation (std::shared_ptr< Location > location, double proportion)
Adds a Location and a proportion to the incoming commuting vector.
int OutGoingCommutingPeople (double fractionOfPopulationCommuting) const
Gets the absolute amount of poeple leaving from this location.
int IncomingCommutingPeople (double fractionOfPopulationCommuting) const
Gets the absolute amount of people going to this location.
const Coordinate & GetCoordinate () const
Gets the Coordinate of this location.
void SetCoordinate (const Coordinate &coordinate)
const std::vector< std::shared_ptr< ContactCenter > > & GetContactCenters () const
Gets all contact centers at this location.
iterator begin ()
Gets iterator to the first location.
iterator end ()
Gets iterator to the end of the locations.
Private Attributes
unsigned int m_id = 0
Id.
std::string m_name
Name.
unsigned int m_province
Province id.
unsigned int m_population
The absolute population.
double m_relativePopulation
The relative population (relative against whole population)
Coordinate m_coordinate
Coordinate.
std::vector< std::shared_ptr< ContactCenter > > m_contactCenters
All contactCenters.
std::vector< std::pair< Location *, double > > m_incomingCommutingLocations
Incomming commutes stored as pair of location and proportion relative to the given location.
std::vector< std::pair< Location *, double > > m_outgoingCommutingLocations
std::unordered_map< std::type_index, std::vector< std::shared_ptr< ContactCenter > > > m_contactCenterByType
Stores the contact centers indexed by their type.
Detailed Description
A location for use within the GeoGrid Contains useful information, both spatial and administrative.
Definition at line 38 of file Location.h.
Member Typedef Documentation
using gengeopop::Location::iterator = std::vector<std::shared_ptr<ContactCenter>>::iterator
Definition at line 125 of file Location.h.
Constructor & Destructor Documentation
gengeopop::Location::Location (unsigned int id, unsigned int province, Coordinate coordinate = Coordinate(0.0, 0.0), std::string name = "")
Definition at line 23 of file Location.cpp.
gengeopop::Location::Location (unsigned int id, unsigned int province, unsigned int population, Coordinate coordinate = Coordinate(0.0, 0.0), std::string name = "")
Definition at line 30 of file Location.cpp.
References m_population.
Member Function Documentation
bool gengeopop::Location::operator== (const Location & other) const
Perform a full compare of the given locations.
Definition at line 141 of file Location.cpp.
References GetContactCenters(), GetCoordinate(), GetID(), GetIncomingCommuningCities(), GetName(), GetOutgoingCommuningCities(), GetPopulation(), and GetProvince().
template<typename T > void gengeopop::Location::AddContactCenter (std::shared_ptr< T > contactCenter) inline
Add a ContactCenter.
Definition at line 53 of file Location.h.
References m_contactCenterByType, and m_contactCenters.
template<typename T > std::vector<std::shared_ptr<ContactCenter> > gengeopop::Location::GetContactCentersOfType () inline
Gets the Contact Centers of a specific type T.
Definition at line 61 of file Location.h.
References AddIncomingCommutingLocation(), AddOutgoingCommutingLocation(), CalculatePopulation(), GetContactCenters(), GetCoordinate(), GetID(), GetIncomingCommuningCities(), GetInfectedCount(), GetInfectedRatio(), GetName(), GetOutgoingCommuningCities(), GetPopulation(), GetProvince(), GetRelativePopulationSize(), GetSimulationPopulation(), IncomingCommutingPeople(), m_contactCenterByType, OutGoingCommutingPeople(), SetCoordinate(), and SetRelativePopulation().
std::string gengeopop::Location::GetName () const
Gets the name.
Definition at line 37 of file Location.cpp.
References m_name.
Referenced by GetContactCentersOfType(), and operator==().
unsigned int gengeopop::Location::GetProvince () const
Gets the province.
Definition at line 39 of file Location.cpp.
References m_province.
Referenced by GetContactCentersOfType(), and operator==().
unsigned int gengeopop::Location::GetID () const
Gets the ID.
Definition at line 41 of file Location.cpp.
References m_id.
Referenced by GetContactCentersOfType(), and operator==().
unsigned int gengeopop::Location::GetPopulation () const
Gets the absolute population.
Definition at line 43 of file Location.cpp.
References m_population.
Referenced by GetContactCentersOfType(), GetInfectedRatio(), and operator==().
unsigned int gengeopop::Location::GetSimulationPopulation () const
Gets the population amount used in the simulation.
Definition at line 77 of file Location.cpp.
References m_contactCenters.
Referenced by GetContactCentersOfType().
double gengeopop::Location::GetInfectedRatio () const
Gets the ratio of infected persons in all contactPools of this location.
Definition at line 45 of file Location.cpp.
References GetPopulation(), and m_contactCenters.
Referenced by GetContactCentersOfType().
double gengeopop::Location::GetInfectedCount () const
Gets the amount of people infected in the contactpools of this location.
Definition at line 65 of file Location.cpp.
References m_contactCenters.
Referenced by GetContactCentersOfType().
void gengeopop::Location::CalculatePopulation (unsigned int totalPopulation)
Given the total population calculates this location's population using the relative population of this location.
Definition at line 152 of file Location.cpp.
References m_population, and m_relativePopulation.
Referenced by GetContactCentersOfType().
void gengeopop::Location::SetRelativePopulation (double relativePopulation)
Sets the relative population, which will be later used by.
See also
CalculatePopulation
Definition at line 156 of file Location.cpp.
References m_relativePopulation.
Referenced by GetContactCentersOfType().
double gengeopop::Location::GetRelativePopulationSize () const
Gets the relative population.
Definition at line 157 of file Location.cpp.
References m_relativePopulation.
Referenced by GetContactCentersOfType().
const std::vector< std::pair< Location *, double > > & gengeopop::Location::GetIncomingCommuningCities () const
Gets a vector with the outgoing cities which people are commuting to + the proportion.
Definition at line 99 of file Location.cpp.
References m_incomingCommutingLocations.
Referenced by GetContactCentersOfType(), and operator==().
void gengeopop::Location::AddIncomingCommutingLocation (std::shared_ptr< Location > location, double proportion)
Adds a Location and a proportion to the incoming commutng vector I.e.
proportion of the commuting population in location are commuting to this
Definition at line 104 of file Location.cpp.
References m_incomingCommutingLocations.
Referenced by GetContactCentersOfType().
const std::vector< std::pair< Location *, double > > & gengeopop::Location::GetOutgoingCommuningCities () const
Returns
a vector with the outgoing cities which people are commuting to + the proportion
Definition at line 109 of file Location.cpp.
References m_outgoingCommutingLocations.
Referenced by GetContactCentersOfType(), and operator==().
void gengeopop::Location::AddOutgoingCommutingLocation (std::shared_ptr< Location > location, double proportion)
Adds a Location and a proportion to the incoming commuting vector.
Definition at line 114 of file Location.cpp.
References m_outgoingCommutingLocations.
Referenced by GetContactCentersOfType().
int gengeopop::Location::OutGoingCommutingPeople (double fractionOfPopulationCommuting) const
Gets the absolute amount of poeple leaving from this location.
Definition at line 130 of file Location.cpp.
References m_outgoingCommutingLocations, and m_population.
Referenced by GetContactCentersOfType().
int gengeopop::Location::IncomingCommutingPeople (double fractionOfPopulationCommuting) const
Gets the absolute amount of people going to this location.
Definition at line 119 of file Location.cpp.
References m_incomingCommutingLocations.
Referenced by GetContactCentersOfType().
const Coordinate & gengeopop::Location::GetCoordinate () const
Gets the Coordinate of this location.
Definition at line 91 of file Location.cpp.
References m_coordinate.
Referenced by GetContactCentersOfType(), and operator==().
void gengeopop::Location::SetCoordinate (const Coordinate & coordinate)
Definition at line 93 of file Location.cpp.
References m_coordinate.
Referenced by GetContactCentersOfType().
const std::vector< std::shared_ptr< ContactCenter > > & gengeopop::Location::GetContactCenters () const
Gets all contact centers at this location.
Definition at line 89 of file Location.cpp.
References m_contactCenters.
Referenced by GetContactCentersOfType(), and operator==().
Location::iterator gengeopop::Location::begin ()
Gets iterator to the first location.
Definition at line 95 of file Location.cpp.
References m_contactCenters.
Location::iterator gengeopop::Location::end ()
Gets iterator to the end of the locations.
Definition at line 97 of file Location.cpp.
References m_contactCenters.
Member Data Documentation
unsigned int gengeopop::Location::m_id = 0 private
Id.
Definition at line 134 of file Location.h.
Referenced by GetID().
std::string gengeopop::Location::m_name private
Name.
Definition at line 135 of file Location.h.
Referenced by GetName().
unsigned int gengeopop::Location::m_province private
Province id.
Definition at line 136 of file Location.h.
Referenced by GetProvince().
unsigned int gengeopop::Location::m_population private
The absolute population.
Definition at line 137 of file Location.h.
Referenced by CalculatePopulation(), GetPopulation(), Location(), and OutGoingCommutingPeople().
double gengeopop::Location::m_relativePopulation private
The relative population (relative against whole population)
Definition at line 138 of file Location.h.
Referenced by CalculatePopulation(), GetRelativePopulationSize(), and SetRelativePopulation().
Coordinate gengeopop::Location::m_coordinate private
Coordinate.
Definition at line 139 of file Location.h.
Referenced by GetCoordinate(), and SetCoordinate().
std::vector<std::shared_ptr<ContactCenter> > gengeopop::Location::m_contactCenters private
All contactCenters.
Definition at line 140 of file Location.h.
Referenced by AddContactCenter(), begin(), end(), GetContactCenters(), GetInfectedCount(), GetInfectedRatio(), and GetSimulationPopulation().
std::vector<std::pair<Location*, double> > gengeopop::Location::m_incomingCommutingLocations private
Incomming commutes stored as pair of location and proportion relative to the given location.
Outgoing commutes stored as pair of location and proportion relative to the this location
Definition at line 142 of file Location.h.
Referenced by AddIncomingCommutingLocation(), GetIncomingCommuningCities(), and IncomingCommutingPeople().
std::vector<std::pair<Location*, double> > gengeopop::Location::m_outgoingCommutingLocations private
Definition at line 144 of file Location.h.
Referenced by AddOutgoingCommutingLocation(), GetOutgoingCommuningCities(), and OutGoingCommutingPeople().
std::unordered_map<std::type_index, std::vector<std::shared_ptr<ContactCenter> > > gengeopop::Location::m_contactCenterByType private
Stores the contact centers indexed by their type.
Definition at line 146 of file Location.h.
Referenced by AddContactCenter(), and GetContactCentersOfType().
The documentation for this class was generated from the following files:
Location.h
Location.cpp