Stride Reference Manual: ExcAssert.h File Reference
ExcAssert.h File Reference
#include "util/Exception.h"
#include <string>
Functions
void ExcAssert (bool condition, const std::string &error)
Function Documentation
void ExcAssert (bool condition, const std::string & error) inline
Definition at line 25 of file ExcAssert.h.
Referenced by gengeopop::CollegePopulator::Apply(), gengeopop::WorkplacePopulator::CalculateCommutingLocations(), and gengeopop::GeneratorInterface::CheckWeight().