Stride Reference Manual: geopop::GeoGridJSONReader Class Reference
geopop::GeoGridJSONReader Class Reference
An implementation of the GeoGridReader using JSON.
#include <GeoGridJSONReader.h>
Public Member Functions
GeoGridJSONReader (std::unique_ptr< std::istream > inputStream, stride::Population *pop)
Construct the GeoGridJSONReader with the istream which contains the JSON.
GeoGridJSONReader (const GeoGridJSONReader &)=delete
No copy constructor.
GeoGridJSONReader operator= (const GeoGridJSONReader &)=delete
No copy assignement.
void Read () override
Actually perform the read and return the GeoGrid.
Public Member Functions inherited from geopop::GeoGridReader
GeoGridReader (std::unique_ptr< std::istream > inputStream, stride::Population *pop)
Parametrized constructor.
GeoGridReader (const GeoGridReader &)=delete
No copy constructor.
GeoGridReader & operator= (const GeoGridReader &)=delete
No copy assignment.
virtual ~GeoGridReader ()=default
Default destructor.
Private Member Functions
std::shared_ptr< ContactCenter > ParseContactCenter (boost::property_tree::ptree &contactCenter)
Create a ContactCenter based on the information stored in the provided boost property tree.
stride::ContactPool * ParseContactPool (boost::property_tree::ptree &contactPool, stride::ContactType::Id typeId)
Create a ContactCenter based on the information stored in the provided boost property tree.
Coordinate ParseCoordinate (boost::property_tree::ptree &coordinate)
Create a Coordinate based on the information stored in the provided boost property tree.
std::shared_ptr< Location > ParseLocation (boost::property_tree::ptree &location)
Create a Location based on the information stored in the provided boost property tree.
stride::Person * ParsePerson (boost::property_tree::ptree &person)
Create a Person based on the information stored in the provided boost property tree.
Additional Inherited Members
Protected Member Functions inherited from geopop::GeoGridReader
void AddCommutes (GeoGrid &geoGrid)
Add the commutes that were found to their respective Locations symmetrically.
Protected Attributes inherited from geopop::GeoGridReader
std::map< unsigned int, stride::Person * > m_people
< Store the persons (id->person) that were found while loping over the ContactPools.
std::vector< std::tuple< unsigned int, unsigned int, double > > m_commutes
std::unique_ptr< std::istream > m_inputStream
File to read.
stride::Population * m_population
Population to use in the GeoGrid may be nullptr.
Detailed Description
An implementation of the GeoGridReader using JSON.
This class is used to read a GeoGrid from a JSON file.
Definition at line 33 of file GeoGridJSONReader.h.
Constructor & Destructor Documentation
geopop::GeoGridJSONReader::GeoGridJSONReader (std::unique_ptr< std::istream > inputStream, stride::Population * pop)
Construct the GeoGridJSONReader with the istream which contains the JSON.
Definition at line 41 of file GeoGridJSONReader.cpp.
geopop::GeoGridJSONReader::GeoGridJSONReader (const GeoGridJSONReader &) delete
No copy constructor.
Member Function Documentation
GeoGridJSONReader geopop::GeoGridJSONReader::operator= (const GeoGridJSONReader &) delete
No copy assignement.
void geopop::GeoGridJSONReader::Read () override virtual
Actually perform the read and return the GeoGrid.
Implements geopop::GeoGridReader.
Definition at line 46 of file GeoGridJSONReader.cpp.
References geopop::GeoGridReader::AddCommutes(), geopop::GeoGridReader::m_commutes, geopop::GeoGridReader::m_inputStream, geopop::GeoGridReader::m_people, geopop::GeoGridReader::m_population, ParseLocation(), ParsePerson(), and stride::Population::RefGeoGrid().
shared_ptr< ContactCenter > geopop::GeoGridJSONReader::ParseContactCenter (boost::property_tree::ptree & contactCenter) private
Create a ContactCenter based on the information stored in the provided boost property tree.
Definition at line 145 of file GeoGridJSONReader.cpp.
References ParseContactPool(), and stride::ContactLogMode::ToString().
Referenced by ParseLocation().
ContactPool * geopop::GeoGridJSONReader::ParseContactPool (boost::property_tree::ptree & contactPool, stride::ContactType::Id typeId) private
Create a ContactCenter based on the information stored in the provided boost property tree.
Definition at line 199 of file GeoGridJSONReader.cpp.
References stride::ContactPoolSys::CreateContactPool(), geopop::GeoGridReader::m_people, geopop::GeoGridReader::m_population, and stride::Population::RefPoolSys().
Referenced by ParseContactCenter().
Coordinate geopop::GeoGridJSONReader::ParseCoordinate (boost::property_tree::ptree & coordinate) private
Create a Coordinate based on the information stored in the provided boost property tree.
Definition at line 138 of file GeoGridJSONReader.cpp.
Referenced by ParseLocation().
shared_ptr< Location > geopop::GeoGridJSONReader::ParseLocation (boost::property_tree::ptree & location) private
Create a Location based on the information stored in the provided boost property tree.
Definition at line 96 of file GeoGridJSONReader.cpp.
References geopop::GeoGridReader::m_commutes, ParseContactCenter(), and ParseCoordinate().
Referenced by Read().
Person * geopop::GeoGridJSONReader::ParsePerson (boost::property_tree::ptree & person) private
Create a Person based on the information stored in the provided boost property tree.
Definition at line 217 of file GeoGridJSONReader.cpp.
References stride::Population::CreatePerson(), and geopop::GeoGridReader::m_population.
Referenced by Read().
The documentation for this class was generated from the following files:
GeoGridJSONReader.h
GeoGridJSONReader.cpp