Stride Reference Manual: geopop::GeoGridJSONWriter Class Reference
geopop::GeoGridJSONWriter Class Reference
Writes a GeoGrid to a JSON file.
#include <GeoGridJSONWriter.h>
Public Member Functions
GeoGridJSONWriter ()
Construct the GeoGridJSONWriter.
void Write (std::shared_ptr< GeoGrid > geoGrid, std::ostream &stream) override
Write the provided GeoGrid to the proved ostream in JSON format.
Public Member Functions inherited from geopop::GeoGridWriter
virtual ~GeoGridWriter ()=default
Construct the Writer.
Private Member Functions
boost::property_tree::ptree WriteContactCenter (std::shared_ptr< ContactCenter > contactCenter)
Create a Boost Property Tree containing all info needed to reconstruct a ContactCenter.
boost::property_tree::ptree WriteContactPool (stride::ContactPool *contactPool)
Create a Boost Property Tree containing all info needed to reconstruct a ContactPool.
boost::property_tree::ptree WriteCoordinate (const Coordinate &coordinate)
Create a Boost Property Tree containing all info needed to reconstruct a Coordinate.
boost::property_tree::ptree WriteLocation (std::shared_ptr< Location > location)
Create a Boost Property Tree containing all info needed to reconstruct a Location.
boost::property_tree::ptree WritePerson (stride::Person *person)
Create a Boost Property Tree containing all info needed to reconstruct a Person.
Private Attributes
std::set< stride::Person * > m_persons_found
The persons found when looping over the ContactPools.
Detailed Description
Writes a GeoGrid to a JSON file.
Definition at line 36 of file GeoGridJSONWriter.h.
Constructor & Destructor Documentation
geopop::GeoGridJSONWriter::GeoGridJSONWriter ()
Construct the GeoGridJSONWriter.
Definition at line 31 of file GeoGridJSONWriter.cpp.
Member Function Documentation
void geopop::GeoGridJSONWriter::Write (std::shared_ptr< GeoGrid > geoGrid, std::ostream & stream) override virtual
Write the provided GeoGrid to the proved ostream in JSON format.
Implements geopop::GeoGridWriter.
Definition at line 33 of file GeoGridJSONWriter.cpp.
References m_persons_found, WriteLocation(), and WritePerson().
boost::property_tree::ptree geopop::GeoGridJSONWriter::WriteContactCenter (std::shared_ptr< ContactCenter > contactCenter) private
Create a Boost Property Tree containing all info needed to reconstruct a ContactCenter.
Definition at line 77 of file GeoGridJSONWriter.cpp.
References stride::ContactLogMode::ToString(), and WriteContactPool().
Referenced by WriteLocation().
boost::property_tree::ptree geopop::GeoGridJSONWriter::WriteContactPool (stride::ContactPool * contactPool) private
Create a Boost Property Tree containing all info needed to reconstruct a ContactPool.
Definition at line 101 of file GeoGridJSONWriter.cpp.
References stride::ContactPool::GetId(), and m_persons_found.
Referenced by WriteContactCenter().
boost::property_tree::ptree geopop::GeoGridJSONWriter::WriteCoordinate (const Coordinate & coordinate) private
Create a Boost Property Tree containing all info needed to reconstruct a Coordinate.
Definition at line 117 of file GeoGridJSONWriter.cpp.
Referenced by WriteLocation().
boost::property_tree::ptree geopop::GeoGridJSONWriter::WriteLocation (std::shared_ptr< Location > location) private
Create a Boost Property Tree containing all info needed to reconstruct a Location.
Definition at line 125 of file GeoGridJSONWriter.cpp.
References stride::ContactType::IdList, WriteContactCenter(), and WriteCoordinate().
Referenced by Write().
boost::property_tree::ptree geopop::GeoGridJSONWriter::WritePerson (stride::Person * person) private
Create a Boost Property Tree containing all info needed to reconstruct a Person.
Definition at line 159 of file GeoGridJSONWriter.cpp.
References stride::Person::GetAge(), stride::Person::GetId(), and stride::Person::GetPoolId().
Referenced by Write().
Member Data Documentation
std::set<stride::Person*> geopop::GeoGridJSONWriter::m_persons_found private
The persons found when looping over the ContactPools.
Definition at line 62 of file GeoGridJSONWriter.h.
Referenced by Write(), and WriteContactPool().
The documentation for this class was generated from the following files:
GeoGridJSONWriter.h
GeoGridJSONWriter.cpp