Stride Reference Manual: stride::util::Rn< E > Class Template Reference
stride::util::Rn< E > Class Template Reference
Manages random number generation in parallel (OpenMP) calculations.
#include <Rn.h>
Classes
struct Info
POD representation of the RNManager's state.
Public Types
using EngineType = E
using RnType = randutils::random_generator< E, randutils::seed_seq_fe128 >
using ContainerType = std::vector< randutils::random_generator< E, randutils::seed_seq_fe128 >>
Public Member Functions
Rn (const Info &info=Info())
Initializes.
Rn (const Rn &)=delete
No copying.
Rn & operator= (const Rn &)=delete
No copy assignment.
bool operator== (const Rn &other)
Equality of states.
Info GetInfo () const
Return the state of the random engines.
void Initialize (const Info &info=Info())
Initalize with data in Info.
Private Member Functions
void Seed (randutils::seed_seq_fe128 &seseq)
Actual first-time seeding. Procedure varies according to engine type, see specialisations.
template<>
void Seed (randutils::seed_seq_fe128 &seseq)
template<>
void Seed (randutils::seed_seq_fe128 &seseq)
Private Attributes
std::string m_seed_seq_init
Seed sequence initializer used with engines.
unsigned int m_stream_count
Number of threads/streams set up with the engine.
Detailed Description
template<typename E>
class stride::util::Rn< E >
Manages random number generation in parallel (OpenMP) calculations.
Definition at line 38 of file Rn.h.
Member Typedef Documentation
template<typename E > using stride::util::Rn< E >::EngineType = E
Definition at line 41 of file Rn.h.
template<typename E > using stride::util::Rn< E >::RnType = randutils::random_generator<E, randutils::seed_seq_fe128>
Definition at line 42 of file Rn.h.
template<typename E > using stride::util::Rn< E >::ContainerType = std::vector<randutils::random_generator<E, randutils::seed_seq_fe128>>
Definition at line 43 of file Rn.h.
Constructor & Destructor Documentation
template<typename E > stride::util::Rn< E >::Rn (const Info & info = Info()) inline explicit
Initializes.
Definition at line 67 of file Rn.h.
References stride::util::Rn< E >::GetInfo(), stride::util::Rn< E >::Info::Info(), stride::util::Rn< E >::Initialize(), stride::util::Rn< E >::operator=(), stride::util::Rn< E >::operator==(), and stride::util::Rn< E >::Seed().
template<typename E > stride::util::Rn< E >::Rn (const Rn< E > &) delete
No copying.
Member Function Documentation
template<typename E > Rn& stride::util::Rn< E >::operator= (const Rn< E > &) delete
No copy assignment.
Referenced by stride::util::Rn< E >::Rn().
template<typename E > bool stride::util::Rn< E >::operator== (const Rn< E > & other)
Equality of states.
Definition at line 41 of file Rn.cpp.
References stride::util::Rn< E >::m_stream_count.
Referenced by stride::util::Rn< E >::Rn().
template<typename E > Rn< E >::Info stride::util::Rn< E >::GetInfo () const
Return the state of the random engines.
Definition at line 53 of file Rn.cpp.
References stride::util::Rn< E >::Info::m_seed_seq_init, stride::util::Rn< E >::Info::m_state, and stride::util::Rn< E >::Info::m_stream_count.
Referenced by stride::util::Rn< E >::Rn().
template<typename E > void stride::util::Rn< E >::Initialize (const Info & info = Info())
Initalize with data in Info.
Definition at line 67 of file Rn.cpp.
References stride::util::CheckAllDigits(), stride::util::Rn< E >::Info::m_seed_seq_init, stride::util::Rn< E >::Info::m_state, stride::util::Rn< E >::Info::m_stream_count, and stride::util::Split().
Referenced by stride::ControlHelper::ControlHelper(), and stride::util::Rn< E >::Rn().
template<typename E > void stride::util::Rn< E >::Seed (randutils::seed_seq_fe128 & seseq) private
Actual first-time seeding. Procedure varies according to engine type, see specialisations.
Definition at line 108 of file Rn.cpp.
Referenced by stride::util::Rn< E >::Rn().
template<> void stride::util::Rn< pcg64 >::Seed (randutils::seed_seq_fe128 & seseq) private
Definition at line 96 of file Rn.cpp.
template<> void stride::util::Rn< pcg64 >::Seed (randutils::seed_seq_fe128 & seseq) private
Member Data Documentation
template<typename E > std::string stride::util::Rn< E >::m_seed_seq_init private
Seed sequence initializer used with engines.
Definition at line 94 of file Rn.h.
template<typename E > unsigned int stride::util::Rn< E >::m_stream_count private
Number of threads/streams set up with the engine.
Definition at line 95 of file Rn.h.
Referenced by stride::util::Rn< E >::operator==().
The documentation for this class was generated from the following files:
Rn.h
Rn.cpp