Stride Reference Manual: calibration::Boxplot Class Reference
calibration::Boxplot Class Reference
A class used to compute the necessary information to generate boxplots.
#include <Boxplot.h>
Public Member Functions
Boxplot ()
Setup.
std::vector< BoxplotData > Calculate (const std::map< std::string, std::vector< std::vector< unsigned int >>> &data) const
Compute the information for each step in a list of testcase results.
std::vector< BoxplotData > Calculate (const std::map< std::string, std::vector< std::vector< unsigned int >>> &data, unsigned int step) const
Compute the information for a specific step in a list of testcase results.
std::vector< BoxplotData > CalculateLastStep (const std::map< std::string, std::vector< std::vector< unsigned int >>> &data) const
Compute the information for the last step in a list of testcase results.
BoxplotData Calculate (std::vector< unsigned int > data, std::string name) const
Compute the information for a single set of data.
Private Member Functions
double FindMedian (unsigned long begin, unsigned long end, std::vector< unsigned int > &results) const
Find the median of values between begin and end in the results. This vector needs to be sorted.
Private Attributes
std::shared_ptr< spdlog::logger > m_logger
Logger to use for this class.
Detailed Description
A class used to compute the necessary information to generate boxplots.
Definition at line 29 of file Boxplot.h.
Constructor & Destructor Documentation
calibration::Boxplot::Boxplot ()
Setup.
Definition at line 26 of file Boxplot.cpp.
Member Function Documentation
std::vector< BoxplotData > calibration::Boxplot::Calculate (const std::map< std::string, std::vector< std::vector< unsigned int >>> & data) const
Compute the information for each step in a list of testcase results.
Definition at line 70 of file Boxplot.cpp.
References m_logger.
Referenced by Calculate(), CalculateLastStep(), calibration::CalibrationRunner::DisplayBoxplots(), and calibration::CalibrationRunner::WriteBoxplots().
std::vector< BoxplotData > calibration::Boxplot::Calculate (const std::map< std::string, std::vector< std::vector< unsigned int >>> & data, unsigned int step) const
Compute the information for a specific step in a list of testcase results.
Definition at line 39 of file Boxplot.cpp.
References Calculate(), and m_logger.
std::vector< BoxplotData > calibration::Boxplot::CalculateLastStep (const std::map< std::string, std::vector< std::vector< unsigned int >>> & data) const
Compute the information for the last step in a list of testcase results.
Definition at line 56 of file Boxplot.cpp.
References Calculate().
Referenced by calibration::CalibrationRunner::DisplayBoxplots().
BoxplotData calibration::Boxplot::Calculate (std::vector< unsigned int > data, std::string name) const
Compute the information for a single set of data.
Definition at line 93 of file Boxplot.cpp.
References FindMedian(), calibration::BoxplotData::lower_quartile, m_logger, calibration::BoxplotData::max_value, calibration::BoxplotData::median, calibration::BoxplotData::min_value, calibration::BoxplotData::name, and calibration::BoxplotData::upper_quartile.
double calibration::Boxplot::FindMedian (unsigned long begin, unsigned long end, std::vector< unsigned int > & results) const private
Find the median of values between begin and end in the results. This vector needs to be sorted.
Definition at line 28 of file Boxplot.cpp.
Referenced by Calculate().
Member Data Documentation
std::shared_ptr<spdlog::logger> calibration::Boxplot::m_logger private
Logger to use for this class.
Definition at line 54 of file Boxplot.h.
Referenced by Calculate().
The documentation for this class was generated from the following files:
Boxplot.h
Boxplot.cpp