Stride Reference Manual: stride::util::FileSys Class Reference
stride::util::FileSys Class Reference
Utilities for interaction with filesystem.
#include <FileSys.h>
Classes
struct Dirs
Using this to avoid global variables & their initialization.
Static Public Member Functions
static bool IsDirectoryString (const std::string &s)
String represents a directory path (relative or absolute) iff it contains at least one / (may be a trailing one).
static bool CreateDirectory (std::string s)
Create a directory relative to the current directory with the given path, returns if it was succesful.
static filesys::path BuildPath (const std::string &output_prefix, const std::string &filename)
Interpret prefix (directory or filename prefix) and return appropriate path.
static boost::property_tree::ptree ReadPtreeFile (const filesys::path &f_p)
Read ptree from file at path.
static boost::property_tree::ptree ReadPtreeFile (const std::string &f_n)
Read ptree from file specifified by name string.
static void WritePtreeFile (const filesys::path &f_p, const boost::property_tree::ptree &pt)
Write ptree to file at path.
static void WritePtreeFile (const std::string &f_n, const boost::property_tree::ptree &pt)
Write ptree to file specifified by name string.
static filesys::path GetCurrentDir ()
Get path to the current directory.
static filesys::path GetExecPath ()
Get path of the executable.
static bool CheckInstallEnv (std::function< void(const std::string &)> logger=std::function< void(const std::string &)>())
Verify that current dir is root dir and all install dirs are present.
static filesys::path GetBinDir ()
Return bin dir (only relevant when use_install_dirs mode is active)
static filesys::path GetConfigDir ()
Return config dir (only relevant when use_install_dirs mode is active)
static filesys::path GetDataDir ()
/// Return data dir (only relevant when use_install_dirs mode is active)
static filesys::path GetRootDir ()
Return install root dir (only relevant when use_install_dirs mode is active)
static filesys::path GetTestsDir ()
Return tests dir (only relevant when use_install_dirs mode is active)
Static Private Member Functions
static Dirs Initialize ()
Initialize all paths.
static Dirs & Get ()
Return paths.
Detailed Description
Utilities for interaction with filesystem.
Definition at line 42 of file FileSys.h.
Member Function Documentation
bool stride::util::FileSys::IsDirectoryString (const std::string & s) static
String represents a directory path (relative or absolute) iff it contains at least one / (may be a trailing one).
Definition at line 192 of file FileSys.cpp.
Referenced by BuildPath(), and stride::ControlHelper::CheckOutputPrefix().
bool stride::util::FileSys::CreateDirectory (std::string s) static
Create a directory relative to the current directory with the given path, returns if it was succesful.
Definition at line 198 of file FileSys.cpp.
Referenced by stride::ControlHelper::CheckOutputPrefix().
filesys::path stride::util::FileSys::BuildPath (const std::string & output_prefix, const std::string & filename) static
Interpret prefix (directory or filename prefix) and return appropriate path.
Definition at line 51 of file FileSys.cpp.
References IsDirectoryString().
Referenced by stride::StanController::Control(), stride::output::InfectedFile::InfectedFile(), stride::output::AdoptedFile::Initialize(), stride::output::SummaryFile::Initialize(), stride::output::PersonsFile::Initialize(), and stride::ControlHelper::InstallLogger().
ptree stride::util::FileSys::ReadPtreeFile (const filesys::path & f_p) static
Read ptree from file at path.
Definition at line 207 of file FileSys.cpp.
Referenced by stride::SimBuilder::ReadAgeContactPtree(), stride::SimBuilder::ReadDiseasePtree(), and stride::DiseaseSeeder::Vaccinate().
ptree stride::util::FileSys::ReadPtreeFile (const std::string & f_n) static
Read ptree from file specifified by name string.
Definition at line 226 of file FileSys.cpp.
void stride::util::FileSys::WritePtreeFile (const filesys::path & f_p, const boost::property_tree::ptree & pt) static
Write ptree to file at path.
Definition at line 228 of file FileSys.cpp.
void stride::util::FileSys::WritePtreeFile (const std::string & f_n, const boost::property_tree::ptree & pt) static
Write ptree to file specifified by name string.
Definition at line 239 of file FileSys.cpp.
static filesys::path stride::util::FileSys::GetCurrentDir () inline static
Get path to the current directory.
Definition at line 69 of file FileSys.h.
References Get(), and stride::util::FileSys::Dirs::m_current_dir.
Referenced by stride::ControlHelper::LogStartup().
static filesys::path stride::util::FileSys::GetExecPath () inline static
Get path of the executable.
Definition at line 72 of file FileSys.h.
References CheckInstallEnv(), Get(), and stride::util::FileSys::Dirs::m_exec_path.
Referenced by stride::ControlHelper::LogStartup().
bool stride::util::FileSys::CheckInstallEnv (std::function< void(const std::string &)> logger = std::function<void(const std::string&)>()) static
Verify that current dir is root dir and all install dirs are present.
Parameters
logger logger verification finds failures; defaults to no-op.
Returns
staus true iff everything verifies ok.
There has to be a config dir in the install root dir.
There has to be a data dir in the install root dir.
There has to be a data dir in the install root dir.
Definition at line 64 of file FileSys.cpp.
Referenced by stride::ControlHelper::CheckEnv(), and GetExecPath().
static filesys::path stride::util::FileSys::GetBinDir () inline static
Return bin dir (only relevant when use_install_dirs mode is active)
Definition at line 82 of file FileSys.h.
References Get(), and stride::util::FileSys::Dirs::m_bin_dir.
static filesys::path stride::util::FileSys::GetConfigDir () inline static
Return config dir (only relevant when use_install_dirs mode is active)
Definition at line 85 of file FileSys.h.
References Get(), and stride::util::FileSys::Dirs::m_config_dir.
Referenced by stride::ControlHelper::LogStartup().
static filesys::path stride::util::FileSys::GetDataDir () inline static
/// Return data dir (only relevant when use_install_dirs mode is active)
Definition at line 88 of file FileSys.h.
References Get(), and stride::util::FileSys::Dirs::m_data_dir.
Referenced by gengeopop::ReaderFactory::CreateCitiesReader(), gengeopop::ReaderFactory::CreateCommutesReader(), gengeopop::ReaderFactory::CreateHouseholdReader(), stride::Calendar::InitializeHolidays(), stride::ControlHelper::LogStartup(), stride::DefaultPopBuilder::MakePersons(), stride::SimBuilder::ReadAgeContactPtree(), and stride::SimBuilder::ReadDiseasePtree().
static filesys::path stride::util::FileSys::GetRootDir () inline static
Return install root dir (only relevant when use_install_dirs mode is active)
Definition at line 91 of file FileSys.h.
References Get(), and stride::util::FileSys::Dirs::m_root_dir.
Referenced by stride::ControlHelper::LogStartup().
static filesys::path stride::util::FileSys::GetTestsDir () inline static
Return tests dir (only relevant when use_install_dirs mode is active)
Definition at line 94 of file FileSys.h.
References Get(), and stride::util::FileSys::Dirs::m_tests_dir.
FileSys::Dirs stride::util::FileSys::Initialize () static private
Initialize all paths.
Definition at line 101 of file FileSys.cpp.
References stride::util::FileSys::Dirs::m_bin_dir, stride::util::FileSys::Dirs::m_config_dir, stride::util::FileSys::Dirs::m_current_dir, stride::util::FileSys::Dirs::m_data_dir, stride::util::FileSys::Dirs::m_exec_path, stride::util::FileSys::Dirs::m_root_dir, stride::util::FileSys::Dirs::m_tests_dir, and stride::util::ToLower().
FileSys::Dirs & stride::util::FileSys::Get () static private
Return paths.
Definition at line 95 of file FileSys.cpp.
Referenced by GetBinDir(), GetConfigDir(), GetCurrentDir(), GetDataDir(), GetExecPath(), GetRootDir(), and GetTestsDir().
The documentation for this class was generated from the following files:
FileSys.h
FileSys.cpp