Stride Reference Manual: stride::util::ConfigInfo Class Reference
stride::util::ConfigInfo Class Reference
Config information.
#include <ConfigInfo.h>
Static Public Member Functions
static constexpr bool HaveOpenMP ()
True if OpenMP in executable, false otherwise.
static std::string GitRevision ()
Return git revision string.
static std::string GetHostname ()
Return current hostname.
static unsigned int NumberAvailableThreads ()
Return number of threads (in case of OpenMP).
static unsigned int ProcessorCount ()
Return processor count for system.
Detailed Description
Config information.
Definition at line 31 of file ConfigInfo.h.
Member Function Documentation
static constexpr bool stride::util::ConfigInfo::HaveOpenMP () inline static
True if OpenMP in executable, false otherwise.
Definition at line 35 of file ConfigInfo.h.
References GetHostname(), GitRevision(), NumberAvailableThreads(), and ProcessorCount().
Referenced by stride::ControlHelper::LogStartup().
std::string stride::util::ConfigInfo::GitRevision () static
Return git revision string.
Definition at line 33 of file ConfigInfo.cpp.
References TOSTRING.
Referenced by HaveOpenMP(), and stride::ControlHelper::LogStartup().
std::string stride::util::ConfigInfo::GetHostname () static
Return current hostname.
Definition at line 35 of file ConfigInfo.cpp.
Referenced by HaveOpenMP().
unsigned int stride::util::ConfigInfo::NumberAvailableThreads () static
Return number of threads (in case of OpenMP).
Definition at line 44 of file ConfigInfo.cpp.
Referenced by HaveOpenMP(), and stride::ControlHelper::LogStartup().
unsigned int stride::util::ConfigInfo::ProcessorCount () static
Return processor count for system.
Definition at line 42 of file ConfigInfo.cpp.
Referenced by HaveOpenMP(), and stride::ControlHelper::LogStartup().
The documentation for this class was generated from the following files:
ConfigInfo.h
ConfigInfo.cpp