Stride Reference Manual: proto::GeoGrid_Location Class Reference
proto::GeoGrid_Location Class Reference final
#include <geogrid.pb.h>
Public Types
typedef GeoGrid_Location_Coordinate Coordinate
typedef GeoGrid_Location_ContactPools ContactPools
typedef GeoGrid_Location_Commute Commute
Public Member Functions
GeoGrid_Location ()
virtual ~GeoGrid_Location ()
GeoGrid_Location (const GeoGrid_Location &from)
GeoGrid_Location & operator= (const GeoGrid_Location &from)
void Swap (GeoGrid_Location *other)
GeoGrid_Location * New () const final
GeoGrid_Location * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const GeoGrid_Location &from)
void MergeFrom (const GeoGrid_Location &from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int contactpools_size () const
void clear_contactpools ()
::proto::GeoGrid_Location_ContactPools * mutable_contactpools (int index)
::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location_ContactPools > * mutable_contactpools ()
const ::proto::GeoGrid_Location_ContactPools & contactpools (int index) const
::proto::GeoGrid_Location_ContactPools * add_contactpools ()
const ::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location_ContactPools > & contactpools () const
int commutes_size () const
void clear_commutes ()
::proto::GeoGrid_Location_Commute * mutable_commutes (int index)
::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location_Commute > * mutable_commutes ()
const ::proto::GeoGrid_Location_Commute & commutes (int index) const
::proto::GeoGrid_Location_Commute * add_commutes ()
const ::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location_Commute > & commutes () const
void clear_name ()
const ::std::string & name () const
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
::std::string * mutable_name ()
::std::string * release_name ()
void set_allocated_name (::std::string *name)
bool has_coordinate () const
void clear_coordinate ()
const ::proto::GeoGrid_Location_Coordinate & coordinate () const
::proto::GeoGrid_Location_Coordinate * release_coordinate ()
::proto::GeoGrid_Location_Coordinate * mutable_coordinate ()
void set_allocated_coordinate (::proto::GeoGrid_Location_Coordinate *coordinate)
void clear_id ()
::google::protobuf::int64 id () const
void set_id (::google::protobuf::int64 value)
void clear_province ()
::google::protobuf::int64 province () const
void set_province (::google::protobuf::int64 value)
void clear_population ()
::google::protobuf::int64 population () const
void set_population (::google::protobuf::int64 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const GeoGrid_Location & default_instance ()
static void InitAsDefaultInstance ()
static const GeoGrid_Location * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kContactPoolsFieldNumber = 6
static const int kCommutesFieldNumber = 7
static const int kNameFieldNumber = 2
static const int kCoordinateFieldNumber = 5
static const int kIdFieldNumber = 1
static const int kProvinceFieldNumber = 3
static const int kPopulationFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const final
void InternalSwap (GeoGrid_Location *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location_ContactPools > contactpools_
::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location_Commute > commutes_
::google::protobuf::internal::ArenaStringPtr name_
::proto::GeoGrid_Location_Coordinate * coordinate_
::google::protobuf::int64 id_
::google::protobuf::int64 province_
::google::protobuf::int64 population_
mutable::google::protobuf::internal::CachedSize _cached_size_
Friends
struct ::TableStruct_geogrid_2eproto
void swap (GeoGrid_Location &a, GeoGrid_Location &b)
Detailed Description
Definition at line 647 of file geogrid.pb.h.
Member Typedef Documentation
typedef GeoGrid_Location_Coordinate proto::GeoGrid_Location::Coordinate
Definition at line 740 of file geogrid.pb.h.
typedef GeoGrid_Location_ContactPools proto::GeoGrid_Location::ContactPools
Definition at line 741 of file geogrid.pb.h.
typedef GeoGrid_Location_Commute proto::GeoGrid_Location::Commute
Definition at line 742 of file geogrid.pb.h.
Constructor & Destructor Documentation
proto::GeoGrid_Location::GeoGrid_Location ()
virtual proto::GeoGrid_Location::~GeoGrid_Location () virtual
proto::GeoGrid_Location::GeoGrid_Location (const GeoGrid_Location & from)
Member Function Documentation
GeoGrid_Location& proto::GeoGrid_Location::operator= (const GeoGrid_Location & from) inline
Definition at line 655 of file geogrid.pb.h.
References GetArenaNoVirtual().
static const ::google::protobuf::Descriptor* proto::GeoGrid_Location::descriptor () inline static
Definition at line 674 of file geogrid.pb.h.
static const GeoGrid_Location& proto::GeoGrid_Location::default_instance () static
static void proto::GeoGrid_Location::InitAsDefaultInstance () static
static const GeoGrid_Location* proto::GeoGrid_Location::internal_default_instance () inline static
Definition at line 680 of file geogrid.pb.h.
References proto::_GeoGrid_Location_default_instance_.
void proto::GeoGrid_Location::Swap (GeoGrid_Location * other)
GeoGrid_Location* proto::GeoGrid_Location::New () const inline final
Definition at line 694 of file geogrid.pb.h.
GeoGrid_Location* proto::GeoGrid_Location::New (::google::protobuf::Arena * arena) const inline final
Definition at line 698 of file geogrid.pb.h.
void proto::GeoGrid_Location::CopyFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Location::MergeFrom (const ::google::protobuf::Message & from) final
void proto::GeoGrid_Location::CopyFrom (const GeoGrid_Location & from)
void proto::GeoGrid_Location::MergeFrom (const GeoGrid_Location & from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void proto::GeoGrid_Location::Clear () final
bool proto::GeoGrid_Location::IsInitialized () const final
size_t proto::GeoGrid_Location::ByteSizeLong () const final
bool proto::GeoGrid_Location::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
void proto::GeoGrid_Location::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
::google::protobuf::uint8* proto::GeoGrid_Location::InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 * target) const final
int proto::GeoGrid_Location::GetCachedSize () const inline final
Definition at line 720 of file geogrid.pb.h.
void proto::GeoGrid_Location::SharedCtor () private
void proto::GeoGrid_Location::SharedDtor () private
void proto::GeoGrid_Location::SetCachedSize (int size) const final private
void proto::GeoGrid_Location::InternalSwap (GeoGrid_Location * other) private
inline ::google::protobuf::Arena* proto::GeoGrid_Location::GetArenaNoVirtual () const inline private
Definition at line 728 of file geogrid.pb.h.
Referenced by operator=().
void* proto::GeoGrid_Location::MaybeArenaPtr () const inline private
Definition at line 731 of file geogrid.pb.h.
::google::protobuf::Metadata proto::GeoGrid_Location::GetMetadata () const final
int proto::GeoGrid_Location::contactpools_size () const inline
Definition at line 1411 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::clear_contactpools () inline
Definition at line 1414 of file geogrid.pb.h.
References proto::GeoGrid_Location_Coordinate::Clear().
proto::GeoGrid_Location_ContactPools * proto::GeoGrid_Location::mutable_contactpools (int index) inline
Definition at line 1417 of file geogrid.pb.h.
google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_ContactPools > * proto::GeoGrid_Location::mutable_contactpools () inline
Definition at line 1422 of file geogrid.pb.h.
const ::proto::GeoGrid_Location_ContactPools & proto::GeoGrid_Location::contactpools (int index) const inline
Definition at line 1426 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseLocation().
proto::GeoGrid_Location_ContactPools * proto::GeoGrid_Location::add_contactpools () inline
Definition at line 1430 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WriteLocation().
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_ContactPools > & proto::GeoGrid_Location::contactpools () const inline
Definition at line 1435 of file geogrid.pb.h.
int proto::GeoGrid_Location::commutes_size () const inline
Definition at line 1441 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::clear_commutes () inline
Definition at line 1444 of file geogrid.pb.h.
proto::GeoGrid_Location_Commute * proto::GeoGrid_Location::mutable_commutes (int index) inline
Definition at line 1447 of file geogrid.pb.h.
google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_Commute > * proto::GeoGrid_Location::mutable_commutes () inline
Definition at line 1452 of file geogrid.pb.h.
const ::proto::GeoGrid_Location_Commute & proto::GeoGrid_Location::commutes (int index) const inline
Definition at line 1456 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseLocation().
proto::GeoGrid_Location_Commute * proto::GeoGrid_Location::add_commutes () inline
Definition at line 1460 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WriteLocation().
const ::google::protobuf::RepeatedPtrField<::proto::GeoGrid_Location_Commute > & proto::GeoGrid_Location::commutes () const inline
Definition at line 1465 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_name () inline
Definition at line 1279 of file geogrid.pb.h.
const ::std::string & proto::GeoGrid_Location::name () const inline
Definition at line 1282 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::set_name (const ::std::string & value) inline
Definition at line 1286 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WriteLocation().
void proto::GeoGrid_Location::set_name (const char * value) inline
Definition at line 1299 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_name (const char * value, size_t size) inline
Definition at line 1305 of file geogrid.pb.h.
std::string * proto::GeoGrid_Location::mutable_name () inline
Definition at line 1311 of file geogrid.pb.h.
std::string * proto::GeoGrid_Location::release_name () inline
Definition at line 1316 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_allocated_name (::std::string * name) inline
Definition at line 1321 of file geogrid.pb.h.
bool proto::GeoGrid_Location::has_coordinate () const inline
Definition at line 1360 of file geogrid.pb.h.
void proto::GeoGrid_Location::clear_coordinate () inline
Definition at line 1363 of file geogrid.pb.h.
const ::proto::GeoGrid_Location_Coordinate & proto::GeoGrid_Location::coordinate () const inline
Definition at line 1369 of file geogrid.pb.h.
References proto::_GeoGrid_Location_Coordinate_default_instance_.
Referenced by geopop::GeoGridProtoReader::ParseLocation().
proto::GeoGrid_Location_Coordinate * proto::GeoGrid_Location::release_coordinate () inline
Definition at line 1375 of file geogrid.pb.h.
proto::GeoGrid_Location_Coordinate * proto::GeoGrid_Location::mutable_coordinate () inline
Definition at line 1382 of file geogrid.pb.h.
void proto::GeoGrid_Location::set_allocated_coordinate (::proto::GeoGrid_Location_Coordinate * coordinate) inline
Definition at line 1391 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WriteLocation().
void proto::GeoGrid_Location::clear_id () inline
Definition at line 1265 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location::id () const inline
Definition at line 1268 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::set_id (::google::protobuf::int64 value) inline
Definition at line 1272 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WriteLocation().
void proto::GeoGrid_Location::clear_province () inline
Definition at line 1332 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location::province () const inline
Definition at line 1335 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::set_province (::google::protobuf::int64 value) inline
Definition at line 1339 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WriteLocation().
void proto::GeoGrid_Location::clear_population () inline
Definition at line 1346 of file geogrid.pb.h.
google::protobuf::int64 proto::GeoGrid_Location::population () const inline
Definition at line 1349 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoReader::ParseLocation().
void proto::GeoGrid_Location::set_population (::google::protobuf::int64 value) inline
Definition at line 1353 of file geogrid.pb.h.
Referenced by geopop::GeoGridProtoWriter::WriteLocation().
Friends And Related Function Documentation
friend struct ::TableStruct_geogrid_2eproto friend
Definition at line 824 of file geogrid.pb.h.
void swap (GeoGrid_Location & a, GeoGrid_Location & b) friend
Definition at line 688 of file geogrid.pb.h.
Member Data Documentation
constexpr int proto::GeoGrid_Location::kIndexInFileMessages static
Initial value:
=
    4
Definition at line 684 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kContactPoolsFieldNumber = 6 static
Definition at line 749 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kCommutesFieldNumber = 7 static
Definition at line 761 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kNameFieldNumber = 2 static
Definition at line 772 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kCoordinateFieldNumber = 5 static
Definition at line 787 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kIdFieldNumber = 1 static
Definition at line 795 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kProvinceFieldNumber = 3 static
Definition at line 801 of file geogrid.pb.h.
const int proto::GeoGrid_Location::kPopulationFieldNumber = 4 static
Definition at line 807 of file geogrid.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::GeoGrid_Location::_internal_metadata_ private
Definition at line 813 of file geogrid.pb.h.
::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location_ContactPools > proto::GeoGrid_Location::contactpools_ private
Definition at line 816 of file geogrid.pb.h.
::google::protobuf::RepeatedPtrField< ::proto::GeoGrid_Location_Commute > proto::GeoGrid_Location::commutes_ private
Definition at line 817 of file geogrid.pb.h.
::google::protobuf::internal::ArenaStringPtr proto::GeoGrid_Location::name_ private
Definition at line 818 of file geogrid.pb.h.
::proto::GeoGrid_Location_Coordinate* proto::GeoGrid_Location::coordinate_ private
Definition at line 819 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Location::id_ private
Definition at line 820 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Location::province_ private
Definition at line 821 of file geogrid.pb.h.
::google::protobuf::int64 proto::GeoGrid_Location::population_ private
Definition at line 822 of file geogrid.pb.h.
mutable ::google::protobuf::internal::CachedSize proto::GeoGrid_Location::_cached_size_ private
Definition at line 823 of file geogrid.pb.h.
The documentation for this class was generated from the following file:
geogrid.pb.h